// Maps API-Football's English country names to the Portuguese names seeded
// in the "countries" table (supabase/migrations/0002_seed_countries.sql).
const EN_TO_PT: Record<string, string> = {
  Afghanistan: "Afeganistão",
  "South Africa": "África do Sul",
  Albania: "Albânia",
  Germany: "Alemanha",
  Andorra: "Andorra",
  Angola: "Angola",
  "Antigua and Barbuda": "Antígua e Barbuda",
  "Saudi Arabia": "Arábia Saudita",
  Algeria: "Argélia",
  Argentina: "Argentina",
  Armenia: "Arménia",
  Australia: "Austrália",
  Austria: "Áustria",
  Azerbaijan: "Azerbaijão",
  Bahamas: "Baamas",
  Bangladesh: "Bangladeche",
  Barbados: "Barbados",
  Bahrain: "Barém",
  Belgium: "Bélgica",
  Belize: "Belize",
  Benin: "Benim",
  Belarus: "Bielorrússia",
  Myanmar: "Birmânia",
  Bolivia: "Bolívia",
  "Bosnia and Herzegovina": "Bósnia e Herzegovina",
  Botswana: "Botsuana",
  Brazil: "Brasil",
  Brunei: "Brunei",
  Bulgaria: "Bulgária",
  "Burkina Faso": "Burquina Faso",
  Burundi: "Burundi",
  Bhutan: "Butão",
  "Cape Verde": "Cabo Verde",
  Cameroon: "Camarões",
  Cambodia: "Camboja",
  Canada: "Canadá",
  Qatar: "Catar",
  Kazakhstan: "Cazaquistão",
  Chad: "Chade",
  Chile: "Chile",
  China: "China",
  Cyprus: "Chipre",
  Colombia: "Colômbia",
  Comoros: "Comores",
  Congo: "Congo",
  "North Korea": "Coreia do Norte",
  "South Korea": "Coreia do Sul",
  "Ivory Coast": "Costa do Marfim",
  "Costa Rica": "Costa Rica",
  Croatia: "Croácia",
  Cuba: "Cuba",
  Denmark: "Dinamarca",
  Dominica: "Domínica",
  Egypt: "Egito",
  "El Salvador": "El Salvador",
  "United Arab Emirates": "Emirados Árabes Unidos",
  Ecuador: "Equador",
  Eritrea: "Eritreia",
  Slovakia: "Eslováquia",
  Slovenia: "Eslovénia",
  Spain: "Espanha",
  USA: "Estados Unidos",
  "United States": "Estados Unidos",
  Estonia: "Estónia",
  Eswatini: "Essuatíni",
  Ethiopia: "Etiópia",
  Fiji: "Fiji",
  Philippines: "Filipinas",
  Finland: "Finlândia",
  France: "França",
  Gabon: "Gabão",
  Gambia: "Gâmbia",
  Ghana: "Gana",
  Georgia: "Geórgia",
  Grenada: "Granada",
  Greece: "Grécia",
  Guatemala: "Guatemala",
  Guyana: "Guiana",
  Guinea: "Guiné",
  "Guinea-Bissau": "Guiné-Bissau",
  "Equatorial Guinea": "Guiné Equatorial",
  Haiti: "Haiti",
  Honduras: "Honduras",
  Hungary: "Hungria",
  Yemen: "Iémen",
  "Marshall Islands": "Ilhas Marshall",
  "Solomon Islands": "Ilhas Salomão",
  India: "Índia",
  Indonesia: "Indonésia",
  Iran: "Irão",
  Iraq: "Iraque",
  Ireland: "Irlanda",
  "Republic of Ireland": "Irlanda",
  Iceland: "Islândia",
  Israel: "Israel",
  Italy: "Itália",
  Jamaica: "Jamaica",
  Japan: "Japão",
  Djibouti: "Jibuti",
  Jordan: "Jordânia",
  Kiribati: "Kiribati",
  Kosovo: "Kosovo",
  Kuwait: "Kuwait",
  Laos: "Laos",
  Lesotho: "Lesoto",
  Latvia: "Letónia",
  Lebanon: "Líbano",
  Liberia: "Libéria",
  Libya: "Líbia",
  Liechtenstein: "Listenstaine",
  Lithuania: "Lituânia",
  Luxembourg: "Luxemburgo",
  "North Macedonia": "Macedónia do Norte",
  Macedonia: "Macedónia do Norte",
  Madagascar: "Madagáscar",
  Malaysia: "Malásia",
  Malawi: "Malawi",
  Maldives: "Maldivas",
  Mali: "Mali",
  Malta: "Malta",
  Morocco: "Marrocos",
  Mauritius: "Maurícia",
  Mauritania: "Mauritânia",
  Mexico: "México",
  Micronesia: "Micronésia",
  Mozambique: "Moçambique",
  Moldova: "Moldávia",
  Monaco: "Mónaco",
  Mongolia: "Mongólia",
  Montenegro: "Montenegro",
  Namibia: "Namíbia",
  Nauru: "Nauru",
  Nepal: "Nepal",
  Nicaragua: "Nicarágua",
  Niger: "Níger",
  Nigeria: "Nigéria",
  Norway: "Noruega",
  "New Zealand": "Nova Zelândia",
  Oman: "Omã",
  Netherlands: "Países Baixos",
  Palau: "Palau",
  Palestine: "Palestina",
  Panama: "Panamá",
  "Papua New Guinea": "Papua-Nova Guiné",
  Pakistan: "Paquistão",
  Paraguay: "Paraguai",
  Peru: "Peru",
  Poland: "Polónia",
  Portugal: "Portugal",
  Kenya: "Quénia",
  Kyrgyzstan: "Quirguistão",
  "Central African Republic": "República Centro-Africana",
  "Czech Republic": "República Checa",
  Czechia: "República Checa",
  "DR Congo": "República Democrática do Congo",
  "Dominican Republic": "República Dominicana",
  Romania: "Roménia",
  Rwanda: "Ruanda",
  Russia: "Rússia",
  Samoa: "Samoa",
  "San Marino": "San Marino",
  "Saint Lucia": "Santa Lúcia",
  "Saint Kitts and Nevis": "São Cristóvão e Neves",
  "Sao Tome and Principe": "São Tomé e Príncipe",
  "Saint Vincent and the Grenadines": "São Vicente e Granadinas",
  Seychelles: "Seicheles",
  Senegal: "Senegal",
  "Sierra Leone": "Serra Leoa",
  Serbia: "Sérvia",
  Singapore: "Singapura",
  Syria: "Síria",
  Somalia: "Somália",
  "Sri Lanka": "Sri Lanka",
  Sudan: "Sudão",
  "South Sudan": "Sudão do Sul",
  Sweden: "Suécia",
  Switzerland: "Suíça",
  Suriname: "Suriname",
  Thailand: "Tailândia",
  Taiwan: "Taiwan",
  "Chinese Taipei": "Taiwan",
  Tajikistan: "Tajiquistão",
  Tanzania: "Tanzânia",
  "East Timor": "Timor-Leste",
  "Timor-Leste": "Timor-Leste",
  Togo: "Togo",
  Tonga: "Tonga",
  "Trinidad and Tobago": "Trindade e Tobago",
  Tunisia: "Tunísia",
  Turkmenistan: "Turcomenistão",
  Turkey: "Turquia",
  Türkiye: "Turquia",
  Tuvalu: "Tuvalu",
  Ukraine: "Ucrânia",
  Uganda: "Uganda",
  Uruguay: "Uruguai",
  Uzbekistan: "Usbequistão",
  Vanuatu: "Vanuatu",
  Vatican: "Vaticano",
  Venezuela: "Venezuela",
  Vietnam: "Vietname",
  Zambia: "Zâmbia",
  Zimbabwe: "Zimbabué",
  World: "Mundo",
};

// Football associations for the UK's four nations compete separately, but
// our countries table only has a single political "Reino Unido" entry.
const UK_NATIONS = new Set([
  "England",
  "Scotland",
  "Wales",
  "Northern Ireland",
  "Great Britain",
  "United Kingdom",
]);

export function translateCountryName(apiCountryName: string): string {
  if (UK_NATIONS.has(apiCountryName)) return "Reino Unido";
  return EN_TO_PT[apiCountryName] ?? "Mundo";
}
