-- Seeds the countries table with all countries of the world (PT-PT names)
-- plus a special "Mundo" entry for international competitions
-- (e.g. Liga dos Campeões, Mundial de Clubes, Eurocopa, etc).
-- Safe to re-run: uses ON CONFLICT DO NOTHING on the unique "name" column.

insert into countries (name) values
  ('Mundo'),
  ('Afeganistão'),
  ('África do Sul'),
  ('Albânia'),
  ('Alemanha'),
  ('Andorra'),
  ('Angola'),
  ('Antígua e Barbuda'),
  ('Arábia Saudita'),
  ('Argélia'),
  ('Argentina'),
  ('Arménia'),
  ('Austrália'),
  ('Áustria'),
  ('Azerbaijão'),
  ('Baamas'),
  ('Bangladeche'),
  ('Barbados'),
  ('Barém'),
  ('Bélgica'),
  ('Belize'),
  ('Benim'),
  ('Bielorrússia'),
  ('Birmânia'),
  ('Bolívia'),
  ('Bósnia e Herzegovina'),
  ('Botsuana'),
  ('Brasil'),
  ('Brunei'),
  ('Bulgária'),
  ('Burquina Faso'),
  ('Burundi'),
  ('Butão'),
  ('Cabo Verde'),
  ('Camarões'),
  ('Camboja'),
  ('Canadá'),
  ('Catar'),
  ('Cazaquistão'),
  ('Chade'),
  ('Chile'),
  ('China'),
  ('Chipre'),
  ('Colômbia'),
  ('Comores'),
  ('Congo'),
  ('Coreia do Norte'),
  ('Coreia do Sul'),
  ('Costa do Marfim'),
  ('Costa Rica'),
  ('Croácia'),
  ('Cuba'),
  ('Dinamarca'),
  ('Domínica'),
  ('Egito'),
  ('El Salvador'),
  ('Emirados Árabes Unidos'),
  ('Equador'),
  ('Eritreia'),
  ('Eslováquia'),
  ('Eslovénia'),
  ('Espanha'),
  ('Estados Unidos'),
  ('Estónia'),
  ('Essuatíni'),
  ('Etiópia'),
  ('Fiji'),
  ('Filipinas'),
  ('Finlândia'),
  ('França'),
  ('Gabão'),
  ('Gâmbia'),
  ('Gana'),
  ('Geórgia'),
  ('Granada'),
  ('Grécia'),
  ('Guatemala'),
  ('Guiana'),
  ('Guiné'),
  ('Guiné-Bissau'),
  ('Guiné Equatorial'),
  ('Haiti'),
  ('Honduras'),
  ('Hungria'),
  ('Iémen'),
  ('Ilhas Marshall'),
  ('Ilhas Salomão'),
  ('Índia'),
  ('Indonésia'),
  ('Irão'),
  ('Iraque'),
  ('Irlanda'),
  ('Islândia'),
  ('Israel'),
  ('Itália'),
  ('Jamaica'),
  ('Japão'),
  ('Jibuti'),
  ('Jordânia'),
  ('Kiribati'),
  ('Kosovo'),
  ('Kuwait'),
  ('Laos'),
  ('Lesoto'),
  ('Letónia'),
  ('Líbano'),
  ('Libéria'),
  ('Líbia'),
  ('Listenstaine'),
  ('Lituânia'),
  ('Luxemburgo'),
  ('Macedónia do Norte'),
  ('Madagáscar'),
  ('Malásia'),
  ('Malawi'),
  ('Maldivas'),
  ('Mali'),
  ('Malta'),
  ('Marrocos'),
  ('Maurícia'),
  ('Mauritânia'),
  ('México'),
  ('Micronésia'),
  ('Moçambique'),
  ('Moldávia'),
  ('Mónaco'),
  ('Mongólia'),
  ('Montenegro'),
  ('Namíbia'),
  ('Nauru'),
  ('Nepal'),
  ('Nicarágua'),
  ('Níger'),
  ('Nigéria'),
  ('Noruega'),
  ('Nova Zelândia'),
  ('Omã'),
  ('Países Baixos'),
  ('Palau'),
  ('Palestina'),
  ('Panamá'),
  ('Papua-Nova Guiné'),
  ('Paquistão'),
  ('Paraguai'),
  ('Peru'),
  ('Polónia'),
  ('Portugal'),
  ('Quénia'),
  ('Quirguistão'),
  ('Reino Unido'),
  ('República Centro-Africana'),
  ('República Checa'),
  ('República Democrática do Congo'),
  ('República Dominicana'),
  ('Roménia'),
  ('Ruanda'),
  ('Rússia'),
  ('Samoa'),
  ('San Marino'),
  ('Santa Lúcia'),
  ('São Cristóvão e Neves'),
  ('São Tomé e Príncipe'),
  ('São Vicente e Granadinas'),
  ('Seicheles'),
  ('Senegal'),
  ('Serra Leoa'),
  ('Sérvia'),
  ('Singapura'),
  ('Síria'),
  ('Somália'),
  ('Sri Lanka'),
  ('Sudão'),
  ('Sudão do Sul'),
  ('Suécia'),
  ('Suíça'),
  ('Suriname'),
  ('Tailândia'),
  ('Taiwan'),
  ('Tajiquistão'),
  ('Tanzânia'),
  ('Timor-Leste'),
  ('Togo'),
  ('Tonga'),
  ('Trindade e Tobago'),
  ('Tunísia'),
  ('Turcomenistão'),
  ('Turquia'),
  ('Tuvalu'),
  ('Ucrânia'),
  ('Uganda'),
  ('Uruguai'),
  ('Usbequistão'),
  ('Vanuatu'),
  ('Vaticano'),
  ('Venezuela'),
  ('Vietname'),
  ('Zâmbia'),
  ('Zimbabué')
on conflict (name) do nothing;
