-- Football clubs from Wikidata (CC0), part 1 of 4. Safe to re-run: a club that already exists (same name and country) is kept and only gets its other names filled in.
-- Run 0023_uk_countries.sql first (it creates Inglaterra, Escocia, etc. and the aliases column).
insert into teams (name, country_id, aliases)
select v.name, c.id, v.aliases
from (values
  ('Ariana Kabul FC', 'Afeganistão', 'Ariana Kabul F.C.'),
  ('Attack Energy SC', 'Afeganistão', null::text),
  ('De Abasin Sape FC', 'Afeganistão', 'De Abasin Sape F.C.'),
  ('De Maiwand Atalan FC', 'Afeganistão', 'De Maiwand Atalan F.C.'),
  ('De Spin Ghar Bazan FC', 'Afeganistão', 'De Spin Ghar Bazan F.C.'),
  ('Hakim Sanayi Kabul FC', 'Afeganistão', 'Hakim Sanayi Kabul F.C. | Hakim Sanayi F.C.'),
  ('Javan Azadi Kabul FC', 'Afeganistão', 'Javan Azadi Kabul F.C.'),
  ('Kabul Bank FC', 'Afeganistão', 'Kabul Bank F.C.'),
  ('Kandahar Aryan', 'Afeganistão', null::text),
  ('Maiwand Kabul FC', 'Afeganistão', 'Maiwand Kabul F.C.'),
  ('Mawjhai Amu FC', 'Afeganistão', 'Mawjhai Amu F.C.'),
  ('Oqaban Hindukush FC', 'Afeganistão', 'Oqaban Hindukush F.C.'),
  ('Ordu Kabul FC', 'Afeganistão', 'Ordu Kabul F.C.'),
  ('Pamir Kabul FC', 'Afeganistão', 'Pamir Kabul F.C.'),
  ('Real Afghan Kabul', 'Afeganistão', null::text),
  ('Sabawoon Kabul FC', 'Afeganistão', null::text),
  ('Sarmi Yashy Kabul FC', 'Afeganistão', 'Sarmi Yashy Kabul F.C.'),
  ('Seramiasht FC', 'Afeganistão', 'Seramiasht F.C.'),
  ('Shaheen Asmayee FC', 'Afeganistão', 'Shaheen Asmayee F.C.'),
  ('Simorgh Alborz FC', 'Afeganistão', 'Simorgh Alborz F.C.'),
  ('Toofaan Harirod FC', 'Afeganistão', 'Toofaan Harirod F.C.'),
  ('AmaZulu FC', 'África do Sul', 'AmaZulu F.C. | AmaZulu'),
  ('Baroka FC', 'África do Sul', 'Baroka F.C. | Baroka'),
  ('Bidvest Wits FC', 'África do Sul', 'Bidvest Wits F.C. | Bidvest Wits | Wits | Wits University F.C. | Wits University FC'),
  ('Black Leopards FC', 'África do Sul', 'Black Leopards F.C. | Black Leopards'),
  ('Bloemfontein Celtic FC', 'África do Sul', 'Bloemfontein Celtic F.C. | Bloemfontein Celtic Football Club | Bloemfontein Celtic | Celtic'),
  ('Bush Bucks FC', 'África do Sul', 'Bush Bucks F.C.'),
  ('Cape Town City FC', 'África do Sul', 'Cape Town City F.C. | Cape Town City | CT City'),
  ('Cape Town Spurs FC', 'África do Sul', 'Cape Town Spurs F.C. | Ajax Cape Town FC | Ajax Cape Town Football Club | Ajax Cape Town'),
  ('Chippa United FC', 'África do Sul', 'Chippa United F.C. | Chippa United | Chippa'),
  ('Free State Stars FC', 'África do Sul', 'Free State Stars F.C. | Free State Stars | FS Stars | Stars | Makwane Computer Stars | Qwa Qwa Stars'),
  ('Jomo Cosmos FC', 'África do Sul', 'Jomo Cosmos F.C. | Jomo Cosmos'),
  ('Kaizer Chiefs FC', 'África do Sul', 'Kaizer Chiefs F.C. | Kaizer Chiefs Football Club | Kaizer Chiefs | Chiefs'),
  ('Lamontville Golden Arrows FC', 'África do Sul', 'Lamontville Golden Arrows F.C. | Golden Arrows F.C. | Golden Arrows | Lamontville Golden Arrows'),
  ('Mamelodi Sundowns FC', 'África do Sul', 'Mamelodi Sundowns F.C. | Mamelodi Sundowns Football Club | Mamelodi Sundowns | Sundowns'),
  ('Manning Rangers FC', 'África do Sul', 'Manning Rangers F.C.'),
  ('Maritzburg United FC', 'África do Sul', 'Maritzburg United F.C. | Maritzburg United | Maritzburg'),
  ('Moroka Swallows FC', 'África do Sul', 'Moroka Swallows F.C.'),
  ('Orlando Pirates FC', 'África do Sul', 'Orlando Pirates F.C. | Orlando Pirates Football Club | Pirates | Orlando Pirates | Orlando Pirates Football Club Natasha FC'),
  ('Platinum Stars FC', 'África do Sul', 'Platinum Stars F.C. | Platinum Stars'),
  ('Polokwane City FC', 'África do Sul', 'Polokwane City F.C. | Polokwane City | Polokwane'),
  ('Santos FC', 'África do Sul', 'Santos F.C.'),
  ('SuperSport United FC', 'África do Sul', 'SuperSport United F.C. | SuperSport United | SuperSport'),
  ('TS Galaxy FC', 'África do Sul', 'TS Galaxy F.C. | The Rockets'),
  ('University of Pretoria FC', 'África do Sul', 'University of Pretoria F.C. | University of Pretoria Football Club | Tuks FC'),
  ('AF Elbasani', 'Albânia', null::text),
  ('Apolonia Fier', 'Albânia', null::text),
  ('Besëlidhja Lezhë', 'Albânia', 'Klubi Sportiv Besëlidhja Lezhë'),
  ('FK Apolonia', 'Albânia', null::text),
  ('FK Kukësi', 'Albânia', null::text),
  ('FK Shënkolli', 'Albânia', null::text),
  ('FK Skrapari', 'Albânia', null::text),
  ('FK Tomori', 'Albânia', null::text),
  ('FK Vora', 'Albânia', null::text),
  ('Flamurtari Vlorë', 'Albânia', null::text),
  ('K.FAda Velipojë', 'Albânia', null::text),
  ('KF Adriatiku Mamurrasi', 'Albânia', 'Klubi i Futbollit Adriatiku Mamurras'),
  ('KF Besa Kavajë', 'Albânia', null::text),
  ('KF Butrinti', 'Albânia', null::text),
  ('KF Egnatia', 'Albânia', null::text),
  ('KF Erzeni', 'Albânia', 'K.F. Erzeni Shijak'),
  ('KF Laçi', 'Albânia', null::text),
  ('KF Memaliaj', 'Albânia', null::text),
  ('KF Skënderbeu', 'Albânia', null::text),
  ('KF Spartaku Tiranë', 'Albânia', null::text),
  ('KF Teuta Durrës', 'Albânia', null::text),
  ('KF Tirana', 'Albânia', 'K.F. Tirana | Tirana Football Club | Tirana F.C. | Tirana FC'),
  ('KF Vlora', 'Albânia', null::text),
  ('Korabi', 'Albânia', null::text),
  ('KS Burreli', 'Albânia', 'Klubi Sportiv Burreli'),
  ('KS Bylis Ballsh', 'Albânia', 'KS Bylis Balls'),
  ('KS Devolli', 'Albânia', null::text),
  ('KS Dinamo Tirana', 'Albânia', 'Klubi Sportiv Dinamo Tirana'),
  ('KS Elbasani', 'Albânia', 'Klubi i Futbollit or KF Elbasani'),
  ('KS Iliria', 'Albânia', 'Klubi Sportiv Iliria Fushë-Krujë'),
  ('KS Kamza', 'Albânia', 'FC Kamza'),
  ('KS Kastrioti', 'Albânia', null::text),
  ('KS Lushnja', 'Albânia', 'Klubi Sportiv Lushnja | Klubi Futbollit Lushnja'),
  ('KS Pogradeci', 'Albânia', 'Klubi Sportiv Pogradeci'),
  ('KS Turbina', 'Albânia', null::text),
  ('KS Vllaznia Shkodër', 'Albânia', null::text),
  ('Luftëtari Gjirokastër', 'Albânia', null::text),
  ('Naftëtari', 'Albânia', null::text),
  ('Partizani Tirana', 'Albânia', null::text),
  ('Shkumbini Peqin', 'Albânia', 'KS Shkumbini Peqin'),
  ('1. FC Frankfurt', 'Alemanha', null::text),
  ('1. FC Heidenheim 1846', 'Alemanha', 'Heidenheim | FCH'),
  ('1. FC Kaiserslautern', 'Alemanha', '1. FCK | FCK | Kaiserslautern'),
  ('1. FC Köln', 'Alemanha', '1. FC Cologne | 1. Fußball-Club Köln 01/07 e. V. | FC Köln | F.C. Köln | FC Koln | F.C. Koln | FCKoln'),
  ('1. FC Magdeburg', 'Alemanha', 'F.C. Magdeburg | 1. FCM | Die Blau-Weißen | Der Club'),
  ('1. FC Nürnberg', 'Alemanha', '1. FC Nurnberg | 1. FCN'),
  ('1. FC Saarbrücken', 'Alemanha', '1.F.C. Saarbrücken'),
  ('1. FC Union Berlin', 'Alemanha', '1. Fußballclub Union Berlin | Berlin FC | FC Union Berlin | FC Berlin | Union Berlin | Die Eisernen | The Iron Ones'),
  ('1. FSV Mainz 05', 'Alemanha', 'Mainz 05 | Mainz | Die Nullfünfer | The Zero-Fivers | FSV Mainz'),
  ('Alemannia Aachen', 'Alemanha', null::text),
  ('Altonaer FC von 1893', 'Alemanha', null::text),
  ('Arminia Bielefeld', 'Alemanha', null::text),
  ('Bayer 04 Leverkusen', 'Alemanha', 'Bayer 04 Leverkusen Fußball GmbH | Bayer Leverkusen | Bayer | Leverkusen | Die Werkself | Bayer 04 Leverkusen Fußball GmbH Soccer | Bayer 04 Football | The Company XI'),
  ('Berliner AK 07', 'Alemanha', 'Berliner Athletik-Klub 07 e. V.'),
  ('BFC Dynamo', 'Alemanha', 'Berliner FC Dynamo | BFC Dynamo Berlin | Dynamo Berlin'),
  ('Blumenthaler SV', 'Alemanha', 'ASV Blumenthal | Blumenthaler Sportverein von 1919 e.V.'),
  ('Bonner SC', 'Alemanha', 'Bonner Sport-Club'),
  ('Borussia Dortmund', 'Alemanha', 'BVB | Dortmund | Die Borussen | Die Schwarzgelben | The Black and Yellows'),
  ('Borussia Mönchengladbach', 'Alemanha', null::text),
  ('Borussia Neunkirchen', 'Alemanha', 'Neunkirchen e.V.'),
  ('BV Cloppenburg', 'Alemanha', null::text),
  ('Chemnitzer FC', 'Alemanha', null::text),
  ('Dynamo Dresden', 'Alemanha', 'SG Dynamo Dresden'),
  ('Eintracht Braunschweig', 'Alemanha', null::text),
  ('Eintracht Frankfurt', 'Alemanha', 'Eintracht Frankfurt e. V. | Frankfurt | Eintracht | Die Adler | The Eagles'),
  ('FC 08 Homburg', 'Alemanha', 'F.C. 08 Homburg'),
  ('FC Augsburg', 'Alemanha', 'Fußball-Club Augsburg 1907 e. V | FC Augsburg Football Team | Fußball-Club Augsburg | FC Augsburg Soccer Team | Augsburg | Die Fuggerstädter'),
  ('FC Bayern Alzenau', 'Alemanha', null::text),
  ('FC Bayern Munich', 'Alemanha', 'Bayern Munich | Bayern Muenchen | Bayern Munchen | FC Bayern Muenchen | FC Bayern Munchen | Bayern | Bayern München | FC Bayern München'),
  ('FC Carl Zeiss Jena', 'Alemanha', null::text),
  ('FC Energie Cottbus', 'Alemanha', null::text),
  ('FC Gütersloh 2000', 'Alemanha', null::text),
  ('FC Hansa Rostock', 'Alemanha', 'F.C. Hansa Rostock'),
  ('FC Ingolstadt 04', 'Alemanha', null::text),
  ('FC Oberneuland', 'Alemanha', null::text),
  ('FC Rot-Weiß Erfurt', 'Alemanha', null::text),
  ('FC St. Pauli', 'Alemanha', 'St. Pauli | Football Club St. Pauli | FCSP | Die Kiezkicker'),
  ('FC Stahl Brandenburg', 'Alemanha', 'BSG Einheit Brandenburg | BSG Stahl Brandenberg | BSV Stahl Brandenburg | Stahl Brandenburg'),
  ('FC Viktoria 1889 Berlin', 'Alemanha', 'FC Viktoria 1889 Berlin Fußball GmbH | FC Viktoria Berlin | Viktoria Berlin'),
  ('FC Viktoria Köln', 'Alemanha', null::text),
  ('FK Pirmasens', 'Alemanha', 'FK 03 Pirmasens'),
  ('Fortuna Düsseldorf', 'Alemanha', 'Fortuna Dusseldorf | Fortuna 95 | Die Fortuna | F95 | Fortuna'),
  ('Freiburger FC', 'Alemanha', 'FFC'),
  ('FSV Frankfurt', 'Alemanha', null::text),
  ('FSV Salmrohr', 'Alemanha', null::text),
  ('FSV Zwickau', 'Alemanha', null::text),
  ('Hallescher FC', 'Alemanha', null::text),
  ('Hamburger SV', 'Alemanha', 'HSV | Hamburger Sport-Verein | Hamburger | Hamburg SV | Hamburg Sport Club | Hamburg | H.S.V. | Hamburger S.V.'),
  ('Hannover 96', 'Alemanha', 'Hannoverscher Sport-Verein von 1896 e.V. | H96 | Hannoveraner'),
  ('Hertha BSC', 'Alemanha', 'Hertha, Berliner Sport-Club e. V | Hertha | Hertha Berlin | Hertha Berliner Sport-Club'),
  ('Holstein Kiel', 'Alemanha', 'Die Störche | The Storks'),
  ('Karlsruher FV', 'Alemanha', null::text),
  ('Karlsruher SC', 'Alemanha', 'KSC'),
  ('KFC Uerdingen 05', 'Alemanha', null::text),
  ('Kickers Emden', 'Alemanha', null::text),
  ('Kickers Offenbach', 'Alemanha', null::text),
  ('KSV Hessen Kassel', 'Alemanha', 'KSV Hessen | VfL Hessen Kassel | FC Hessen Kassel | Hessen Kassel'),
  ('MSV Duisburg', 'Alemanha', 'Meidericher Spielverein Duisburg 02 e.V'),
  ('RB Leipzig', 'Alemanha', 'RasenBallsport Leipzig e.V. | Die Roten Bullen | The Red Bulls'),
  ('Rot Weiss Ahlen', 'Alemanha', null::text),
  ('Rot-Weiss Essen', 'Alemanha', null::text),
  ('Rot-Weiß Oberhausen', 'Alemanha', null::text),
  ('SC Fortuna Köln', 'Alemanha', null::text),
  ('SC Freiburg', 'Alemanha', 'Sport Club Freiburg | Sport-Club Freiburg e.V. | S.C. Freiburg | Die Breisgau-Brasilianer | The Breisgau Brazilians'),
  ('SC Paderborn 07', 'Alemanha', 'Sport-Club Paderborn 07 e.V. | SCP 07 | Paderborn 07 | Die Ostwestfalen'),
  ('SC Preußen Münster', 'Alemanha', 'Die Adler | Preussen Munster | SC Preussen Munster'),
  ('SC Verl', 'Alemanha', null::text),
  ('SC Victoria Hamburg', 'Alemanha', null::text),
  ('Schalke 04', 'Alemanha', 'FC Gelsenkirchen-Schalke 04 | S04 | FC Schalke 04 | F.C. Schalke 04 | Schalke04 | Schalke 0'),
  ('Schwarz-Weiß Essen', 'Alemanha', null::text),
  ('SG Sonnenhof Großaspach', 'Alemanha', null::text),
  ('SG Wattenscheid 09', 'Alemanha', null::text),
  ('Sportfreunde Lotte', 'Alemanha', null::text),
  ('Sportfreunde Siegen', 'Alemanha', 'SF Siegen'),
  ('SpVgg Bayreuth', 'Alemanha', null::text),
  ('SpVgg Greuther Fürth', 'Alemanha', 'Greuther Furth | Greuther Fürth | Greuther | SGF'),
  ('SpVgg Unterhaching', 'Alemanha', 'Spielvereinigung Unterhaching'),
  ('SSV Jahn Regensburg', 'Alemanha', 'SSV Regensburg | SSV Jahn'),
  ('SSV Reutlingen 05', 'Alemanha', null::text),
  ('SSV Ulm 1846 Fußball', 'Alemanha', null::text),
  ('Stuttgarter Kickers', 'Alemanha', 'S.V. Stuttgarter Kickers | Sportverein Stuttgarter Kickers e. V.'),
  ('SV Babelsberg 03', 'Alemanha', null::text),
  ('SV Darmstadt 98', 'Alemanha', 'S.V. Darmstadt 98'),
  ('SV Eintracht Trier 05', 'Alemanha', 'Eintracht Trier'),
  ('SV Elversberg', 'Alemanha', 'SV 07 Elversberg | Elversberg'),
  ('SV Meppen', 'Alemanha', null::text),
  ('SV Sandhausen', 'Alemanha', 'SV Sandhausen 1916'),
  ('SV Türkgücü-Ataspor München', 'Alemanha', null::text),
  ('SV Waldhof Mannheim', 'Alemanha', 'S.V. Waldhof Mannheim | Sportverein Waldhof Mannheim e.V.'),
  ('SV Wehen Wiesbaden', 'Alemanha', null::text),
  ('SV Werder Bremen', 'Alemanha', 'Werder Bremen | Werder | Die Werderaner | Die Grün-Weißen | The Green-Whites'),
  ('SV Wilhelmshaven', 'Alemanha', 'Sport-Verein Wilhelmshaven Germania 1905'),
  ('Tennis Borussia Berlin', 'Alemanha', 'TeBe'),
  ('TSG 1899 Hoffenheim', 'Alemanha', 'TSG Hoffenheim | 1899 Hoffenheim II | 1899 Hoffenheim | TSG Hoffenheim II | Hoffenheim | Die Kraichgauer'),
  ('TSG Neustrelitz', 'Alemanha', null::text),
  ('TSV 1860 München', 'Alemanha', '1860 Munich'),
  ('TSV Havelse', 'Alemanha', null::text),
  ('Türkiyemspor Berlin', 'Alemanha', null::text),
  ('TuS Koblenz', 'Alemanha', null::text),
  ('VfB Lübeck', 'Alemanha', null::text),
  ('VfB Oldenburg', 'Alemanha', null::text),
  ('VfB Stuttgart', 'Alemanha', 'Die Schwaben | The Swabians'),
  ('VfL Bochum', 'Alemanha', 'VfL Bochum 1848 | Die Unabsteigbaren | The Unrelegatables'),
  ('VfL Osnabrück', 'Alemanha', null::text),
  ('VfL Wolfsburg', 'Alemanha', 'Wolfsburg | Die Wölfe | The Wolves'),
  ('VfR Aalen', 'Alemanha', null::text),
  ('VfR Mannheim', 'Alemanha', null::text),
  ('Viktoria Aschaffenburg', 'Alemanha', null::text),
  ('Wormatia Worms', 'Alemanha', null::text),
  ('Wuppertaler SV', 'Alemanha', 'Wuppertaler SV Borussia | Wuppertaler Sportverein'),
  ('Würzburger Kickers', 'Alemanha', null::text),
  ('Atlètic Club d''Escaldes', 'Andorra', 'Atlètic Escaldes | Atletic Escaldes'),
  ('CE Benito', 'Andorra', null::text),
  ('CE Carroi', 'Andorra', null::text),
  ('CF Atlètic Amèrica', 'Andorra', null::text),
  ('CF Esperança d''Andorra', 'Andorra', null::text),
  ('Deportivo La Massana', 'Andorra', null::text),
  ('FC Andorra', 'Andorra', 'Football Club Andorra | Andorra Football Club | Andorra FC | president Ferran Vilaseca'),
  ('FC Andorra Veterans', 'Andorra', null::text),
  ('FC Encamp', 'Andorra', null::text),
  ('FC Ordino', 'Andorra', null::text),
  ('FC Pas de la Casa', 'Andorra', 'Pas de la Casa'),
  ('FC Rànger''s', 'Andorra', 'FC Ranger''s | Restaurant Camping Valira'),
  ('FC Santa Coloma', 'Andorra', null::text),
  ('FS La Massana', 'Andorra', null::text),
  ('Futbol Club Penya d''Andorra', 'Andorra', null::text),
  ('GALAXY FCI JENLAI', 'Andorra', null::text),
  ('Inter Club d''Escaldes', 'Andorra', null::text),
  ('UE Engordany', 'Andorra', null::text),
  ('UE Extremenya', 'Andorra', null::text),
  ('UE Sant Julià', 'Andorra', 'UE Sant Julia'),
  ('UE Santa Coloma', 'Andorra', null::text),
  ('Académica Petróleo Kwanda Soyo', 'Angola', 'Academica Petroleo Kwanda Soyo'),
  ('Académica Petróleos do Lobito', 'Angola', 'Academica Petroleos do Lobito'),
  ('Atlético Petróleos do Huambo', 'Angola', 'Atletico Petroleos do Huambo'),
  ('Atlético Petróleos do Namibe', 'Angola', 'Atletico Petroleos do Namibe'),
  ('Atlético Petróleos Luanda', 'Angola', 'Atletico Petroleos Luanda'),
  ('Atlético Sport Aviação', 'Angola', null::text),
  ('CD Huíla', 'Angola', 'C.D. Huíla | C.D. Huila'),
  ('CD São Salvador', 'Angola', 'C.D. São Salvador'),
  ('Clube Atlético de Luanda', 'Angola', null::text),
  ('Clube Desportivo Primeiro de Agosto', 'Angola', 'Primeiro de Agosto Football'),
  ('CR Caála', 'Angola', 'C.R. Caála | C.R. Caala'),
  ('CRD Libolo', 'Angola', 'C.R.D. Libolo'),
  ('Domant FC', 'Angola', null::text),
  ('Estrela Clube Primeiro de Maio', 'Angola', null::text),
  ('FC Casa Militar', 'Angola', 'F.C. Casa Militar | GD Casa Militar'),
  ('FC Desportivo 4 de Abril', 'Angola', null::text),
  ('FC Luanda', 'Angola', 'F.C. Luanda'),
  ('FC Onze Bravos', 'Angola', 'F.C. Onze Bravos | Futebol Clube Onze Bravos do Maquis | Bravos do Maquis'),
  ('GD Interclube', 'Angola', 'G.D. Interclube | Grupo Desportivo Interclube | Inter Luanda'),
  ('GD Sagrada Esperança', 'Angola', 'G.D. Sagrada Esperança'),
  ('Grupo Desportivo Atlético Juventude do Moxico', 'Angola', null::text),
  ('Guelson F. C.', 'Angola', null::text),
  ('Isaac de Benguela F. C.', 'Angola', null::text),
  ('JGM ASC Huambo', 'Angola', 'J.G.M. A.S.C. Huambo | G.D. Jorge Gomes Mangrinha'),
  ('Kabuscorp SC', 'Angola', 'Kabuscorp S.C. | Kabuscorp Sport Clube do Palanca'),
  ('Porcelana Futebol Clube do Cazengo', 'Angola', null::text),
  ('Progresso Associação do Sambizanga', 'Angola', null::text),
  ('Progresso da Lunda Sul', 'Angola', null::text),
  ('Real M''buco', 'Angola', null::text),
  ('Redonda FC', 'Angola', null::text),
  ('Santa Rita de Cássia FC', 'Angola', 'Santa Rita de Cássia Futebol Clube'),
  ('Santos Futebol Clube de Angola', 'Angola', null::text),
  ('SL Benfica', 'Angola', 'S.L. Benfica | Sport Luanda e Benfica'),
  ('Sporting Clube de Luanda', 'Angola', null::text),
  ('Sporting Clube Petróleos de Cabinda', 'Angola', 'Sporting Clube Petroleos de Cabinda'),
  ('União Sport Clube do Uíge', 'Angola', null::text),
  ('Abha', 'Arábia Saudita', null::text),
  ('Al Ahli FC', 'Arábia Saudita', 'Al Ahli Jeddah | Al Ahli Saudi FC | Al Ahli Saudi | Al Ahli Sports Club | Al Ahli Football Club | Al Ahli Jeddah FC'),
  ('Al Fateh SC', 'Arábia Saudita', null::text),
  ('Al Hazem SC', 'Arábia Saudita', null::text),
  ('Al Hilal SFC', 'Arábia Saudita', 'نادي الهلال السعودي | AlHilal SFC | AlHilal | Al-Hilal SFC | AlHilal Saudi Club | Al Hilal Saudi Club | Al-Hilal Saudi Club | Al Hilal SC'),
  ('Al Ittihad FC', 'Arábia Saudita', 'Al-Ittihad Football Club | Al-Ittihad Club Saudi Arabia | Al-Ittihad Jeddah | Ittihad FC | Al-Ittihad'),
  ('Al Jabalain', 'Arábia Saudita', null::text),
  ('Al Okhdood Club', 'Arábia Saudita', 'Al Okhdood'),
  ('Al Qadsiah FC', 'Arábia Saudita', 'Qadsiah FC | Qadsiah SC | AlQadsiah | Al-Qadsiah FC | Al-Qadsiah Saudi Club of Kings | Al-Qadsiah Saudi Club | AlQadsiah SC | Al-Qadsiah SC'),
  ('Al Wehda FC', 'Arábia Saudita', 'Al-Wehda FC'),
  ('Al-Adalh FC', 'Arábia Saudita', null::text),
  ('Al-Ain FC', 'Arábia Saudita', null::text),
  ('Al-Ansar', 'Arábia Saudita', null::text),
  ('Al-Batin', 'Arábia Saudita', null::text),
  ('Al-Diriyah Club', 'Arábia Saudita', null::text),
  ('Al-Ettifaq FC', 'Arábia Saudita', 'Al-Ettifaq | Ettifaq Dammam | Ettifaq FC'),
  ('Al-Faisaly FC', 'Arábia Saudita', null::text),
  ('Al-Feiha FC', 'Arábia Saudita', null::text),
  ('Al-Khaleej FC', 'Arábia Saudita', 'Khaleej FC | Al-Khaleej Club of Saihat'),
  ('Al-Kholood', 'Arábia Saudita', null::text),
  ('Al-Najma', 'Arábia Saudita', null::text),
  ('Al-Nassr', 'Arábia Saudita', 'Al Nassr | Al Nassr FC | Al-Nassr F.C. | Al Nassr Football Club'),
  ('Al-Orobah FC', 'Arábia Saudita', 'Al-Orobah F.C.'),
  ('Al-Raed FC', 'Arábia Saudita', 'Al-Ra''ed'),
  ('Al-Riyadh SC', 'Arábia Saudita', null::text),
  ('Al-Shabab Football Club', 'Arábia Saudita', 'Al Shabab | Al Shabab FC'),
  ('Al-Shoalah', 'Arábia Saudita', null::text),
  ('Al-Taawon FC', 'Arábia Saudita', 'Al-Taawoun FC'),
  ('Al-Tai FC', 'Arábia Saudita', null::text),
  ('Al-Zulfi FC', 'Arábia Saudita', null::text),
  ('Damac Club', 'Arábia Saudita', 'Damac FC'),
  ('Hajer Club', 'Arábia Saudita', null::text),
  ('Najran SC', 'Arábia Saudita', 'Najran Sport Club'),
  ('Neom SC', 'Arábia Saudita', 'Neom Sports Club | Al-Suqoor Club'),
  ('Ohod Club', 'Arábia Saudita', 'Ohud Medina | Ohob Club | Ohod Saudi Football Club'),
  ('AS Khroub', 'Argélia', null::text),
  ('ASM Oran', 'Argélia', 'Association Sportive Madinet Oran | ASMO | Association Sportive Madinet d''Oran'),
  ('ASO Chlef', 'Argélia', 'Shlef Olimpie'),
  ('CA Batna', 'Argélia', null::text),
  ('CA Bordj Bou Arréridj', 'Argélia', 'Chabab Ahly Bordj Bou Arreridj | CA Bordj Bou Arreridj'),
  ('CMB Thénia', 'Argélia', 'CMBT'),
  ('CR Belouizdad', 'Argélia', 'CRB | Chabab Riadhi Belouizdad'),
  ('CS Constantine', 'Argélia', null::text),
  ('DRB Tadjenanet', 'Argélia', null::text),
  ('ES Sétif', 'Argélia', 'ES Setif | ES Setifienne | ESS | ES Sétifienne | Entente Sportive Sétifienne | Entente Sportive Setifienne | E.S.S | E.S. Sétif'),
  ('JS Kabylie', 'Argélia', 'JSK | J.S.K | Jeunesse Sportive de Kabylie | JSK 1946 | J.S.K 1946 | JSKabylie | J.S. Kabylie'),
  ('JS Saoura', 'Argélia', 'Jeunesse Sportive Saoura | JSS'),
  ('JSM Béjaïa', 'Argélia', null::text),
  ('MC Algiers', 'Argélia', 'Mouloudia | Mouloudia of Algiers | MCA | Mouloudia Club Algiers | Mouloudia Chaabia | Mouloudia Club d''Alger | Mouloudia CA | M.C.A.'),
  ('MC El Eulma', 'Argélia', null::text),
  ('MC Saïda', 'Argélia', null::text),
  ('Medea Olympic', 'Argélia', 'Olympic of Medea'),
  ('MO Béjaïa', 'Argélia', 'MO Bejaia | Mouloudia Olympique de Béjaïa'),
  ('MO Constantine', 'Argélia', null::text),
  ('Mouloudia Club of Oran', 'Argélia', 'Mouloudia of Oran | MC Oran'),
  ('NA Hussein Dey', 'Argélia', 'NAHD | Nasria | The NAHD'),
  ('NC Magra', 'Argélia', 'NCM MAGRA'),
  ('Paradou AC', 'Argélia', null::text),
  ('RC Kouba', 'Argélia', 'Raed Chabab Kouba | Raed Kouba | RCK'),
  ('Union Sportive Madinet El Harrach', 'Argélia', 'USM El Harrach | USMH'),
  ('US Souf', 'Argélia', null::text),
  ('USM Alger', 'Argélia', 'Union Sportive Médina d''Alger | USMA | USMAlger | U.S.M.A.'),
  ('USM Bel-Abbès', 'Argélia', 'USM Bel-Abbes'),
  ('USM Blida', 'Argélia', 'USMB | Union Sportive Madinet Blida | Union of Blida'),
  ('WA Tlemcen', 'Argélia', null::text),
  ('Argentino de Quilmes', 'Argentina', null::text),
  ('Argentinos Juniors', 'Argentina', 'Asociacion Atletica Argentinos Juniors'),
  ('Atlético Tucumán', 'Argentina', 'Atletico Tucuman'),
  ('Club Agropecuario Argentino', 'Argentina', 'Agropecuario Club'),
  ('Club Almagro', 'Argentina', null::text),
  ('Club Almirante Brown', 'Argentina', 'Almirante Brown de Isidro Casanova'),
  ('Club Atlético Aldosivi', 'Argentina', 'Aldosivi | Aldosivi de Mar del Plata'),
  ('Club Atlético Argentino del Sud', 'Argentina', null::text),
  ('Club Atlético Atlanta', 'Argentina', 'Club Atletico Atlanta'),
  ('Club Atlético Banfield', 'Argentina', null::text),
  ('Club Atlético Brown', 'Argentina', 'Club Atletico Brown | Brown de Adrogue'),
  ('Club Atlético Chaco For Ever', 'Argentina', 'Chaco For Ever | T Chacal'),
  ('Club Atlético Colón', 'Argentina', 'Colón de Santa Fe'),
  ('Club Atlético Huracán', 'Argentina', 'Huracan de Parque Patricios | Club Atletico Huracan'),
  ('Club Atlético Independiente', 'Argentina', 'CA Independiente | Independiente de Avellaneda | Independiente'),
  ('Club Atlético Juventud Unida Universitario', 'Argentina', null::text),
  ('Club Atlético Lanús', 'Argentina', 'Club Atletico Lanus | Club Lanus'),
  ('Club Atlético Los Andes', 'Argentina', 'Club Atletico Los Andes'),
  ('Club Atlético Mitre', 'Argentina', 'Mitre de Santiago del Estero | Mitre SdE | Atlético Mitre | Mitre | CA Mitre | CAM | Mitre (Santiago del Estero)'),
  ('Club Atlético Nueva Chicago', 'Argentina', 'Club Atletico Nueva Chicago'),
  ('Club Atlético River Plate', 'Argentina', 'River Plate | CA River Plate | C.A. River Plate | River | RiverPlate | CARP | C.A.R.P.'),
  ('Club Atlético Rosario Central', 'Argentina', 'Club Atletico Rosario Central | Rosario Central'),
  ('Club Atlético Talleres de Remedios de Escalada', 'Argentina', 'Talleres RE | Talleres de Remedios de Escalada'),
  ('Club Atlético Tigre', 'Argentina', 'Club Atletico Tigre'),
  ('Club Atlético Vélez Sarsfield', 'Argentina', 'Club Atletico Velez Sarsfield | Velez Sarsfield'),
  ('Club Deportivo Morón', 'Argentina', 'Deportivo Moron | Club Deportivo Moron | Deportivo Morón'),
  ('Club Social y Atlético Guillermo Brown', 'Argentina', 'Guillermo Brown de Puerto Madryn'),
  ('Club Social y Deportivo Flandria', 'Argentina', 'Flandria Club'),
  ('Club Tristán Suárez', 'Argentina', 'Club Tristan Suarez | CSD Tristan Suarez'),
  ('Club y Biblioteca Ramón Santamarina', 'Argentina', 'Club y Biblioteca Ramon Santamarina | Deportivo Santamarina | Club Ramon Santamarina'),
  ('Crucero del Norte Mutual Club', 'Argentina', 'Northern Cruise | Northern Cruise Club'),
  ('Defensa y Justicia', 'Argentina', null::text),
  ('Defensores Unidos', 'Argentina', 'Club Atlético Defensores Unidos'),
  ('Deportivo Armenio', 'Argentina', null::text),
  ('Deportivo Español', 'Argentina', null::text),
  ('Deportivo Riestra', 'Argentina', null::text),
  ('Estudiantes de La Plata', 'Argentina', 'Estudiantes LP | Club Estudiantes de La Plata'),
  ('Ferro Carril Oeste', 'Argentina', 'Club Ferro Carril Oeste'),
  ('Gimnasia y Esgrima de Jujuy', 'Argentina', 'GyE Jujuy | Gimnasia de Jujuy'),
  ('Gimnasia y Esgrima de Mendoza', 'Argentina', 'GyE Mendoza | Gimnasia de Mendoza'),
  ('Godoy Cruz Antonio Tomba', 'Argentina', 'Godoy Cruz de Mendoza'),
  ('Independiente Rivadavia', 'Argentina', 'Indesingente RiBadavia'),
  ('Instituto Atlético Central Córdoba', 'Argentina', 'Instituto de Cordoba | Instituto Atletico Central Cordoba | Instituto (Cba)'),
  ('Juventud Unida de Gualeguaychú', 'Argentina', 'Juventud Unida de Gualeguaychu | Club Deportivo Juventud Unida'),
  ('Newell''s Old Boys', 'Argentina', 'Newells Old Boys'),
  ('Quilmes Atlético Club', 'Argentina', 'Quilmes Atletico Club | Quilmes AC | Quilmes Athletic Club'),
  ('Racing Club', 'Argentina', 'Racing Club de Avellaneda | Racing Club Avellaneda | Racing Avellaneda'),
  ('Racing de Córdoba', 'Argentina', 'Racing de Cordoba'),
  ('Real Madrid', 'Argentina', 'Rosario central | Rosariocentral'),
  ('San Martín de San Juan', 'Argentina', 'San Martin de San Juan'),
  ('Sarmiento', 'Argentina', 'Olimpo de Bahia Blanca | Club Olimpo de Bahia Blanca'),
  ('Sportivo Dock Sud', 'Argentina', null::text),
  ('Talleres de Córdoba', 'Argentina', 'Talleres de Cordoba | Club Atlético Talleres'),
  ('Tiro al aire', 'Argentina', 'Club Atletico Tiro Federal Argentino | Tiro Federal de Rosario'),
  ('Unión de Santa Fe', 'Argentina', 'Union de Santa Fe | Club Atletico Unión'),
  ('Villa Dálmine', 'Argentina', 'Villa Dalmine | Club Villa Dálmine | Atletico Campana'),
  ('Alashkert FC', 'Arménia', 'Alashkert Martuni'),
  ('BKMA Yerevan', 'Arménia', null::text),
  ('FC Ararat Yerevan', 'Arménia', null::text),
  ('FC Ararat-Armenia', 'Arménia', 'Ararat-Moscow Yerevan | Ararat-Moskva Yerevan'),
  ('FC Mika', 'Arménia', 'Football Club Mika'),
  ('FC Noah', 'Arménia', 'Football Club Noah | F.C. Noah | FC Artsakh'),
  ('FC Pyunik', 'Arménia', 'Football Club Pyunik'),
  ('FC Urartu', 'Arménia', 'Football Club Banants | FC Banants'),
  ('FC Van', 'Arménia', null::text),
  ('FC West Armenia', 'Arménia', null::text),
  ('Gandzasar-Kapan FC', 'Arménia', null::text),
  ('Junior Sevan FC', 'Arménia', null::text),
  ('Lernayin Artsakh Stepanakert', 'Arménia', null::text),
  ('Noravank SC', 'Arménia', null::text),
  ('Shirak FC', 'Arménia', null::text),
  ('SV River Plate Aruba', 'Aruba', null::text),
  ('Adelaide City Football Club', 'Austrália', 'Zebras'),
  ('Adelaide United FC', 'Austrália', null::text),
  ('Adelaide United Football Club', 'Austrália', 'Adelaide United | Adelaide United F.C. | Adelaide United FC'),
  ('APIA Leichhardt', 'Austrália', 'APIA club'),
  ('Brisbane Roar FC', 'Austrália', 'Brisbane Roar Women | Brisbane Roar | Roar | Roar Women'),
  ('Central Coast Mariners FC', 'Austrália', 'Central Coast Mariners Football Club | Central Coast Mariners | CCMFC | Mariners'),
  ('Gold Coast United FC', 'Austrália', null::text),
  ('Macarthur FC', 'Austrália', 'Macarthur South West United FC | Macarthur Football Club | Macarthur Bulls FC | Macarthur Bulls | Macarthur Bulls Football Club'),
  ('Marconi Stallions FC', 'Austrália', null::text),
  ('Melbourne City FC', 'Austrália', 'Melbourne City Women''s Football Club | Melbourne City Women | Melbourne City | City Women'),
  ('Melbourne Knights Football Club', 'Austrália', null::text),
  ('Melbourne Victory FC', 'Austrália', 'Melbourne Victory | Melbourne Victory Football Club | Melbourne Victory F.C.'),
  ('Newcastle Jets FC', 'Austrália', 'Newcastle United Jets Football Club | Newcastle United Jets FC | Newcastle United Jets | NUJFC | The Jets'),
  ('Perth Glory FC', 'Austrália', 'Perth Glory Football Club | Perth Glory F.C. | Perth | Glory | The Glory | PGFC | Perth Glory'),
  ('South Melbourne Football Club', 'Austrália', 'South Melbourne FC'),
  ('Sydney FC', 'Austrália', 'Sydney FC Women | Sydney Football Club | Sydney Football Club Women'),
  ('Sydney Olympic FC', 'Austrália', null::text),
  ('Sydney United FC', 'Austrália', null::text),
  ('Western Sydney Wanderers FC', 'Austrália', 'Western Sydney Wanderers | WSW | Western Sydney | Western Sydney Wanderers Women | WSW Women | Western Sydney Women | WSWFC | WSWFCW'),
  ('Western United FC', 'Austrália', 'Western United | Western Melbourne FC'),
  ('Wollongong Wolves FC', 'Austrália', 'Wollongong City F.C. | Wollongong F.C. | Wollongong Community F.C. | Wollongong Wolves | Wollongong Wolves Football Club | South Coast Wolves FC'),
  ('1. Simmeringer SC', 'Áustria', null::text),
  ('Admira Wacker', 'Áustria', 'SK Admira Wien | FC Admira Wacker Mödling | AdmiraWacker'),
  ('Brigittenauer AC', 'Áustria', null::text),
  ('DSV Leoben', 'Áustria', null::text),
  ('FC Blau-Weiß Linz', 'Áustria', 'F.C. Blau-Weiß Linz | FC Blau-WeiÃŸ Linz | Blau-WeiÃŸ Linz | BW Linz | FC BW Linz'),
  ('FC Gratkorn', 'Áustria', null::text),
  ('FC Juniors OÖ', 'Áustria', 'FC Pasching | Fußballklub Superfund Pasching | FC Juniors OÖ.'),
  ('FC Liefering', 'Áustria', null::text),
  ('FC Lustenau 07', 'Áustria', null::text),
  ('FC Red Bull Salzburg', 'Áustria', 'Red Bull Salzburg | Football Club Red Bull Salzburg | Red Bull | Salzburg | FCRBS'),
  ('FC Wacker Innsbruck', 'Áustria', null::text),
  ('FC Wien', 'Áustria', null::text),
  ('First Vienna FC', 'Áustria', 'First Vienna F.C. 1894 | First Vienna Football Club 1894'),
  ('FK Austria Wien', 'Áustria', 'Fußballklub Austria Wien | Austria Vienna'),
  ('Floridsdorfer AC', 'Áustria', 'Floridsdorfer A.C.'),
  ('Grazer AK', 'Áustria', 'Grazer A.K. | Grazer Athletik-Klub | GAK | GAK 1902 | Grazer AK FuÃŸball | Grazer AK 1902'),
  ('Kapfenberger SV', 'Áustria', 'SV Kapfenberg | Kapfenberger SV 1919'),
  ('Kremser SC', 'Áustria', null::text),
  ('LASK Linz', 'Áustria', 'Linzer Athletik-Sport-Klub | Linzer ASK | LASK | L.A.S.K. Linz'),
  ('SC Austria Lustenau', 'Áustria', null::text),
  ('SC Rheindorf Altach', 'Áustria', null::text),
  ('SC Schwarz-Weiß Bregenz', 'Áustria', 'SC Bregenz'),
  ('SC Wacker Wien', 'Áustria', null::text),
  ('SC Wiener Neustadt', 'Áustria', 'SC Magna Wiener Neustadt'),
  ('SK Admira Wien', 'Áustria', null::text),
  ('SK Austria Klagenfurt', 'Áustria', 'Austria Klagenfurt | SKAK | Klagenfurt | Austria Klagenfurt FuÃŸball'),
  ('SK Rapid Wien', 'Áustria', 'Rapid Wien | Rapid Vienna | Sportklub Rapid Wien'),
  ('SK Sturm Graz', 'Áustria', null::text),
  ('SK Vorwärts Steyr', 'Áustria', null::text),
  ('SKN St. Pölten', 'Áustria', 'Sportklub Niederösterreich St. Pölten'),
  ('SV Austria Salzburg', 'Áustria', 'SV Salzburg | Austria Salzburg'),
  ('SV Grödig', 'Áustria', null::text),
  ('SV Horn', 'Áustria', null::text),
  ('SV Lafnitz', 'Áustria', null::text),
  ('SV Ried', 'Áustria', null::text),
  ('TSV Hartberg', 'Áustria', 'Hartberg'),
  ('Union Kleinmünchen Linz', 'Áustria', 'Union Kleinmünchen'),
  ('Vienna Cricket and Football-Club', 'Áustria', null::text),
  ('VSE St. Pölten', 'Áustria', null::text),
  ('Wiener Sport-Club', 'Áustria', null::text),
  ('Wolfsberger AC', 'Áustria', null::text),
  ('WSG Tirol', 'Áustria', 'WSG Wattens | Wattens | WSG Swarovski Tirol'),
  ('Young Violets Austria Wien', 'Áustria', 'Austria Wien II'),
  ('Ağsu FK', 'Azerbaijão', null::text),
  ('Araz PFK', 'Azerbaijão', 'Araz-Naxçıvan PFK'),
  ('Araz Saatli', 'Azerbaijão', 'Saatli-Araz | Saatli Araz | Saatly-Araz'),
  ('Avtomobilçi Yevlax FK', 'Azerbaijão', null::text),
  ('Azeri Baku FK', 'Azerbaijão', null::text),
  ('Bakili Baku', 'Azerbaijão', null::text),
  ('Baku Sporting', 'Azerbaijão', null::text),
  ('Bine FK', 'Azerbaijão', null::text),
  ('Çıraqqala Siyəzən FK', 'Azerbaijão', null::text),
  ('Difai FK', 'Azerbaijão', null::text),
  ('Energetik FC', 'Azerbaijão', null::text),
  ('FC Absheron', 'Azerbaijão', null::text),
  ('FC Shahdag Qusar', 'Azerbaijão', null::text),
  ('FK Daşqın Zaqatala', 'Azerbaijão', null::text),
  ('FK Gänclärbirliyi Sumqayit', 'Azerbaijão', null::text),
  ('FK Göyazan Qazax', 'Azerbaijão', 'Göyazan Qazakh FK'),
  ('FK Karvan', 'Azerbaijão', null::text),
  ('FK Masallı', 'Azerbaijão', null::text),
  ('FK MKT Araz', 'Azerbaijão', null::text),
  ('FK Neftqaz Bakı', 'Azerbaijão', null::text),
  ('FK Pambiqci Neftcala', 'Azerbaijão', null::text),
  ('FK Qaradağ', 'Azerbaijão', null::text),
  ('FK Şərurspor', 'Azerbaijão', null::text),
  ('FK Shamkir', 'Azerbaijão', null::text),
  ('Gabala FC', 'Azerbaijão', null::text),
  ('Ganjabasar FC', 'Azerbaijão', null::text),
  ('Imishli', 'Azerbaijão', null::text),
  ('Kapaz PFC', 'Azerbaijão', null::text),
  ('Kürmük Qakh FK', 'Azerbaijão', null::text),
  ('MOIK Baku', 'Azerbaijão', null::text),
  ('Neftchi Baku PFC', 'Azerbaijão', null::text),
  ('Plastik Salyan FK', 'Azerbaijão', null::text),
  ('Qarabağ FK', 'Azerbaijão', 'FK Qarabağ | Qarabagh FC | Qarabagh | Qarabağ | Qarabağ Futbol Klubu | Qarabagh Football Club | FC Qarabagh | The Horsemen'),
  ('Ravan Baku FC', 'Azerbaijão', null::text),
  ('Sabah Football Club', 'Azerbaijão', 'Sabah FK | Sabah FC'),
  ('Səbail FK', 'Azerbaijão', 'FK Sabail | Sabail FK'),
  ('Shamakhi FK', 'Azerbaijão', 'Inter Baku PFC | Keşla FK'),
  ('Sharurspor PFK', 'Azerbaijão', null::text),
  ('Shirvan FK', 'Azerbaijão', null::text),
  ('Şirvan Kürdəmir FK', 'Azerbaijão', null::text),
  ('Şirvan Şamaxı FK', 'Azerbaijão', null::text),
  ('Sumgayit PFC', 'Azerbaijão', 'Sumgayit FK'),
  ('Turan Tovuz PFK', 'Azerbaijão', null::text),
  ('Ümid FK', 'Azerbaijão', null::text),
  ('Zagatala PFK', 'Azerbaijão', null::text),
  ('Zira FK', 'Azerbaijão', 'Zirə Futbol Klubu'),
  ('Abahani Limited Dhaka', 'Bangladeche', 'Abahani Krirachakra | Abahani | Dhaka Abahani | Abahani Krira Chakra'),
  ('Arambagh Krira Sangha', 'Bangladeche', null::text),
  ('Bashundhara Kings', 'Bangladeche', 'The Kings | Kings | দ্যা কিংস'),
  ('Brothers Union', 'Bangladeche', null::text),
  ('Chittagong Mohammedan SC', 'Bangladeche', null::text),
  ('Feni Soccer Club', 'Bangladeche', null::text),
  ('Mohammedan SC', 'Bangladeche', 'Mohammedan Sporting Club (Dhaka) | Dhaka Mohammedan | Mohammedan SC (Dhaka)'),
  ('Muktijoddha Sangsad KC', 'Bangladeche', null::text),
  ('Narayanganj Suktara Sangsad', 'Bangladeche', null::text),
  ('Rahmatganj MFS', 'Bangladeche', null::text),
  ('Saif Sporting Club', 'Bangladeche', null::text),
  ('Sheikh Jamal Dhanmondi Club', 'Bangladeche', null::text),
  ('Sheikh Russel KC', 'Bangladeche', null::text),
  ('Team BJMC', 'Bangladeche', null::text),
  ('Uttar Baridhara SC', 'Bangladeche', null::text),
  ('Al Ettihad Club', 'Barém', null::text),
  ('Al Hala SC', 'Barém', null::text),
  ('Al-Khaldiya SC', 'Barém', 'Al-Khaldiya'),
  ('Al-Muharraq SC', 'Barém', null::text),
  ('Al-Najma', 'Barém', null::text),
  ('Al-Shabab Club', 'Barém', null::text),
  ('Bahrain SC', 'Barém', 'Al-Bahrain Sports Club'),
  ('Busaiteen Club', 'Barém', null::text),
  ('East Riffa Club', 'Barém', null::text),
  ('Hidd SCC', 'Barém', 'Hidd Sports and Cultural Club'),
  ('Malkiya Club', 'Barém', null::text),
  ('Manama Club', 'Barém', null::text),
  ('Riffa SC', 'Barém', 'Riffa S.C. | Al-Riffa Sports Club'),
  ('Cercle Brugge KSV', 'Bélgica', 'Cercle Brugge K.S.V. | Cercle Brugge'),
  ('Club Brugge KV', 'Bélgica', 'Club Brugge K.V. | Club Brugge | Club Bruges | Club Bruges KV'),
  ('FC Verbroedering Dender Eendracht Hekelgem', 'Bélgica', 'F.C. Verbroedering Dender Eendracht Hekelgem | FCV Dender EH | F.C.V. Dender E.H.'),
  ('K Beerschot VA', 'Bélgica', 'K. Beerschot V.A. | Beerschot VA | KFCO Wilrijk | KFCO Beerschot Wilrijk | Beerschot Voetbalclub Antwerpen | Beerschot'),
  ('K. Berchem Sport', 'Bélgica', null::text),
  ('K. Patro Eisden Maasmechelen', 'Bélgica', null::text),
  ('K. Tubantia Borgerhout VK', 'Bélgica', 'K. Tubantia Borgerhout V.K.'),
  ('KAA Gent', 'Bélgica', 'Koninklijke Atletiek Associatie Gent | K.A.A. Gent | Gent | Ghent'),
  ('KAS Eupen', 'Bélgica', 'K.A.S. Eupen'),
  ('KRC Genk', 'Bélgica', 'K.R.C. Genk | Koninklijke Racing Club Genk'),
  ('KRC Mechelen', 'Bélgica', 'K.R.C. Mechelen | Racing Mechelen'),
  ('KSV Roeselare', 'Bélgica', 'K.S.V. Roeselare'),
  ('KV Kortrijk', 'Bélgica', 'K.V. Kortrijk | Koninklijke Voetbalclub Kortrijk'),
  ('KV Mechelen', 'Bélgica', 'Y.R. K.V. Mechelen | K.V. Mechelen | YR KV Mechelen'),
  ('KV Oostende', 'Bélgica', 'Koninklijke Voetbalclub Oostende'),
  ('KVC Westerlo', 'Bélgica', 'K.V.C. Westerlo | Koninklijke Voetbal Club Westerlo | Westerlo'),
  ('Lommel SK', 'Bélgica', 'Lommel United'),
  ('Oud-Heverlee Leuven', 'Bélgica', 'OH Leuven'),
  ('RAAL La Louvière', 'Bélgica', 'RAAL La Louviere | Racing Charleroi | Racing Charleroi-Couillet-Fleurus | FC Charleroi'),
  ('RE Virton', 'Bélgica', 'R.E. Virton | Royal Excelsior Virton | Excelsior Virton'),
  ('RFC de Liège', 'Bélgica', 'R.F.C. de Liège | Royal Football Club de Liège | R.F.C. de Liege | Royal Football Club de Liege'),
  ('RFC Seraing', 'Bélgica', null::text),
  ('RFC Tournai', 'Bélgica', 'R.F.C. Tournai'),
  ('ROC de Charleroi-Marchienne', 'Bélgica', 'R.O.C. de Charleroi-Marchienne | Olympic Charleroi | Charleroi-Marchienne'),
  ('Royal Antwerp FC', 'Bélgica', 'Royal Antwerp F.C. | Royal Antwerp | Antwerp FC | Antwerp F.C.'),
  ('Royal Charleroi SC', 'Bélgica', 'Royal Charleroi S.C. | R. Charleroi S.C.'),
  ('Royale Union Saint-Gilloise', 'Bélgica', 'R. Union Saint-Gilloise | Union Saint-Gilloise | Union St.-Gilloise | Royale Union St.-Gilloise | R. Union St.-Gilloise'),
  ('Royale Union Tubize-Braine', 'Bélgica', 'A F C Tubize | A. F. C. Tubize | AFC Tubize | F.C. Tubize | FC Tubize | Association Football Clubs Tubize'),
  ('RSC Anderlecht', 'Bélgica', 'R.S.C. Anderlecht | RSCA | Royal Sporting Club Anderlecht | Anderlecht'),
  ('RWDM Brussels', 'Bélgica', 'RWDM | Racing White Daring Molenbeek | Daring Brussels'),
  ('SC Eendracht Aalst', 'Bélgica', null::text),
  ('Sint-Truidense VV', 'Bélgica', 'Sint-Truidense V.V. | K. Sint-Truidense V.V. | K Sint-Truidense VV'),
  ('Sportkring Beveren', 'Bélgica', 'SK Beveren | S.K. Beveren'),
  ('Standard Liège', 'Bélgica', 'Royal Standard Club de Liège | Standard Liege | Royal Standard Club de Liege'),
  ('SV Zulte Waregem', 'Bélgica', 'S.V. Zulte Waregem | Sportvereniging Zulte Waregem | Zulte Waregem | Essevee'),
  ('Ajijas Cotonou', 'Benim', null::text),
  ('Akanké FC', 'Benim', null::text),
  ('AS Cotonou', 'Benim', null::text),
  ('AS Dragons FC de l''Ouémé', 'Benim', null::text),
  ('AS Police', 'Benim', null::text),
  ('AS Tonnerre de Bohicon', 'Benim', null::text),
  ('ASPAC FC', 'Benim', null::text),
  ('Association Sportive Oussou Saka', 'Benim', null::text),
  ('Avrankou Omnisport FC', 'Benim', null::text),
  ('Ayema FC', 'Benim', null::text),
  ('Béké Bembèrèkè', 'Benim', null::text),
  ('Buffles du Borgou FC', 'Benim', 'Buffles Barakou'),
  ('Dynamo Abomey FC', 'Benim', 'Dynamo Abomey F.C.'),
  ('Dynamo Unacob FC de Parakou', 'Benim', null::text),
  ('Energie FC', 'Benim', null::text),
  ('ESAE FC', 'Benim', 'Adjobi Football Club'),
  ('Espoir FC', 'Benim', null::text),
  ('Etoile Sportive Porto-Novo', 'Benim', null::text),
  ('Forces Armées', 'Benim', null::text),
  ('Hodio FC', 'Benim', 'Hodio Football Club'),
  ('JA Plateau', 'Benim', null::text),
  ('Lions de l''Atakory', 'Benim', null::text),
  ('Mambas Noirs FC', 'Benim', null::text),
  ('Mogas 90 FC', 'Benim', null::text),
  ('Panthères FC', 'Benim', 'Panthères Football Club | Pantheres FC | Pantheres Football Club'),
  ('Postel Sport FC', 'Benim', null::text),
  ('Requins de l''Atlantique FC', 'Benim', null::text),
  ('Soleil FC', 'Benim', null::text),
  ('Toffa Cotonou', 'Benim', null::text),
  ('Université Nationale du Bénin FC', 'Benim', null::text),
  ('USS Kraké', 'Benim', 'USS Krake'),
  ('Bumprom Gomel', 'Bielorrússia', null::text),
  ('FC Arsenal Dzerzhinsk', 'Bielorrússia', null::text),
  ('FC Astraviec', 'Bielorrússia', 'FC Astravets | FC Ostrovets'),
  ('FC Baranovichi', 'Bielorrússia', null::text),
  ('FC BATE Borisov', 'Bielorrússia', 'BATE | Borisov | BATE Borisov | Football Club BATE | FC BATE'),
  ('FC BATE-2 Borisov', 'Bielorrússia', 'BATE-2'),
  ('FC Belshina Bobruisk', 'Bielorrússia', null::text),
  ('FC Dinamo Minsk', 'Bielorrússia', 'FC Dinamo-Minsk | Football Club Dinamo Minsk | Dinamo Minsk | Dinamo'),
  ('FC Dinamo-2 Minsk', 'Bielorrússia', null::text),
  ('FC Dinamo-Juni Minsk', 'Bielorrússia', null::text),
  ('FC Dnepr Mogilev', 'Bielorrússia', null::text),
  ('FC DSK Gomel', 'Bielorrússia', null::text),
  ('FC Dynamo Brest', 'Bielorrússia', 'FC Brest'),
  ('FC Gomel', 'Bielorrússia', 'Gomel FC | Homel | Homel FC | FC Homel | Gomel | FC Homieĺ'),
  ('FC Granit Mikashevichi', 'Bielorrússia', null::text),
  ('FC Isloch Minsk Raion', 'Bielorrússia', 'FC Islač'),
  ('FC Khimik Svetlogorsk', 'Bielorrússia', null::text),
  ('FC Klechesk Kletsk', 'Bielorrússia', null::text),
  ('FC Kobrin', 'Bielorrússia', null::text),
  ('FC Krumkačy Miensk', 'Bielorrússia', null::text),
  ('FC Lida', 'Bielorrússia', null::text),
  ('FC Luninets', 'Bielorrússia', null::text),
  ('FC Maladziečna', 'Bielorrússia', 'FC Zabudova Molodechno'),
  ('FC Maxline Viciebsk', 'Bielorrússia', 'ML Viciebsk'),
  ('FC Minsk', 'Bielorrússia', 'FK Minsk'),
  ('FC Naftan Novopolotsk', 'Bielorrússia', null::text),
  ('FC Neman Grodno', 'Bielorrússia', null::text),
  ('FC Niva Doŭbizna', 'Bielorrússia', null::text),
  ('FC Orsha', 'Bielorrússia', 'Football Club Orsha | Orsha'),
  ('FC Oshmyany', 'Bielorrússia', null::text),
  ('FC Osipovichi', 'Bielorrússia', 'FC Asipovičy'),
  ('FC Salihorsk', 'Bielorrússia', 'FK Soligorsk'),
  ('FC Shakhtyor Salihorsk', 'Bielorrússia', 'FC Shakhtyor'),
  ('FC SKA-1938', 'Bielorrússia', 'Zvezda-BGU Minsk | Enerhetyk-BDU Minsk | Zorka-BDU | Zorka-BDU-VA | FC Enerhetyk-BDU Minsk | FC Enierhietyk-BDU Minsk'),
  ('FC Slavia-Mozyr', 'Bielorrússia', null::text),
  ('FC Slonim', 'Bielorrússia', null::text),
  ('FC Slutsk-2024', 'Bielorrússia', 'FC Sluck'),
  ('FC Smolevichi', 'Bielorrússia', 'FC Smolevichi-STI'),
  ('FC Smorgon', 'Bielorrússia', 'FC Smarhoń'),
  ('FC Torpedo-BelAZ Zhodino', 'Bielorrússia', null::text),
  ('FC Torpedo-Kadino Mogilev', 'Bielorrússia', null::text),
  ('FC Torpedo-MAZ Minsk', 'Bielorrússia', null::text),
  ('FC UAS Zhitkovichi', 'Bielorrússia', null::text),
  ('FC Underdog Chist', 'Bielorrússia', 'FC Chist | FC Underdog Čysć'),
  ('FC Unixlabs', 'Bielorrússia', 'FC Juni Minsk'),
  ('FC Vitebsk', 'Bielorrússia', null::text),
  ('FC Volna Pinsk', 'Bielorrússia', 'Volna Pinsk'),
  ('FC ZLiN Gomel', 'Bielorrússia', null::text),
  ('FK Shakhtyor-2 Salihorsk', 'Bielorrússia', 'FK Shakhtyor Petrikov | FC Šachcior Pietrykaŭ | FK Shakhtyor Petrykaw'),
  ('AMORETTI', 'Bolívia', 'AMO'),
  ('CD Jorge Wilstermann', 'Bolívia', 'C.D. Jorge Wilstermann | Club Deportivo Jorge Wilstermann'),
  ('CD San Antonio Bulo Bulo', 'Bolívia', 'C.D. San Antonio Bulo Bulo | San Antonio Bulo Bulo'),
  ('CD San José', 'Bolívia', 'Club San José | Club Deportivo San José | San José Sports Club | SJS | CDSJ'),
  ('Chaco Petrolero', 'Bolívia', null::text),
  ('Club 31 de Octubre', 'Bolívia', null::text),
  ('Club Always Ready', 'Bolívia', null::text),
  ('Club Aurora', 'Bolívia', null::text),
  ('Club Blooming', 'Bolívia', 'Blooming Santa Cruz'),
  ('Club Bolívar', 'Bolívia', null::text),
  ('Club Deportivo Petrolero', 'Bolívia', 'Club Atletico Petrolero'),
  ('Club Destroyers', 'Bolívia', null::text),
  ('Club Real Potosí', 'Bolívia', 'Club Bamin Real Potosi'),
  ('Club Universitario', 'Bolívia', null::text),
  ('Deportivo Municipal de La Paz', 'Bolívia', null::text),
  ('Guabirá', 'Bolívia', 'Guabira'),
  ('Litoral de Cochabamba', 'Bolívia', null::text),
  ('Municipal Real Mamoré', 'Bolívia', 'Municipal Real Mamore'),
  ('Nacional Potosí', 'Bolívia', 'Nacional Potosi'),
  ('Oriente Petrolero', 'Bolívia', 'Club Deportivo Oriente Petrolero'),
  ('Sport Boys Warnes', 'Bolívia', 'Club Sport Boys Warnes'),
  ('The Strongest', 'Bolívia', 'Club The Strongest'),
  ('Universitario de La Paz', 'Bolívia', null::text),
  ('Universitario de Pando', 'Bolívia', 'Club Universitario de Pando'),
  ('FK Borac Banja Luka', 'Bósnia e Herzegovina', 'Fudbalski Klub Borac | FK Borac | Borac | Borac Banja Luka'),
  ('FK Borac Šamac', 'Bósnia e Herzegovina', null::text),
  ('FK BSK Banja Luka', 'Bósnia e Herzegovina', null::text),
  ('FK Budućnost Banovići', 'Bósnia e Herzegovina', null::text),
  ('FK Drina HE Višegrad', 'Bósnia e Herzegovina', null::text),
  ('FK Drina Zvornik', 'Bósnia e Herzegovina', null::text),
  ('FK Famos Vojkovići', 'Bósnia e Herzegovina', null::text),
  ('FK Igman Konjic', 'Bósnia e Herzegovina', null::text),
  ('FK Kozara Gradiška', 'Bósnia e Herzegovina', null::text),
  ('FK Krupa', 'Bósnia e Herzegovina', null::text),
  ('FK Laktaši', 'Bósnia e Herzegovina', null::text),
  ('FK Leotar', 'Bósnia e Herzegovina', 'Leotar Trebinje'),
  ('FK Ljubić Prnjavor', 'Bósnia e Herzegovina', null::text),
  ('FK Mladost Doboj Kakanj', 'Bósnia e Herzegovina', null::text),
  ('FK Mladost Gacko', 'Bósnia e Herzegovina', null::text),
  ('FK Mladost Velika Obarska', 'Bósnia e Herzegovina', null::text),
  ('FK Modriča', 'Bósnia e Herzegovina', null::text),
  ('FK Podrinje Janja', 'Bósnia e Herzegovina', null::text),
  ('FK Proleter Teslić', 'Bósnia e Herzegovina', null::text),
  ('FK Radnik Bijeljina', 'Bósnia e Herzegovina', 'FK Radnik'),
  ('FK Rudar Kakanj', 'Bósnia e Herzegovina', null::text),
  ('FK Rudar Prijedor', 'Bósnia e Herzegovina', null::text),
  ('FK Rudar Ugljevik', 'Bósnia e Herzegovina', null::text),
  ('FK Sarajevo', 'Bósnia e Herzegovina', 'Fudbalski klub Sarajevo'),
  ('FK Slavija Istočno Sarajevo', 'Bósnia e Herzegovina', 'Fudbalski klub Slavija'),
  ('FK Sloboda Mrkonjić Grad', 'Bósnia e Herzegovina', null::text),
  ('FK Sloboda Novi Grad', 'Bósnia e Herzegovina', null::text),
  ('FK Sloboda Tuzla', 'Bósnia e Herzegovina', null::text),
  ('FK Sloga Doboj', 'Bósnia e Herzegovina', null::text),
  ('FK Sutjeska Foča', 'Bósnia e Herzegovina', null::text),
  ('FK Tekstilac Derventa', 'Bósnia e Herzegovina', null::text),
  ('FK Tuzla City', 'Bósnia e Herzegovina', 'FK Sloga Simin Han'),
  ('FK Velež Mostar', 'Bósnia e Herzegovina', 'Velež Mostar | Velež | RSD Velež Mostar | RSD Velež | Rođeni | Velez Mostar'),
  ('FK Željezničar Sarajevo', 'Bósnia e Herzegovina', 'Nogometni Klub Željezničar Sarajevo'),
  ('FK Zvijezda 09', 'Bósnia e Herzegovina', null::text),
  ('HNK Brotnjo Čitluk', 'Bósnia e Herzegovina', null::text),
  ('HNK Orašje', 'Bósnia e Herzegovina', null::text),
  ('HNK Sloga Uskoplje', 'Bósnia e Herzegovina', null::text),
  ('HŠK Posušje', 'Bósnia e Herzegovina', 'NK Posušje | Hrvatski športski klub Posušje'),
  ('HŠK Zrinjski Mostar', 'Bósnia e Herzegovina', null::text),
  ('NK Bosna Visoko', 'Bósnia e Herzegovina', null::text),
  ('NK Čelik Zenica', 'Bósnia e Herzegovina', 'Football club Čelik Zenica | Fudbalski klub Čelik Zenica | Nogometni klub Čelik Zenica | Football club Celik Zenica'),
  ('NK GOŠK Gabela', 'Bósnia e Herzegovina', null::text),
  ('NK Iskra Bugojno', 'Bósnia e Herzegovina', null::text),
  ('NK Jedinstvo Bihać', 'Bósnia e Herzegovina', null::text),
  ('NK Metalleghe-BSI', 'Bósnia e Herzegovina', null::text),
  ('NK SAŠK Napredak', 'Bósnia e Herzegovina', null::text),
  ('NK Široki Brijeg', 'Bósnia e Herzegovina', null::text),
  ('NK Travnik', 'Bósnia e Herzegovina', null::text),
  ('NK Vitez', 'Bósnia e Herzegovina', null::text),
  ('NK Žepče', 'Bósnia e Herzegovina', null::text),
  ('NK Zvijezda Gradačac', 'Bósnia e Herzegovina', null::text),
  ('OFK Gradina', 'Bósnia e Herzegovina', null::text),
  ('Black Forest FC', 'Botsuana', null::text),
  ('Botswana Defence Force XI FC', 'Botsuana', null::text),
  ('Botswana Meat Commission FC', 'Botsuana', 'Botswana Meat Commission F.C.'),
  ('Botswana Railways Highlanders', 'Botsuana', null::text),
  ('ECCO City Green', 'Botsuana', null::text),
  ('Extension Gunners FC', 'Botsuana', 'Extension Gunners'),
  ('FC Satmos', 'Botsuana', 'F.C. Satmos'),
  ('Gaborone United SC', 'Botsuana', 'Gaborone United S.C. | GU'),
  ('Great North Tigers FC', 'Botsuana', 'Great North Tigers F.C.'),
  ('Jwaneng Galaxy FC', 'Botsuana', 'Jwaneng Galaxy F.C.'),
  ('Matebele FC', 'Botsuana', 'Matebele Football Club'),
  ('Miscellaneous SC Serowe', 'Botsuana', null::text),
  ('Mochudi Centre Chiefs', 'Botsuana', null::text),
  ('Mogoditshane Fighters', 'Botsuana', null::text),
  ('Motlakase Power Dynamos', 'Botsuana', null::text),
  ('Nico United', 'Botsuana', null::text),
  ('Notwane FC', 'Botsuana', 'Notwane F.C.'),
  ('Orapa United FC', 'Botsuana', null::text),
  ('Police XI', 'Botsuana', null::text),
  ('Sankoyo Bush Bucks', 'Botsuana', null::text),
  ('Sharps Shooting Stars FC', 'Botsuana', null::text),
  ('TAFIC FC', 'Botsuana', 'TAFIC F.C.'),
  ('TASC FC', 'Botsuana', null::text),
  ('Township Rollers FC', 'Botsuana', 'Township Rollers F.C.'),
  ('Uniao Flamengo Santos FC', 'Botsuana', 'Uniao Flamengo Santos F.C.'),
  ('Wonder Sporting Club', 'Botsuana', null::text),
  ('Academia Desportiva Manthiqueira Futebol', 'Brasil', null::text),
  ('Agremiação Sportiva Arapiraquense', 'Brasil', 'ASA de Arapiraca'),
  ('Águia de Marabá Futebol Clube', 'Brasil', 'Aguia de Maraba Futebol Clube'),
  ('Amazonas Futebol Clube', 'Brasil', 'Amazonas | Amazonas FC'),
  ('America Football Club', 'Brasil', null::text),
  ('América Futebol Clube', 'Brasil', 'América (AM) | América de Manaus | Manaos | America Futebol Clube | America | America de Manaus'),
  ('Americano Futebol Clube', 'Brasil', null::text),
  ('Anápolis Futebol Clube', 'Brasil', 'Anapolis Futebol Clube'),
  ('Associação Atlética Anapolina', 'Brasil', null::text),
  ('Associação Atlética Caldense', 'Brasil', null::text),
  ('Associação Atlética Coruripe', 'Brasil', null::text),
  ('Associação Atlética Internacional', 'Brasil', 'Inter de Limeira | AA Inter de Limeira | Internacional de Limeira | Internacional-SP'),
  ('Associação Atlética Ponte Preta', 'Brasil', null::text),
  ('Associação Atlética Portuguesa', 'Brasil', 'Portuguesa Santista'),
  ('Associação Chapecoense de Futebol', 'Brasil', 'Chape'),
  ('Associação Cultural Esporte Clube Baraúnas', 'Brasil', null::text),
  ('Associação Desportiva Bahia de Feira', 'Brasil', null::text),
  ('Associação Desportiva Cabofriense', 'Brasil', null::text),
  ('Associação Desportiva Confiança', 'Brasil', 'Confiança'),
  ('Associação Desportiva Ferroviária', 'Brasil', null::text),
  ('Associação Desportiva Recreativa e Cultural Icasa', 'Brasil', null::text),
  ('Associação Desportiva São Caetano', 'Brasil', 'AD São Caetano | AD Sao Caetano | Associacao Desportiva Sao Caetano | A.D. São Caetano'),
  ('Associação Ferroviária de Esportes', 'Brasil', null::text),
  ('Associação Portuguesa de Desportos', 'Brasil', 'Portuguesa | Lusa'),
  ('Atlético Acreano', 'Brasil', 'Atletico Acreano'),
  ('Atlético Clube Goianiense', 'Brasil', 'Atletico Clube Goianiense | AC Goianiense'),
  ('Audax São Paulo Esporte Clube', 'Brasil', 'Grêmio Osasco Audax Esporte Clube | Gremio Osasco Audax Esporte Clube'),
  ('Avaí Futebol Clube', 'Brasil', 'Avai Futebol Clube'),
  ('Bangu Atlético Clube', 'Brasil', 'Bangu Atletico Clube'),
  ('Boa Esporte Clube', 'Brasil', null::text),
  ('Boavista Sport Club', 'Brasil', 'Boavista SC'),
  ('Bonsucesso Futebol Clube', 'Brasil', null::text),
  ('Botafogo FR', 'Brasil', 'Botafogo F.R. | Botafogo de Futebol e Regatas'),
  ('Botafogo Futebol Clube', 'Brasil', 'Botafogo de Ribeirão Preto'),
  ('Brasília Futebol Clube', 'Brasil', 'Brasilia Futebol Clube'),
  ('Brasiliense Futebol Clube', 'Brasil', null::text),
  ('Brasilis Futebol Clube', 'Brasil', null::text),
  ('CA Estudantes de São Paulo', 'Brasil', null::text),
  ('Campinas FC', 'Brasil', 'Campinas F.C.'),
  ('Campinense Clube', 'Brasil', 'Campinense'),
  ('Campo Grande AC', 'Brasil', 'Campo Grande A.C. | Campo Grande Atlético Clube | Campo Grande Atletico Clube'),
  ('Ceará Sporting Club', 'Brasil', 'Ceará SC'),
  ('Central Sport Club', 'Brasil', null::text),
  ('Centro Sportivo Alagoano', 'Brasil', 'CSA'),
  ('Club Athletico Paranaense', 'Brasil', 'Athletico Paranaense | Club Atlético Paranaense'),
  ('Club Sportivo Sergipe', 'Brasil', null::text),
  ('Clube Atlético Juventus', 'Brasil', 'Clube Atletico Juventus'),
  ('Clube Atlético Linense', 'Brasil', 'Clube Atletico Linense'),
  ('Clube Atlético Metropolitano', 'Brasil', 'Clube Atletico Metropolitano'),
  ('Clube Atlético Mineiro', 'Brasil', 'Atlético Mineiro | Galo | Atlético-MG | CA Mineiro | Clube Atletico Mineiro | Atletico Mineiro | Atletico-MG'),
  ('Clube Atlético Paulistinha', 'Brasil', 'Clube Atletico Paulistinha'),
  ('Clube Atlético Penapolense', 'Brasil', 'Clube Atletico Penapolense'),
  ('Clube Atlético Sorocaba', 'Brasil', 'Atlético de Sorocaba | Atlético Sorocaba'),
  ('Clube de Regatas Brasil', 'Brasil', 'CRB'),
  ('Clube de Regatas do Flamengo', 'Brasil', 'Flamengo | CR Flamengo | C.R. Flamengo | Flamengo Rio de Janeiro'),
  ('Clube do Remo', 'Brasil', null::text),
  ('Clube Esportivo Lajeadense', 'Brasil', null::text),
  ('Clube Esportivo Nova Esperança', 'Brasil', null::text),
  ('Clube Náutico Capibaribe', 'Brasil', 'Clube Nautico Capibaribe | Náutico'),
  ('Colo Colo de Futebol e Regatas', 'Brasil', null::text),
  ('Comercial Futebol Clube', 'Brasil', null::text),
  ('Coritiba FC', 'Brasil', 'Coritiba F.C. | Coritiba Foot Ball Club'),
  ('CR Vasco da Gama', 'Brasil', 'Vasco da Gama | Club de Regatas Vasco da Gama | Vasco | CRVG | C.R. Vasco da Gama'),
  ('Criciúma Esporte Clube', 'Brasil', 'Criciuma Esporte Clube'),
  ('Cruzeiro EC', 'Brasil', 'Cruzeiro E.C. | Cruzeiro Esporte Clube'),
  ('Cuiabá Esporte Clube', 'Brasil', 'Cuiaba Esporte Clube | Cuiabá'),
  ('Deportivo La Coruña Brasil Futebol Clube', 'Brasil', null::text),
  ('Duque de Caxias Futebol Clube', 'Brasil', null::text),
  ('EC Vitória', 'Brasil', 'E.C. Vitória | Esporte Clube Vitória | E.C. Vitoria | Esporte Clube Vitoria'),
  ('Esporte Clube Águia Negra', 'Brasil', 'Esporte Clube Aguia Negra'),
  ('Esporte Clube Bahia', 'Brasil', 'E.C. Bahia'),
  ('Esporte Clube Comercial', 'Brasil', 'EC Comercial'),
  ('Esporte Clube Democrata', 'Brasil', null::text),
  ('Esporte Clube Flamengo', 'Brasil', null::text),
  ('Esporte Clube Juventude', 'Brasil', 'E.C. Juventude | EC Juventude'),
  ('Esporte Clube Noroeste', 'Brasil', 'EC Noroeste'),
  ('Esporte Clube Novo Hamburgo', 'Brasil', null::text),
  ('Esporte Clube Primeiro Passo Vitória da Conquista', 'Brasil', null::text),
  ('Esporte Clube Santo André', 'Brasil', 'Esporte Clube Santo Andre'),
  ('Esporte Clube São Bento', 'Brasil', null::text),
  ('Esporte Clube São Luiz', 'Brasil', null::text),
  ('Esporte Clube XV de Novembro', 'Brasil', 'XV de Piracicaba'),
  ('Ferroviário Atlético Clube', 'Brasil', 'Ferroviario Atletico Clube'),
  ('Figueirense Futebol Clube', 'Brasil', 'Figueirense FC'),
  ('Fluminense de Feira Futebol Clube', 'Brasil', null::text),
  ('Fluminense FC', 'Brasil', 'Fluminense F.C. | Fluminense Football Club'),
  ('Fortaleza EC', 'Brasil', 'Fortaleza E.C. | Fortaleza Esporte Clube | Fortaleza'),
  ('Friburguense Atlético Clube', 'Brasil', 'Friburguense Atletico Clube'),
  ('Galícia Esporte Clube', 'Brasil', 'Galicia Esporte Clube'),
  ('Globo Futebol Clube', 'Brasil', null::text),
  ('Goiânia Esporte Clube', 'Brasil', 'Goiania Esporte Clube'),
  ('Goiás Esporte Clube', 'Brasil', 'Goiás E.C. | Goias E.C.'),
  ('Goytacaz Futebol Clube', 'Brasil', null::text),
  ('Grêmio Barueri Futebol', 'Brasil', 'Gremio Barueri Futebol'),
  ('Grêmio Esportivo Brasil', 'Brasil', 'Gremio Esportivo Brasil | Brasil de Pelotas'),
  ('Grêmio FBPA', 'Brasil', 'Gremio Foot-Ball Porto Alegrense | Gremio Porto Alegre | Grêmio Foot-Ball Porto Alegrense | Grêmio Football Porto Alegrense | Grêmio F.B.P.A. | Gremio FBPA | Gremio F.B.P.A. | Gremio'),
  ('Grêmio Novorizontino', 'Brasil', null::text),
  ('Guarani Futebol Clube', 'Brasil', 'Guarani F.C.'),
  ('Guarany Sporting Club', 'Brasil', null::text),
  ('Guaratinguetá Futebol', 'Brasil', 'Guaratingueta Futebol'),
  ('Ipatinga Futebol Clube', 'Brasil', 'Ipatinga Esporte Clube | Betim Esporte Clube'),
  ('Ituano Futebol Clube', 'Brasil', null::text),
  ('Joinville Esporte Clube', 'Brasil', 'JEC | Joinville'),
  ('Londrina EC', 'Brasil', 'Londrina E.C. | Londrina Esporte Clube'),
  ('Luverdense Esporte Clube', 'Brasil', null::text),
  ('Macaé Esporte Futebol Clube', 'Brasil', 'Macae Esporte Futebol Clube'),
  ('Madureira Esporte Clube', 'Brasil', null::text),
  ('Marília Atlético Clube', 'Brasil', 'Marilia Atletico Clube'),
  ('Mirassol Futebol Clube', 'Brasil', null::text),
  ('Mixto Esporte Clube', 'Brasil', null::text),
  ('Mogi Mirim Esporte Clube', 'Brasil', null::text),
  ('Moto Club de São Luís', 'Brasil', null::text),
  ('Nacional Atlético Clube', 'Brasil', 'Nacional Atletico Clube'),
  ('Nacional Futebol Clube', 'Brasil', null::text),
  ('Niteroiense FC', 'Brasil', null::text),
  ('Nova Iguaçu Futebol Clube', 'Brasil', null::text),
  ('Oeste Futebol Clube', 'Brasil', null::text),
  ('Olaria Atlético Clube', 'Brasil', 'Olaria Atletico Clube'),
  ('Operário Ferroviário Esporte Clube', 'Brasil', 'Operario Ferroviario Esporte Clube'),
  ('Operário Futebol Clube', 'Brasil', 'Operario Futebol Clube'),
  ('Paraná Clube', 'Brasil', 'EC Pinheiros | Colorado EC | Parana Clube'),
  ('Paulínia FC', 'Brasil', 'Paulinia FC'),
  ('Paulista Futebol Clube', 'Brasil', null::text),
  ('Paysandu Sport Club', 'Brasil', 'Paysandu S.C.'),
  ('Porto Alegre Futebol Clube', 'Brasil', null::text),
  ('Red Bull Bragantino', 'Brasil', 'RB Bragantino | Bragantino | Clube Atletico Bragantino'),
  ('Rio Branco Atlético Clube', 'Brasil', 'Rio Branco Atletico Clube'),
  ('Rio Branco Esporte Clube', 'Brasil', 'Rio Branco EC'),
  ('Rio Branco Football Club', 'Brasil', 'Rio Branco'),
  ('Rio Claro Futebol Clube', 'Brasil', null::text),
  ('River Atlético Clube', 'Brasil', 'River-PI'),
  ('Salgueiro Atlético Clube', 'Brasil', 'Salgueiro Atletico Clube'),
  ('Sampaio Corrêa FC', 'Brasil', 'Sampaio Corrêa F.C. | Sampaio Corrêa Futebol Clube | Sampaio Correa F.C. | Sampaio Correa Futebol Clube'),
  ('Santa Cruz Futebol Clube', 'Brasil', 'Santa Cruz | Santa Cruz FC'),
  ('Santos FC', 'Brasil', 'Santos F.C. | Santos Futebol Clube'),
  ('Santos Futebol Clube Amapá', 'Brasil', 'Santos of Amapá | Santos Futebol Clube (AP)'),
  ('São Bernardo Futebol Clube', 'Brasil', 'São Bernardo F.C.'),
  ('São Carlos FC', 'Brasil', 'São Carlos F.C. | São Carlos Futebol Clube'),
  ('São Cristóvão de Futebol e Regatas', 'Brasil', null::text),
  ('São José Esporte Clube', 'Brasil', null::text),
  ('São Paulo Athletic Club', 'Brasil', null::text),
  ('São Paulo FC', 'Brasil', 'São Paulo Futebol Clube'),
  ('São Raimundo Esporte Clube', 'Brasil', null::text),
  ('SC Corinthians Paulista', 'Brasil', 'S.C. Corinthians Paulista | Sport Club Corinthians Paulista | Corinthians Paulista | SCCP | Corinthians'),
  ('SC Internacional', 'Brasil', 'S.C. Internacional | Sport Club Internacional | Internacional | Internacional Porto Alegre | S.C.I | SCI 1909 | S.C.I 1909 | SC Internacional Porto Alegre | SCI'),
  ('Sertãozinho Futebol Clube', 'Brasil', null::text),
  ('Social Futebol Clube', 'Brasil', null::text),
  ('Sociedade Desportiva Juazeirense', 'Brasil', null::text),
  ('Sociedade Esportiva do Gama', 'Brasil', null::text),
  ('Sociedade Esportiva e Recreativa Caxias do Sul', 'Brasil', 'Caxias do Sul | Caxias'),
  ('Sociedade Esportiva Palmeiras', 'Brasil', 'SE Palmeiras'),
  ('Sociedade Imperatriz de Desportos', 'Brasil', null::text),
  ('Sport Club Corinthians Alagoano', 'Brasil', 'Corinthians Alagoano'),
  ('Sport Club Corinthians Paulista', 'Brasil', null::text),
  ('Sport Club do Recife', 'Brasil', 'Sport | Sport Recife | SCR'),
  ('Sumaré Atlético Clube', 'Brasil', 'Sumare Atletico Clube'),
  ('Tocantinópolis Esporte Clube', 'Brasil', 'Tocantinopolis Esporte Clube'),
  ('Tombense Futebol Clube', 'Brasil', null::text),
  ('Treze Futebol Clube', 'Brasil', 'Treze FC | Galo da Borborema'),
  ('Tuna Luso Brasileira', 'Brasil', null::text),
  ('Tupi Football Club', 'Brasil', null::text),
  ('Uberaba Sport Club', 'Brasil', null::text),
  ('Uberlândia EC', 'Brasil', 'Uberlândia E.C. | Uberlândia Esporte Clube | Uberlandia E.C. | Uberlandia Esporte Clube'),
  ('União São João EC', 'Brasil', 'União São João E.C. | União São João Esporte Clube'),
  ('Vila Nova Futebol Clube', 'Brasil', null::text),
  ('Villa Nova Atlético Clube', 'Brasil', 'Villa Nova Atletico Clube'),
  ('Vitória Futebol Clube', 'Brasil', 'Vitoria Futebol Clube'),
  ('Volta Redonda Futebol Clube', 'Brasil', null::text),
  ('Ypiranga Clube', 'Brasil', null::text),
  ('Ypiranga Futebol Clube', 'Brasil', 'Ypiranga de Erechim'),
  ('Duli Pengiran Muda Mahkota Football Club', 'Brunei', 'DPMM FC'),
  ('Akademik Sofia', 'Bulgária', 'PFC Akademik Sofia'),
  ('Botev Plovdiv', 'Bulgária', null::text),
  ('FC Arda', 'Bulgária', 'Arda | Arda Kardzhali | FC Arda Kardzhali'),
  ('FC CSKA 1948 Sofia', 'Bulgária', 'CSKA 1948'),
  ('FC Dunav Ruse', 'Bulgária', null::text),
  ('FC Haskovo', 'Bulgária', null::text),
  ('FC Hebar 1918', 'Bulgária', 'Hebar Pazardzhik | Hebar'),
  ('FC Lokomotiv 1929 Sofia', 'Bulgária', 'Railway Sports Club | RSC | PFC Lokomotiv Sofia'),
  ('FC Lokomotiv Gorna Oryahovitsa', 'Bulgária', null::text),
  ('FC Maritsa Plovdiv', 'Bulgária', null::text),
  ('FC Pirin Blagoevgrad', 'Bulgária', null::text),
  ('FC Tsarsko Selo', 'Bulgária', 'Tsarsko Selo | FC Tsarsko Selo (Sofia)'),
  ('FC Vereya', 'Bulgária', 'F.C. Vereya | Vereya Stara Zagora'),
  ('FC Vihren Sandanski', 'Bulgária', null::text),
  ('FC Vitosha Bistritsa', 'Bulgária', 'F.C. Vitosha Bistritsa'),
  ('FK Krumovgrad', 'Bulgária', null::text),
  ('Lyubimetz 2007', 'Bulgária', 'FC Lyubimets'),
  ('OFC Etar Veliko Tarnovo', 'Bulgária', null::text),
  ('OFC Sliven 2000', 'Bulgária', null::text),
  ('PFC Belasitsa Petrich', 'Bulgária', null::text),
  ('PFC Beroe Stara Zagora', 'Bulgária', 'Beroe | PFC Beroe | Beroe Stara Zabora'),
  ('PFC Cherno More Varna', 'Bulgária', null::text),
  ('PFC CSKA Sofia', 'Bulgária', 'CSKA Sofia'),
  ('PFC Dobrudzha Dobrich', 'Bulgária', null::text),
  ('PFC Kaliakra Kavarna', 'Bulgária', null::text),
  ('PFC Levski Sofia', 'Bulgária', 'PFC Levski | Levski'),
  ('PFC Lokomotiv Mezdra', 'Bulgária', null::text),
  ('PFC Lokomotiv Plovdiv', 'Bulgária', null::text),
  ('PFC Ludogorets 1945', 'Bulgária', 'Ludogorets | Ludogorets Razgrad | P.F.C. Ludogorets 1945 | PFC Ludogorets Razgrad'),
  ('PFC Marek Dupnitsa', 'Bulgária', null::text),
  ('PFC Minyor Pernik', 'Bulgária', null::text),
  ('PFC Montana', 'Bulgária', null::text),
  ('PFC Naftex Burgas', 'Bulgária', null::text),
  ('PFC Neftochimic Burgas', 'Bulgária', null::text),
  ('PFC Pirin Gotse Delchev', 'Bulgária', null::text),
  ('PFC Shumen 2010', 'Bulgária', null::text),
  ('PFC Slavia Sofia', 'Bulgária', null::text),
  ('PFC Spartak Varna', 'Bulgária', 'FC Spartak Varna | Spartak Varna'),
  ('PFC Svetkavitsa', 'Bulgária', null::text),
  ('PFC Velbazhd Kyustendil', 'Bulgária', null::text),
  ('POFC Botev Vratsa', 'Bulgária', null::text),
  ('PSFC Chernomorets Burgas', 'Bulgária', null::text),
  ('Septemvri Sofia PFC', 'Bulgária', null::text),
  ('AS Maya', 'Burquina Faso', null::text),
  ('AS SONABEL', 'Burquina Faso', 'Association Sportive SONABEL'),
  ('ASEC Koudougou', 'Burquina Faso', null::text),
  ('ASF Bobo', 'Burquina Faso', 'ASF Bobo-Dioulasso | ASFB | ASF Bobo Dioulasso'),
  ('ASFA Yennenga', 'Burquina Faso', null::text),
  ('Bobo Sport', 'Burquina Faso', null::text),
  ('Bouloumpoukou FC', 'Burquina Faso', null::text),
  ('Commune FC', 'Burquina Faso', null::text),
  ('Étoile Filante de Ouagadougou', 'Burquina Faso', 'Etoile Filante Ouagadougou | Étoile Filante Ouagadougou | Étoile Filante (Ouagadougou) | Etoile Filante de Ouagadougou'),
  ('Jeunesse Club de Bobo Dioulasso', 'Burquina Faso', null::text),
  ('KOZAF', 'Burquina Faso', null::text),
  ('Majestic FC', 'Burquina Faso', null::text),
  ('Rahimo FC', 'Burquina Faso', null::text),
  ('Rail Club du Kadiogo', 'Burquina Faso', null::text),
  ('RC Bobo', 'Burquina Faso', null::text),
  ('Salimata et Taséré FC', 'Burquina Faso', 'Salitas'),
  ('Santos FC', 'Burquina Faso', null::text),
  ('Silures Bobo-Dioulasso', 'Burquina Faso', null::text),
  ('Sourou Sport de Tougan', 'Burquina Faso', null::text),
  ('Union Sportive des Forces Armées', 'Burquina Faso', 'Union Sportive des Forces Armees'),
  ('US FRAN', 'Burquina Faso', null::text),
  ('US Ouagadougou', 'Burquina Faso', null::text),
  ('US Yatenga', 'Burquina Faso', null::text),
  ('USCO Banfora', 'Burquina Faso', null::text),
  ('Académie Tchité FC', 'Burundi', 'Academie Tchite FC'),
  ('Aigle Noir Makamba FC', 'Burundi', null::text),
  ('AS Inter Star', 'Burundi', null::text),
  ('Atlético Olympic FC', 'Burundi', 'Atlético Olympic F.C. | Atletico Olympic F.C.'),
  ('Burundi Sport Dynamik New Look', 'Burundi', null::text),
  ('Espoir de Mutimbuzi', 'Burundi', 'Espoir Football Club de Mutimbuzi'),
  ('Flambeau de l’Est', 'Burundi', null::text),
  ('Guêpiers du Lac', 'Burundi', null::text),
  ('Le Messager FC de Bujumbara', 'Burundi', null::text),
  ('Le Messager Ngozi FC', 'Burundi', null::text),
  ('LLB Amasipiri FC', 'Burundi', 'Amasipiri'),
  ('Lydia Ludic Burundi Académic', 'Burundi', 'Lydia Ludic Burundi Academic'),
  ('Maniema FC', 'Burundi', null::text),
  ('Muzinga FC', 'Burundi', null::text),
  ('Nyanza United', 'Burundi', null::text),
  ('Olympique Star', 'Burundi', null::text),
  ('Prince Louis FC', 'Burundi', 'Prince Louis F.C.'),
  ('Royal FC de Muramvya', 'Burundi', null::text),
  ('Rusizi FC', 'Burundi', null::text),
  ('Tigre Noir Ruyigi', 'Burundi', null::text),
  ('Vital''O FC', 'Burundi', null::text),
  ('Volontaires FC', 'Burundi', null::text),
  ('Bhutan Clearing FC', 'Butão', 'Bhutan Clearing F.C.'),
  ('Paro FC', 'Butão', null::text),
  ('Phuentsholing United FC', 'Butão', null::text),
  ('Tensung FC', 'Butão', 'Tensung F.C.'),
  ('Thimphu City FC', 'Butão', 'Zimdra FC'),
  ('Transport United', 'Butão', null::text),
  ('Ugyen Academy FC', 'Butão', 'Ugyen Academy F.C.'),
  ('Yeedzin FC', 'Butão', null::text),
  ('CS Mindelense', 'Cabo Verde', null::text),
  ('Sporting Clube da Praia', 'Cabo Verde', null::text),
  ('APEJES Academy', 'Camarões', null::text),
  ('AS Lausanne de Yaoundé', 'Camarões', 'AS Lausanne de Yaounde'),
  ('AS Matelots', 'Camarões', null::text),
  ('Astres FC', 'Camarões', null::text),
  ('Bamboutos FC', 'Camarões', null::text),
  ('Botafogo FC', 'Camarões', null::text),
  ('Caïman Douala', 'Camarões', null::text),
  ('Canon Yaoundé', 'Camarões', 'Canon Yaounde'),
  ('Cosmos de Bafia', 'Camarões', null::text),
  ('Coton Sport FC de Garoua', 'Camarões', 'Cotonsport F.C. Garoua | Cotonsport Garoua'),
  ('Danay FC', 'Camarões', null::text),
  ('Dragon Club', 'Camarões', null::text),
  ('Dynamo Douala', 'Camarões', 'Dynamo FC'),
  ('Eding Sport FC', 'Camarões', null::text),
  ('Fovu Club', 'Camarões', 'Fovu Baham'),
  ('Gazelle FA', 'Camarões', 'Gazelle Football Academy de Garoua'),
  ('Impôts FC', 'Camarões', 'Impots FC'),
  ('Kadji Sports Academy', 'Camarões', null::text),
  ('Lion Blessé', 'Camarões', null::text),
  ('Mount Cameroon FC', 'Camarões', 'Mount Cameroon F.C.'),
  ('New Star de Douala', 'Camarões', null::text),
  ('Njala Quan Sports Academy', 'Camarões', null::text),
  ('Oryx Douala', 'Camarões', null::text),
  ('Panthère du Ndé', 'Camarões', 'Panthere du Nde'),
  ('Racing FC Bafoussam', 'Camarões', 'Racing F.C. Bafoussam | Racing Club Bafoussam | Racing Club de Bafoussam'),
  ('Renaissance FC de Ngoumou', 'Camarões', null::text),
  ('Sable FC', 'Camarões', null::text),
  ('Scorpion de Bey', 'Camarões', null::text),
  ('Tiko United FC', 'Camarões', 'Tiko United F.C. | Tiko United'),
  ('Tonnerre Yaoundé', 'Camarões', 'Tonnerre Kalara Club de Yaoundé | Tonnerre Yaounde | Tonnerre Kalara Club de Yaounde'),
  ('UMS de Loum', 'Camarões', null::text),
  ('Union Douala', 'Camarões', 'Union Sportive Douala'),
  ('Unisport Bafang', 'Camarões', null::text),
  ('Université FC de Ngaoundéré', 'Camarões', 'Universite FC de Ngaoundere'),
  ('Young Sports Academy Bamenda', 'Camarões', 'YOSA'),
  ('Angkor Tiger FC', 'Camboja', 'Angkor Tiger F.C. | Cambodian Tiger FC'),
  ('Asia Euro United', 'Camboja', null::text),
  ('Boeung Ket FC', 'Camboja', 'Boeung Ket F.C. | Boeung Ket Angkor'),
  ('Build Bright University FC', 'Camboja', null::text),
  ('Cambodian Army Association FC', 'Camboja', 'Cambodian Army Association F.C.'),
  ('CMAC FC', 'Camboja', 'CMAC United FC'),
  ('Electricite du Cambodge FC', 'Camboja', null::text),
  ('Khemara Keila FC', 'Camboja', 'Khemara'),
  ('Kirivong Sok Sen Chey FC', 'Camboja', 'Kirivong Sok Sen Chey F.C.'),
  ('Life FC', 'Camboja', 'ឡាយហ្វ ខេត្តព្រះសីហនុ'),
  ('Military Police', 'Camboja', null::text),
  ('Naga World FC', 'Camboja', 'Naga World F.C. | Nagaworld FC'),
  ('National Police Commissary FC', 'Camboja', null::text),
  ('Phnom Penh Crown FC', 'Camboja', 'Phnom Penh Crown F.C. | Phnom Penh Crown Football Club'),
  ('Post Tel Club', 'Camboja', null::text),
  ('Preah Khan Reach Svay Rieng FC', 'Camboja', 'Preah Khan Reach Svay Rieng F.C. | Svay Rieng F.C. | Preah Khan Reach F.C.'),
  ('Royal Cambodian Air Force FC', 'Camboja', null::text),
  ('Soltilo Angkor FC', 'Camboja', null::text),
  ('Visakha AFC', 'Camboja', null::text),
  ('Wat Phnom FC', 'Camboja', null::text),
  ('Western University FC', 'Camboja', 'Western Phnom Penh'),
  ('Atlético Ottawa', 'Canadá', 'Atletico Ottawa | Atl. Ottawa'),
  ('Brampton United', 'Canadá', null::text),
  ('Brantford Galaxy', 'Canadá', null::text),
  ('Burlington SC', 'Canadá', null::text),
  ('Caribbean Selects', 'Canadá', null::text),
  ('Cavalry FC', 'Canadá', 'Cavalry Football Club'),
  ('CF Montréal', 'Canadá', 'Impact Montreal | Club de Foot Montréal | Montreal Impact | CFM | CF Montreal | CFMTL | CF of Montreal | Montreal Football Club'),
  ('Durham Flames', 'Canadá', null::text),
  ('FC Continentals', 'Canadá', 'FC Vorkuta | Continentals, FC'),
  ('FC Supra du Québec', 'Canadá', null::text),
  ('FC Ukraine United', 'Canadá', null::text),
  ('Forge FC', 'Canadá', 'Forge Football Club'),
  ('Hamilton City Soccer Club', 'Canadá', null::text),
  ('HFX Wanderers FC', 'Canadá', 'Halifax Wanderers | HFX Wanderers | HFX Wanderers Football Club'),
  ('Inter Toronto FC', 'Canadá', 'York 9 Football Club | York9 Football Club | Y9FC | York9 FC | York United | York United Football Club | York United FC | Inter Toronto'),
  ('Kingsman SC', 'Canadá', null::text),
  ('Kingston FC', 'Canadá', null::text),
  ('London City Soccer Club', 'Canadá', null::text),
  ('Mississauga Eagles FC', 'Canadá', null::text),
  ('Montreal Impact Academy', 'Canadá', null::text),
  ('Niagara United', 'Canadá', null::text),
  ('Pacific FC', 'Canadá', 'Pacific Football Club'),
  ('SC Toronto', 'Canadá', null::text),
  ('SC Waterloo Region', 'Canadá', null::text),
  ('Scarborough SC', 'Canadá', null::text),
  ('Serbian White Eagles FC', 'Canadá', null::text),
  ('Toronto Atomic FC', 'Canadá', null::text),
  ('Toronto Croatia', 'Canadá', 'C.N.S.C. Toronto Croatia | CNSC Toronto Croatia'),
  ('Toronto FC', 'Canadá', 'Toronto F.C. | Toronto Football Club | Toronto Soccer Club | Toronto Soccer | Football Club of Toronto | Soccer Club of Toronto | TorontoFC'),
  ('Trois-Rivières Attak', 'Canadá', 'Trois-Rivieres Attak'),
  ('Valour FC', 'Canadá', 'Valour Football Club'),
  ('Vancouver FC', 'Canadá', 'Vancouver Football Club'),
  ('Vancouver Whitecaps FC', 'Canadá', 'Vancouver Whitecaps | Vancouver Caps | Vancouver Caps FC | Whitecaps FC | Whitecaps Football Club | Vancouver Whitecaps Football Club | Whitecaps | Caps'),
  ('Windsor Stars', 'Canadá', null::text),
  ('York Region Shooters', 'Canadá', 'Italia Shooters | Glen Shields Sun Devils | Vaughan Sun Devils'),
  ('Al Ahli SC', 'Catar', 'Al Ahli Doha'),
  ('Al Kharaitiyat SC', 'Catar', null::text),
  ('Al Sadd Sports Club', 'Catar', 'Al-Sadd S.C.'),
  ('Al-Arabi SC', 'Catar', 'Ruma Sporting Saint FC nortch anthamce'),
  ('Al-Duhail SC', 'Catar', 'Al-Duhail Sports Club | Al Duhail SC'),
  ('Al-Gharafa SC', 'Catar', 'Al-Gharafa Sports Club | Al-Gharafa S.C. | Al-Gharrafa SC | Al-Gharrafa S.C.'),
  ('Al-Khor Sports Club', 'Catar', null::text),
  ('Al-Markhiya Sports Club', 'Catar', null::text),
  ('Al-Mesaimeer Sports Club', 'Catar', null::text),
  ('Al-Mu''aidar Sports Club', 'Catar', null::text),
  ('Al-Rayyan', 'Catar', 'Al-Rayyan Sports Club'),
  ('Al-Sailiya Sports Club', 'Catar', 'Al-Sailiya SC'),
  ('Al-Shahaniya Sports Club', 'Catar', null::text),
  ('Al-Shamal Sports Club', 'Catar', null::text),
  ('Al-Wakrah Sports Club', 'Catar', 'Al-Wakrah S.C.'),
  ('El Jaish SC', 'Catar', null::text),
  ('Qatar SC', 'Catar', 'Qatar S.C. | Qatar Sports Club | Q.S.C.'),
  ('Umm Salal SC', 'Catar', null::text),
  ('FC Aksu', 'Cazaquistão', null::text),
  ('FC Aktobe', 'Cazaquistão', null::text),
  ('FC Akzhayik', 'Cazaquistão', null::text),
  ('FC Alma-Ata', 'Cazaquistão', 'FC Cesna | FC Tsesna | FC Tcesna | Cesna Almaty'),
  ('FC Altai Semey', 'Cazaquistão', null::text),
  ('FC Arman', 'Cazaquistão', null::text),
  ('FC Astana', 'Cazaquistão', 'Astana Football Club'),
  ('FC Atyrau', 'Cazaquistão', 'Football Club Atyrau'),
  ('FC Azhar', 'Cazaquistão', null::text),
  ('FC Dinamo Almaty', 'Cazaquistão', null::text),
  ('FC Dostyk', 'Cazaquistão', null::text),
  ('FC Ekibastuzets', 'Cazaquistão', null::text),
  ('FC Irtysh Pavlodar', 'Cazaquistão', null::text),
  ('FC Kairat', 'Cazaquistão', 'Football Club Kairat Almaty | Kairat Almaty | Qairat Almaty | Kairat | Qairat'),
  ('FC Kaisar', 'Cazaquistão', 'Kaisar | FC Kaysar'),
  ('FC Kyzylzhar', 'Cazaquistão', null::text),
  ('FC Maktaaral', 'Cazaquistão', null::text),
  ('FC Megasport', 'Cazaquistão', null::text),
  ('FC Okzhetpes', 'Cazaquistão', null::text),
  ('FC Ordabasy', 'Cazaquistão', 'Football Club Ordabasy Shymkent'),
  ('FC Shakhter Karagandy', 'Cazaquistão', 'FC Shakhtyor Karaganda'),
  ('FC Taraz', 'Cazaquistão', null::text),
  ('FC Tobol', 'Cazaquistão', null::text),
  ('FC Turan', 'Cazaquistão', null::text),
  ('FC Ulytau', 'Cazaquistão', null::text),
  ('FC Vostok', 'Cazaquistão', null::text),
  ('FC Yelimay', 'Cazaquistão', 'FC Spartak Semey'),
  ('FC Zhenis', 'Cazaquistão', 'Jenis'),
  ('FC Zhetysu', 'Cazaquistão', null::text),
  ('Kaspii Aqtau', 'Cazaquistão', 'FC Caspiy'),
  ('Gazelle FC', 'Chade', null::text),
  ('Tourbillon FC', 'Chade', null::text),
  ('AC Barnechea City', 'Chile', 'A.C. Barnechea City | Athletic Club Barnechea City'),
  ('Audax Italiano', 'Chile', 'Audax | Audax Club Sportivo Italiano | Audax Italiano La Florida'),
  ('CCD Arturo Fernández Vial', 'Chile', 'C.C.D. Arturo Fernández Vial | C.C.D. Arturo Fernandez Vial'),
  ('CD Palestino', 'Chile', 'C.D. Palestino | Club Deportivo Palestino | Palestino | Palestino Sports Club | Palestine Sports Club | Palestine Football Club | Palestine FC'),
  ('CD Universidad de Concepción', 'Chile', 'C.D. Universidad de Concepción | Universidad de Concepción | C.D. Universidad de Concepcion .l. | Campanil | U de Conce'),
  ('CDP Curi', 'Chile', 'C.D.P. Curi | C.D.P. Curico Unido'),
  ('Club de Deportes Green Cross', 'Chile', null::text),
  ('Club de Deportes Limache', 'Chile', 'Deportes Limache | D. Limache | Limache'),
  ('Club Deportes Antofagasta', 'Chile', 'C.D.A'),
  ('Club Deportes Concepción', 'Chile', 'Club Deportes Concepcion | Deportes Concepción'),
  ('Club Deportes La Serena', 'Chile', null::text),
  ('Club Deportivo Huachipato', 'Chile', 'Huachipato | Huachipato FC'),
  ('Club Deportivo Magallanes', 'Chile', 'Magallanes'),
  ('Club Deportivo Ñublense', 'Chile', null::text),
  ('Club Deportivo Universidad Católica', 'Chile', 'Católica, La Franja, Los Cruzados'),
  ('Club Social de Deportes Rangers', 'Chile', 'Club Social de Deportes Rangers de Talca | C.S.D. Rangers'),
  ('Club Social y Deportivo Colo Colo', 'Chile', 'Club Social y Deportivo Colo-Colo'),
  ('Club Universidad de Chile', 'Chile', 'U de Chile'),
  ('Cobreloa', 'Chile', 'Club de Deportes Cobreloa'),
  ('Cobresal', 'Chile', 'Club Deportes Cobresal'),
  ('Coquimbo Unido', 'Chile', null::text),
  ('Deportes Copiapó', 'Chile', 'Deportes Copiapo'),
  ('Deportes Iquique', 'Chile', null::text),
  ('Deportes Melipilla', 'Chile', null::text),
  ('Deportes Puerto Montt', 'Chile', 'Club de Deportes Puerto Montt'),
  ('Deportes Temuco', 'Chile', null::text),
  ('Everton de Viña del Mar', 'Chile', null::text),
  ('Lota Schwager', 'Chile', null::text),
  ('O''Higgins FC', 'Chile', 'O''Higgins F.C. | O''Higgins de Rancagua | Club Deportivo O''Higgins'),
  ('San Luis de Quillota', 'Chile', null::text),
  ('San Marcos de Arica', 'Chile', null::text),
  ('Santiago Morning', 'Chile', null::text),
  ('Santiago Wanderers', 'Chile', 'Club de Deportes Santiago Wanderers'),
  ('Unión Española', 'Chile', null::text),
  ('Unión La Calera', 'Chile', 'Union La Calera | Union Calera | Unión Calera'),
  ('Unión San Felipe', 'Chile', 'Union San Felipe'),
  ('Anhui Jiufang FC', 'China', 'Anhui Jiufang F.C.'),
  ('Baoding Yingli Yitong', 'China', null::text),
  ('Beijing Guoan FC', 'China', 'Beijing Guoan F.C. | Beijing Sinobo Guoan Football Club'),
  ('Beijing Guoan Talent Singapore FC', 'China', null::text),
  ('Beijing Hongdeng FC', 'China', 'Beijing Hongdeng F.C.'),
  ('Beijing Institute of Technology FC', 'China', null::text),
  ('Beijing Sport University FC', 'China', 'Beijing Sport University F.C. | Beijing Baxy F.C. | BSU | Běitǐdà | Beijing Enterprises Group F.C.'),
  ('Cangzhou Mighty Lions FC', 'China', 'Cangzhou Mighty Lions F.C.'),
  ('CD Monte Carlo', 'China', 'C.D. Monte Carlo | Clube Desportivo Monte Carlo'),
  ('Changchun Yatai FC', 'China', 'Changchun Yatai F.C.'),
  ('Chao Pak Kei', 'China', 'CPK'),
  ('Chengdu Rongcheng FC', 'China', 'Chengdu Rongcheng F.C. | Chengdu Better City'),
  ('Chuac Lun', 'China', null::text),
  ('Citizen AA', 'China', 'Citizen'),
  ('Dalian Shide Siwu FC', 'China', 'Dalian Shide Siwu Football Club'),
  ('Dalian Transcendence FC', 'China', 'Dalian Transcendence F.C.'),
  ('Dreams Football Club', 'China', 'Dreams FC | Hong Kong Sapling'),
  ('Eastern FC', 'China', 'Eastern Football Team | Eastern Sports Club Football Team | Eastern AA | Eastern Long Lions | Eastern Athletic Association | Eastern Sports Club | Eastern SC'),
  ('FC Porto de Macau', 'China', 'Futebol Clube do Porto em Macau'),
  ('GD Lam Pak', 'China', 'G.D. Lam Pak'),
  ('Guangdong Hongyuan FC', 'China', 'Guangdong Hongyuan F.C.'),
  ('Guangdong Sunray Cave FC', 'China', 'Guangdong Sunray Cave F.C.'),
  ('Guangzhou FC', 'China', 'Guangzhou F.C. | Guangzhou Evergrande | Guangzhou Football Club'),
  ('Guizhou FC', 'China', 'Guizhou F.C. | Guizhou Hengfeng F.C.'),
  ('Guizhou Renhe FC', 'China', 'Guizhou Renhe F.C.'),
  ('Happy Valley AA', 'China', null::text),
  ('Harbin Yiteng FC', 'China', 'Harbin Yiteng F.C.'),
  ('Henan FC', 'China', 'Henan F.C. | Henan Jianye FC | Luoyang Longmen | Henan Songshan Longmen | Henan Jianye | Henan Songshan Longmen F.C.'),
  ('Heng Tai', 'China', null::text),
  ('HKFC Soccer Section', 'China', null::text),
  ('Hohhot Black Horse', 'China', null::text),
  ('Hoi Fan', 'China', null::text),
  ('Hong Kong Pegasus FC', 'China', 'Sun Pegasus FC | Hong Kong Pegasus | HK Pegasus FC | HK Pegasus | TSW Pegasus | TSW Pegasus FC | Sun Pegasus Football Club | HK Pegasus Football Club'),
  ('Hong Kong Rangers FC', 'China', null::text),
  ('Hong Ngai', 'China', null::text),
  ('Hunan Billows FC', 'China', 'Hunan Billows F.C.'),
  ('Kei Cheong', 'China', null::text),
  ('Kei Lun', 'China', null::text),
  ('Kuan Tai', 'China', 'Kuan Tai FC'),
  ('Kunshan FC', 'China', 'Kunshan F.C.'),
  ('Lai Chi', 'China', 'Lai Chi Football Team'),
  ('Lam Ieng', 'China', null::text),
  ('Liaoning FC', 'China', 'Liaoning F.C. | Liaoning Whowin F.C.'),
  ('Liaoning Guangyuan FC', 'China', 'Liaoning Guangyuan Football Club'),
  ('Meizhou Hakka FC', 'China', 'Meizhou Hakka F.C. | Meizhou Wuhua | Meizhou Hakka Football Club'),
  ('MFA Develop', 'China', 'MFA Development'),
  ('Polícia de Segurança Pública', 'China', null::text),
  ('Qingdao FC', 'China', 'Qingdao F.C. | Qingdao Hainiu Football Club | Qingdao Huanghai Football Club'),
  ('Qingdao Hainiu FC', 'China', 'Qingdao Hainiu F.C. | Qingdao Manatee F.C. | Qingdao Jonoon F.C.'),
  ('Qingdao Qingchundao FC', 'China', 'Qingdao Qingchundao F.C. | Qingdao Zhongchuang Hengtai F.C.'),
  ('R&F (Hong Kong)', 'China', 'R&F'),
  ('Shaanxi Guoli FC', 'China', 'Shaanxi Guoli F.C.'),
  ('Shandong Taishan FC', 'China', 'Shandong Taishan F.C.'),
  ('Shanghai Port FC', 'China', 'Shanghai Port F.C. | SIPG FC | SIPG F.C. | Shanghai SIPG FC | Shanghai Dongya FC | Shanghai Dongya F.C. | Shanghai Haigang F.C. | Shanghai SIPG F.C.'),
  ('Shanghai Pudong Zobon FC', 'China', 'Shanghai Pudong Zobon F.C.'),
  ('Shanghai Shenhua FC', 'China', 'Shanghai Shenhua F.C. | Shanghai Greenland Shenhua FC'),
  ('Shanghai Shenxin FC', 'China', 'Shanghai Shenxin F.C.'),
  ('Shenyang Shenbei FC', 'China', 'Shenyang Shenbei F.C.'),
  ('Shenzhen Peng City FC', 'China', 'Shenzhen Peng City F.C. | Sichuan Jiuniu F.C.'),
  ('SL Benfica de Macau', 'China', 'S.L. Benfica de Macau | Benfica de Macau | Casa do Benfica em Macau'),
  ('South China AA', 'China', 'South China Athletic Association | South China'),
  ('Southern District FC', 'China', 'Southern District Football Club | Southern District RSA'),
  ('Sporting Clube de Macau', 'China', null::text),
  ('Sun Hei SC', 'China', 'Sun Hei Sports Club'),
  ('Tai Po FC', 'China', 'Tai Po Football Club'),
  ('Taiyuan Zhongyou Jiayi FC', 'China', 'Taiyuan Zhongyou Jiayi F.C. | Nei Mongol Zhongyou Football Club'),
  ('Windsor Arch Ka I', 'China', 'Tak Chun Ka I | Kai I'),
  ('Wuhan Three Towns FC', 'China', 'Wuhan Three Towns F.C.'),
  ('Xinjiang Tianshan Leopard FC', 'China', 'Xinjiang Tianshan Leopard F.C. | Hubei Huakaier F.C. | Xinjiang Tianshan Leopard | Hubei Léopard China FC | FC Xinjiang Tianshan'),
  ('Yanbian Funde FC', 'China', 'Yanbian Funde F.C.'),
  ('Yuen Long FC', 'China', 'Yuen Long District SA | Yuen Long Football Club | YL FC'),
  ('Yunnan Feihu FC', 'China', 'Yunnan Feihu F.C. | Lijiang Jiayunhao F.C.'),
  ('Yunnan Yukun FC', 'China', 'Yunnan Yukun F.C.'),
  ('Zhejiang Professional FC', 'China', 'Zhejiang Professional F.C. | Hangzhou Greentown F.C. | Zhejiang FC'),
  ('AC Omonia', 'Chipre', 'Athletic Club Omonoia Nicosia | AC Omonia Nicosia'),
  ('AEK Kouklia FC', 'Chipre', 'AEK Kouklia F.C.'),
  ('AEK Larnaca FC', 'Chipre', 'AEK Larnaca F.C. | AEK Larnaca'),
  ('AEL Limassol FC', 'Chipre', 'AEL FC | FC AEL | AEL Lemesos | ΑΕΛ Λεμεσού | AEL Limassol F.C. | Athlitiki Enosi Lemesou'),
  ('AEZ Zakakiou', 'Chipre', null::text),
  ('Akritas Chlorakas', 'Chipre', null::text),
  ('Alki Oroklini FC', 'Chipre', 'Omonia Oroklinis'),
  ('Anorthosis Famagusta FC', 'Chipre', null::text),
  ('APEP FC', 'Chipre', 'APEP F.C. | APEP Pitsilia | APEP Limassol'),
  ('Apollon Limassol FC', 'Chipre', 'Apollon Limassol Men'),
  ('Aris Limassol FC', 'Chipre', 'Aris Limassol F.C. | Aris Limassol'),
  ('ASIL Lysi', 'Chipre', null::text),
  ('Ayia Napa FC', 'Chipre', 'Ayia Napa F.C.'),
  ('Digenis Akritas Morphou FC', 'Chipre', null::text),
  ('Doxa Katokopias FC', 'Chipre', 'Doxa Katokopias F.C.'),
  ('Enosis Neon Paralimni FC', 'Chipre', null::text),
  ('Ermis Aradippou FC', 'Chipre', 'Ermis Aradippou'),
  ('Ethnikos Achna FC', 'Chipre', null::text),
  ('Karmiotissa Pano Polemidion', 'Chipre', null::text),
  ('Nea Salamis Famagusta FC', 'Chipre', 'Nea Salamis | Nea Salamina | Nea Salamina Famagusta FC'),
  ('Olympiakos Nicosia FC', 'Chipre', null::text),
  ('Omonia Aradippou', 'Chipre', null::text),
  ('Othellos Athienou FC', 'Chipre', 'Othellos Athienou F.C.'),
  ('Pafos FC', 'Chipre', 'Paphos FC'),
  ('América de Cali', 'Colômbia', 'America de Cali S.A.'),
  ('Atlético Bucaramanga', 'Colômbia', 'Búcaros | Leopardos | Canarios | A.B. | El Bucaramanga | El Amarillo'),
  ('Atlético Huila', 'Colômbia', null::text),
  ('Atlético Nacional', 'Colômbia', null::text),
  ('Boyacá Chicó FC', 'Colômbia', 'Boyacá Chicó F.C. | Boyaca Chico F.C.'),
  ('Boyacá Patriotas', 'Colômbia', 'Lanceros'),
  ('Cortuluá', 'Colômbia', 'Cortulua'),
  ('Cúcuta Deportivo', 'Colômbia', null::text),
  ('Deportes Quindío', 'Colômbia', null::text),
  ('Deportes Tolima', 'Colômbia', 'Club Deportes Tolima | El vinotinto y oro | Los pijaos'),
  ('Deportivo Cali', 'Colômbia', 'Asociación Deportivo Cali'),
  ('Deportivo Independiente Medellín', 'Colômbia', 'Independiente Medellin | DIM'),
  ('Deportivo Pasto', 'Colômbia', null::text),
  ('Deportivo Pereira', 'Colômbia', 'los papás del nacional'),
  ('Deportivo Unicosta', 'Colômbia', null::text),
  ('Envigado Fútbol Club', 'Colômbia', 'Envigado Futbol Club'),
  ('Fortaleza Fútbol Club', 'Colômbia', null::text),
  ('Gold Eagles', 'Colômbia', 'Aguilas Doradas | Rionegro | Aguilas Doradas Rionegro'),
  ('Huracán de Medellín', 'Colômbia', 'Huracan de Medellin'),
  ('Independiente Santa Fe', 'Colômbia', 'Santa Fe'),
  ('Internacional de Bogotá', 'Colômbia', null::text),
  ('Jaguares de Córdoba', 'Colômbia', 'Jaguares F.C. | Jaguares de Cordoba'),
  ('Junior de Barranquilla', 'Colômbia', 'Atletico Junior | Júnior'),
  ('La Equidad', 'Colômbia', 'Club Deportivo La Equidad Seguros'),
  ('Leones FC', 'Colômbia', 'Leones F.C. | Itagüí Leones | Deportivo Rionegro'),
  ('Millonarios', 'Colômbia', 'Millonarios Fútbol Club | Millonarios Futbol Club'),
  ('Once Caldas', 'Colômbia', null::text),
  ('Real Cartagena', 'Colômbia', null::text),
  ('Real Santander', 'Colômbia', null::text),
  ('Tigres Fútbol Club', 'Colômbia', null::text),
  ('Unión Magdalena', 'Colômbia', 'Union Magdalena | Banana Cyclone | The Samarios'),
  ('AC Léopards', 'Congo', 'AC Leopards'),
  ('CARA Brazzaville', 'Congo', null::text),
  ('Diables Noirs', 'Congo', null::text),
  ('Étoile du Congo', 'Congo', 'Etoile du Congo'),
  ('Amnokgang Sports Club', 'Coreia do Norte', null::text),
  ('April 25 Sports Club', 'Coreia do Norte', '4.25 Sports Club'),
  ('Chadongcha Sports Club', 'Coreia do Norte', null::text),
  ('Chandongja Sports Club', 'Coreia do Norte', null::text),
  ('Hwaebul Sports Club', 'Coreia do Norte', 'Hwaebul Sports Team'),
  ('Jebi Sports Club', 'Coreia do Norte', null::text),
  ('Kigwancha Sports Club', 'Coreia do Norte', 'Sinŭiju Locomotive'),
  ('Kyonggongop Sports Club', 'Coreia do Norte', null::text),
  ('Moranbong Sports Club', 'Coreia do Norte', 'Moranbong SC'),
  ('Pyongyang City Sports Club', 'Coreia do Norte', null::text),
  ('Rimyongsu Sports Club', 'Coreia do Norte', null::text),
  ('Rodongja Sports Club', 'Coreia do Norte', 'Rodongja SC'),
  ('Ryongnamsan Sports Club', 'Coreia do Norte', null::text),
  ('Sobaeksu Sports Club', 'Coreia do Norte', null::text),
  ('Unpasan Sports Club', 'Coreia do Norte', 'Woonpasan Sports Club'),
  ('Wolmido Sports Club', 'Coreia do Norte', null::text),
  ('Ansan Greeners FC', 'Coreia do Sul', 'Ansan Greeners Football Club | Ansan Greeners'),
  ('Bucheon FC 1995', 'Coreia do Sul', 'Bucheon Football Club 1995'),
  ('Busan IPark FC', 'Coreia do Sul', 'Busan IPark Football Club | Busan IPark | Saehan Motors Football Club | Daewoo Royals Football Club | Pusan Daewoo Royals FC | Pusan I.cons FC | Busan I''Cons FC | Busan I''Park FC'),
  ('Cheonan City FC', 'Coreia do Sul', 'Cheonan City Football Club | Cheonan City Government FC'),
  ('Chungbuk Cheongju FC', 'Coreia do Sul', null::text),
  ('Chungnam Asan FC', 'Coreia do Sul', 'Chungnam Asan Football Club'),
  ('Daegu FC', 'Coreia do Sul', 'Daegu Football Club'),
  ('Daejeon Hana Citizen FC', 'Coreia do Sul', 'Daejeon Citizen | Daejeon Citizen Football Club | Daejeon Citizen FC | Daejeon Hana Citizen Football Club | Daejeon Hana Citizen'),
  ('FC Anyang', 'Coreia do Sul', 'Football Club Anyang'),
  ('FC Pohang Steelers', 'Coreia do Sul', 'Football Club Pohang Steelers | Pohang Steelers | Pohang Atoms FC | Pohang Steel Football Club | Pohang Steel Dolphins Football Club | Pohang Steel Atoms Football Club'),
  ('FC Seoul', 'Coreia do Sul', 'Lucky-Goldstar Football Club | Lucky-Goldstar FC | LG Cheetahs | Anyang LG Cheetahs | Football Club Seoul | Anyang LG Cheetahs FC | LG Cheetahs Football Club'),
  ('Gangwon FC', 'Coreia do Sul', 'Gangwon Football Club'),
  ('Gimcheon Sangmu FC', 'Coreia do Sul', null::text),
  ('Gimhae FC 2008', 'Coreia do Sul', 'Gimhae City Government Football Club | Gimhae City Government FC'),
  ('Gimpo FC', 'Coreia do Sul', 'Gimpo Football Club | Gimpo Citizen FC'),
  ('Gwangju FC', 'Coreia do Sul', 'Gwangju Football Club'),
  ('Gyeongnam FC', 'Coreia do Sul', 'Gyeongnam Football Club'),
  ('Hwaseong FC', 'Coreia do Sul', 'Hwaseong Football Club'),
  ('Incheon Hyundai Steel Red Angels WFC', 'Coreia do Sul', 'Incheon Steel Women''s Football Club | Hyundai Steel Women''s Football Club | INI Steel Women''s Football Club'),
  ('Incheon United FC', 'Coreia do Sul', 'Incheon United Football Club | Incheon United'),
  ('Jeju SK FC', 'Coreia do Sul', 'Jeju United Football Club | Jeju United | Yukong Elephants | Bucheon SK | Jeju United FC | Bucheon Yukong FC | Bucheon SK FC | Yukong Elephants Football Club'),
  ('Jeonbuk Hyundai Motors FC', 'Coreia do Sul', 'Jeonbuk Hyundai Motors Football Club | Jeonbuk Dinos | Jeonbuk Hyundai Dinos | Chonbuk Dinos | Chonbuk Hyundai Dinos | Jeonbuk Dinos FC | Chonbuk Dinos FC | Jeonbuk Hyundai Dinos FC'),
  ('Jeonnam Dragons FC', 'Coreia do Sul', 'Chunnam Dragons | Jeonnam Dragons Football Club | Jeonnam Dragons | Chunnam Dragons FC'),
  ('Paju Frontier FC', 'Coreia do Sul', 'Paju Citizen FC'),
  ('Seongnam FC', 'Coreia do Sul', 'Ilhwa Chunma | Seongnam Ilhwa Chunma | Seongnam Football Club | Ilhwa Chunma Football Club | Cheonan Ilhwa Chunma FC | Seongnam Ilhwa Chunma FC | Chionan Ilhwa Chunma FC | Songnam Ilhwa Chungma FC'),
  ('Seoul E-Land FC', 'Coreia do Sul', 'Seoul E-Land Football Club'),
  ('Suwon FC', 'Coreia do Sul', 'Suwon Football Club | Suwon City Government FC'),
  ('Suwon Samsung Bluewings FC', 'Coreia do Sul', 'Suwon Samsung Bluewings Football Club | Suwon Samsung Bluewings'),
  ('Ulsan HD FC', 'Coreia do Sul', 'Ulsan Hyundai Football Club | Ulsan Hyundai Horang-i | Ulsan Hyundai FC | Ulsan Hyundai Horang-i FC | Hyundai Horang-i Football Club'),
  ('Yongin FC', 'Coreia do Sul', null::text),
  ('Academie de Foot Amadou Diallo', 'Costa do Marfim', 'AFAD Djékanou'),
  ('Africa Sports d''Abidjan', 'Costa do Marfim', 'Africa Sports National'),
  ('AS Denguélé', 'Costa do Marfim', 'Denguele Sports d''Odienne | AS Denguele | Denguelé Sports d''Odienné | Association Sportive Denguélé'),
  ('AS Indenié Abengourou', 'Costa do Marfim', 'AS Indenie Abengourou'),
  ('ASC Ouragahio', 'Costa do Marfim', null::text),
  ('ASEC Mimosas', 'Costa do Marfim', null::text),
  ('Association Sportive Tanda', 'Costa do Marfim', null::text),
  ('Bouaké FC', 'Costa do Marfim', null::text),
  ('CO Korhogo', 'Costa do Marfim', null::text),
  ('ES Bingerville', 'Costa do Marfim', null::text),
  ('FC Hiré', 'Costa do Marfim', 'FC Hire'),
  ('FC Mouna', 'Costa do Marfim', 'Football Club Mouna d''Akoupé'),
  ('FC San Pédro', 'Costa do Marfim', null::text),
  ('Issia Wazi FC', 'Costa do Marfim', null::text),
  ('Jeunesse Club d''Abidjan', 'Costa do Marfim', null::text),
  ('Moossou FC', 'Costa do Marfim', null::text),
  ('RC Daloa', 'Costa do Marfim', null::text),
  ('Séwé FC', 'Costa do Marfim', 'Séwé Sport de San-Pédro | Séwé Sport'),
  ('Société Omnisports de l''Armée', 'Costa do Marfim', null::text),
  ('Sporting Club de Gagnoa', 'Costa do Marfim', null::text),
  ('Stade d''Abidjan', 'Costa do Marfim', null::text),
  ('Stella Club d''Adjamé', 'Costa do Marfim', null::text),
  ('USC Bassam', 'Costa do Marfim', null::text),
  ('Williamsville AC', 'Costa do Marfim', null::text),
  ('AD Belén', 'Costa Rica', 'A.D. Belén | A.D. Belen'),
  ('AD Guanacasteca', 'Costa Rica', 'Asociación Deportiva Guanacasteca'),
  ('Asociación Deportiva Carmelita', 'Costa Rica', 'AD Carmelita | Asociacion Deportiva Carmelita'),
  ('Asociación Deportiva San Carlos', 'Costa Rica', 'AD San Carlos | Sancarleños | Toros del Norte'),
  ('Club Sport Uruguay de Coronado', 'Costa Rica', 'Uruguay Coronado'),
  ('CS Cartaginés', 'Costa Rica', 'C.S. Cartaginés | Cartago | Brumosos'),
  ('CS Herediano', 'Costa Rica', 'C.S. Herediano | Heredia | Herediano | Florenses'),
  ('Deportivo Saprissa', 'Costa Rica', 'Saprissa'),
  ('Guadalupe Fútbol Club', 'Costa Rica', 'Guadalupe FC | Guadalupe'),
  ('La U Universitarios', 'Costa Rica', 'Universitarios FC | Universitarios'),
  ('Liga Deportiva Alajuelense', 'Costa Rica', 'L.D. Alajuelense | Alajuelense | La Liga'),
  ('Municipal Liberia', 'Costa Rica', 'A.D. Municipal Liberia | Asociación Deportiva Municipal Liberia'),
  ('Municipal Pérez Zeledón', 'Costa Rica', 'Pérez Zeledón | Guerreros del Sur | PZ | Pezeteros | Sureños'),
  ('Puntarenas FC', 'Costa Rica', 'Puntarenas F.C. | Las sardinas, Las chuchecas'),
  ('Santos de Guápiles', 'Costa Rica', 'Santistas | Guapileños | Rojiblancos | La Marea Roja'),
  ('GNK Dinamo Zagreb', 'Croácia', 'Dinamo Zagreb | NK Dinamo Zagreb | Građanski nogometni klub Dinamo Zagreb | Croatia Zagreb | GNK Dinamo'),
  ('HAŠK', 'Croácia', null::text),
  ('HNK Cibalia', 'Croácia', 'Cibalia Vinkovci'),
  ('HNK Gorica', 'Croácia', null::text),
  ('HNK Hajduk Split', 'Croácia', 'HNK Hajduk | Hajduk Split | Hajduk'),
  ('HNK Rijeka', 'Croácia', null::text),
  ('HNK Segesta', 'Croácia', null::text),
  ('HNK Šibenik', 'Croácia', null::text),
  ('HNK Vukovar 1991', 'Croácia', null::text),
  ('NK Belišće', 'Croácia', null::text),
  ('NK Bistra', 'Croácia', null::text),
  ('NK Dugopolje', 'Croácia', null::text),
  ('NK HAŠK 1903', 'Croácia', null::text),
  ('NK Hrvatski Dragovoljac', 'Croácia', null::text),
  ('NK Imotski', 'Croácia', null::text),
  ('NK Inter Zaprešić', 'Croácia', null::text),
  ('NK Istra 1961', 'Croácia', 'Nogometni klub Istra 1961 | NK Istra Pula'),
  ('NK Kustošija Zagreb', 'Croácia', null::text),
  ('NK Lokomotiva', 'Croácia', null::text),
  ('NK Lučko', 'Croácia', null::text),
  ('NK Marsonia', 'Croácia', null::text),
  ('NK Međimurje', 'Croácia', null::text),
  ('NK Mosor', 'Croácia', null::text),
  ('NK Novigrad', 'Croácia', null::text),
  ('NK Osijek', 'Croácia', 'Nogometni klub Osijek'),
  ('NK Primorac 1929', 'Croácia', null::text),
  ('NK Radnik Sesvete', 'Croácia', 'NK Sesvete'),
  ('NK Rudeš', 'Croácia', null::text),
  ('NK Slaven Belupo', 'Croácia', null::text),
  ('NK Solin', 'Croácia', null::text),
  ('NK Trešnjevka', 'Croácia', null::text),
  ('NK Varaždin ŠN', 'Croácia', null::text),
  ('NK Zadar', 'Croácia', 'Nogometni Klub Zadar'),
  ('NK Zagreb', 'Croácia', 'N.K. Zagreb'),
  ('NK Zelina', 'Croácia', null::text),
  ('RNK Split', 'Croácia', null::text),
  ('CF Granma', 'Cuba', null::text),
  ('Ciudad de La Habana', 'Cuba', null::text),
  ('FC Artemisa', 'Cuba', null::text),
  ('FC Camagüey', 'Cuba', null::text),
  ('FC Ciego de Ávila', 'Cuba', 'FC Ciego de Avila'),
  ('FC Cienfuegos', 'Cuba', null::text),
  ('FC Guantánamo', 'Cuba', 'FC Guantanamo'),
  ('FC Industriales', 'Cuba', null::text),
  ('FC Isla de La Juventud', 'Cuba', null::text),
  ('FC La Habana', 'Cuba', null::text),
  ('FC Las Tunas', 'Cuba', null::text),
  ('FC Matanzas', 'Cuba', null::text),
  ('FC Mayabeque', 'Cuba', null::text),
  ('FC Pinar del Río', 'Cuba', 'FC Pinar del Rio'),
  ('FC Santiago de Cuba', 'Cuba', null::text),
  ('FC Villa Clara', 'Cuba', null::text),
  ('Holguín FC', 'Cuba', 'FC Holguin'),
  ('Sancti Spíritus FC', 'Cuba', 'FC Sancti Spiritus'),
  ('CRKSV Jong Colombia', 'Curaçau', 'Jong Colombia'),
  ('CRKSV Jong Holland', 'Curaçau', null::text),
  ('AaB Fodbold', 'Dinamarca', null::text),
  ('Aarhus Gymnastikforening', 'Dinamarca', 'Aarhus GF | AGF Århus | AGF Arhus | AGF Aarhus | Aarhus Gymnastik Forening | Århus GF'),
  ('AC Horsens', 'Dinamarca', 'Horsens fS'),
  ('Akademisk Boldklub', 'Dinamarca', 'AB Copenhagen | Akademisk BK | AB | Akademisk Boldklub Gladsaxe | AB Gladsaxe | Fredericia Studenternes Kricketklub | Polyteknisk Boldklub'),
  ('Boldklubben 1903', 'Dinamarca', 'B 1903'),
  ('Boldklubben 1909', 'Dinamarca', null::text),
  ('Boldklubben 1913', 'Dinamarca', 'B 1913 | B 1913 Odense'),
  ('Boldklubben af 1893', 'Dinamarca', 'BK 93 Copenhagen'),
  ('Boldklubben Frem', 'Dinamarca', null::text),
  ('Brøndby IF', 'Dinamarca', 'Brondby IF | BIF | Brøndbyernes Idrætsforening | Brondby Idraetsforening'),
  ('Brønshøj Boldklub', 'Dinamarca', null::text),
  ('Esbjerg fB', 'Dinamarca', 'Esbjerg forenede Boldklubber'),
  ('FC Copenhagen', 'Dinamarca', 'F.C. Copenhagen | Football Club Copenhagen | FC København | FCK'),
  ('FC Fredericia', 'Dinamarca', 'Fodbold Club Fredericia af 1991'),
  ('FC Helsingør', 'Dinamarca', 'Football Club Helsingør'),
  ('FC Midtjylland', 'Dinamarca', null::text),
  ('FC Nordsjælland', 'Dinamarca', null::text),
  ('FC Roskilde', 'Dinamarca', null::text),
  ('Fremad Amager', 'Dinamarca', 'Boldklubben Fremad Amager'),
  ('HB Køge', 'Dinamarca', null::text),
  ('Hellerup IK', 'Dinamarca', 'Hellerup Idræts Klub'),
  ('Herfølge Boldklub', 'Dinamarca', null::text),
  ('Hillerød Fodbold', 'Dinamarca', null::text),
  ('Hobro IK', 'Dinamarca', 'Hobro Idræts Klub'),
  ('Holbæk B&I', 'Dinamarca', null::text),
  ('Hvidovre IF', 'Dinamarca', 'Hvidovre Idrætsforening'),
  ('Ikast FS', 'Dinamarca', null::text),
  ('Jammerbugt FC', 'Dinamarca', 'Blokhus FC'),
  ('Køge Boldklub', 'Dinamarca', null::text),
  ('Lyngby Boldklub', 'Dinamarca', null::text),
  ('Næstved BK', 'Dinamarca', null::text),
  ('Nykøbing FC', 'Dinamarca', null::text),
  ('Odense Boldklub', 'Dinamarca', null::text)
) as v(name, country, aliases)
join countries c on c.name = v.country
on conflict (name, country_id) do update set aliases = coalesce(teams.aliases, excluded.aliases);
