-- Football clubs from Wikidata (CC0), part 2 of 4. Safe to re-run: a club that already exists (same name and country) is kept and only gets its other names filled in.
-- Run 0023_uk_countries.sql first (it creates Inglaterra, Escocia, etc. and the aliases column).
insert into teams (name, country_id, aliases)
select v.name, c.id, v.aliases
from (values
  ('Ølstykke FC', 'Dinamarca', 'Ølstykke Fodbold Club'),
  ('Randers FC', 'Dinamarca', 'Randers Football Club'),
  ('Silkeborg IF', 'Dinamarca', 'Silkeborg Idrætsforening | Silkeborg'),
  ('Skive IK', 'Dinamarca', null::text),
  ('Sønderjyske Fodbold', 'Dinamarca', 'SønderjyskE | Haderslev FK'),
  ('Thisted FC', 'Dinamarca', null::text),
  ('Vanløse IF', 'Dinamarca', 'Vanløse Idræts Forening | V.I.F.'),
  ('Vejle Boldklub', 'Dinamarca', null::text),
  ('Vendsyssel FF', 'Dinamarca', 'Vendsyssel Forenede Fodboldklubber'),
  ('Viborg FF', 'Dinamarca', 'Viborg Fodsports Forening | VFF'),
  ('VSK Aarhus', 'Dinamarca', 'Vejlby Skovbakken Aarhus'),
  ('Al Ahly SC', 'Egito', 'Al Ahly | Al-Ahly | Al Ahly Sporting Club | Al-Ahly SC | Al-Ahly Sporting Club | Al Ahly S.C. | Al-Ahly S.C.'),
  ('Al Ittihad Alexandria Club', 'Egito', 'El Ittihad El Sakandary'),
  ('Al Masry SC', 'Egito', 'Al Masry Sporting Club'),
  ('Al Nasr Lel Taa''den SC', 'Egito', 'Nasr Mining FC | El Nasr Tadeen | Al Tadeen SC'),
  ('Aswan SC', 'Egito', null::text),
  ('Ceramica Cleopatra FC', 'Egito', 'Ceramica Cleopatra Football Club'),
  ('Eastern Company SC', 'Egito', 'Sharqiya Lel Dokhan | El Sharqiya Lelddukhan | Eastern Tobacco SC | Eastern Tobacco Club'),
  ('El Dakhleya', 'Egito', null::text),
  ('El Gouna FC', 'Egito', null::text),
  ('El Raja Marsa Matruh', 'Egito', null::text),
  ('El-Entag El-Harby', 'Egito', 'نادي الانتاج الحربي الرياضي'),
  ('El-Olympi', 'Egito', 'Al-Olympi | Egyptian Olympic Athletes Club | El Olympi'),
  ('ENPPI SC', 'Egito', 'ENPPI Sporting Club'),
  ('Ghazl El Mahalla SC', 'Egito', 'Ghazl El-Mahalla'),
  ('Haras El-Hodood SC', 'Egito', 'Haras El-Hodood'),
  ('Ismaily SC', 'Egito', null::text),
  ('Ittihad El-Shorta', 'Egito', null::text),
  ('Misr Lel Makkasa SC', 'Egito', 'Misr Lel Makkasa'),
  ('Modern SC', 'Egito', 'Future FC | Modern Future FC | Modern Sport FC | Modern Sport Club | Modern S.C.'),
  ('National Bank of Egypt SC', 'Egito', null::text),
  ('Nogoom FC', 'Egito', null::text),
  ('Petrojet FC', 'Egito', 'Petrojet'),
  ('Pyramids FC', 'Egito', 'Pyramids F.C. | Pyramids | PFC'),
  ('Smouha SC', 'Egito', 'Smouha Sporting Club'),
  ('Tala''ea El-Gaish SC', 'Egito', 'Tala''ae El Jaishis'),
  ('Telephonat Bani Sweif', 'Egito', null::text),
  ('Tersana SC', 'Egito', 'Tersana Sporting Club'),
  ('Wadi Degla SC', 'Egito', null::text),
  ('Zamalek SC', 'Egito', 'Zamalek Sporting Club | ZSC | Zamalek | Zamalek S.C. | ZamalekSportingClub | Al-Zamalek | El-Zamalek | Z.S.C.'),
  ('ZED FC', 'Egito', 'FC Masr'),
  ('AD Isidro Metapán', 'El Salvador', 'A.D. Isidro Metapán | A.D. Isidro Metapan | CD Isidro-Metapán | CD Isidro-Metapan | C.D. Isidro Metapán | C.D. Isidro Metapan'),
  ('Alianza Fútbol Cub', 'El Salvador', 'Albos | Paquidermos | La orquesta alba | Elefantes'),
  ('CD Águila', 'El Salvador', 'C.D. Águila | Eagles | Zopes'),
  ('CD Atlético Marte', 'El Salvador', 'C.D. Atlético Marte | C.D. Atletico Marte'),
  ('CD FAS', 'El Salvador', 'C.D. FAS | Tigrillos'),
  ('CD Luis Ángel Firpo', 'El Salvador', 'C.D. Luis Ángel Firpo | C.D. Luis Angel Firpo | L.A. Firpo | LA Firpo | Firpo'),
  ('Ajman Club', 'Emirados Árabes Unidos', null::text),
  ('Al Ain FC', 'Emirados Árabes Unidos', null::text),
  ('Al Dhafra Club', 'Emirados Árabes Unidos', 'Al Dhafra Sport & Culture Club | Al Dhafra S.C.C.'),
  ('Al Jazira Club', 'Emirados Árabes Unidos', null::text),
  ('Al Wasl FC', 'Emirados Árabes Unidos', 'Al Wasl Football Club'),
  ('Al-Fujairah FC', 'Emirados Árabes Unidos', 'Al-Fujairah SC | Al-Fujairah | Fujairah SC'),
  ('Al-Shaab CSC', 'Emirados Árabes Unidos', null::text),
  ('Alshariqa', 'Emirados Árabes Unidos', 'Al-Nasr Dubai | Al-Nasr S.C.'),
  ('Al-Wahda SCC', 'Emirados Árabes Unidos', 'Al-Wahda S.C.C. | Al-Wahda Abu Dhabi'),
  ('Baniyas SC', 'Emirados Árabes Unidos', null::text),
  ('Dibba Club', 'Emirados Árabes Unidos', 'Dibba Al-Fujairah Club'),
  ('Dubai CSC', 'Emirados Árabes Unidos', null::text),
  ('Emirates Club', 'Emirados Árabes Unidos', 'Emirates Cultural Sport Club | Emirates C.S.C.'),
  ('Hatta Club', 'Emirados Árabes Unidos', null::text),
  ('Kalba FC', 'Emirados Árabes Unidos', null::text),
  ('Khor Fakkan Club', 'Emirados Árabes Unidos', 'Al Khaleej Club'),
  ('Palm City FC', 'Emirados Árabes Unidos', 'Al Qabila FC'),
  ('Shabab AlAhli Dubai Club', 'Emirados Árabes Unidos', 'Shabab Al-Ahli Dubai FC | Shabab AlAhli Dubai FC | Shabab AlAhli | Shabab AlAhli Club | Shabab Al-Ahli Club | Shabab Al-Ahli Dubai Club'),
  ('Sharjah FC', 'Emirados Árabes Unidos', 'Sharjah C.S.C. | Al Sharjah SC'),
  ('Barcelona SC', 'Equador', 'Barcelona S.C. | Coloso de América'),
  ('Bonita Banana Fútbol Club', 'Equador', null::text),
  ('CD Cuenca', 'Equador', 'C.D. Cuenca | Deportivo Cuenca | Club Deportivo Cuenca'),
  ('Centro Deportivo Olmedo', 'Equador', null::text),
  ('Club 9 de Octubre', 'Equador', 'Asociación Deportiva Nueve de Octubre'),
  ('Club Deportivo El Nacional', 'Equador', 'CD El Nacional | El Nacional'),
  ('Club Deportivo ESPOLI', 'Equador', null::text),
  ('Club Deportivo Politécnico', 'Equador', 'Club Deportivo Politecnico'),
  ('Club Deportivo Quevedo', 'Equador', null::text),
  ('Club Social y Deportivo Macará', 'Equador', 'Club Social y Deportivo Macara'),
  ('Club Sport Emelec', 'Equador', 'CS Emelec | Emelec | Bicampeones | Tricampeones'),
  ('Delfín Sporting Club', 'Equador', 'Delfin Sporting Club'),
  ('Fuerza Amarilla Sporting Club', 'Equador', null::text),
  ('Guayaquil City FC', 'Equador', 'Guayaquil City F.C.'),
  ('Imbabura Sporting Club', 'Equador', null::text),
  ('Independiente del Valle', 'Equador', 'C.S.D. Independiente del Valle | CSD Independiente del Valle'),
  ('Liga Deportiva Universitaria de Loja', 'Equador', null::text),
  ('Liga Deportiva Universitaria de Portoviejo', 'Equador', null::text),
  ('Liga Deportiva Universitaria de Quito', 'Equador', 'Liga de Quito | LDU | LDU Quito | Rey de Copas Ecuatoriano'),
  ('Manta Fútbol Club', 'Equador', 'Manta Futbol Club'),
  ('Mushuc Runa Sporting Club', 'Equador', 'El Ponchito'),
  ('SD Quito', 'Equador', 'S.D. Quito | Sociedad Deportivo Quito | Deportivo Quito'),
  ('Sociedad Deportiva Aucas', 'Equador', 'SD Aucas'),
  ('Técnico Universitario', 'Equador', 'Rodillo Rojo'),
  ('Universidad Católica del Ecuador', 'Equador', 'Universidad Catolica del Ecuador'),
  ('Red Sea FC', 'Eritreia', null::text),
  ('Aberdeen', 'Escócia', 'Aberdeen F.C. | Aberdeen FC | Aberdeen Football Club | AFC | The Dons'),
  ('Airdrieonians', 'Escócia', 'Airdrieonians F.C. | Airdrie United Football Club | Airdrieonians Football Club'),
  ('Albion Rovers', 'Escócia', 'Albion Rovers F.C. | Albion Rovers Football Club'),
  ('Alloa Athletic', 'Escócia', 'Alloa Athletic F.C. | Alloa Athletic Football Club'),
  ('Annan Athletic', 'Escócia', 'Annan Athletic F.C.'),
  ('Arbroath', 'Escócia', 'Arbroath F.C.'),
  ('Arthurlie', 'Escócia', 'Arthurlie F.C.'),
  ('Ayr United', 'Escócia', 'Ayr United F.C. | Ayr United Football Club | Ayr United FC | Ayr | AUFC | The Honest Men'),
  ('Brechin City', 'Escócia', 'Brechin City F.C. | Brechin City Football Club'),
  ('Celtic', 'Escócia', 'Celtic F.C. | Celtic Football Club | Celtic plc | The Celtic Football Club | The Hoops | The Bhoys | The Celts'),
  ('Clyde', 'Escócia', 'Clyde F.C. | Clyde Football Club'),
  ('Cove Rangers', 'Escócia', 'Cove Rangers F.C.'),
  ('Cowdenbeath', 'Escócia', 'Cowdenbeath F.C. | Cowdenbeath Football Club'),
  ('Dumbarton', 'Escócia', 'Dumbarton F.C. | Dumbarton Football Club'),
  ('Dundee', 'Escócia', 'Dundee F.C. | Dundee Football Club | Dundee FC | The Dee'),
  ('Dundee United', 'Escócia', 'Dundee United F.C. | Dundee United Football Club | Dundee United FC | DUFC | The Terrors | The Tangerines | Dundee Hibernian'),
  ('Dundee Wanderers', 'Escócia', 'Dundee Wanderers F.C.'),
  ('Dunfermline Athletic', 'Escócia', 'Dunfermline Athletic F.C. | Dunfermline Athletic Football Club | Dunfermline Athletic FC | The Pars | Dunfermline | DAFC'),
  ('East Fife', 'Escócia', 'East Fife F.C.'),
  ('East Stirlingshire', 'Escócia', 'East Stirlingshire F.C.'),
  ('Edinburgh City', 'Escócia', 'Edinburgh City F.C.'),
  ('Elgin City', 'Escócia', 'Elgin City F.C. | Elgin City Football Club'),
  ('Falkirk', 'Escócia', 'Falkirk F.C. | Falkirk Football Club | Falkirk FC | The Bairns | FFC'),
  ('Forfar Athletic', 'Escócia', 'Forfar Athletic F.C. | Forfar Athletic Football Club'),
  ('Greenock Morton', 'Escócia', 'Greenock Morton F.C. | Greenock Morton Football Club | Morton Football Club'),
  ('Hamilton Academical', 'Escócia', 'Hamilton Academical F.C. | Hamilton Academical Football Club | Hamilton Academicals'),
  ('Heart of Midlothian', 'Escócia', 'Heart of Midlothian F.C. | Heart of Midlothian Football Club | Hearts'),
  ('Hibernian', 'Escócia', 'Hibernian F.C. | Hibernian Football Club | Hibernian FC | Hibs | Hibees'),
  ('Inverness Caledonian Thistle', 'Escócia', 'Inverness Caledonian Thistle F.C. | Inverness Caledonian Thistle FC | Inverness | ICTFC | Caley Thistle'),
  ('Kelty Hearts', 'Escócia', 'Kelty Hearts F.C.'),
  ('Kilmarnock', 'Escócia', 'Kilmarnock F.C. | Kilmarnock Football Club | Killie | KFC'),
  ('Livingston', 'Escócia', 'Livingston F.C. | Livingston Football Club | Livingston FC | Livi'),
  ('Montrose', 'Escócia', 'Montrose F.C.'),
  ('Motherwell', 'Escócia', 'Motherwell F.C. | Well'),
  ('Partick Thistle', 'Escócia', 'Partick Thistle F.C. | Partick Thistle Football Club'),
  ('Peebles Rovers', 'Escócia', 'Peebles Rovers F.C.'),
  ('Peterhead', 'Escócia', 'Peterhead F.C.'),
  ('Queen of the South', 'Escócia', 'Queen of the South F.C. | Queen of the South Football Club | Queen of the South FC | The Doonhamers | QOTSFC'),
  ('Queen''s Park', 'Escócia', 'Queen''s Park F.C. | Queen''s Park Football Club | Queen''s Park FC | The Spiders | QPFC'),
  ('Raith Rovers', 'Escócia', 'Raith Rovers F.C. | Raith Rovers Football Club'),
  ('Rangers', 'Escócia', 'Rangers F.C. | Rangers Football Club | Rangers FC | RFC | The Gers | Glasgow Rangers'),
  ('Ross County', 'Escócia', 'Ross County F.C. | Ross County Football Club'),
  ('Shawfield', 'Escócia', 'Shawfield F.C.'),
  ('St Johnstone', 'Escócia', 'St Johnstone F.C. | St Johnstone Football Club | SJFC'),
  ('St. Mirren', 'Escócia', 'St. Mirren F.C. | St. Mirren Football Club | Saint Mirren Football Club | St Mirren'),
  ('Stenhousemuir', 'Escócia', 'Stenhousemuir F.C. | Stenhousemuir Football Club'),
  ('Stirling Albion', 'Escócia', 'Stirling Albion F.C. | Stirling Albion Football Club'),
  ('Stranraer', 'Escócia', 'Stranraer F.C. | Stranraer Football Club'),
  ('Vale of Leven', 'Escócia', 'Vale of Leven F.C.'),
  ('1. FC Tatran Prešov', 'Eslováquia', null::text),
  ('FC DAC 1904 Dunajská Streda', 'Eslováquia', 'Dunajská Streda'),
  ('FC Košice', 'Eslováquia', null::text),
  ('FC Lokomotíva Košice', 'Eslováquia', null::text),
  ('FC Nitra', 'Eslováquia', null::text),
  ('FC Petržalka', 'Eslováquia', 'Pozsonyi Torna Egyesület (PTE) | Engerau Pressburg | ŠK Petržalka | ZŠJ Kovosmalt Petržalka | TJ Spartak Kovosmalt Bratislava | TJ Považské Strojárne Bratislava | SKS Petržalka | TJ ZŤS Petržalka'),
  ('FC Spartak Trnava', 'Eslováquia', 'Spartak Trnava'),
  ('FC VSS Košice', 'Eslováquia', 'Football Club VSS Košice'),
  ('FC Zlaté Moravce', 'Eslováquia', 'FC ViOn Zlate Moravce'),
  ('FK AS Trenčín', 'Eslováquia', null::text),
  ('FK Inter Bratislava', 'Eslováquia', null::text),
  ('FK Pohronie', 'Eslováquia', null::text),
  ('FK Púchov', 'Eslováquia', 'FK Puchov'),
  ('FK Senica', 'Eslováquia', null::text),
  ('KFC Komárno', 'Eslováquia', 'KFC Komarno'),
  ('MFK Dubnica', 'Eslováquia', null::text),
  ('MFK Ružomberok', 'Eslováquia', null::text),
  ('MFK Skalica', 'Eslováquia', null::text),
  ('MFK Tatran Liptovský Mikuláš', 'Eslováquia', 'Tatran Liptovský Mikuláš | Tatran Liptovsky Mikulas'),
  ('MFK Zemplín Michalovce', 'Eslováquia', 'MFK Zemplin Michalovce'),
  ('MŠK Rimavská Sobota', 'Eslováquia', null::text),
  ('MŠK Žilina', 'Eslováquia', 'ŠK Žilina'),
  ('ŠK Slovan Bratislava', 'Eslováquia', null::text),
  ('ŠKF Sereď', 'Eslováquia', 'Športový Klub Futbalu Sereď | Sportovy Klub Futbalu Sered | SKF Sered'),
  ('Spartak Myjava', 'Eslováquia', 'TJ Spartak Myjava'),
  ('ŽP Šport Podbrezová', 'Eslováquia', null::text),
  ('DNŠ Primorje', 'Eslovénia', null::text),
  ('FC Koper', 'Eslovénia', 'Football Club Koper'),
  ('ND Gorica', 'Eslovénia', 'Nogometno Društvo Gorica | HIT Gorica'),
  ('ND Ilirija Ljubljana', 'Eslovénia', 'Nogometno Društvo Ilirija 1911'),
  ('ND Slovan', 'Eslovénia', null::text),
  ('NK Aluminij', 'Eslovénia', 'Nogometni Klub Aluminij | Aluminij'),
  ('NK Bela Krajina', 'Eslovénia', null::text),
  ('NK Bravo', 'Eslovénia', 'Nogometni klub Bravo'),
  ('NK Celje', 'Eslovénia', 'Nogometni Klub Celje | Celje'),
  ('NK Domžale', 'Eslovénia', null::text),
  ('NK Dravograd', 'Eslovénia', null::text),
  ('NK Interblock', 'Eslovénia', null::text),
  ('NK Krka', 'Eslovénia', 'Football club Krka'),
  ('NK Krško', 'Eslovénia', null::text),
  ('NK Ljubljana', 'Eslovénia', 'Ljubljana'),
  ('NK Maribor', 'Eslovénia', 'Nogometni Klub Maribor'),
  ('NK Olimpija Ljubljana', 'Eslovénia', 'Olimpija Ljubljana'),
  ('NK Primorje', 'Eslovénia', null::text),
  ('NK Radomlje', 'Eslovénia', null::text),
  ('NK Rogaška', 'Eslovénia', null::text),
  ('NK Rudar Velenje', 'Eslovénia', null::text),
  ('NK Tabor Sežana', 'Eslovénia', null::text),
  ('NK Triglav Kranj', 'Eslovénia', null::text),
  ('NK Zavrč', 'Eslovénia', null::text),
  ('ŠD NŠ Mura 05', 'Eslovénia', 'NŠ Mura | Nogometna Šola Mura'),
  ('ACD San Marcial', 'Espanha', null::text),
  ('AD Alcorcón', 'Espanha', 'Agrupación Deportiva Alcorcón | AD Alcorcon | Agrupacion Deportiva Alcorcon'),
  ('AD Almudévar', 'Espanha', null::text),
  ('AD Cerro de Reyes', 'Espanha', null::text),
  ('AD Ceuta FC', 'Espanha', 'Club Atletico de Ceuta | Club Atlético de Ceuta'),
  ('AD Colmenar Viejo', 'Espanha', 'Agrupación Deportiva Colmenar Viejo'),
  ('AD Parla', 'Espanha', null::text),
  ('AD Sabiñánigo', 'Espanha', null::text),
  ('AD San Juan', 'Espanha', null::text),
  ('AD Unión Adarve Barrio del Pilar', 'Espanha', 'UNION ZONA NORTE'),
  ('AD Universidad de Oviedo', 'Espanha', null::text),
  ('AD Villaviciosa de Odón', 'Espanha', 'AD Villaviciosa de Odon'),
  ('AE Prat', 'Espanha', null::text),
  ('Águilas FC', 'Espanha', 'Aguilas FC'),
  ('Albacete Balompié', 'Espanha', 'Albacete Balompié, S.A.D.'),
  ('Alcobendas CF', 'Espanha', null::text),
  ('Algeciras CF', 'Espanha', null::text),
  ('Alhaurín de la Torre CF', 'Espanha', 'Alhaurin de la Torre CF'),
  ('Alondras CF', 'Espanha', null::text),
  ('Amurrio Club', 'Espanha', null::text),
  ('Andorra CF', 'Espanha', null::text),
  ('Antequera CF', 'Espanha', null::text),
  ('Aravaca CF', 'Espanha', null::text),
  ('Arcos CF EL LAPILLA', 'Espanha', null::text),
  ('Arenas CD', 'Espanha', null::text),
  ('Arenas Club de Getxo', 'Espanha', null::text),
  ('Arosa SC', 'Espanha', null::text),
  ('Arroyo CP', 'Espanha', null::text),
  ('Arucas CF', 'Espanha', null::text),
  ('Athletic Club', 'Espanha', 'Athletic Bilbao | Athletic Club de Bilbao'),
  ('Atlétich Chichizola', 'Espanha', 'Atletico Monzon'),
  ('Atlético Arteixo', 'Espanha', 'Atletico Arteixo'),
  ('Atlético Astorga FC', 'Espanha', 'Atletico Astorga FC | es un nabo'),
  ('Atlético Calatayud', 'Espanha', 'Atletico Calatayud'),
  ('Atlético Granadilla', 'Espanha', 'Atletico Granadilla'),
  ('Atlético Levante UD', 'Espanha', 'Levante UD B'),
  ('Atlético Madrid', 'Espanha', 'Club Atlético de Madrid, SAD | Club Atlético de Madrid | Atletico | El Atleti | ATM Football Club | Atletico of Madrid | Atleti de Madrid | ATM'),
  ('Atlético Malagueño', 'Espanha', 'Atlético Malagueno | Málaga CF B | Málaga C.F. B | Màlaga Club de Futbol B'),
  ('Atlético Mancha Real', 'Espanha', 'Atletico Mancha Real'),
  ('Atlético Saguntino', 'Espanha', 'Atletico Saguntino'),
  ('Atlético Sanluqueño CF', 'Espanha', null::text),
  ('Atlético Tordesillas', 'Espanha', 'Atletico Tordesillas'),
  ('Atzeneta UE', 'Espanha', 'Atzeneta'),
  ('Ayamonte CF', 'Espanha', null::text),
  ('Barakaldo CF', 'Espanha', null::text),
  ('Benalup CF', 'Espanha', null::text),
  ('Bergantiños FC', 'Espanha', null::text),
  ('Betanzos CF', 'Espanha', null::text),
  ('Betis', 'Espanha', null::text),
  ('Burgos CF', 'Espanha', null::text),
  ('Burgos CF Promesas', 'Espanha', null::text),
  ('C.D BURGALÉS', 'Espanha', null::text),
  ('CA Antoniano', 'Espanha', 'Club Atlético Antoniano'),
  ('CA Artajonés', 'Espanha', null::text),
  ('CA Cirbonero', 'Espanha', null::text),
  ('CA Pinto', 'Espanha', null::text),
  ('CA Pulpileño', 'Espanha', null::text),
  ('CA River Ebro', 'Espanha', null::text),
  ('CA Vianés', 'Espanha', null::text),
  ('Cádiz', 'Espanha', 'Cádiz Club de Fútbol | Cadiz CF | Cadiz Club de Fútbol'),
  ('Candás CF', 'Espanha', 'Candas CF'),
  ('CAP Ciudad de Murcia', 'Espanha', null::text),
  ('Casalarreina CF', 'Espanha', null::text),
  ('Castillo CF', 'Espanha', null::text),
  ('Castro FC', 'Espanha', null::text),
  ('Caudal Deportivo', 'Espanha', 'Caudal de Mieres'),
  ('CCD Alberite', 'Espanha', null::text),
  ('CCD Cerceda', 'Espanha', null::text),
  ('CD Agoncillo', 'Espanha', null::text),
  ('CD Albacete', 'Espanha', 'Guijuelo'),
  ('CD Alcalá', 'Espanha', 'CD Alcala'),
  ('CD Alcoyano', 'Espanha', 'C.D. Alcoyano | Club Deportivo Alcoyano | los rompe ortos'),
  ('CD Aldeano', 'Espanha', null::text),
  ('CD Alfaro', 'Espanha', null::text),
  ('CD Alhaurino', 'Espanha', null::text),
  ('CD Altorricón', 'Espanha', 'CD Altorricon'),
  ('CD Aluvión', 'Espanha', 'CD Aluvion'),
  ('CD Anguiano', 'Espanha', null::text),
  ('CD Aoiz', 'Espanha', 'Reds'),
  ('CD Arenas de Frajanas', 'Espanha', null::text),
  ('CD Arenteiro', 'Espanha', null::text),
  ('CD Arnedo', 'Espanha', null::text),
  ('CD As Pontes', 'Espanha', 'Club Deportivo As Pontes'),
  ('CD Atlético Baleares', 'Espanha', 'Club Deportivo Atlético Baleares | CD Atletico Baleares | Club Deportivo Atletico Baleares | Atlètic Balears | ATB'),
  ('CD Aurrerá de Vitoria', 'Espanha', 'CD Aurrera de Vitoria'),
  ('CD Aurrerá Ondarroa', 'Espanha', null::text),
  ('CD Azkoyen', 'Espanha', null::text),
  ('CD Azuqueca', 'Espanha', 'Club Deportivo Azuqueca'),
  ('CD Bala Azul', 'Espanha', null::text),
  ('CD Barco', 'Espanha', 'Centro de Deportes Barco'),
  ('CD Baskonia', 'Espanha', 'Club Deportivo Baskonia | Club Deportivo Basconia'),
  ('CD Becerril', 'Espanha', null::text),
  ('CD Beniel', 'Espanha', 'Club Deportivo Beniel'),
  ('CD Berceo', 'Espanha', null::text),
  ('CD Berio FT', 'Espanha', null::text),
  ('CD Beti Onak', 'Espanha', null::text),
  ('CD Binéfar', 'Espanha', 'CD Binefar'),
  ('CD Binissalem', 'Espanha', null::text),
  ('CD Brea', 'Espanha', null::text),
  ('CD Bullense', 'Espanha', 'Club Deportivo Bullense'),
  ('CD Burriana', 'Espanha', null::text),
  ('CD Calahorra', 'Espanha', null::text),
  ('CD Carranque', 'Espanha', null::text),
  ('CD Castellón', 'Espanha', 'C.D. Castellón | CD Castellon | C.D. Castellon'),
  ('CD Cayón', 'Espanha', 'CD Cayon'),
  ('CD Cebrereña', 'Espanha', null::text),
  ('CD Cenicero', 'Espanha', null::text),
  ('CD Choco', 'Espanha', null::text),
  ('CD Cieza', 'Espanha', 'Club Deportivo Cieza'),
  ('CD Colindres', 'Espanha', null::text),
  ('CD Colonia Moscardó', 'Espanha', 'CD Colonia Moscardo'),
  ('CD Colunga', 'Espanha', null::text),
  ('CD Comarca de Níjar', 'Espanha', 'CD Comarca de Nijar'),
  ('CD Corellano', 'Espanha', null::text),
  ('CD Coria', 'Espanha', null::text),
  ('CD Corralejo', 'Espanha', null::text),
  ('CD Cortes', 'Espanha', null::text),
  ('CD Covadonga', 'Espanha', null::text),
  ('CD Cristo Atlético', 'Espanha', 'CD Cristo Atletico'),
  ('CD Cuarte', 'Espanha', null::text),
  ('CD Cultural Areas', 'Espanha', null::text),
  ('CD Dénia', 'Espanha', 'CD Denia'),
  ('CD Don Benito', 'Espanha', 'Club Deportivo Don Benito | Don Benito'),
  ('CD Ebro', 'Espanha', null::text),
  ('CD Egüés', 'Espanha', null::text),
  ('CD El Álamo', 'Espanha', 'CD El Alamo | Club Deportivo El Álamo'),
  ('CD El Ejido 2012', 'Espanha', null::text),
  ('CD El Palo', 'Espanha', 'Centro de Deportes El Palo'),
  ('CD Eldense', 'Espanha', 'Club Deportivo Eldense'),
  ('CD Elgoibar', 'Espanha', null::text),
  ('CD Ferriolense', 'Espanha', null::text),
  ('CD Getxo', 'Espanha', null::text),
  ('CD Griñón', 'Espanha', null::text),
  ('CD Guadalcacín', 'Espanha', null::text),
  ('CD Guarnizo', 'Espanha', null::text),
  ('CD Huétor Tájar', 'Espanha', 'CD Huetor Tajar'),
  ('CD Ibiza Islas Pitiusas', 'Espanha', null::text),
  ('CD Idoya', 'Espanha', null::text),
  ('CD Illescas', 'Espanha', null::text),
  ('CD Íscar', 'Espanha', 'CD Iscar'),
  ('CD Itaroa Huarte', 'Espanha', null::text),
  ('CD Izarra', 'Espanha', null::text),
  ('CD La Virgen del Camino', 'Espanha', null::text),
  ('CD Lagun Onak', 'Espanha', null::text),
  ('CD Laudio', 'Espanha', null::text),
  ('CD Leganés', 'Espanha', 'CD Leganes | Leganes Football | CD Leganes Soccer | Leganes Soccer Club | CD Leganes Football | Club Deportivo Leganés, S.A.D.'),
  ('CD Llanes', 'Espanha', null::text),
  ('CD Llosetense', 'Espanha', null::text),
  ('CD Madalena de Morcín', 'Espanha', null::text),
  ('CD Madridejos', 'Espanha', null::text),
  ('CD Mairena', 'Espanha', null::text),
  ('CD Manacor', 'Espanha', null::text),
  ('CD Manchego C.Real', 'Espanha', 'Manchego | Depor'),
  ('CD Marchamalo', 'Espanha', null::text),
  ('CD Mariño', 'Espanha', null::text),
  ('CD Masnou', 'Espanha', null::text),
  ('CD Mendi', 'Espanha', null::text),
  ('CD Mensajero', 'Espanha', 'Club Deportivo Mensajero'),
  ('CD Minera', 'Espanha', 'Aguante el Aston villa'),
  ('CD Mirandés', 'Espanha', 'Club Deportivo Mirandes | C.D. Mirandes'),
  ('CD Mosconia', 'Espanha', null::text),
  ('CD Naval', 'Espanha', null::text),
  ('CD Olímpic de Xàtiva', 'Espanha', 'Olímpic'),
  ('CD Palencia Balompié', 'Espanha', 'Club Deportivo Palencia Balompié'),
  ('CD Peña Azagresa', 'Espanha', null::text),
  ('CD Plus Ultra', 'Espanha', null::text),
  ('CD Pontejos', 'Espanha', 'Club Deportivo Pontejos'),
  ('CD Pozoblanco', 'Espanha', null::text),
  ('CD Praviano', 'Espanha', null::text),
  ('CD Quintanar del Rey', 'Espanha', null::text),
  ('CD Revilla', 'Espanha', 'Club Deportivo Revilla | Sociedad Deportiva Revilla'),
  ('CD River Ega', 'Espanha', null::text),
  ('CD Roces', 'Espanha', null::text),
  ('CD Roda', 'Espanha', null::text),
  ('CD Ronda', 'Espanha', null::text),
  ('CD San Isidro', 'Espanha', null::text),
  ('CD San Roque de Lepe', 'Espanha', null::text),
  ('CD Santa Amalia', 'Espanha', 'Club Deportivo Santa Amalia'),
  ('CD Santanyí', 'Espanha', 'CD Santanyi'),
  ('CD Sariñena', 'Espanha', null::text),
  ('CD Siete Villas', 'Espanha', null::text),
  ('CD Tedeón EF', 'Espanha', 'CD Tedeon EF'),
  ('CD Tenerife', 'Espanha', 'C.D. Tenerife | Club Deportivo Tenerife, S.A.D.'),
  ('CD Teruel', 'Espanha', 'Club Deportivo Teruel'),
  ('CD Tineo', 'Espanha', null::text),
  ('CD Toledo', 'Espanha', 'Club Deportivo Toledo'),
  ('CD Torrijos', 'Espanha', 'Club Deportivo Torrijos'),
  ('CD Tropezón', 'Espanha', 'CD Tropezon'),
  ('CD Tudelano', 'Espanha', null::text),
  ('CD Tuilla', 'Espanha', null::text),
  ('CD Utiel', 'Espanha', null::text),
  ('CD Utrera', 'Espanha', 'Club Deportivo Utrera'),
  ('CD Valdefierro', 'Espanha', null::text),
  ('CD Valdelacalzada', 'Espanha', null::text),
  ('CD Varea', 'Espanha', null::text),
  ('CD Villegas', 'Espanha', null::text),
  ('CD Vitoria', 'Espanha', null::text),
  ('CDFC La Calzada', 'Espanha', null::text),
  ('CE Alaior', 'Espanha', null::text),
  ('CE Andratx', 'Espanha', null::text),
  ('CE Campos', 'Espanha', null::text),
  ('CE Constància', 'Espanha', 'CD Constancia'),
  ('CE Europa', 'Espanha', null::text),
  ('CE Mercadal', 'Espanha', null::text),
  ('Céltiga FC', 'Espanha', 'Celtiga FC'),
  ('Centre d''Esports Sabadell Futbol Club', 'Espanha', 'Sabadell FC'),
  ('Cerdanyola del Vallès FC', 'Espanha', null::text),
  ('CF Ardoi FE', 'Espanha', null::text),
  ('CF Badalona', 'Espanha', null::text),
  ('CF Badalona Futur', 'Espanha', null::text),
  ('CF Borriol', 'Espanha', 'C.F. Borriol'),
  ('CF Calamocha', 'Espanha', 'Club de Fútbol Calamocha'),
  ('CF Fuenlabrada', 'Espanha', null::text),
  ('CF Fuenlabrada Promesas Madrid 2021', 'Espanha', 'Móstoles Balompié | Flat Earth FC'),
  ('CF Gandía', 'Espanha', 'CF Gandia'),
  ('CF Gimnástico Alcázar', 'Espanha', 'CF Gimnastico Alcazar'),
  ('CF Illueca', 'Espanha', null::text),
  ('CF Intercity', 'Espanha', 'Club de Fútbol Intercity | Club de Futbol Intercity | Intercity'),
  ('CF La Nucía', 'Espanha', 'CF La Nucia | La Nucia'),
  ('CF Lorca Deportiva', 'Espanha', null::text),
  ('CF Montañesa', 'Espanha', null::text),
  ('CF Motril', 'Espanha', null::text),
  ('CF Panadería Pulido', 'Espanha', null::text),
  ('CF Peralada', 'Espanha', 'Club de Fútbol Peralada | Peralada del Girona'),
  ('CF Platges de Calvià', 'Espanha', 'Platges de Calvià'),
  ('CF Pozuelo de Alarcón', 'Espanha', 'CF Pozuelo de Alarcon'),
  ('CF Rápid', 'Espanha', null::text),
  ('CF Rayo Majadahonda', 'Espanha', 'Club de Fútbol Rayo Majadahonda'),
  ('CF Ribamontán al Mar', 'Espanha', 'CF Ribamontan al Mar'),
  ('CF San Rafael', 'Espanha', null::text),
  ('CF Sóller', 'Espanha', 'CF Soller'),
  ('CF Talavera de la Reina', 'Espanha', null::text),
  ('CF Trival Valderas.', 'Espanha', 'C.F. Trival Valderas.'),
  ('CF Trujillo', 'Espanha', null::text),
  ('CF Unión Viera', 'Espanha', 'CF Union Viera'),
  ('CF Villanovense', 'Espanha', null::text),
  ('CF Vimenor', 'Espanha', null::text),
  ('Ciudad Rodrigo CF', 'Espanha', null::text),
  ('Club Atlético Osasuna', 'Espanha', 'CA Osasuna'),
  ('Club Deportivo Badajoz', 'Espanha', 'CD Badajoz | Club Deportivo Badajoz 1905 | CDB 1905'),
  ('Club Deportivo Betoño-Elgorriaga', 'Espanha', null::text),
  ('Club Deportivo Guadalajara', 'Espanha', 'Club Deportivo Guadalajara, S.A.D | GUADALAJARA'),
  ('Club Deportivo Lugo', 'Espanha', 'CD Lugo'),
  ('Club Deportivo Numancia de Soria', 'Espanha', 'Club Deportivo Numancia de Soria, S.A.D. | CD Numancia'),
  ('Club Deportivo Pamplona', 'Espanha', 'CD Pamplona'),
  ('Club Español de Madrid', 'Espanha', null::text),
  ('Club Esportiu Almassora', 'Espanha', null::text),
  ('Club Lleida Esportiu', 'Espanha', 'Lleida Esportiu'),
  ('Club Marino de Luanco', 'Espanha', 'Marino de Luanco'),
  ('Club Olímpico de Totana', 'Espanha', 'Club Olimpico de Totana'),
  ('Club Portugalete', 'Espanha', null::text),
  ('Club Recreativo Granada', 'Espanha', 'Granada Club de Futbol "B"'),
  ('Condal Club', 'Espanha', null::text),
  ('Conil CF', 'Espanha', null::text),
  ('Córdoba CF', 'Espanha', 'Córdoba Club de Fútbol, S.A.D. | Cordoba CF | Cordoba Club de Futbol'),
  ('Coria CF', 'Espanha', 'Coria'),
  ('Coruxo FC', 'Espanha', 'Coruxo'),
  ('CP Amanecer', 'Espanha', null::text),
  ('CP Cacereño', 'Espanha', 'Cacereño'),
  ('CP Calasancio', 'Espanha', null::text),
  ('CP Sanvicenteño', 'Espanha', null::text),
  ('CP Villarrobledo', 'Espanha', null::text),
  ('Crevillente Deportivo', 'Espanha', null::text),
  ('CU Collado Villalba', 'Espanha', null::text),
  ('DAV Santa Ana', 'Espanha', null::text),
  ('Deportivo Alavés', 'Espanha', 'Alavés | Alaves | Deportivo Alaves | Deportivo Alaves Soccer | Alaves Football | Alaves Soccer'),
  ('Deportivo Aragón', 'Espanha', 'Deportivo Aragon'),
  ('Deportivo de A Coruña', 'Espanha', 'Real Club Deportivo de La Coruña | Dépor | Deportivo | Real Club Deportivo de La Coruña S.A.D. | Club Deportivo de la Sala Calvet, Turcos | Depor | R.C. Deportivo de La Coruña | Real Club Deportivo de A Coruña'),
  ('Deportivo Dorneda CF', 'Espanha', null::text),
  ('Deportivo Fabril', 'Espanha', 'Deportivo de La Coruña B | Real Club Deportivo Fabril'),
  ('Deportivo Rayo Cantabria', 'Espanha', null::text),
  ('Écija Balompié', 'Espanha', 'Ecija Balompie | Ecija Balompié'),
  ('EI San Martín', 'Espanha', null::text),
  ('El Palmar CF', 'Espanha', null::text),
  ('Elche CF', 'Espanha', 'Elche Club de Fútbol, S.A.D.'),
  ('Elche CF Ilicitano', 'Espanha', null::text),
  ('FC Ascó', 'Espanha', 'FC Asco'),
  ('FC Barcelona Atlètic', 'Espanha', 'Fútbol Club Barcelona "B" | CF Barcelona Atlético | Barcelona B | Futbol Club Barcelona Atlètic | F.C. Barcelona "B" | Barcelona "B" | CF Barcelona Atletico | Futbol Club Barcelona Atletic'),
  ('FC Cartagena', 'Espanha', null::text),
  ('FC Jove Español San Vicente', 'Espanha', null::text),
  ('FC Jumilla', 'Espanha', null::text),
  ('FC Torrevieja', 'Espanha', null::text),
  ('Formac Villarrubia CF', 'Espanha', null::text),
  ('Gernika Club', 'Espanha', null::text),
  ('Getafe CF', 'Espanha', 'Getafe Club de Fútbol | Getafe Club de Futbol | Getafe Club de Fútbol Team | Getafe | Getafe Football Club | Getafe Club of Football | Getafe C.F.'),
  ('Gimnàstic de Tarragona', 'Espanha', null::text),
  ('Gimnástica Arandina CF', 'Espanha', null::text),
  ('Gimnástica de Torrelavega', 'Espanha', 'Gimnastica de Torrelavega'),
  ('Gimnástica Segoviana CF', 'Espanha', 'Gimnastica Segoviana CF'),
  ('Girona FC', 'Espanha', 'Girona Futbol Club, S.A.D. | Girona Futbol Club | Girona FC Club | Girona Soccer Team | Girona'),
  ('Granada CF', 'Espanha', 'Granada Club de Fútbol | Granada Club de Futbol | Granada C.F.'),
  ('Guadix CF', 'Espanha', null::text),
  ('Haro Deportivo', 'Espanha', null::text),
  ('Hellín CF', 'Espanha', 'Baku Hellin Deportivo'),
  ('Hércules CF', 'Espanha', 'Hercules CF'),
  ('Huércal-Overa CF', 'Espanha', 'Huercal-Overa CF'),
  ('Internacional de Madrid CF', 'Espanha', 'Inter de Madrid | Internacional de Madrid'),
  ('Jerez CF', 'Espanha', null::text),
  ('Jerez Industrial CF', 'Espanha', 'Jerez Industrial Club de Fútbol'),
  ('Juventud de Torremolinos CF', 'Espanha', null::text),
  ('La Gineta CF', 'Espanha', null::text),
  ('La Roda CF', 'Espanha', null::text),
  ('Laracha CF', 'Espanha', null::text),
  ('Las Rozas CF', 'Espanha', 'Las Rozas Club de Fútbol'),
  ('L''Entregu CF', 'Espanha', null::text),
  ('Levante UD', 'Espanha', 'Levante Unión Deportiva | Levante Union Deportiva | Levante UD Football | Levante | Levante U.D. | Levante Football Club | Levante FC | Levante Sports Union'),
  ('Linares Deportivo', 'Espanha', null::text),
  ('Loja CD', 'Espanha', null::text),
  ('Málaga CF', 'Espanha', 'Málaga Club of Football | Málaga C.F. | MálagaCF | MCF | Malaga CF | Malaga Football Club | Malaga C.F. | M.C.F.'),
  ('Manzanares CF', 'Espanha', 'Manzanares Club de Fútbol'),
  ('Martos CD', 'Espanha', null::text),
  ('Mérida AD', 'Espanha', 'Merida AD'),
  ('México FC SAD', 'Espanha', 'México FC   S.A.D. | Fútbol Alcobendas Sport'),
  ('Mora CF', 'Espanha', null::text),
  ('Moralo CP', 'Espanha', null::text),
  ('Murchante FC', 'Espanha', null::text),
  ('Muro CF', 'Espanha', null::text),
  ('Narón BP', 'Espanha', 'Naron BP'),
  ('Náxara CD', 'Espanha', 'Naxara CD'),
  ('Novelda CF', 'Espanha', 'Novelda Club de Fútbol | Novelda'),
  ('Olivenza FC', 'Espanha', null::text),
  ('Orihuela CF', 'Espanha', null::text),
  ('Palamós CF', 'Espanha', 'Palamós Club de Futbol'),
  ('Pasaia KE', 'Espanha', null::text),
  ('Paterna CF', 'Espanha', null::text),
  ('PD Santa Eulalia', 'Espanha', null::text),
  ('Peña Sport FC', 'Espanha', null::text),
  ('Peñarroya-Porronuevo', 'Espanha', 'Peñarroya-Porronuevo Club de Fútbol'),
  ('Pobla de Mafumet CF', 'Espanha', null::text),
  ('Pontevedra CF', 'Espanha', 'Pontevedra C.F.'),
  ('Racing Cartagena Mar Menor FC', 'Espanha', null::text),
  ('Racing Club de Ferrol', 'Espanha', 'Racing de Ferrol'),
  ('Racing Club Portuense', 'Espanha', null::text),
  ('Racing de Santander', 'Espanha', 'Real Racing Club de Santander, S.A.D. | Real Racing Club de Santander | Racing Santander | Racing Club de Santander | Real Racing Club | Real Santander SD'),
  ('Racing Lermeño', 'Espanha', null::text),
  ('Rápido de Bouzas', 'Espanha', 'Rapido de Bouzas'),
  ('Rayo Cantabria', 'Espanha', 'Racing de Santander B'),
  ('Rayo Vallecano', 'Espanha', 'Rayo Vallecano de Madrid | Rayo Football | Rayo Vellecano Football | Rayo Vellecano Soccer Club | Rayo | Vallecano'),
  ('RB Linense', 'Espanha', 'Real Balompédica Linense'),
  ('RC Celta de Vigo', 'Espanha', 'Real Club Celta S.A.D. | RC Celta | Real Club Celta | R.C. Celta de Vigo | RCCV | Celta Vigo | Celta'),
  ('RC Celta Fortuna', 'Espanha', 'Celta Turista | Celta B | Real Club Celta de Vigo "B" | Celta de Vigo B | Panda Team | RC Celta B'),
  ('RC Villalbés', 'Espanha', 'RC Villalbes'),
  ('RCD Carabanchel', 'Espanha', null::text),
  ('RCD Espanyol de Barcelona', 'Espanha', 'RCDE | RCD Espanyol | Espanyol | R.C.D. Espanyol de Barcelona | R.C.D. Espanyol of Barcelona | R.C.D. Espanyol | RCD Espanyol of Barcelona | Espanyol of Barcelona'),
  ('RCD Mallorca', 'Espanha', 'Real Club Deportivo Mallorca | Mallorca | R.C.D. Mallorca'),
  ('Real Aranjuez CF', 'Espanha', null::text),
  ('Real Ávila CF', 'Espanha', 'What parkour'),
  ('Real Avilés CF', 'Espanha', 'Real Avilés Club de Fútbol | Real Avilés C. F., SAD | Real Aviles | Real Aviles Club de Futbol | Real Aviles CF | Real Avilés | Real Avilés C.F.'),
  ('Real Betis Balompié', 'Espanha', 'balompédicos | Real Betis football | Real Betis Soccer | Real Betis | Beticos, verdiblancos | Real Betis Balompié S.A.D. | Betis'),
  ('Real Burgos CF', 'Espanha', null::text),
  ('Real Jaén', 'Espanha', 'Real Jaén C.F. | Real Jaen | Real Jaen C.F.'),
  ('Real Madrid', 'Espanha', 'Real Madrid Club de Fútbol | Real Madrid Football Club | Real Madrid C.F. | RMCF | Real FC | Royal Madrid Football Club | Real Madrid Club of Football | Real Football Club | Royal Madrid'),
  ('Real Murcia', 'Espanha', 'Real Club de Fútbol, ​​SAD'),
  ('Real Murcia Imperial', 'Espanha', null::text),
  ('Real Oviedo', 'Espanha', 'Real Oviedo S.A.D.'),
  ('Real Oviedo Vetusta', 'Espanha', 'Real Oviedo B | Vetusta | Sociedad Deportiva Vetusta | Sportiva Ovetense'),
  ('Real Sociedad', 'Espanha', 'Real Sociedad de Fútbol, S.A.D. | Real Sociedad de Fútbol | Donostia Football Club | San Sebastián Foot-Ball Club | Real Sociedad de Futbol | San Sebastian Foot-Ball Club'),
  ('Real Sporting San José', 'Espanha', 'Real Sporting San Jose'),
  ('Real Tapia CF', 'Espanha', null::text),
  ('Real Unión', 'Espanha', 'Real Union'),
  ('Real Valladolid', 'Espanha', 'Real Valladolid Club de Fútbol, S.A.D | Real Valladolid Football | Real Valladolid Soccer | Real Valladolid Club | Valladolid'),
  ('Real Zaragoza', 'Espanha', 'Real Zaragoza S.A.D. | Real Zaragoza SAD | R. Zaragoza'),
  ('Recreativo de Huelva', 'Espanha', 'R.C.D. Huelva'),
  ('Ribadumia CF', 'Espanha', null::text),
  ('Ribarroja CF', 'Espanha', null::text),
  ('RSD Alcalá', 'Espanha', 'RSD Alcala'),
  ('Salamanca CF UDS', 'Espanha', null::text),
  ('Santa Teresa CD', 'Espanha', 'UD Badajoz | Deportivo Pacense'),
  ('Santfeliuenc FC', 'Espanha', null::text),
  ('Santoña CF', 'Espanha', null::text),
  ('SCD Durango', 'Espanha', null::text),
  ('SD Almazán', 'Espanha', 'SD Almazan | Sociedad Deportiva Almazán'),
  ('SD Amorebieta', 'Espanha', null::text),
  ('SD Atlético Albericia', 'Espanha', 'SD Atletico Albericia'),
  ('SD Balmaseda FC', 'Espanha', null::text),
  ('SD Barreda Balompié', 'Espanha', 'SD Barreda Balompie'),
  ('SD Beasain', 'Espanha', null::text),
  ('SD Borja', 'Espanha', null::text),
  ('SD Buelna', 'Espanha', null::text),
  ('SD Compostela', 'Espanha', null::text),
  ('SD Deusto', 'Espanha', null::text),
  ('SD Eibar', 'Espanha', 'SD Eibar Soccer | Eibar Soccer Team | Eibar Football Club | SD Eibar Club | Sociedad Deportiva Eibar, S.A.D.'),
  ('SD Ejea', 'Espanha', 'Sociedad Deportiva Ejea'),
  ('SD Erandio Club', 'Espanha', null::text),
  ('SD Formentera', 'Espanha', null::text),
  ('SD Lagunak', 'Espanha', null::text),
  ('SD Laredo', 'Espanha', null::text),
  ('SD Leioa', 'Espanha', null::text),
  ('SD Logroñés', 'Espanha', null::text),
  ('SD Navarro CF', 'Espanha', null::text),
  ('SD Negreira', 'Espanha', null::text),
  ('SD Oyonesa', 'Espanha', null::text),
  ('SD Tarazona', 'Espanha', null::text),
  ('SD Tenisca', 'Espanha', null::text),
  ('SD Textil Escudo', 'Espanha', null::text),
  ('Selaya FC', 'Espanha', null::text),
  ('Sestao River Club', 'Espanha', 'Sestao | River'),
  ('Sevilla FC', 'Espanha', 'Sevilla | Sevilla Fútbol Club | Sevilla F.C. | Sevilla Football Club | SevillaFC | Sevilla Futbol Club | SevillaF.C. | S.F.C.'),
  ('Silva SD', 'Espanha', null::text),
  ('Sociedad Deportiva Huesca', 'Espanha', 'Sociedad Deportiva Huesca, S.A.D. | SD Huesca Soccer | SD Huesca Football | Huesca Football Club'),
  ('Sociedad Deportiva Ponferradina', 'Espanha', 'Sociedad Deportiva Ponferradina, S.A.D. | SD Ponferradina'),
  ('Solares SD', 'Espanha', null::text),
  ('Sporting de Gijón', 'Espanha', 'Sporting Gijon | Sporting Gijón | Sporting de Gijon | Real Sporting de Gijón | Real Sporting de Gijon | Real Sporting de Gijón, S.A.D. | Real Sporting de Gijon, S.A.D.'),
  ('Sporting Villanueva Promesas', 'Espanha', null::text),
  ('SR Villaverde Boetticher CF', 'Espanha', null::text),
  ('Terrassa FC', 'Espanha', 'Terrassa Futbol Club'),
  ('Tolosa CF', 'Espanha', null::text),
  ('UB Conquense', 'Espanha', null::text),
  ('Úbeda', 'Espanha', 'Úbeda Club de Fútbol | Úbeda C.F. | Úbeda CF | Ubeda Club de Futbol | Ubeda C.F. | Ubeda CF'),
  ('UC Ceares', 'Espanha', null::text),
  ('UCAM Murcia CF', 'Espanha', null::text),
  ('UCD Burladés', 'Espanha', null::text),
  ('UD Almansa', 'Espanha', null::text),
  ('UD Alzira', 'Espanha', null::text),
  ('UD Barbadás', 'Espanha', 'UD Barbadas'),
  ('UD Barbastro', 'Espanha', 'Unión Deportiva Barbastro'),
  ('UD Ciudad de Torredonjimeno', 'Espanha', null::text),
  ('UD Collerense', 'Espanha', null::text),
  ('UD Gijón Industrial', 'Espanha', 'UD Gijon Industrial | Gijón Industrial | Unión Deportivo Gijón Industrial'),
  ('UD Ibiza', 'Espanha', null::text),
  ('UD Juventud Barrio del Cristo', 'Espanha', null::text),
  ('UD Lanzarote', 'Espanha', null::text),
  ('UD Las Palmas', 'Espanha', 'Unión Deportiva Las Palmas | Las Palmas'),
  ('UD Las Palmas Atlético', 'Espanha', 'UD Las Palmas Atletico'),
  ('UD Las Zocas', 'Espanha', null::text),
  ('UD Llanera', 'Espanha', 'Unión Deportiva Llanera'),
  ('UD Logroñés', 'Espanha', 'Ud logroñes'),
  ('UD Los Barrios', 'Espanha', null::text),
  ('UD Los Llanos', 'Espanha', null::text),
  ('UD Maracena', 'Espanha', 'Unión Deportiva Maracena'),
  ('UD Marbella', 'Espanha', null::text),
  ('UD Melilla', 'Espanha', null::text),
  ('UD Montijo', 'Espanha', null::text),
  ('UD Mutilvera', 'Espanha', null::text),
  ('UD Poblense', 'Espanha', null::text),
  ('UD Puçol', 'Espanha', 'Unión Deportiva Puçol'),
  ('UD Realejos', 'Espanha', null::text),
  ('UD San Claudio', 'Espanha', null::text),
  ('UD San Pedro', 'Espanha', null::text),
  ('UD San Sebastián de los Reyes', 'Espanha', 'UD San Sebastian de los Reyes'),
  ('UD Santa Marta', 'Espanha', null::text),
  ('UD Socuéllamos', 'Espanha', 'UD Socuellamos'),
  ('UD Somozas', 'Espanha', 'Unión Deportiva Somozas'),
  ('UD Talavera', 'Espanha', null::text),
  ('UD Tijarafe', 'Espanha', 'Unión Deportiva Tijarafe'),
  ('UD Villa de Santa Brígida', 'Espanha', 'UD Villa de Santa Brigida'),
  ('UDC Chantrea', 'Espanha', null::text),
  ('UE Castelldefels', 'Espanha', null::text),
  ('UE Cornellá', 'Espanha', 'UE Cornella'),
  ('UE Figueres', 'Espanha', null::text),
  ('UE Olot', 'Espanha', null::text),
  ('UE Rapitenca', 'Espanha', null::text),
  ('UE Rubí', 'Espanha', 'UE Rubi'),
  ('UE Sant Andreu', 'Espanha', null::text),
  ('UE Vilassar de Mar', 'Espanha', null::text),
  ('UM Escobedo', 'Espanha', 'UME'),
  ('Unami Club Polideportivo', 'Espanha', null::text),
  ('Unión Deportiva Almería', 'Espanha', 'U.D. Almería | U.D. Almeria'),
  ('Unión Deportiva Ibarra', 'Espanha', 'Union Deportiva Ibarra'),
  ('Unión Molinense C.F', 'Espanha', 'CF Molina'),
  ('Unión Popular de Langreo', 'Espanha', 'UP Langreo'),
  ('Unionistas de Salamanca CF', 'Espanha', null::text),
  ('UP Plasencia', 'Espanha', null::text),
  ('Urraca CF', 'Espanha', null::text),
  ('Utebo FC', 'Espanha', null::text),
  ('Valencia CF', 'Espanha', 'Valencia Club de Fútbol | Valencia | Valencia Club de Futbol | Valencia Club de Fútbol team | Valencia C.F. | Valencia Football Club | Valencia Club of Football | ValenciaCF'),
  ('Valencia CF Mestalla', 'Espanha', null::text),
  ('Velarde CF', 'Espanha', null::text),
  ('Villalonga FC', 'Espanha', 'Villalonga Fútbol Club | Villalonga Football Club'),
  ('Villanueva CF', 'Espanha', null::text),
  ('Villarreal CF', 'Espanha', 'Villarreal Club de Fútbol, S.A.D. | Villarreal Club de Futbol | Villarreal Club Football | Villarreal 1923 | Villarreal Club de Fútbol 1923 | Villarreal Club of Football | Villarreal CF 1923 | Villarreal C.F.'),
  ('Xerez CD', 'Espanha', 'Xerez C.D. | Xerez Club Deportivo, S.A.D. | Xerez'),
  ('Xerez Deportivo Fútbol Club', 'Espanha', 'Xerez DFC'),
  ('Xuventú Sanxenxo', 'Espanha', 'Xuventu Sanxenxo'),
  ('Yagüe CF', 'Espanha', null::text),
  ('Zalla UC', 'Espanha', null::text),
  ('Zamora CF', 'Espanha', null::text),
  ('Zamudio SD', 'Espanha', null::text),
  ('Zarautz KE', 'Espanha', null::text),
  ('Green Mamba FC', 'Essuatíni', null::text),
  ('Manzini Wanderers FC', 'Essuatíni', 'Manzini Wanderers F.C.'),
  ('Mbabane Highlanders FC', 'Essuatíni', 'Mbabane Highlanders F.C.'),
  ('Mbabane Swallows FC', 'Essuatíni', 'Mbabane Swallows F.C. | Mbabane Swallows Football Club'),
  ('Royal Leopards FC', 'Essuatíni', 'Royal Leopards F.C.'),
  ('Young Buffaloes FC', 'Essuatíni', null::text),
  ('Atlanta United FC', 'Estados Unidos', 'Atlanta United | ATL UTD | ATL UTD FC | ATL United | ATL United FC'),
  ('Atlético Dallas', 'Estados Unidos', 'Atletico Dallas | USL Dallas'),
  ('Austin Aztex', 'Estados Unidos', null::text),
  ('Austin Bold FC', 'Estados Unidos', 'Austin Bold | Austin Bold Football Club | USL Austin'),
  ('Austin FC', 'Estados Unidos', 'Austin Football Club'),
  ('Bay FC', 'Estados Unidos', 'Bay Football Club'),
  ('Birmingham Legion FC', 'Estados Unidos', 'USL Birmingham | Birmingham Legion | BHM Legion FC | BHM Legion | Birmingham Legion Football Club | Legion | Legion FC'),
  ('Boston Legacy FC', 'Estados Unidos', 'NWSL Boston | BOS Nation FC'),
  ('Buffalo Pro Soccer', 'Estados Unidos', null::text),
  ('Charleston Battery', 'Estados Unidos', 'Battery'),
  ('Charlotte FC', 'Estados Unidos', 'Charlotte Football Club | Charlotte MLS | Charlotte F.C.'),
  ('Charlotte Independence', 'Estados Unidos', 'the Jacks | CLT Independence'),
  ('Chicago Fire FC', 'Estados Unidos', 'Men in Red | CF97 | Chicago Fire Soccer Club | Chicago Fire S.C. | Chicago Fire SC | Chicago Fire Football Club | Chicago Fire F.C. | the Fire'),
  ('Chicago Stars FC', 'Estados Unidos', 'Red Stars | Chicago Red Stars'),
  ('Colorado Rapids', 'Estados Unidos', 'Colorado Rapids FC | Colorado Rapids Football Club | Colorado Rapids Soccer Club | Colorado Rapids Soccer | CO Rapids | CO Rapids FC'),
  ('Colorado Springs Switchbacks FC', 'Estados Unidos', 'Switchbacks | Switchbacks FC | CSS'),
  ('Columbus Crew', 'Estados Unidos', 'Columbus Crew Soccer Club | Crew SC | Crew Soccer Club | the Massive | the Crew | Columbus Crew SC | Columbus Soccer Club | Columbus SC'),
  ('Columbus NWSL team', 'Estados Unidos', null::text),
  ('DC United', 'Estados Unidos', 'D.C. United | DCU | Black-and-Red | United D.C.'),
  ('Denver Summit FC', 'Estados Unidos', 'Denver Summit'),
  ('Detroit City FC', 'Estados Unidos', 'Detroit City Football Club'),
  ('El Paso Locomotive FC', 'Estados Unidos', 'El Paso USL | El Paso Locomotive | El Paso Locomotive Football Club | EP Locomotive | EP Locomotive FC'),
  ('FC Cincinnati', 'Estados Unidos', 'Futbol Club Cincinnati | FCC | FC Cincy | Fussball Club Cincinnati LLC | CIN | Football Club Cincinnati | Orange and Blue | Knifey Lions'),
  ('FC Dallas', 'Estados Unidos', 'FCD | Hoops | Red Stripes | Toros | Burn | Dallas 96 | Dallas Soccer Club | Dallas FC'),
  ('FC Tulsa', 'Estados Unidos', 'Tulsa Roughnecks | Roughnecks | Tulsa Roughnecks FC'),
  ('Hartford Athletic', 'Estados Unidos', null::text),
  ('Houston Dynamo FC', 'Estados Unidos', 'Orange Crush | La Naranja | The Men in Orange | The Orange | Die Oranje | Houston Dynamo | Dynamo | Dynamo FC'),
  ('Indy Eleven', 'Estados Unidos', null::text),
  ('Inter Miami CF', 'Estados Unidos', 'Vice City | The Herons | Inter Miami FC | Internacional de Miami | Internacional of Miami | Miami Soccer club | Miami Football Club | Miami FC'),
  ('Jacksonville Armada FC', 'Estados Unidos', 'Jacksonville Armada | Jacksonville Armada Football Club'),
  ('LA Galaxy', 'Estados Unidos', 'Galaxy | L.A. Galaxy | Los Angeles Galaxy'),
  ('Las Vegas Lights FC', 'Estados Unidos', 'Las Vegas Lights | LVFC | Las Vegas Lights Football Club | LV Lights | LV Lights FC'),
  ('Los Angeles FC', 'Estados Unidos', 'LAFC | Los Angeles Football Club | LA FC | LA Football Club'),
  ('Loudoun United FC', 'Estados Unidos', 'Loudoun United | Loudoun United Football Club'),
  ('Louisville City FC', 'Estados Unidos', 'Lou City | Louisville City | Louisville City Football Club | LouCity'),
  ('Memphis 901 FC', 'Estados Unidos', 'Memphis 901 | USL Memphis | 901 FC'),
  ('Miami FC', 'Estados Unidos', 'Miami Football Club | The Miami FC | The Miami Football Club'),
  ('Minnesota United FC', 'Estados Unidos', 'Minnesota United | MNU | MNUFC | the Loons | Minnesota United Football Club | MN United FC | MNU FC'),
  ('Nashville SC', 'Estados Unidos', null::text),
  ('New England Revolution', 'Estados Unidos', 'NE Revolution | Revolution Soccer | New England Revs | NE Revs | Revs | NER | Revolution | the Revs'),
  ('New Mexico United', 'Estados Unidos', 'USL New Mexico | New Mexico Utd | NM United'),
  ('New York City FC', 'Estados Unidos', 'New York City Football Club | NYCFC'),
  ('North Carolina FC', 'Estados Unidos', 'Carolina RailHawks | NCFC | North Carolina Football Club | RailHawks'),
  ('Oakland Roots SC', 'Estados Unidos', 'Oakland Roots | Oakland Roots Sports Club | Oakland Roots S.C. | Oakland Roots S. C.'),
  ('OKC Energy FC', 'Estados Unidos', 'Oklahoma City Energy FC | OKC Energy | Oklahoma City Energy | Oklahoma City Energy Football Club | OKC Energy Football Club'),
  ('Orange County SC', 'Estados Unidos', 'OCSC | Orange County Soccer Club | Orange County Blues | Orange County Blues FC | Orange County Blues Football Club | LA Blues | LA Blues SC | LA Blues Soccer Club'),
  ('Orlando City SC', 'Estados Unidos', 'Orlando City Soccer Club | Orlando City | OCSC'),
  ('Philadelphia Fury', 'Estados Unidos', null::text),
  ('Philadelphia Union', 'Estados Unidos', 'Philadelphia | Union | The U | PU'),
  ('Phoenix Rising FC', 'Estados Unidos', 'Arizona United SC | Arizona United Soccer Club | Arizona United | AZ United | AZU | Phoenix Rising | Phoenix Rising Football Club | PHX Rising FC'),
  ('Pittsburgh Riverhounds SC', 'Estados Unidos', 'Pittsburgh Riverhounds | Pittsburgh Riverhounds Soccer Club | Riverhounds | Pittsburgh Hounds'),
  ('Portland Timbers', 'Estados Unidos', 'The Timbers | FC Portland Timbers | Football Club Portland Timbers | Portland Timbers Football Club | Portland Timbers Soccer Club | Soccer Club Portland Timbers | Portland Timbers Soccer | Soccer Club of Portland Timbers'),
  ('Puerto Rico United', 'Estados Unidos', null::text),
  ('Queensboro FC', 'Estados Unidos', null::text),
  ('Real Salt Lake', 'Estados Unidos', 'RSL | Claret and Cobalt | Real Salt Lake City'),
  ('Red Bull New York', 'Estados Unidos', 'NY Red Bulls | Red Bulls | NYRB | RBNY | MetroStars | NY/NJ MetroStars | New York/New Jersey MetroStars | Red Bull NY'),
  ('Rhode Island FC', 'Estados Unidos', null::text),
  ('Richmond Kickers', 'Estados Unidos', 'Kickers'),
  ('Rio Grande Valley FC Toros', 'Estados Unidos', 'RGV FC Toros | Rio Grande Valley FC | Rio Grande Valley Football Club | RGV FC | Toros'),
  ('Sacramento Republic FC', 'Estados Unidos', 'Sacramento Republic | Sacramento Republic Football Club'),
  ('San Antonio FC', 'Estados Unidos', 'San Antonio Football Club | San Antonio USL team'),
  ('San Diego FC', 'Estados Unidos', 'San Diego F.C. | San Diego Football Club | San Diego MLS team | SDFC'),
  ('San Jose Earthquakes', 'Estados Unidos', 'SJ Earthquakes | San Jose Quakes | San Jose Clash | Earthquakes | Quakes | Golden Bay Earthquakes | San José Earthquakes | San José Clash'),
  ('Seattle Sounders FC', 'Estados Unidos', 'Seattle Sounders | Seattle Sounders Football Club | Sounders FC | Sounders Football Club'),
  ('Sporting Kansas City', 'Estados Unidos', 'Kansas City Wizards | Kansas City Wiz | Sporting KC | SKC | Sporting Kansas City FC | Sporting Kansas City Soccer Club | Sporting Kansas City Football Club | Sporting Kansas City Soccer'),
  ('St. Louis City SC', 'Estados Unidos', 'St. Louis MLS team | Saint Louis City SC | Saint Louis City Soccer Club | St. Louis City Soccer Club | Saint Louis MLS team | MLS4TheLou | St Louis City SC | TKFC LC'),
  ('Tampa Bay Rowdies', 'Estados Unidos', 'FC Tampa Bay | Rowdies | TBR'),
  ('USL Chicago', 'Estados Unidos', null::text),
  ('FC Ajax Lasnamäe', 'Estónia', null::text),
  ('FC Flora Tallinn', 'Estónia', 'FC Flora'),
  ('FC Infonet', 'Estónia', null::text),
  ('FC Kuressaare', 'Estónia', null::text),
  ('FC Lootus Kohtla-Järve', 'Estónia', 'Kohtla-Järve FC Lootus'),
  ('FC Nikol Tallinn', 'Estónia', null::text),
  ('FC Nõmme United', 'Estónia', null::text),
  ('FC Santos Tartu', 'Estónia', 'Santos Tartu | Football Club Santos Tartu'),
  ('FC Warrior Valga', 'Estónia', null::text),
  ('FCI Levadia Tallinn', 'Estónia', 'FC Levadia Tallinn | FCI Levadia | Levadia Tallinn | Levadia'),
  ('Harju JK Laagri', 'Estónia', null::text),
  ('JK Maag Tammeka Tartu', 'Estónia', 'JK Maag Tammeka'),
  ('JK Narva Trans', 'Estónia', 'FC Narva Trans'),
  ('JK Sillamäe Kalev', 'Estónia', 'Jalgpalliklubi Sillamäe Kalev'),
  ('JK Tallinna Kalev', 'Estónia', 'JK Kalev Tallinn'),
  ('JK Tallinna Sadam', 'Estónia', null::text),
  ('JK Tammeka Tartu', 'Estónia', 'Tartu JK Tammeka'),
  ('Jõhvi FC Phoenix', 'Estónia', null::text),
  ('Maardu Linnameeskond', 'Estónia', 'Maardu FC Starbunker'),
  ('Nõmme Kalju FC', 'Estónia', 'Nomme Kalju'),
  ('Paide Linnameeskond', 'Estónia', null::text),
  ('Pärnu JK Vaprus', 'Estónia', null::text),
  ('Rakvere JK Tarvas', 'Estónia', 'JK Rakvere Virumaa | Virumaa Rakvere | JK Virumaa Rakvere | Flora Rakvere | Virumaa JK Rakvere | VJK Rakvere | FC Flora Rakvere II | FC Flora Rakvere'),
  ('Tallinna JK', 'Estónia', null::text),
  ('Tallinna JK Dünamo', 'Estónia', 'JK Dünamo Tallinn'),
  ('Tallinna JK Legion', 'Estónia', null::text),
  ('Viljandi JK Tulevik', 'Estónia', 'Viljandi Tulevik'),
  ('Adama City FC', 'Etiópia', 'Adama City F.C.'),
  ('Arba Minch FC', 'Etiópia', null::text),
  ('Awassa City FC', 'Etiópia', 'Awassa City F.C. | Hawassa Kenema FC'),
  ('Bahir Dar Kenema FC', 'Etiópia', 'Bahir Dar Kenema F.C.'),
  ('CBE SA', 'Etiópia', null::text),
  ('Cotton Factory Club', 'Etiópia', null::text),
  ('Dashen Beer FC', 'Etiópia', null::text),
  ('Dedebit', 'Etiópia', null::text),
  ('Defence FC', 'Etiópia', 'Defence F.C.'),
  ('Dire Dawa City', 'Etiópia', null::text),
  ('EEPCO FC', 'Etiópia', 'EEPCO F.C.'),
  ('Ethiopian Coffee FC', 'Etiópia', null::text),
  ('Ethiopian Insurance FC', 'Etiópia', 'Ethiopian Insurance F.C.'),
  ('Fasil Kenema SC', 'Etiópia', 'Fasil Kenema S.C.'),
  ('Guna Trading FC', 'Etiópia', 'Guna Trading F.C.'),
  ('Harrar Beer Bottling FC', 'Etiópia', 'Harrar Beer Bottling F.C.'),
  ('Lideta Nyala', 'Etiópia', null::text),
  ('Medr Babur', 'Etiópia', null::text),
  ('Mekelle 70 Enderta FC', 'Etiópia', 'Mekelle City FC'),
  ('Metehara Sugar', 'Etiópia', null::text),
  ('Muger Cement', 'Etiópia', null::text),
  ('Nyala SC', 'Etiópia', null::text),
  ('Ogaden Anbassa', 'Etiópia', null::text),
  ('Saint George SC', 'Etiópia', 'Saint George Sports Club'),
  ('Sebeta City', 'Etiópia', null::text),
  ('Sidama Coffee', 'Etiópia', null::text),
  ('Southern Police', 'Etiópia', null::text),
  ('Tikur Abay Transport', 'Etiópia', null::text),
  ('Trans Ethiopia', 'Etiópia', null::text),
  ('Weha Serawoch', 'Etiópia', null::text),
  ('Welwalo Adigrat University FC', 'Etiópia', null::text),
  ('Wolayta Dicha', 'Etiópia', null::text),
  ('Woldia City', 'Etiópia', null::text),
  ('Wolkite City FC', 'Etiópia', 'Wolkite City F.C.'),
  ('Ba FC', 'Fiji', 'Ba F.C.'),
  ('Lautoka FC', 'Fiji', 'Lautoka F.C.'),
  ('Nadi FC', 'Fiji', 'Nadi F.C.'),
  ('Rewa FC', 'Fiji', 'Rewa F.C.'),
  ('Suva FC', 'Fiji', 'Suva F.C.'),
  ('Davao Aguilas FC', 'Filipinas', 'Davao Aguilas F.C.'),
  ('Dynamic Herb Cebu FC', 'Filipinas', 'Dynamic Herb Cebu F.C.'),
  ('Global Cebu FC', 'Filipinas', 'Global Cebu F.C. | Global FC | Global Football Club | The People''s Club | Sugbo Warriors | Sugbu Warriors'),
  ('Ilocos United FC', 'Filipinas', 'Ilocos United F.C.'),
  ('Kaya FC', 'Filipinas', 'Kaya F.C.'),
  ('Manila Digger FC', 'Filipinas', 'Manila Digger F.C.'),
  ('One Taguig FC', 'Filipinas', 'One Taguig F.C.'),
  ('Stallion–Laguna FC', 'Filipinas', 'Stallion–Laguna F.C. | Stallions | Stallion Santa Lucia F.C. | Stallion Football Club | Stallion–Laguna Football Club'),
  ('United City FC', 'Filipinas', 'United City F.C. | Ceres–Negros Football Club | Ceres–Negros | Ceres | Ceres–Negros F.C.'),
  ('AC Oulu', 'Finlândia', 'ACO'),
  ('Atlantis FC', 'Finlândia', 'Atlantis Football Club'),
  ('FC Haka', 'Finlândia', 'Football Club Haka'),
  ('FC Hämeenlinna', 'Finlândia', null::text),
  ('FC Honka', 'Finlândia', 'Honka'),
  ('FC Ilves', 'Finlândia', 'Ilves Tampere | Ilves'),
  ('FC Inter Turku', 'Finlândia', 'Football Club Inter Turku | Football Club International Turku'),
  ('FC Jazz', 'Finlândia', 'Football Club Jazz'),
  ('FC Kuusysi', 'Finlândia', null::text),
  ('FC Lahti', 'Finlândia', 'Football Club Lahti'),
  ('FC Viikingit', 'Finlândia', null::text),
  ('FF Jaro', 'Finlândia', null::text),
  ('Helsingin Jalkapalloklubi', 'Finlândia', 'HJK Helsingfors | HJK Helsinki'),
  ('Helsingin Palloseura', 'Finlândia', 'HPS'),
  ('HIFK Fotboll', 'Finlândia', 'HIFK Soccer'),
  ('IF Gnistan', 'Finlândia', null::text),
  ('IFK Mariehamn', 'Finlândia', 'Idrottsföreningen Kamraterna Mariehamn'),
  ('JJK Jyväskylä', 'Finlândia', null::text),
  ('Kokkolan Palloveikot', 'Finlândia', 'KPV'),
  ('Kotkan Työväen Palloilijat', 'Finlândia', null::text),
  ('Kuopion Palloseura', 'Finlândia', 'KUPS'),
  ('Mikkelin Palloilijat', 'Finlândia', null::text),
  ('MYPA', 'Finlândia', 'Myllykosken Pallo -47'),
  ('Oulun Palloseura', 'Finlândia', null::text),
  ('Palloseura Kemi Kings', 'Finlândia', null::text),
  ('RoPS', 'Finlândia', 'Rovaniemen Palloseura'),
  ('Seinäjoen Jalkapallokerho', 'Finlândia', 'SJK'),
  ('Tampere United', 'Finlândia', null::text),
  ('Tampereen Pallo-Veikot', 'Finlândia', null::text),
  ('TPS Turku', 'Finlândia', 'FC TPS | TPS (men''s football) | Turun Palloseura'),
  ('Unitas Sports Club', 'Finlândia', null::text),
  ('Vaasan Palloseura', 'Finlândia', null::text),
  ('AC Ajaccio', 'França', 'A.C. Ajaccio | Athletic Club Ajaccio'),
  ('AC Arles', 'França', null::text),
  ('AF Bobigny', 'França', null::text),
  ('AF Lozère', 'França', 'AF Lozere'),
  ('AFC Compiègne', 'França', 'AFC Compiegne'),
  ('Ain Sud', 'França', null::text),
  ('AJ Auxerre', 'França', 'Association de la Jeunesse auxerroise | Auxerre | AJA | Les Icaunais'),
  ('AJSS Saintes', 'França', null::text),
  ('Amiens AC', 'França', null::text),
  ('Amiens SC', 'França', 'Amiens Sporting Club'),
  ('Angers SCO', 'França', 'Angers Sporting Club de l''Ouest | SCO | SCO of Angers | Angers'),
  ('Angoulême Charente FC', 'França', null::text),
  ('Arras Football', 'França', null::text),
  ('AS Aix-en-Provence', 'França', 'AS Aixoise | Association Sportive Aixoise | AS Aix'),
  ('AS Beauvais Oise', 'França', 'AS Beauvais | L’Association Sportive Beauvais Oise | Association Sportive Beauvais Oise | L''Association Sportive Beauvais Oise'),
  ('AS Béziers', 'França', 'AS Beziers'),
  ('AS Cannes', 'França', 'Association Sportive de Cannes Football | Association Sportive de Cannes'),
  ('AS Cherbourg Football', 'França', 'AS Cherbourg'),
  ('AS Dragon', 'França', 'A.S. Dragon'),
  ('AS Foot Les Verchers-Saint-Georges-sur-Layon', 'França', 'A.S. Foot Les Verchers-Saint-Georges-sur-Layon'),
  ('AS Furiani-Agliani', 'França', null::text),
  ('AS Gardanne', 'França', null::text),
  ('AS Illzach Modenheim', 'França', null::text),
  ('AS Jeunes Tahitiens', 'França', 'A.S. Jeunes Tahitiens'),
  ('AS La Châtaigneraie', 'França', 'AS La Chataigneraie'),
  ('AS Magenta', 'França', null::text),
  ('AS Manu-Ura', 'França', 'A.S. Manu-Ura | Association Sportive Manu-Ura'),
  ('AS Marck', 'França', null::text),
  ('AS Mont-Dore', 'França', 'A.S. Mont-Dore'),
  ('AS Moulins', 'França', 'AS Moulinoise | Association Sportive Moulinoise | Académie Sportive Moulins Football | Moulins'),
  ('AS Nancy-Lorraine', 'França', 'A.S. Nancy-Lorraine | AS Nancy | Association sportive Nancy-Lorraine'),
  ('AS Ornans', 'França', null::text),
  ('AS Pirae', 'França', 'A.S. Pirae | Pirae | Association Sportive Pirae'),
  ('AS Poissy', 'França', null::text),
  ('AS Roniu', 'França', null::text),
  ('AS Saint-Étienne', 'França', 'Saint-Étienne | A.S. Saint-Etienne | AS Saint-Etienne | Saint-Etienne | ASSE | A.S. Saint Étienne | A.S. Saint Etienne | AS Saint Etienne'),
  ('AS Saint-Priest', 'França', 'ASSP | Association Sportive de Saint-Priest | AS Saint Priest | Association Sportive de Saint Priest'),
  ('AS Tamarii Faa''a', 'França', 'A.S. Tamarii Faa''a'),
  ('AS Tefana', 'França', 'A.S. Tefana'),
  ('AS Tournefeuille', 'França', null::text),
  ('AS Valence', 'França', null::text),
  ('AS Vénus', 'França', 'A.S. Vénus | A.S. Venus'),
  ('AS Vitré', 'França', 'AS Vitre | Amicale Sportive de Vitré'),
  ('AS Yzeure', 'França', null::text),
  ('ASA Issy', 'França', null::text),
  ('ASC Biesheim', 'França', null::text),
  ('ASF Andrézieux', 'França', 'ASF Andrezieux'),
  ('ASG Juventus de Sainte-Anne', 'França', null::text),
  ('ASJ Soyaux', 'França', null::text),
  ('ASM Belfort', 'França', null::text),
  ('ASPTT Albi', 'França', null::text),
  ('ASPV Strasbourg', 'França', null::text),
  ('Association Sportive Central Sport', 'França', 'AS Central Sport'),
  ('Aurillac FC2A', 'França', null::text),
  ('Avignon Foot 84', 'França', null::text),
  ('Aviron Bayonnais FC', 'França', 'Bayonne | Bayonnais'),
  ('Balma SC', 'França', null::text),
  ('Beaune FC', 'França', null::text),
  ('Bergerac Périgord FC', 'França', 'Bergerac Perigord FC'),
  ('Besançon RC', 'França', 'Besançon R.C.'),
  ('Blagnac FC', 'França', null::text),
  ('Blois Football 41', 'França', 'AAJ Blois'),
  ('C'' Chartres Football', 'França', 'C''Chartres Football'),
  ('CA Paris-Charenton', 'França', null::text),
  ('CA Pontarlier', 'França', null::text),
  ('Canet Roussillon Football Club', 'França', 'Canet Roussillon FC | Perpignan Canet Football Club | Perpignan Canet FC'),
  ('Chaumont FC', 'França', null::text),
  ('Clermont Foot 63', 'França', 'Clermont Foot Auvergne 63 | Clermont Foot | CF63'),
  ('Club Français', 'França', 'Club Francais'),
  ('Club Franciscain', 'França', null::text),
  ('CMS Oissel', 'França', null::text),
  ('CO Les Ulis', 'França', null::text),
  ('CS Avion', 'França', null::text),
  ('CS Louhans-Cuiseaux', 'França', '97 هدف'),
  ('CS Moulien', 'França', null::text),
  ('CS Sedan Ardennes', 'França', 'Club Sportif Sedan Ardennes'),
  ('CSO Amnéville', 'França', 'CSO Amneville'),
  ('Dijon FCO', 'França', null::text),
  ('Dinan-Léhon FC', 'França', 'Dinan-Lehon FC'),
  ('ÉDS Montluçon', 'França', 'EDS Montluçon'),
  ('ÉF Reims-Champagne', 'França', null::text),
  ('En Avant de Guingamp', 'França', 'EA Guingamp | EAG | Guingamp'),
  ('Entente Feignies Aulnoye FC', 'França', 'Entente Feignies Aulnoye Football Club | SC Feignies | AS Aulnoye'),
  ('Entente SSG', 'França', 'Entente Sannois Saint-Gratien'),
  ('EP Manosque', 'França', null::text),
  ('ES Bonchamp', 'França', null::text),
  ('ES Cannet Rocheville', 'França', null::text),
  ('ES Paulhan-Pézenas', 'França', null::text),
  ('ES Thaon', 'França', null::text),
  ('ES Troyes AC', 'França', 'Troyes AC | ES Troyes | ESTAC'),
  ('ES Uzès Pont du Gard', 'França', 'ES Uzes Pont du Gard'),
  ('ES Viry-Châtillon', 'França', 'ES Viry-Chatillon | L''Entente Sportive Viry-Châtillon'),
  ('ES Wasquehal', 'França', 'E.S. Wasquehal'),
  ('ESM Gonfreville', 'França', null::text),
  ('ESOF Vendée La Roche-sur-Yon', 'França', 'ESOF Vendee La Roche-sur-Yon'),
  ('Étoile Fréjus Saint-Raphaël', 'França', 'Etoile Frejus Saint-Raphael | Etoile Fréjus Saint-Raphaël'),
  ('Evian Thonon Gaillard FC', 'França', 'Evian Thonon Gaillard F.C.'),
  ('Évreux FC 27', 'França', 'Evreux FC'),
  ('FAIRM Île-Rousse Monticello', 'França', 'FAIRM Ile-Rousse Monticello'),
  ('FC Annecy', 'França', 'F.C. Annecy | Football Club Annecy | Football Club of Annecy | FCAnnecy'),
  ('FC Antibes', 'França', 'Football Club Antibes Juan-les-Pins'),
  ('FC Bagnols Pont', 'França', null::text),
  ('FC Bassin d''Arcachon', 'França', null::text),
  ('FC Bastia-Borgo', 'França', null::text),
  ('FC Chambly', 'França', 'Football Club de Chambly-Thelle | Chambly'),
  ('FC Cournon-d''Auvergne', 'França', null::text),
  ('FC Dieppe', 'França', null::text),
  ('FC Drouais', 'França', null::text),
  ('FC Échirolles', 'França', 'FC Echirolles'),
  ('FC Fleury 91', 'França', null::text),
  ('FC Girondins de Bordeaux', 'França', 'Football Club des Girondins de Bordeaux | F.C. Girondins de Bordeaux | Bordeaux FC | Bordeaux Girondins F.C.'),
  ('FC Gueugnon', 'França', null::text),
  ('FC Istres', 'França', 'F.C. Istres Ouest Provence | Football Club Istres Ouest Provence | Istres'),
  ('FC Les Lilas', 'França', null::text),
  ('FC Libourne', 'França', 'Football Club Libourne'),
  ('FC Libourne-Saint-Seurin', 'França', 'F.C. Libourne-Saint-Seurin'),
  ('FC Lorient', 'França', 'F.C. Lorient | Football Club Lorient-Bretagne Sud'),
  ('FC Mantes', 'França', null::text),
  ('FC Marmande', 'França', 'FC Marmande 47'),
  ('FC Martigues', 'França', 'F.C. Martigues | Football Club de Martigues'),
  ('FC Metz', 'França', 'FCM | Football Club of Metz | Metz Football Club | F.C. Metz | FcMetz'),
  ('FC Montceau', 'França', null::text),
  ('FC Mulhouse', 'França', 'F.C. Mulhouse | Football Club de Mulhouse'),
  ('FC Nantes', 'França', 'F.C. Nantes | Football Club of Nantes | FCNantes | F.C.Nantes'),
  ('FC Rouen', 'França', 'F.C. Rouen 1899 | Rouen | Football Club de Rouen 1899'),
  ('FC Saint-Jean-le-Blanc', 'França', null::text),
  ('FC Saint-Lô Manche', 'França', 'FC Saint-Lo Manche'),
  ('FC Saint-Louis Neuweg', 'França', null::text),
  ('FC Sens', 'França', null::text),
  ('FC Sète', 'França', 'F.C. Sète 34 | SC Sétois'),
  ('FC Sochaux-Montbéliard', 'França', 'F.C. Sochaux-Montbeliard | FC Sochaux-Montbeliard | FCSM'),
  ('FC Vendenheim', 'França', null::text),
  ('FC Versailles', 'França', null::text),
  ('FCA Calvi', 'França', null::text),
  ('FCM Aubervilliers', 'França', null::text),
  ('FCSR Haguenau', 'França', 'Football Club Sports Réunis Haguenau'),
  ('FCSR Obernai', 'França', null::text),
  ('FF Yzeure Allier Auvergne', 'França', null::text),
  ('Football Bourg-en-Bresse Péronnas 01', 'França', 'FC Bourg-Peronnas | FC Bourg-Péronnas'),
  ('Football Club Villefranche Beaujolais', 'França', null::text),
  ('FR Saint Marcel', 'França', null::text),
  ('Gap FC', 'França', null::text),
  ('Gazélec Ajaccio', 'França', 'GFC Ajaccio | GFCO Ajaccio | Gazélec FCO Ajaccio | Gazélec Football Club Olympique Ajaccio'),
  ('Genêts Anglet', 'França', 'Genets Anglet'),
  ('Girondins de Bordeaux', 'França', null::text),
  ('Grand Ouest Association Lyonnaise Football Club', 'França', 'Monts d''Or Azergues | Monts d''Or Azergues Foot'),
  ('Grenoble Foot 38', 'França', 'GF38'),
  ('GS Neuves-Maisons', 'França', null::text),
  ('GSI Pontivy', 'França', 'Garde Saint-Ivy Pontivy'),
  ('Hauts Lyonnais', 'França', null::text),
  ('Hienghène Sport', 'França', 'Hienghene Sport'),
  ('Hyères FC', 'França', 'Hyeres FC'),
  ('IC Croix', 'França', 'Iris Club de Croix'),
  ('INF Clairefontaine', 'França', 'Institut national du football'),
  ('J3S Amilly', 'França', null::text),
  ('JA Drancy', 'França', null::text),
  ('JS Saint-Pierroise', 'França', null::text),
  ('Jura Dolois Foot', 'França', null::text),
  ('Jura Sud Foot', 'França', 'Jura Sud Lavans'),
  ('La Roche VF', 'França', null::text),
  ('La Vitréenne FC', 'França', 'La Vitreenne FC'),
  ('Lannion FC', 'França', null::text),
  ('LB Châteauroux', 'França', 'L.B. Châteauroux | La Berrichonne de Châteauroux | Châteauroux | LB Chateauroux | L.B. Chateauroux | La Berrichonne de Chateauroux | Chateauroux'),
  ('Le Havre AC', 'França', 'Le Havre Athletic Club | Le Havre | HAC | Les Ciel et Marine'),
  ('Le Mans FC', 'França', 'Le Mans F.C. | Le MUC | Le Mans Football Club | Le Mans U.C. 72'),
  ('Le Puy Foot 43 Auvergne', 'França', null::text),
  ('Les Herbiers VF', 'França', null::text),
  ('Les Marseillaises', 'França', 'Olympique de Marseille'),
  ('Lille OSC', 'França', 'Lille Olympique Sporting Club | Lille | LOSC'),
  ('Limoges Football', 'França', null::text),
  ('Montpellier Hérault Sport Club', 'França', 'Montpellier Herault Sport Club | Montpellier HSC | MPSC | MPSCL | SOM | MLSC'),
  ('Nîmes Olympique', 'França', 'Nîmes | Nimes | Nimes Olympique'),
  ('OGC Nice', 'França', 'Olympique Gymnaste Club Nice Côte d''Azur'),
  ('Olympique Alès', 'França', 'Olympique Ales'),
  ('Olympique de Marseille', 'França', 'Olympique Marseille | OM | Marseille | Olympic of Marseille | Olympic Marseille | O Marseille'),
  ('Olympique Grande-Synthe', 'França', null::text),
  ('Olympique Lyonnais', 'França', 'Lyon | OL | O. Lyon | O. Lyonnais | O.L.'),
  ('Olympique Noisy-le-Sec', 'França', null::text),
  ('Olympique Saint-Quentin', 'França', null::text),
  ('Olympique Saumur FC', 'França', null::text),
  ('Pacy Ménilles RC', 'França', 'Pacy Vallée-d''Eure'),
  ('Paris 13 Atletico', 'França', 'FC Gobelins'),
  ('Paris FC', 'França', 'Paris F.C. | Paris Football Club | PFC'),
  ('Paris Saint-Germain FC', 'França', 'PSGFC | Paris'),
  ('Paris So Cœur', 'França', 'FF Issy'),
  ('Pau Football Club', 'França', null::text),
  ('Poitiers FC', 'França', 'poitiers football club | poitiers foot 86 | Stade poitevin football club | stade poitevin FC | poitiers PEPP'),
  ('Quimper Kerfeunteun FC', 'França', 'Quimper Kerfeunteun F.C. | Quimper KFC'),
  ('Racing Club de France', 'França', 'R.C. France Football 92 | Racing Club de France Colombes 92 | RCF Paris | Racing Paris | RC Paris | Racing Club de Paris'),
  ('Racing Club de Grasse', 'França', 'RC Grasse'),
  ('Rapid de Menton', 'França', null::text),
  ('RC Lens', 'França', 'R.C. Lens | Racing Club de Lens | Lens'),
  ('RC Strasbourg Alsace', 'França', 'Racing Club de Strasbourg | RCSA | Racing Club de Strasbourg Alsace | Racing Strasbourg | Racing | Strasbourg'),
  ('RCO Agde', 'França', null::text),
  ('Red Star FC', 'França', 'Red Star F.C.'),
  ('Rodez AF', 'França', 'Rodez Aveyron Football | Rodez Foot | Rodez Aveyron'),
  ('SA Thiers', 'França', null::text),
  ('Sablé FC', 'França', 'Sable FC'),
  ('Saint-Alban Aucamville FC', 'França', 'Saint-Alban Aucamville F.C. | Saint-Alban Omnisport'),
  ('Sainte-Geneviève Sports', 'França', 'Sainte-Genevieve Sports | Sainte-Geneviève'),
  ('Saint-Pryve Saint-Hilaire FC', 'França', null::text),
  ('Sarreguemines FC', 'França', null::text),
  ('SAS Épinal', 'França', 'S.A.S. Épinal | S.A.S. Epinal | SAS Epinal'),
  ('SC Bastia', 'França', 'Sporting Club de Bastia | Sporting Club Bastiais | Bastia'),
  ('SC Fives', 'França', null::text),
  ('SC Hazebrouck', 'França', null::text),
  ('SC Marnaval', 'França', null::text),
  ('SC Schiltigheim', 'França', null::text),
  ('SC Selongey', 'França', null::text),
  ('SO Chambéry Foot', 'França', 'SO Chambery Foot'),
  ('SO Châtellerault', 'França', 'SO Chatellerault'),
  ('SO Cholet', 'França', 'Stade Olympique Choletais'),
  ('SO Romorantin', 'França', 'Stade olympique Romorantinais'),
  ('Sporting Club Lyon', 'França', 'AS Lyon Duchere | Association Sportive Lyon-Duchère | AS Lyon Duchère | Sporting Club de Lyon | SC Lyon | Sporting Lyon | AS Lyon-Duchère'),
  ('Sporting Toulon Var', 'França', null::text),
  ('SR Colmar', 'França', 'S.R. Colmar'),
  ('Stade Beaucairois FC', 'França', null::text),
  ('Stade Bordelais', 'França', null::text),
  ('Stade Brestois 29', 'França', null::text),
  ('Stade Briochin', 'França', null::text),
  ('Stade de Reims', 'França', 'Stade Reims | club creado por coquelin'),
  ('Stade Français Football', 'França', 'Stade Francais football'),
  ('Stade Lavallois', 'França', 'Stade Lavallois Mayenne Football Club | Stade Laval'),
  ('Stade Malherbe Caen', 'França', 'S.M. Caen | Stade Malherbe de Caen | SM Caen'),
  ('Stade Montois', 'França', null::text),
  ('Stade Plabennecois', 'França', null::text),
  ('Stade Rennais FC', 'França', 'Stade Rennais F.C. | Stade Rennais Football Club | Stade Rennais | Rennes | Rennais | SRFC'),
  ('Standard Athletic Club', 'França', null::text),
  ('SU Agen Football', 'França', 'Sporting Union Agenais | SUA'),
  ('SU Dives', 'França', null::text),
  ('Tarbes Pyrénées Football', 'França', 'Tarbes Pyrenees Football'),
  ('Thouars Foot 79', 'França', null::text),
  ('Toulouse FC', 'França', 'Toulouse Football Club | Toulouse F.C. | Toulouse | TFC'),
  ('Tours FC.', 'França', 'Tours F.C. | Tours Football Club'),
  ('Trélissac FC', 'França', 'Trelissac FC'),
  ('Trinité Sport Football Club', 'França', 'Trinite Sport Football Club'),
  ('UA Cognac', 'França', null::text),
  ('UA Valettoise', 'França', null::text),
  ('UJA Maccabi Paris Métropole', 'França', 'UJA Maccabi Paris Metropole'),
  ('Union sportive de Forbach', 'França', 'US Forbach | Forbach'),
  ('US Albi', 'França', null::text),
  ('US Alençon', 'França', null::text),
  ('US Avranches', 'França', null::text),
  ('US Boulogne', 'França', null::text),
  ('US Changé', 'França', 'US Change'),
  ('US Chantilly', 'França', null::text),
  ('US Colomiers Football', 'França', 'US Colomiers | US Colomiers Footballl'),
  ('US Concarneau', 'França', 'Union Sportive Concarnoise | US Concarnoise'),
  ('US Créteil-Lusitanos', 'França', 'US Creteil-Lusitanos'),
  ('US de Lège-Cap-Ferret', 'França', 'U.S. de Lège-Cap-Ferret'),
  ('US Feurs', 'França', null::text),
  ('US Granville', 'França', null::text),
  ('US Gravelines Foot', 'França', null::text),
  ('US Le Pontet', 'França', 'Union Sportive Le Pontet Football'),
  ('US Lesquin', 'França', null::text),
  ('US Lusitanos Saint-Maur', 'França', null::text),
  ('US Luzenac', 'França', null::text),
  ('US Marignane', 'França', 'Marignane Gignac Football Club'),
  ('US Marseille Endoume', 'França', null::text),
  ('US Montagnarde', 'França', null::text),
  ('US municipale senlisienne', 'França', 'U.S. municipale senlisienne'),
  ('US Orléans', 'França', 'US Orleans | Orléans'),
  ('US Quevilly', 'França', 'Union sportive quevillaise | US Quevilly-Rouen | US Quevilly-Rouen Métropole'),
  ('US Raon-l''Étape', 'França', null::text),
  ('US Roye-Noyon', 'França', null::text),
  ('US Saint-Malo', 'França', null::text),
  ('US Saint-Omer', 'França', null::text),
  ('US Sarre-Union', 'França', 'Union Sportive Sarre-Union'),
  ('US Sénart-Moissy', 'França', 'US Senart-Moissy'),
  ('US Tourcoing', 'França', null::text),
  ('USC Corte', 'França', null::text),
  ('USE Avoine', 'França', null::text),
  ('USJA Carquefou', 'França', 'Union Sportive Jeanne D''Arc Carquefou'),
  ('USL Dunkerque', 'França', null::text),
  ('USM Montargis', 'França', null::text),
  ('USON Mondeville', 'França', 'Mondeville'),
  ('USSA Vertou', 'França', null::text),
  ('Valenciennes FC', 'França', 'Valenciennes F.C.'),
  ('Vannes OC', 'França', 'Vannes O.C. | Vannes Olympique Club'),
  ('Vendée Fontenay Foot', 'França', 'Vendee Fontenay Foot'),
  ('Vendée Luçon Football', 'França', null::text),
  ('Vendée Poiré sur Vie Football', 'França', 'Vendee Poire sur Vie Football'),
  ('Vesoul Haute-Saône', 'França', 'Vesoul Haute-Saone'),
  ('Vie au grand air de Saint-Maur', 'França', 'VGA Saint-Maur'),
  ('Vierzon FC', 'França', null::text),
  ('Villemomble Sports', 'França', null::text),
  ('Voltigeurs de Châteaubriant', 'França', 'Voltigeurs de Chateaubriant'),
  ('AS Mangasport', 'Gabão', null::text),
  ('CF Mounana', 'Gabão', null::text),
  ('FC 105 Libreville', 'Gabão', null::text),
  ('US Bitam', 'Gabão', null::text),
  ('Gambia Ports Authority FC', 'Gâmbia', 'Gambia Ports Authority F.C.'),
  ('Real de Banjul FC', 'Gâmbia', 'Real de Banjul F.C.'),
  ('Wallidan FC', 'Gâmbia', 'Wallidan F.C.'),
  ('Accra Great Olympics FC', 'Gana', 'Accra Great Olympics F.C. | Great Olympics'),
  ('Accra Hearts of Oak SC', 'Gana', 'Accra Hearts of Oak Sporting Club | Accra Hearts of Oak S.C. | Hearts of Oak'),
  ('Aduana Stars', 'Gana', 'Aduana Stars Football Club'),
  ('All Blacks FC', 'Gana', 'All Blacks F.C. | Gamba All Blacks F.C.'),
  ('Asante Kotoko FC', 'Gana', 'Asante Kotoko F.C. | Kumasi Asante Kotoko FC | Asante Kotoko S.C. | Porcupine Warriors'),
  ('Ashanti Gold SC', 'Gana', 'Ashanti Gold Sporting Club | AshGold'),
  ('BA Stars', 'Gana', null::text),
  ('Basake Holy Stars Football Club', 'Gana', null::text),
  ('Bechem United', 'Gana', null::text),
  ('Berekum Arsenal', 'Gana', 'Arsenal Football Club | Berekum Arsenal Football Club | Berekum Arsenal FC'),
  ('Berekum Chelsea FC', 'Gana', 'Berekum Chelsea F.C.'),
  ('Bibiani Gold Stars FC', 'Gana', 'Gold Stars | Complex Stars | Gold Stars Football Club | The Golden Boys'),
  ('Cornerstones', 'Gana', null::text),
  ('Dreams FC', 'Gana', 'Dreams Football Club'),
  ('Ebusua Dwarfs', 'Gana', null::text),
  ('Elmina Sharks FC', 'Gana', 'Elmina Sharks F.C.'),
  ('Heart of Lions FC', 'Gana', 'Heart of Lions F.C. | Heart of Lions Football Club'),
  ('Hohoe United FC', 'Gana', null::text),
  ('International Allies FC', 'Gana', 'International Allies F.C.'),
  ('Karela United FC', 'Gana', 'Karela United Football Club'),
  ('King Faisal Babes', 'Gana', null::text),
  ('Legon Cities FC', 'Gana', 'All Stars F.C.'),
  ('Liberty Professionals FC', 'Gana', 'Liberty Professionals F.C.'),
  ('Medeama SC', 'Gana', 'Mauve and Yellow'),
  ('Nations FC', 'Gana', 'Nations Football Club'),
  ('New Edubiase United', 'Gana', null::text),
  ('Real Republicans', 'Gana', null::text),
  ('Real Sportive', 'Gana', null::text),
  ('Real Tamale United', 'Gana', 'RTU'),
  ('Samartex', 'Gana', 'Samartex 1996 | Samatex Football Club'),
  ('Sekondi Hasaacas FC', 'Gana', 'Sekondi Hasaacas F.C.'),
  ('Tamale City Football Club', 'Gana', 'Citizens 💛 | Golden Eagles | Tamale City FC'),
  ('Techiman Eleven Wonders FC', 'Gana', null::text),
  ('Wassaman United', 'Gana', null::text),
  ('West African Football Academy', 'Gana', null::text),
  ('FC Baia Zugdidi', 'Geórgia', null::text),
  ('FC Borjomi', 'Geórgia', null::text),
  ('FC Chikhura Sachkhere', 'Geórgia', null::text),
  ('FC Dila Gori', 'Geórgia', null::text),
  ('FC Dinamo Batumi', 'Geórgia', 'Dinamo Batumi'),
  ('FC Dinamo Tbilisi', 'Geórgia', 'Dinamo Tbilisi'),
  ('FC Gagra', 'Geórgia', null::text),
  ('FC Guria Lanchkhuti', 'Geórgia', null::text),
  ('FC Iberia 1999', 'Geórgia', 'FC Saburtalo Tbilisi | FC Saburtalo | Saburtalo Tbilisi | Iberia 1999'),
  ('FC Kakheti Telavi', 'Geórgia', null::text),
  ('FC Kolkheti-1913 Poti', 'Geórgia', null::text),
  ('FC Lokomotivi Tbilisi', 'Geórgia', 'FC Locomotive Tbilisi'),
  ('FC Merani Martvili', 'Geórgia', null::text),
  ('FC Merani Tbilisi', 'Geórgia', null::text),
  ('FC Meskheti Akhaltsikhe', 'Geórgia', null::text),
  ('FC Mglebi Zugdidi', 'Geórgia', null::text),
  ('FC Milani Tsnori', 'Geórgia', null::text),
  ('FC Rustavi', 'Geórgia', null::text),
  ('FC Samgurali Tskhaltubo', 'Geórgia', null::text),
  ('FC Samtredia', 'Geórgia', null::text),
  ('FC Sapovnela Terjola', 'Geórgia', null::text),
  ('FC Shukura Kobuleti', 'Geórgia', null::text),
  ('FC Sioni Bolnisi', 'Geórgia', null::text),
  ('FC Spaeri', 'Geórgia', null::text),
  ('FC Spartaki Tbilisi', 'Geórgia', null::text),
  ('FC Telavi', 'Geórgia', null::text),
  ('FC Torpedo Kutaisi', 'Geórgia', null::text),
  ('FC Tskhinvali', 'Geórgia', 'Spartaki-Tskhinvali'),
  ('FC WIT Georgia', 'Geórgia', 'Football Club WIT Georgia'),
  ('FC Zestaponi', 'Geórgia', null::text),
  ('Meshakhte Tkibuli', 'Geórgia', 'Okriba Tkibuli | Meshakhte | FC Meshakhte Tkibuli'),
  ('TSU Tbilisi', 'Geórgia', null::text),
  ('Lincoln Red Imps FC', 'Gibraltar', 'Lincoln Red Imps F.C. | Lincoln Red Imps Football Club | Lincoln F.C. | Lincoln Red Imps'),
  ('AE Kifisia FC', 'Grécia', 'A.E. Kifisia F.C. | A.E. Kifisia'),
  ('AO Kerkyra', 'Grécia', 'A.O. Kerkyra'),
  ('APO Akratitos Ano Liosia', 'Grécia', 'A.P.O. Akratitos Ano Liosia'),
  ('APS Panthrakikos', 'Grécia', 'A.P.S. Panthrakikos | Panthrakikos F.C.'),
  ('Asteras Tripoli FC', 'Grécia', 'Asteras Tripoli F.C. | Asteras Tripolis'),
  ('Athinaikos FC', 'Grécia', 'Athinaikos F.C.'),
  ('Athlitiki Enosi Larissa FC', 'Grécia', 'Athlitiki Enosi Larissa F.C. | A.E. Larissas'),
  ('Atromitos FC', 'Grécia', 'Atromitos F.C. | Atromitos Athens'),
  ('Diagoras Rodos FC', 'Grécia', 'Diagoras Rodos F.C.'),
  ('Doxa Drama FC', 'Grécia', 'Doxa Drama F.C.'),
  ('Ergotelis FC', 'Grécia', 'Ergotelis F.C. | Ergotelis'),
  ('Ionikos Nikaia FC', 'Grécia', 'Ionikos Nikaia F.C.'),
  ('Kalamata FC', 'Grécia', 'Kalamata F.C.'),
  ('Kalloni SC', 'Grécia', 'Kalloni S.C. | Kalloni Soccer Club Stani Dairy'),
  ('Levadiakos FC', 'Grécia', 'Levadiakos F.C. | Levadiakos'),
  ('MGS Apollon Kalamarias (association football)', 'Grécia', 'M.G.S. Apollon Kalamarias (association football) | Apollon Kalamaria F.C.'),
  ('Panathinaikos FC', 'Grécia', 'Panathinaikos F.C. | Panathinaikos Athlitikos Omilos'),
  ('Panetolikos FC', 'Grécia', 'Panetolikos F.C. | Panetolikos'),
  ('Panionios FC', 'Grécia', 'Panionios F.C. | Panionios G.S.S. | Panionios'),
  ('PAS Lamia 1964', 'Grécia', 'P.A.S. Lamia 1964 | P.A.S. Lamia 1964 F.C.'),
  ('Platanias Chania FC', 'Grécia', 'Platanias Chania F.C. | A.O. Platania'),
  ('Thrasyvoulos FC', 'Grécia', 'Thrasyvoulos F.C. | Thrasyvoulos Fylis'),
  ('Volos NFC', 'Grécia', 'Volos N.F.C. | Volos F.C.'),
  ('Xanthi FC', 'Grécia', 'Xanthi F.C. | A.O. Xanthi'),
  ('Antigua GFC', 'Guatemala', null::text),
  ('Aurora FC', 'Guatemala', 'Aurora F.C. | Aurinegros'),
  ('CD Suchitepéquez', 'Guatemala', 'C.D. Suchitepéquez | Club Social y Deportivo Suchitepéquez | C.D. Suchitepequez | CD Suchitepequez | Club Social y Deportivo Suchitepequez | El gigante del sur | Los venados'),
  ('Club Deportivo Malacateco', 'Guatemala', 'The Bulls'),
  ('Cobán Imperial', 'Guatemala', 'Coban Imperial'),
  ('Comunicaciones FC', 'Guatemala', 'Comunicaciones F.C. | Comunicaciones'),
  ('CSD Municipal', 'Guatemala', 'C.S.D. Municipal | Reds | Devils'),
  ('CSD Xelajú MC', 'Guatemala', 'C.S.D. Xelajú MC | Xela | Super Chivos'),
  ('Deportivo Chiantla', 'Guatemala', null::text),
  ('Deportivo Marquense', 'Guatemala', 'Marquense'),
  ('Deportivo Mictlán', 'Guatemala', 'Deportivo Mictlan'),
  ('Deportivo Petapa', 'Guatemala', null::text),
  ('Deportivo Siquinalá', 'Guatemala', null::text),
  ('Deportivo Xinabajul', 'Guatemala', null::text),
  ('Deportivo Zacapa', 'Guatemala', null::text),
  ('Halcones Fútbol Club', 'Guatemala', 'Halcones FC | Halcones F.C. | Peñarol La Mesilla | Halcones Futbol Club'),
  ('Heredia Jaguares de Peten', 'Guatemala', null::text),
  ('IRCA (football club)', 'Guatemala', null::text),
  ('Juventud Escuintleca', 'Guatemala', null::text),
  ('Universidad SC', 'Guatemala', null::text),
  ('AS Ashanti Golden Boys', 'Guiné', null::text),
  ('AS Batè Nafadji', 'Guiné', null::text),
  ('AS Kaloum Star', 'Guiné', null::text),
  ('ASFAG', 'Guiné', null::text),
  ('Athlético de Coléah', 'Guiné', 'Athletico de Coleah'),
  ('Baraka Djoma SSG', 'Guiné', null::text),
  ('Club Industriel de Kamsar', 'Guiné', null::text),
  ('Espoir de Labé', 'Guiné', null::text),
  ('Étoile de Guinée', 'Guiné', 'Etoile de Guinee'),
  ('FC Séquence de Dixinn', 'Guiné', 'FC Sequence de Dixinn'),
  ('Fello Star', 'Guiné', null::text),
  ('Flamme Olympique FC', 'Guiné', null::text),
  ('Gangan FC', 'Guiné', 'Gangan Football Club'),
  ('Hafia Football Club', 'Guiné', null::text),
  ('Horoya AC', 'Guiné', null::text),
  ('Sankaran FC', 'Guiné', null::text),
  ('Santoba FC', 'Guiné', null::text),
  ('Satellite FC', 'Guiné', null::text),
  ('Soumba FC', 'Guiné', null::text),
  ('Tabounsou FC', 'Guiné', null::text),
  ('Wakriya AC', 'Guiné', null::text),
  ('Akonangui FC', 'Guiné Equatorial', null::text),
  ('CD Elá Nguema', 'Guiné Equatorial', 'CD Ela Nguema - Sony de Elá Nguema'),
  ('Clube de Futebol "Os Balantas"', 'Guiné-Bissau', null::text),
  ('Sport Bissau e Benfica', 'Guiné-Bissau', null::text),
  ('Sporting Clube de Bissau', 'Guiné-Bissau', null::text),
  ('Aigle Noir AC', 'Haiti', null::text),
  ('RC Haïtien', 'Haiti', 'Racing Club Haïtien'),
  ('Violette AC', 'Haiti', 'Violette A.C. | Violette Athletic Club'),
  ('CD Atlético Español', 'Honduras', 'C.D. Atlético Español'),
  ('CD Choloma', 'Honduras', null::text),
  ('CD Marathón', 'Honduras', 'C.D. Marathón | Club Deportivo Marathón | C.D. Marathon | Club Deportivo Marathon'),
  ('CD Olimpia', 'Honduras', 'C.D. Olimpia | Club Deportivo Olimpia | Olimpia'),
  ('CD Petrotela', 'Honduras', 'C.D. Petrotela'),
  ('CD Real Juventud', 'Honduras', 'C.D. Real Juventud'),
  ('CD Real Sociedad', 'Honduras', 'C.D. Real Sociedad'),
  ('CD Verdún', 'Honduras', 'C.D. Verdún | C.D. Verdun | Club Deportivo Verdún'),
  ('CDS Vida', 'Honduras', 'C.D.S. Vida | Club Deportivo y Social Vida | Vida'),
  ('Club Deportivo Victoria', 'Honduras', null::text),
  ('FC Motagua', 'Honduras', 'F.C. Motagua | Motagua | Las águilas azules | El mimado de la afición | El equipo de Poseidón | Club Deportivo Motagua | Club de Fútbol Motagua'),
  ('Hispano FC', 'Honduras', 'Hispano F.C.'),
  ('Honduras Salzburg', 'Honduras', null::text),
  ('Platense FC', 'Honduras', 'Platense F.C. | Platense Football Club S.A. de C.V.'),
  ('Real CD España', 'Honduras', 'Real C.D. España | Real Club Deportivo España | Real España'),
  ('Savio Fútbol Club', 'Honduras', null::text),
  ('Social Sol', 'Honduras', 'Club Deportivo Social Sol'),
  ('Tegucigalpa FC', 'Honduras', 'Tegucigalpa F.C.'),
  ('Kitchee SC', 'Hong Kong', 'Kitchee Sports Club | Kitchee Football Team | Kit Chee Sports Club Limited | Kitchee Sports Club Limited'),
  ('Lee Man FC', 'Hong Kong', 'Lee Man Football Club'),
  ('Balatonlelle SE', 'Hungria', null::text),
  ('Békéscsaba 1912 Előre SE', 'Hungria', null::text),
  ('BFC Siófok', 'Hungria', 'Bodajk FC Siofok | BFC Siofok'),
  ('Budafoki MTE', 'Hungria', 'Budafoki LC'),
  ('Budapest Honvéd FC', 'Hungria', 'Honvéd | Budapest Honved FC | Honved'),
  ('Budapesti TC', 'Hungria', null::text),
  ('Budapesti VSC', 'Hungria', 'BVSC'),
  ('Csepel SC', 'Hungria', null::text),
  ('Debreceni VSC', 'Hungria', 'DVSC'),
  ('Diósgyőri VTK', 'Hungria', 'Diósgyőr | Diosgyőr-Vasgyári Testgyakorlók Köre | DVTK'),
  ('Dorogi FC', 'Hungria', 'Dorogi Futball Club'),
  ('Dunaújváros FC', 'Hungria', 'Dunaujvaros FC'),
  ('Egri FC', 'Hungria', null::text),
  ('Fehérvár FC', 'Hungria', 'MOL Vidi | Vidi | MOL Vidi FC | Videoton FC | MOL Vidi Football Club | Vidi FC'),
  ('Ferenc Puskás Football Academy', 'Hungria', 'Puskás Akadémia FC | Ferenc Puskas Football Academy | Puskas Akademia FC'),
  ('Ferencvárosi TC', 'Hungria', 'FTC | Ferencvarosi TC | Ferencvárosi Torna Club | Ferencvarosi Torna Club'),
  ('Gyirmót FC Győr', 'Hungria', 'Gyirmot SE'),
  ('Győri ETO FC', 'Hungria', 'Raba ETO Gyor | Rába ETO Győr | Gyori ETO FC'),
  ('III. Kerületi TUE', 'Hungria', null::text),
  ('Kaposvári Rákóczi FC', 'Hungria', 'Kaposvari Rakoczi FC'),
  ('Kazincbarcikai SC', 'Hungria', null::text),
  ('Kecskeméti TE', 'Hungria', 'Kecskemeti TE'),
  ('Kisvárda FC', 'Hungria', 'Kisvárda Futball Club | Kisvarda'),
  ('Komlói Bányász SK', 'Hungria', 'Komloi Banyasz SK'),
  ('Körmendi FC', 'Hungria', null::text),
  ('Lombard-Pápa TFC', 'Hungria', 'Lombard-Papa TFC'),
  ('Mezőkövesd-Zsóry SE', 'Hungria', null::text),
  ('MTK Budapest FC', 'Hungria', 'MTK'),
  ('Nyíregyháza Spartacus FC', 'Hungria', 'Nyiregyhaza Spartacus FC'),
  ('Paksi FC', 'Hungria', 'Paksi SE'),
  ('Pécs-Baranya FC', 'Hungria', null::text),
  ('Pécsi MFC', 'Hungria', 'PMFC | Pecsi Mecsek Football Club | Pecsi MFC'),
  ('Salgótarjáni BTC', 'Hungria', 'SBTC | Salgotarjani BTC'),
  ('Szolnoki MÁV FC', 'Hungria', 'Szolnoki MAV FC'),
  ('Szombathelyi Haladás', 'Hungria', 'Haladás | Szombathelyi Haladas | Haladas'),
  ('Tatabányai SC', 'Hungria', 'FC Tatabanya'),
  ('Újpest FC', 'Hungria', 'Újpest Football Club | Újpest | Lilák | UFC'),
  ('Vác FC', 'Hungria', 'Vac FC | Dunakanyar-Vac FC'),
  ('Vasas FC', 'Hungria', null::text),
  ('Zalaegerszegi TE', 'Hungria', 'ZTE | Zalaegerszegi Torna Egylet'),
  ('Al-Ahli Club Sana''a', 'Iémen', null::text),
  ('Al-Saqr', 'Iémen', null::text),
  ('Al-Tilal SC', 'Iémen', null::text),
  ('07 Vestur', 'Ilhas Faroé', null::text),
  ('Argja Bóltfelag', 'Ilhas Faroé', 'AB Argir | Argja Boltfelag | AB Tórshavn | AB Torshavn'),
  ('B36 Tórshavn', 'Ilhas Faroé', 'B36'),
  ('B68 Toftir', 'Ilhas Faroé', null::text),
  ('B71 Sandoy', 'Ilhas Faroé', null::text),
  ('EB/Streymur', 'Ilhas Faroé', null::text),
  ('FC Suðuroy', 'Ilhas Faroé', null::text),
  ('Havnar Bóltfelag', 'Ilhas Faroé', 'Havnar Boltfelag'),
  ('ÍF Fuglafjørður', 'Ilhas Faroé', 'ÍF Fuglafjørdur | ÍF | IF Fuglafjordur | IF Fuglafjørdur | IF'),
  ('KÍ Klaksvík', 'Ilhas Faroé', 'KI Klaksvik | KÍ Klaksvik | Klaksvíkar Ítróttarfelag | Klaksvikar Itrottarfelag'),
  ('MB Miðvágur', 'Ilhas Faroé', null::text),
  ('NSÍ Runavík', 'Ilhas Faroé', 'NSI Runavik'),
  ('Royn Hvalba', 'Ilhas Faroé', null::text),
  ('SÍ Sørvágur', 'Ilhas Faroé', null::text),
  ('Skála ÍF', 'Ilhas Faroé', 'Skala IF'),
  ('TB Tvøroyri', 'Ilhas Faroé', null::text),
  ('TB/FC Suðuroy/Royn', 'Ilhas Faroé', null::text),
  ('Víkingur Gøta', 'Ilhas Faroé', null::text),
  ('Koloale FC', 'Ilhas Salomão', 'Koloale F.C.'),
  ('Kossa FC', 'Ilhas Salomão', 'Kossa F.C.'),
  ('Marist FC', 'Ilhas Salomão', 'Marist F.C. | Marist Fire F.C. | Marist Fire FC'),
  ('Solomon Warriors FC', 'Ilhas Salomão', 'Solomon Warriors F.C.'),
  ('Aizawl FC', 'Índia', 'Aizawl F.C. | Aizawl Football Club'),
  ('Bengaluru FC', 'Índia', 'Blues | Bengaluru Football Club'),
  ('Chennaiyin FC', 'Índia', 'Chennai ISL team'),
  ('Churchill Brothers SC', 'Índia', 'Churchill Brothers S.C.'),
  ('Dempo SC', 'Índia', 'Dempo S.C. | Dempo Sports Club'),
  ('East Bengal FC', 'Índia', 'East Bengal Football Club | East Bengal F.C.'),
  ('FC Goa', 'Índia', 'Football Club Goa'),
  ('FC Pune City', 'Índia', null::text),
  ('Gokulam Kerala FC', 'Índia', 'Gokulam FC'),
  ('Hyderabad FC', 'Índia', 'SC Delhi | Sporting Club Delhi'),
  ('Jamshedpur FC', 'Índia', null::text),
  ('Kerala Blasters FC', 'Índia', 'Kerala Blasters Football Club | Kerala Blasters | Kerala | KBFC'),
  ('Mohammedan Sporting Club', 'Índia', 'Mohammedan SC | Mohammedan Sporting Club (Kolkata) | Mohammedan SC (Kolkata) | Kolkata Mohammedan'),
  ('Mohun Bagan AC', 'Índia', 'Mohun Bagan | Mohun Bagan Athletic Club | Mohun Bagan Sporting Club | Mohun Bagan SC'),
  ('Mohun Bagan Super Giant', 'Índia', 'Mohun Bagan Football Club | Mohun Bagan FC | Mohun Bagan SG'),
  ('Mumbai City FC', 'Índia', 'Mumbai City Football Club'),
  ('Mumbai FC', 'Índia', 'Mumbai F.C. | Mumbai Football Club'),
  ('NEROCA FC', 'Índia', null::text),
  ('NorthEast United FC', 'Índia', 'NorthEast United Football Club'),
  ('Odisha FC', 'Índia', 'Delhi Dynamos Football Club | Delhi Dynamos FC'),
  ('Pune FC', 'Índia', 'Pune Football Club'),
  ('Punjab FC', 'Índia', 'RoundGlass Punjab FC | Punjab Football Club'),
  ('Salgaocar FC', 'Índia', 'Salgaocar Football Club'),
  ('Sporting Clube de Goa', 'Índia', null::text),
  ('Arema FC', 'Indonésia', 'Arema F.C.'),
  ('Bali United FC', 'Indonésia', 'Bali United F.C.'),
  ('Bhayangkara FC', 'Indonésia', 'Bhayangkara F.C.'),
  ('Borneo FC Samarinda', 'Indonésia', 'Borneo F.C. Samarinda'),
  ('Deltras FC', 'Indonésia', 'Deltras F.C.'),
  ('Dewa United FC', 'Indonésia', 'Dewa United F.C. | Martapura Football Club | Martapura FC'),
  ('Madura United FC', 'Indonésia', 'Madura United F.C. | Madura United Football Club'),
  ('Mitra Kukar FC', 'Indonésia', 'Mitra Kukar F.C.'),
  ('Persebaya Surabaya', 'Indonésia', null::text),
  ('Persegres Gresik United', 'Indonésia', 'Persatuan Sepak Bola Gresik'),
  ('Persela Lamongan', 'Indonésia', null::text),
  ('Persepam Madura United', 'Indonésia', 'Persepam Madura Utama'),
  ('Persib Bandung', 'Indonésia', 'Persatuan Sepak Bola Indonesia Bandung'),
  ('Persiba Balikpapan', 'Indonésia', null::text),
  ('Persidafon Dafonsoro', 'Indonésia', null::text),
  ('Persija Jakarta', 'Indonésia', null::text),
  ('Persik Kediri', 'Indonésia', 'Persik'),
  ('Persikabo 1973', 'Indonésia', null::text),
  ('Persipura Jayapura', 'Indonésia', 'Black Pearl'),
  ('Persiram Raja Ampat', 'Indonésia', null::text),
  ('Persita Tangerang', 'Indonésia', null::text),
  ('Persiwa Wamena', 'Indonésia', null::text),
  ('PS Barito Putera', 'Indonésia', null::text),
  ('PSAP Sigli', 'Indonésia', null::text),
  ('PSIS Semarang', 'Indonésia', null::text),
  ('PSM Makassar', 'Indonésia', null::text),
  ('PSMS Medan', 'Indonésia', null::text),
  ('PSPS Riau', 'Indonésia', null::text),
  ('PSS Sleman', 'Indonésia', null::text),
  ('Semen Padang FC', 'Indonésia', 'Semen Padang F.C.'),
  ('Sriwijaya FC', 'Indonésia', 'Sriwijaya F.C. | Sriwijaya Football Club'),
  ('Accrington Stanley', 'Inglaterra', 'Accrington Stanley F.C. | Accrington Stanley Football Club | Accrington Stanley FC | Accrington | Stanley | ASFC'),
  ('AFC Bournemouth', 'Inglaterra', 'Bournemouth | Bournemouth and Boscombe Athletic F.C. | Boscombe F.C. | Boscombe Football Club | Boscombe FC | Boscombe | Bournemouth and Boscombe Athletic FC | Bournemouth and Boscombe Athletic'),
  ('AFC Hayes', 'Inglaterra', 'A.F.C. Hayes'),
  ('AFC Telford United', 'Inglaterra', 'Telford United | The Bucks | Telford | AFCTU | A.F.C. Telford United'),
  ('AFC Wimbledon', 'Inglaterra', 'Wimbledon | The Dons | AFCW | A.F.C. Wimbledon'),
  ('Aldershot Town', 'Inglaterra', 'Aldershot Town F.C. | Aldershot Town Football Club | Aldershot Town FC | Aldershot | The Shots | ATFC'),
  ('Alfreton Town', 'Inglaterra', 'Alfreton Town F.C. | Alfreton Town Football Club | Alfreton Town FC | Alfreton | ATFC'),
  ('Altrincham', 'Inglaterra', 'Altrincham F.C. | Altrincham Football Club | Altrincham FC | Alty | AFC'),
  ('Arsenal', 'Inglaterra', 'Arsenal F.C. | AFC | Arsenal Football Club | The Arsenal | The Ars | The Arsenal F.C. | The Arsenal FC | A.F.C. | Arsenal London'),
  ('Ashton United', 'Inglaterra', 'Ashton United F.C. | Ashton United Football Club | Ashton United FC | AUFC | Ashton | Ashton United F. C.'),
  ('Aston Villa', 'Inglaterra', 'Aston Villa F.C. | Aston Villa Football Club | Aston Villa FC | Villa | The Villans | The Villa | AVFC'),
  ('Barnet', 'Inglaterra', 'Barnet F.C. | Barnet Football Club | Barnet FC | The Bees'),
  ('Barnsley', 'Inglaterra', 'Barnsley F.C. | Barnsley St. Peter''s | Barnsley FC | The Tykes | Barnsley Football Club'),
  ('Barrow', 'Inglaterra', 'Barrow A.F.C. | Barrow Association Football Club | Barrow AFC | The Bluebirds | BAFC'),
  ('Basingstoke Town', 'Inglaterra', 'Basingstoke Town F.C. | Basingstoke Town Football Club | Basingstoke Town FC | Basingstoke | Dragons'),
  ('Bath City', 'Inglaterra', 'Bath City F.C. | Bath City Football Club | Bath City FC | Bath | The Romans'),
  ('Berwick Rangers', 'Inglaterra', 'Berwick Rangers F.C.'),
  ('Bideford', 'Inglaterra', 'Bideford A.F.C.'),
  ('Billericay Town', 'Inglaterra', 'Billericay Town F.C. | Billericay Town Football Club'),
  ('Birmingham City', 'Inglaterra', 'Birmingham City F.C. | Birmingham City Football Club | Birmingham City FC | Birmingham | Blues'),
  ('Bishop''s Stortford', 'Inglaterra', 'Bishop''s Stortford F.C. | Bishop''s Stortford Football Club | Bishop''s Stortford FC | BSFC'),
  ('Blackburn Rovers', 'Inglaterra', 'Blackburn Rovers F.C. | Blackburn Rovers FC | Blackburn Rovers Football Club | Blackburn | BRFC'),
  ('Blackpool', 'Inglaterra', 'Blackpool F.C. | Blackpool Football Club | Blackpool FC | The Seasiders | The Pool | The Tangerines'),
  ('Blyth Spartans', 'Inglaterra', 'Blyth Spartans A.F.C. | Blyth Spartans Association Football Club | Blyth Spartans AFC | Blyth | The Spartans | BSAFC'),
  ('Bognor Regis Town', 'Inglaterra', 'Bognor Regis Town F.C. | Bognor Regis Town Football Club'),
  ('Bolton Wanderers', 'Inglaterra', 'Bolton Wanderers F.C. | Bolton Wanderers Football Club | Bolton Wanderers FC | Bolton | BWFC | The Trotters'),
  ('Boreham Wood', 'Inglaterra', 'Boreham Wood F.C. | Boreham Wood Football Club | Boreham Wood FC | The Wood | BWFC'),
  ('Boston United', 'Inglaterra', 'Boston United F.C. | Boston United Football Club | Boston United FC | Boston | The Pilgrims | BUFC'),
  ('Bradford (Park Avenue)', 'Inglaterra', 'Bradford (Park Avenue) A.F.C. | Bradford (Park Avenue) AFC | Bradford Park Avenue AFC | Bradford Park Avenue | Bradford PA | Bradford | BPA | The Avenue | BPAAFC'),
  ('Bradford City', 'Inglaterra', 'Bradford City A.F.C. | The Bantams | The Paraders | The Citizens | Bradford City Association Football Club | Bradford City AFC | Bradford | BCAFC'),
  ('Braintree Town', 'Inglaterra', 'Braintree Town F.C. | Braintree Town Football Club | Braintree Town FC | Braintree | The Iron'),
  ('Brentford', 'Inglaterra', 'Brentford F.C. | Brentford Football Club | Brentford FC | The Bees'),
  ('Brighton & Hove Albion', 'Inglaterra', 'Brighton & Hove Albion F.C. | Brighton and Hove Albion F.C. | Brighton & Hove Albion Football Club | Brighton and Hove Albion | Brighton and Hove Albion Football Club | Brighton & Hove | Brighton and Hove Albion FC | Brighton & Hove Albion FC | Brighton'),
  ('Bristol City', 'Inglaterra', 'Bristol City F.C. | Bristol City Football Club | Bristol City FC'),
  ('Bristol Rovers', 'Inglaterra', 'Bristol Rovers F.C. | Bristol Rovers Football Club | Bristol Rovers FC | The Pirates | The Gas | BRFC'),
  ('Bromley', 'Inglaterra', 'Bromley F.C. | Bromley Football Club | The Ravens | The Lillywhites | Bromley FC'),
  ('Burnley', 'Inglaterra', 'Burnley F.C. | Burnley Football Club | Burnley FC | The Clarets'),
  ('Burton Albion', 'Inglaterra', 'Burton Albion F.C. | Burton Albion Football Club | Burton Albion FC | Burton | Brewers | Albion | BAFC'),
  ('Bury', 'Inglaterra', 'Bury F.C. | Bury Football Club | Bury FC | The Shakers | Bury F.C'),
  ('Bury Town', 'Inglaterra', 'Bury Town F.C. | Bury Town Football Club | Bury Town FC | Bury'),
  ('Cambridge United', 'Inglaterra', 'Cambridge United F.C. | Cambridge United Football Club | Cambridge United FC | Cambridge | CUFC'),
  ('Canvey Island', 'Inglaterra', 'Canvey Island F.C. | Canvey Island Football Club'),
  ('Carlisle United', 'Inglaterra', 'Carlisle United F.C. | Carlisle United Football Club | Carlisle United FC | Cumbrians | Carlisle | CUFC'),
  ('Charlton Athletic', 'Inglaterra', 'Charlton Athletic F.C. | Charlton Athletic Football Club | Charlton Athletic FC | Charlton | The Addicks | CAFC'),
  ('Chelmsford City', 'Inglaterra', 'Chelmsford City F.C. | Chelmsford City Football Club | Chelmsford City FC | Chelmsford | CCFC'),
  ('Chelsea FC Development Squad and Academy', 'Inglaterra', 'Chelsea F.C. Development Squad and Academy | Chelsea Football Club Youth'),
  ('Cheltenham Town', 'Inglaterra', 'Cheltenham Town F.C. | Cheltenham Town Football Club | Cheltenham Town FC | Cheltenham'),
  ('Chester', 'Inglaterra', 'Chester F.C. | Chester Football Club | Chester FC'),
  ('Chesterfield', 'Inglaterra', 'Chesterfield F.C. | Chesterfield Football Club | Chesterfield FC | The Spireites'),
  ('Chorley', 'Inglaterra', 'Chorley F.C. | Chorley Football Club | Chorley FC'),
  ('Colchester United', 'Inglaterra', 'Colchester United F.C. | Colchester United Football Club | Colchester United FC | Colchester | CUFC'),
  ('Congleton Town', 'Inglaterra', 'Congleton Town F.C.'),
  ('Corinthian Casuals', 'Inglaterra', 'Corinthian Casuals F.C. | Corinthian-Casuals Football Club'),
  ('Coventry City', 'Inglaterra', 'Coventry City F.C. | Coventry City Football Club | Coventry City FC | Coventry | CCFC | Sky Blues'),
  ('Crawley Town', 'Inglaterra', 'Crawley Town F.C. | Crawley Town Football Club | Crawley Town FC | Crawley'),
  ('Cray Wanderers', 'Inglaterra', 'Cray Wanderers F.C. | Cray Wanderers Football Club'),
  ('Crewe Alexandra', 'Inglaterra', 'Crewe Alexandra F.C. | Crewe Alexandra Football Club | Crewe Alexandra FC | The Railwaymen | The Alex | Crewe | CAFC'),
  ('Crystal Palace', 'Inglaterra', 'Crystal Palace F.C. | Crystal Palace Football Club | Crystal Palace FC | Palace | The Eagles | The Glaziers | CPFC'),
  ('Dagenham & Redbridge', 'Inglaterra', 'Dagenham & Redbridge F.C. | Dagenham & Redbridge Football Club | Dagenham & Redbridge FC | Dagenham | Daggers | DRFC'),
  ('Darlington', 'Inglaterra', 'Darlington F.C. | Darlington Football Club | Darlington FC | Darlington 1883 | The Quakers'),
  ('Dartford', 'Inglaterra', 'Dartford F.C. | Dartford Football Club | Dartford FC | The Darts'),
  ('Derby County', 'Inglaterra', 'Derby County F.C. | Derby County FC | The Rams | DCFC | Derby'),
  ('Doncaster Rovers', 'Inglaterra', 'Doncaster Rovers F.C. | Doncaster Rovers Football Club | Doncaster Rovers FC | Doncaster | DRFC'),
  ('Dorchester Town', 'Inglaterra', 'Dorchester Town F.C. | Dorchester Town Football Club | Dorchester Town FC | Dorchester | DTFC'),
  ('Dorking Wanderers', 'Inglaterra', 'Dorking Wanderers F.C. | Dorking Wanderers Football Club | Dorking Wanderers FC | Dorking | The Wanderers'),
  ('Dover Athletic', 'Inglaterra', 'Dover Athletic F.C. | Dover Athletic Football Club | Dover Athletic FC | Dover | The Whites | DAFC'),
  ('Droylsden', 'Inglaterra', 'Droylsden F.C. | Droylsden Football Club | Droylsden FC | The Bloods'),
  ('Dulwich Hamlet', 'Inglaterra', 'Dulwich Hamlet F.C. | Dulwich Hamlet Football Club'),
  ('Eastbourne Borough', 'Inglaterra', 'Eastbourne Borough F.C. | Eastbourne Borough Football Club'),
  ('Eastbourne Town', 'Inglaterra', 'Eastbourne Town F.C. | Eastbourne Town Football Club'),
  ('Eastleigh', 'Inglaterra', 'Eastleigh F.C. | Eastleigh Football Club | Eastleigh FC | The Spitfires | EFC'),
  ('Ebbsfleet United', 'Inglaterra', 'Ebbsfleet United F.C. | Ebbsfleet United Football Club | Ebbsfleet United FC | Ebbsfleet | Gravesend & Northfleet Football Club | Gravesend & Northfleet FC | Gravesend & Northfleet | Gravesend | The Fleet'),
  ('Enfield Town', 'Inglaterra', 'Enfield Town F.C. | Enfield Town Football Club')
) as v(name, country, aliases)
join countries c on c.name = v.country
on conflict (name, country_id) do update set aliases = coalesce(teams.aliases, excluded.aliases);
