-- Football clubs from Wikidata (CC0), part 4 of 4. Safe to re-run: a club that already exists (same name and country) is kept and only gets its other names filled in.
-- Run 0023_uk_countries.sql first (it creates Inglaterra, Escocia, etc. and the aliases column).
insert into teams (name, country_id, aliases)
select v.name, c.id, v.aliases
from (values
  ('Sparta Rotterdam', 'Países Baixos', 'Sparta'),
  ('Sportclub Enschede', 'Países Baixos', null::text),
  ('SV Spakenburg', 'Países Baixos', 'Sportvereniging Spakenburg'),
  ('SVV Scheveningen', 'Países Baixos', null::text),
  ('TOP Oss', 'Países Baixos', 'FC Oss'),
  ('VV DOS', 'Países Baixos', null::text),
  ('VV Katwijk', 'Países Baixos', null::text),
  ('VV Noordwijk', 'Países Baixos', null::text),
  ('VVK/Telstar', 'Países Baixos', 'Telstar'),
  ('VVV-Venlo', 'Países Baixos', 'Venlose Voetbal Vereniging Venlo'),
  ('Hilal Al-Quds Club', 'Palestina', null::text),
  ('Club Deportivo Árabe Unido', 'Panamá', 'Club Deportivo Arabe Unido | DAU | Expreso Azul'),
  ('Club Deportivo Plaza Amador', 'Panamá', 'C.D. Plaza Amador | Plaza Amador'),
  ('Club Deportivo Universitario', 'Panamá', 'CD Universitario | Chorrillo Fútbol Club | Chorrillo F.C.'),
  ('San Francisco FC', 'Panamá', 'San Francisco F.C.'),
  ('Sporting San Miguelito', 'Panamá', null::text),
  ('Tauro FC', 'Panamá', 'Tauro F.C.'),
  ('Hekari United FC', 'Papua-Nova Guiné', 'PRK Hekari United | Hekari United | Hekari United Football Club'),
  ('Afghan FC', 'Paquistão', 'Afghan F.C.'),
  ('Baloch FC', 'Paquistão', 'Baloch F.C.'),
  ('HBL FC', 'Paquistão', 'HBL F.C.'),
  ('KESC FC', 'Paquistão', 'KESC F.C.'),
  ('KPT FC', 'Paquistão', 'KPT F.C.'),
  ('KRL FC', 'Paquistão', 'KRL F.C. | Khan Research Laboratories Football Club'),
  ('Lyallpur FC', 'Paquistão', 'Lyallpur Football Club'),
  ('Muslim FC', 'Paquistão', null::text),
  ('NBP FC', 'Paquistão', 'NBP F.C.'),
  ('PAF FC', 'Paquistão', 'PAF F.C.'),
  ('Pak Afghan Clearing FC', 'Paquistão', null::text),
  ('Pakistan Army FC', 'Paquistão', 'Pakistan Army F.C.'),
  ('Pakistan International Airlines FC', 'Paquistão', null::text),
  ('Pakistan Navy FC', 'Paquistão', 'Pakistan Navy F.C.'),
  ('Pakistan Railways FC', 'Paquistão', 'Pakistan Railways F.C.'),
  ('PEL FC', 'Paquistão', 'PEL F.C.'),
  ('PMC Club Athletico Faisalabad', 'Paquistão', null::text),
  ('SSGC FC', 'Paquistão', 'SSGC F.C.'),
  ('WAPDA FC', 'Paquistão', 'WAPDA F.C.'),
  ('ZTBL FC', 'Paquistão', 'ZTBL F.C.'),
  ('Cerro Porteño', 'Paraguai', 'Cerro'),
  ('Club 12 de Octubre', 'Paraguai', 'Club 12 de Octubre de Itaugua'),
  ('Club Atlético 3 de Febrero', 'Paraguai', null::text),
  ('Club Cerro Porteño', 'Paraguai', null::text),
  ('Club Deportivo Capiatá', 'Paraguai', 'Club Deportivo Capiata'),
  ('Club General Díaz', 'Paraguai', 'Club General Diaz'),
  ('Club Guaraní', 'Paraguai', 'Club Guarani'),
  ('Club Libertad', 'Paraguai', 'Libertad'),
  ('Club Nacional', 'Paraguai', null::text),
  ('Club Olimpia', 'Paraguai', null::text),
  ('Club Presidente Hayes', 'Paraguai', null::text),
  ('Club River Plate Asunción', 'Paraguai', 'River Plate Asunción'),
  ('Club Rubio Ñu', 'Paraguai', null::text),
  ('Club Silvio Pettirossi', 'Paraguai', null::text),
  ('Club Sol de América', 'Paraguai', 'Club Sol de America'),
  ('Club Sport Colombia', 'Paraguai', null::text),
  ('Club Sportivo 2 de Mayo', 'Paraguai', 'GALLO NORTEÑO'),
  ('Club Sportivo San Lorenzo', 'Paraguai', null::text),
  ('Deportivo Recoleta', 'Paraguai', 'pero que mandan'),
  ('Independiente FBC', 'Paraguai', 'Independiente F.B.C.'),
  ('Resistencia SC', 'Paraguai', 'Resistencia S.C.'),
  ('Sportivo Carapeguá', 'Paraguai', 'Sportivo Carapegua'),
  ('Sportivo Luqueño', 'Paraguai', null::text),
  ('Sportivo Trinidense', 'Paraguai', 'Triqui'),
  ('Tacuary Football Club', 'Paraguai', 'Tacuary FBC | Tacuary'),
  ('Atlético Grau', 'Peru', 'Club Atlético Grau'),
  ('Ayacucho FC', 'Peru', 'Ajaxcucho | Los zorros'),
  ('CD Universidad César Vallejo', 'Peru', 'Club Deportivo Universidad César Vallejo'),
  ('Centro Iqueño', 'Peru', null::text),
  ('Cienciano', 'Peru', 'Club Sportivo Cienciano'),
  ('Club Alianza Lima', 'Peru', 'Alianza Lima'),
  ('Club Deportivo Municipal', 'Peru', 'Deportivo Municipal'),
  ('Club Deportivo Pacífico FC', 'Peru', 'Pacífico FC | Club Deportivo Pacifico FC | Pacifico FC | Deportivo Pacífico | Deportivo Pacifico'),
  ('Club Juan Aurich', 'Peru', null::text),
  ('Club Sporting Cristal', 'Peru', 'Sporting Cristal'),
  ('Club Universitario de Deportes', 'Peru', 'Universitario | La "U" | Federación Universitaria de Fútbol | Universitario de Perú | U of Lima | University Club of Sports'),
  ('Cultural and Sports Club Technical University of Cajamarca', 'Peru', 'Universidad Tecnica de Cajamarca | UTC | UTC of Cajamarca'),
  ('Cusco FC', 'Peru', null::text),
  ('FBC Melgar', 'Peru', 'Foot Ball Club Melgar | F.B.C. Melgar'),
  ('José Gálvez FBC', 'Peru', 'Jose Galvez FBC'),
  ('León de Huánuco', 'Peru', 'Leon de Huanuco'),
  ('Merchants United Social, Sports and Cultural Association', 'Peru', 'Comerciantes Unidos from Cutervo | Merchants United'),
  ('Pirata F.C', 'Peru', null::text),
  ('San Simón de Moquegua', 'Peru', null::text),
  ('Sport Áncash', 'Peru', 'Sport Ancash'),
  ('Sport Boys', 'Peru', 'Sport Boys Association | Club Sport Boys Association'),
  ('Sport Huancayo', 'Peru', null::text),
  ('Sport Rosario', 'Peru', null::text),
  ('Sporting Tabaco (1926–1955)', 'Peru', null::text),
  ('Sports Association Club Alianza Atlético de Sullana', 'Peru', 'Alianza Atletico | Club Alianza Atlético de Sullana'),
  ('Unión Comercio', 'Peru', 'Union Comercio'),
  ('Unión Huaral', 'Peru', 'Club Unión Huaral | Union Huaral'),
  ('Arka Gdynia', 'Polónia', null::text),
  ('Chrobry Głogów', 'Polónia', null::text),
  ('Cracovia', 'Polónia', null::text),
  ('Dolcan Ząbki', 'Polónia', null::text),
  ('Flota Świnoujście', 'Polónia', null::text),
  ('Garbarnia Kraków', 'Polónia', 'Garbarnia Krakow'),
  ('GKS Bełchatów', 'Polónia', null::text),
  ('GKS Katowice', 'Polónia', null::text),
  ('GKS Tychy', 'Polónia', null::text),
  ('Górnik Łęczna', 'Polónia', null::text),
  ('Górnik Zabrze', 'Polónia', 'Gornik Zabrze'),
  ('Gwardia Warsaw', 'Polónia', 'Gwardia Warszawa'),
  ('Hutnik Nowa Huta', 'Polónia', null::text),
  ('Jagiellonia Białystok', 'Polónia', null::text),
  ('Korona Kielce', 'Polónia', null::text),
  ('KS Lechia Gdańsk', 'Polónia', null::text),
  ('KSZO Ostrowiec Świętokrzyski', 'Polónia', null::text),
  ('Lech Poznań', 'Polónia', null::text),
  ('ŁKS Łódź', 'Polónia', null::text),
  ('LKS Nieciecza', 'Polónia', 'Bruk-Bet Termalica Nieciecza'),
  ('Miedź Legnica', 'Polónia', null::text),
  ('MKP Pogoń Siedlce', 'Polónia', null::text),
  ('Motor Lublin', 'Polónia', null::text),
  ('Odra Opole', 'Polónia', null::text),
  ('Odra Wodzisław', 'Polónia', null::text),
  ('Piast Gliwice', 'Polónia', 'Gliwicki Klub Sportowy Piast Gliwice'),
  ('Podbeskidzie Bielsko-Biała', 'Polónia', null::text),
  ('Pogoń Szczecin', 'Polónia', null::text),
  ('Polonia Bytom', 'Polónia', null::text),
  ('Polonia Warsaw', 'Polónia', 'Polonia Warszawa | KS Polonia Warsaw'),
  ('Puszcza Niepołomice', 'Polónia', null::text),
  ('Radomiak Radom', 'Polónia', null::text),
  ('Raków Częstochowa', 'Polónia', null::text),
  ('ROW 1964 Rybnik', 'Polónia', null::text),
  ('RTS Widzew Łódź', 'Polónia', 'Widzew Lodz'),
  ('Ruch Chorzów', 'Polónia', 'Ruch Chorzow'),
  ('Sandecja Nowy Sącz', 'Polónia', null::text),
  ('Śląsk Wrocław', 'Polónia', 'WKS Śląsk Wrocław'),
  ('Stal Mielec', 'Polónia', null::text),
  ('Stal Rzeszów', 'Polónia', 'Stal Rzeszow'),
  ('Stal Stalowa Wola', 'Polónia', null::text),
  ('Szombierki Bytom', 'Polónia', null::text),
  ('Warta Poznań', 'Polónia', null::text),
  ('Wieczysta Kraków', 'Polónia', null::text),
  ('Wigry Suwałki', 'Polónia', null::text),
  ('Wisła Kraków', 'Polónia', 'Wisla Krakow'),
  ('Wisła Płock', 'Polónia', null::text),
  ('Zagłębie Lubin', 'Polónia', 'KGHM Zagłębie Lubin'),
  ('Zagłębie Sosnowiec', 'Polónia', 'Zagłębie | Sosnowiec'),
  ('Zagłębie Wałbrzych', 'Polónia', null::text),
  ('Zawisza Bydgoszcz', 'Polónia', null::text),
  ('Znicz Pruszków', 'Polónia', 'Znicz Pruszkow'),
  ('Académico de Viseu FC', 'Portugal', 'Academico de Viseu FC | Academico de Viseu'),
  ('AD Ovarense', 'Portugal', 'A.D. Ovarense | Associacao Desportiva Ovarense | Associação Desportiva Ovarense'),
  ('AD Sanjoanense', 'Portugal', 'A.D. Sanjoanense'),
  ('Associação Académica de Coimbra – OAF', 'Portugal', 'Associação Académica de Coimbra – O.A.F. | A.A.C. – O.A.F. | Académica de Coimbra | Académica | Academica de Coimbra | Academica'),
  ('Associação Naval 1º de Maio', 'Portugal', 'Naval'),
  ('Atlético Clube de Portugal', 'Portugal', null::text),
  ('AVS Futebol SAD', 'Portugal', 'AVS Futebol'),
  ('Boavista FC', 'Portugal', 'Boavista F.C.'),
  ('B-SAD', 'Portugal', 'Os Belenenses Futebol, SAD | Belenenses SAD'),
  ('Casa Pia AC', 'Portugal', 'Casa Pia A.C.'),
  ('CD Cova da Piedade', 'Portugal', 'C.D. Cova da Piedade'),
  ('CD Fátima', 'Portugal', 'C.D. Fátima | Fátima | C.D. Fatima | Fatima'),
  ('CD Feirense', 'Portugal', 'C.D. Feirense | Clube Desportivo Feirense | Feirense'),
  ('CD Mafra', 'Portugal', 'C.D. Mafra | Club Deportivo Mafra'),
  ('CD Nacional', 'Portugal', 'C.D. Nacional | Clube Desportivo Nacional | Nacional | Nacional da Madeira'),
  ('CD Santa Clara', 'Portugal', 'C.D. Santa Clara | Santa Clara Azores'),
  ('CD Tondela', 'Portugal', null::text),
  ('CD Trofense', 'Portugal', 'C.D. Trofense | Trofense'),
  ('CF Andorinha', 'Portugal', null::text),
  ('CF Estrela da Amadora', 'Portugal', 'C.F. Estrela da Amadora | Estrela | Estrela da Amadora | CF Estrela Amadora | Estrela Amadora | Club Football Estrela da Amadora'),
  ('CF Os Belenenses', 'Portugal', 'C.F. Os Belenenses | Belenenses'),
  ('CF União', 'Portugal', 'C.F. União'),
  ('Clube Desportivo das Aves', 'Portugal', 'Desportivo das Aves | C.D. Aves | Aves'),
  ('Clube Oriental de Lisboa', 'Portugal', null::text),
  ('CS Marítimo', 'Portugal', 'C.S. Marítimo | Marítimo | C.S. Maritimo | Maritimo | CS Maritimo'),
  ('FC Alverca', 'Portugal', 'F.C. Alverca'),
  ('FC Arouca', 'Portugal', 'F.C. Arouca | Futebol Clube de Arouca'),
  ('FC Barreirense', 'Portugal', 'F.C. Barreirense'),
  ('FC Famalicão', 'Portugal', 'FC Famalicao | F.C. Famalicão | F.C. Famalicao'),
  ('FC Felgueiras', 'Portugal', 'F.C. Felgueiras'),
  ('FC Maia', 'Portugal', 'F.C. Maia'),
  ('FC Paços de Ferreira', 'Portugal', 'F.C. Paços de Ferreira | Paços de Ferreira'),
  ('FC Penafiel', 'Portugal', 'F.C. Penafiel | Futebol Clube Penafiel'),
  ('FC Porto', 'Portugal', 'FCP | FCPorto | F.C.Porto | F.C.P. | F.C. Porto | Futebol Clube do Porto | Porto'),
  ('FC Tirsense', 'Portugal', 'F.C. Tirsense'),
  ('FC Vizela', 'Portugal', 'F.C. Vizela | Futebol Clube de Vizela'),
  ('GD Chaves', 'Portugal', 'G.D. Chaves | Grupo Desportivo de Chaves | Chaves'),
  ('GD Estoril Praia', 'Portugal', 'G.D. Estoril Praia | Grupo Desportivo Estoril Praia | Estoril | Estoril Praia'),
  ('GD Fabril', 'Portugal', 'G.D. Fabril | CUF Barreiro'),
  ('GD Ribeirão', 'Portugal', 'G.D. Ribeirão'),
  ('Gil Vicente FC', 'Portugal', 'Gil Vicente F.C. | Gil Vicente Futebol Clube'),
  ('Gondomar SC', 'Portugal', 'Gondomar S.C.'),
  ('Leça FC', 'Portugal', 'Leça F.C.'),
  ('Leixões SC', 'Portugal', 'Leixões S.C. | Leixões'),
  ('Louletano DC', 'Portugal', 'Louletano D.C.'),
  ('Moreirense FC', 'Portugal', 'Moreirense F.C. | Moreirense | Moreirense Futebol Clube'),
  ('Portimonense SC', 'Portugal', 'Portimonense S.C. | Portimonense Sporting Clube'),
  ('Real Sport Clube', 'Portugal', null::text),
  ('Rio Ave FC', 'Portugal', 'Rio Ave F.C.'),
  ('SC Beira-Mar', 'Portugal', 'S.C. Beira-Mar | Beira-Mar | Sport Clube Beira-Mar | SC Beira Mar | Beira-Mar Aveiro'),
  ('SC Braga', 'Portugal', 'S.C. Braga | Sporting de Braga | Sporting Braga | Sp. Braga | Sporting Clube de Braga'),
  ('SC Campomaiorense', 'Portugal', 'S.C. Campomaiorense'),
  ('SC Covilhã', 'Portugal', 'S.C. Covilhã | Cobilhã'),
  ('SC Espinho', 'Portugal', 'S.C. Espinho'),
  ('SC Farense', 'Portugal', 'S.C. Farense | Farense'),
  ('SC Freamunde', 'Portugal', 'S.C. Freamunde | Sport Clube de Freamunde'),
  ('SC Olhanense', 'Portugal', 'S.C. Olhanense'),
  ('SC Salgueiros', 'Portugal', 'S.C. Salgueiros | Salgueiros'),
  ('SCU Torreense', 'Portugal', 'S.C.U. Torreense'),
  ('SL Benfica', 'Portugal', 'S.L. Benfica | Sport Lisboa e Benfica | Benfica | SLB'),
  ('SL Benfica de Macau', 'Portugal', 'S.L. Benfica de Macau | Benfica de Macau | Casa do Benfica em Macau'),
  ('Sporting CP', 'Portugal', 'Sporting Club Portugal | Sporting Portugal | SCP | Sporting Lisbon'),
  ('UD Leiria', 'Portugal', 'U.D. Leiria | União de Leiria | Uniao de Leiria | União Desportiva de Leiria'),
  ('UD Oliveirense', 'Portugal', 'U.D. Oliveirense'),
  ('UD Vilafranquense', 'Portugal', 'Vilafranquense | União Desportiva Vilafranquense | U.D. Vilafranquense'),
  ('Varzim SC', 'Portugal', 'Varzim S.C. | Varzim Sport Club'),
  ('Vitória FC', 'Portugal', 'Vitória F.C. | Vitória Futebol Clube | Vitória de Setúbal | Vitoria F.C. | Vitoria Futebol Clube | Vitoria de Setubal'),
  ('Vitória SC', 'Portugal', 'Vitória S.C. | Vitoria S.C. | Vitoria de Guimaraes | Vitória Guimarães SC | Vitoria Guimaraes SC | Vitoria SC | Vitória de Guimarães'),
  ('AFC Leopards', 'Quénia', 'A.F.C. Leopards | Ingwe | A.F.C. Leopards S.C. | Abaluhya F.C.'),
  ('Bandari FC', 'Quénia', 'Bandari F.C.'),
  ('Chemelil Sugar FC', 'Quénia', 'Chemelil Sugar F.C. | Chemelil Sugar Football Club'),
  ('Gor Mahia FC', 'Quénia', 'Gor Mahia F.C. | Gor Mahia Football Club | K''Ogalo | Mayienga | Sirkal | Taya'),
  ('Kakamega Homeboyz FC', 'Quénia', 'Kakamega Homeboyz F.C.'),
  ('Kariobangi Sharks', 'Quénia', null::text),
  ('Karuturi Sports', 'Quénia', null::text),
  ('Kenya Commercial Bank', 'Quénia', null::text),
  ('Kenya Pipeline FC', 'Quénia', 'Kenya Pipeline F.C.'),
  ('Kenya Revenue Authority FC', 'Quénia', 'Kenya Revenue Authority F.C.'),
  ('Kisumu Telkom', 'Quénia', null::text),
  ('Mara Sugar', 'Quénia', 'Mara Sugar Football Club'),
  ('Mathare United FC', 'Quénia', 'Mathare United F.C.'),
  ('Nairobi City Stars', 'Quénia', null::text),
  ('Nairobi United', 'Quénia', null::text),
  ('Nakumatt FC', 'Quénia', 'Nakumatt Football Club | Mt. Kenya United FC | Nakumatti Football Club | Nakumatti FC'),
  ('Nakuru AllStars', 'Quénia', null::text),
  ('Nzoia United FC', 'Quénia', 'Nzoia United F.C.'),
  ('Reunion FC', 'Quénia', 'Reunion F.C.'),
  ('Sofapaka FC', 'Quénia', 'Sofapaka F.C.'),
  ('Sony Sugar FC', 'Quénia', 'Sony Sugar F.C.'),
  ('Thika United FC', 'Quénia', 'Thika United F.C.'),
  ('Tusker FC', 'Quénia', 'Tusker F.C.'),
  ('Ulinzi Stars FC', 'Quénia', 'Ulinzi Stars F.C.'),
  ('Utalii FC', 'Quénia', 'Utalii F.C.'),
  ('Vihiga Bullets', 'Quénia', null::text),
  ('Wazito FC', 'Quénia', 'Wazito F.C.'),
  ('Western Stima FC', 'Quénia', 'Western Stima F.C. | Western Stima Football Club'),
  ('Zoo Kericho FC', 'Quénia', 'Zoo Kericho F.C.'),
  ('FC Abdish-Ata Kant', 'Quirguistão', 'Abdish-Ata Kant'),
  ('FC Abdish-Ata-91', 'Quirguistão', null::text),
  ('FC Akademija Osh', 'Quirguistão', null::text),
  ('FC Ak-Bura Osh', 'Quirguistão', null::text),
  ('FC Ak-Maral Tokmok', 'Quirguistão', null::text),
  ('FC Ak-Zhol', 'Quirguistão', null::text),
  ('FC Alamudun', 'Quirguistão', null::text),
  ('FC Ala-Too Naryn', 'Quirguistão', 'Ala Too Naryn | Ala-Too Naryn'),
  ('FC Alay', 'Quirguistão', null::text),
  ('FC Aldiyer Kurshab', 'Quirguistão', null::text),
  ('FC Alga Bishkek', 'Quirguistão', null::text),
  ('FC Alga-2 Bishkek', 'Quirguistão', null::text),
  ('FC Asia Talas', 'Quirguistão', null::text),
  ('FC Ata-Spor Bishkek', 'Quirguistão', null::text),
  ('FC Bazar-Korgon-Babur', 'Quirguistão', null::text),
  ('FC Dinamo Ala-Buka', 'Quirguistão', null::text),
  ('FC Dinamo Kant', 'Quirguistão', null::text),
  ('FC Dinamo-Manas-SKIF Bishkek', 'Quirguistão', null::text),
  ('FC Dinamo-UVD Osh', 'Quirguistão', null::text),
  ('FC Dordoi Bishkek', 'Quirguistão', 'FC Dordoi-Dynamo'),
  ('FC Dordoi-Plaza', 'Quirguistão', null::text),
  ('FC Dostuk Uzgen', 'Quirguistão', null::text),
  ('FC Dzhalal-Abad', 'Quirguistão', null::text),
  ('FC Ekolog Bishkek', 'Quirguistão', null::text),
  ('FC Energetik Karaköl', 'Quirguistão', null::text),
  ('FC Issyk-Kol Karakol', 'Quirguistão', null::text),
  ('FC Kambar-Ata', 'Quirguistão', null::text),
  ('FC Kant', 'Quirguistão', null::text),
  ('FC Kant-Oil', 'Quirguistão', null::text),
  ('FC Kelechek Osh', 'Quirguistão', null::text),
  ('FC Khimik Suzak', 'Quirguistão', null::text),
  ('FC Kyrgyzaltyn', 'Quirguistão', 'FC Khimik Kara-Balta'),
  ('FC Lokomotiv Jalal-Abad', 'Quirguistão', null::text),
  ('FC Manas Talas', 'Quirguistão', null::text),
  ('FC Manas-Ordo Talas', 'Quirguistão', null::text),
  ('FC Muras-Sport Bishkek', 'Quirguistão', null::text),
  ('FC Neftchi Kochkor-Ata', 'Quirguistão', null::text),
  ('FC Nookat', 'Quirguistão', null::text),
  ('FC Olimpia-85 Bishkek', 'Quirguistão', null::text),
  ('FC Orto-Nur Sokuluk', 'Quirguistão', null::text),
  ('FC Pivo Belovodskoye', 'Quirguistão', null::text),
  ('FC Polyot Bishkek', 'Quirguistão', null::text),
  ('FC Rotor Bishkek', 'Quirguistão', null::text),
  ('FC RUOR-Guardia Bishkek', 'Quirguistão', null::text),
  ('FC Shakhtyor Kyzyl-Kiya', 'Quirguistão', null::text),
  ('FC Shakhtyor Tashkömür', 'Quirguistão', null::text),
  ('FC Sher-Ak-Dan Bishkek', 'Quirguistão', null::text),
  ('FC Shoro Bishkek', 'Quirguistão', null::text),
  ('FC SKA-Alay Osh', 'Quirguistão', null::text),
  ('FC Svetotekhnika Mayli-Su', 'Quirguistão', null::text),
  ('FC Uchkun Kara-Suu', 'Quirguistão', null::text),
  ('FC Zhashtyk-Ak-Altyn Kara-Suu', 'Quirguistão', null::text),
  ('FC-95 Bishkek', 'Quirguistão', null::text),
  ('Muras United FC', 'Quirguistão', 'Футбольный клуб «Мурас Юнайтед» | футбол Клубурас Юнайтед | Мурас Юнайтед Джалал-Абад | ФК Мурас Юнайтед'),
  ('OshMU Aldier FC', 'Quirguistão', 'OshMU Aldier Football Club | футбол Клубу ОшМУ-Алдиер'),
  ('1. FC Slovácko', 'República Checa', '1. FC Synot | 1.FC SLOVÁCKO | 1.FC SLOVÁCKO, a.s.'),
  ('1. SC Znojmo', 'República Checa', null::text),
  ('1. SK Prostějov', 'República Checa', null::text),
  ('AC Sparta Prague', 'República Checa', 'Sparta Prague | A.C. Sparta Prague | Athletic Club Sparta Prague | ACS | A.C.S. | ACSparta | SpartaPrague'),
  ('Bohemians 1905', 'República Checa', 'FC Bohemians Praha | Bohemians Praha 1905 | Bohemians Prague | Bohemians Prague 1905 | Bohemka | The Kangaroos'),
  ('FC Baník Ostrava', 'República Checa', 'FC Banik Ostrava'),
  ('FC Hradec Králové', 'República Checa', 'FC Hradec Kralove'),
  ('FC Silon Táborsko', 'República Checa', 'FK MAS Taborsko'),
  ('FC Slovan Liberec', 'República Checa', null::text),
  ('FC Viktoria Plzeň', 'República Checa', 'Viktoria Plzen'),
  ('FC Vysočina Jihlava', 'República Checa', null::text),
  ('FC Zbrojovka Brno', 'República Checa', null::text),
  ('FC Zlín', 'República Checa', 'FC Fastav Zlin | FC Fastav Zlín | FC Trinity Zlín'),
  ('FK Baník Sokolov', 'República Checa', 'FK Banik Sokolov'),
  ('FK Chmel Blšany', 'República Checa', 'Chmel Blšany'),
  ('FK Dukla Prague', 'República Checa', 'FK Dukla Praha'),
  ('FK Hvězda Cheb', 'República Checa', null::text),
  ('FK Jablonec', 'República Checa', 'Jablonec'),
  ('FK Mladá Boleslav', 'República Checa', 'FK Mlada Boleslav'),
  ('FK Pardubice', 'República Checa', null::text),
  ('FK Příbram', 'República Checa', '1. FK Příbram'),
  ('FK Teplice', 'República Checa', null::text),
  ('FK Ústí nad Labem', 'República Checa', 'FK Usti nad Labem'),
  ('FK Varnsdorf', 'República Checa', null::text),
  ('FK Viktoria Žižkov', 'República Checa', null::text),
  ('MFK Karviná', 'República Checa', 'MFK OKD Karviná | MFK Karvina | MFK OKD Karvina'),
  ('MFK Vítkovice', 'República Checa', 'FC Vitkovice'),
  ('SFC Opava', 'República Checa', null::text),
  ('SK Dynamo České Budějovice', 'República Checa', null::text),
  ('SK Kladno', 'República Checa', null::text),
  ('SK Sigma Olomouc', 'República Checa', 'Sportovní Klub Sigma Olomouc | Sportovni Klub Sigma Olomouc'),
  ('SK Slavia Prague', 'República Checa', 'Slavia Prague | S.K. Slavia Prague | SlaviaPrague | Slavia Praha | Slavia Prague Football | Slavia Prague FC'),
  ('AC Capaco', 'República Democrática do Congo', null::text),
  ('AC Sodigraf', 'República Democrática do Congo', null::text),
  ('AS Dauphins Noirs', 'República Democrática do Congo', null::text),
  ('AS Dragons', 'República Democrática do Congo', 'Amicale Sportive Dragons'),
  ('AS Makiso', 'República Democrática do Congo', null::text),
  ('AS Maniema Union', 'República Democrática do Congo', 'Maniema Union'),
  ('AS New Soger', 'República Democrática do Congo', null::text),
  ('AS Nika', 'República Democrática do Congo', null::text),
  ('AS Rojolu', 'República Democrática do Congo', null::text),
  ('AS Saint-Luc', 'República Democrática do Congo', 'Association sportive Saint-Luc'),
  ('AS Veti', 'República Democrática do Congo', 'Association sportive Veti Club'),
  ('Association Sportive Vita Club', 'República Democrática do Congo', 'AS Vita Kinshasa | ASV Club | AS V.Club | AS Vita Club Kinshasa | AS Vita | Vita Club | A.S. Vita Club | AS V. Club'),
  ('CS Don Bosco', 'República Democrática do Congo', null::text),
  ('Daring Club Motema Pembe', 'República Democrática do Congo', 'Daring Club Motema Pemba'),
  ('DC Virunga', 'República Democrática do Congo', null::text),
  ('FC MK Etanchéité', 'República Democrática do Congo', 'Football Club MK Étanchéité'),
  ('FC Saint Eloi Lupopo', 'República Democrática do Congo', null::text),
  ('JS Groupe Bazano', 'República Democrática do Congo', null::text),
  ('Lubumbashi Sport', 'República Democrática do Congo', null::text),
  ('OC Bukavu Dawa', 'República Democrática do Congo', null::text),
  ('OC Muungano', 'República Democrática do Congo', null::text),
  ('SC Cilu', 'República Democrática do Congo', null::text),
  ('SCOM Mikishi', 'República Democrática do Congo', null::text),
  ('Sharks XI FC', 'República Democrática do Congo', 'Sharks XI F.C.'),
  ('SM Sanga Balende', 'República Democrática do Congo', 'Sa Majesté Sanga Balende'),
  ('TC Elima', 'República Democrática do Congo', null::text),
  ('TP Mazembe', 'República Democrática do Congo', 'Tout Puissant Mazembe'),
  ('TP Molunge', 'República Democrática do Congo', null::text),
  ('US Panda B52', 'República Democrática do Congo', 'Union sportive Panda B52'),
  ('US Tshinkunku', 'República Democrática do Congo', 'Union sportive Tshinkunku'),
  ('Club Deportivo Pantoja', 'República Dominicana', 'Atlético Pantoja'),
  ('AFC Chindia Târgoviște', 'Roménia', null::text),
  ('AFC Dacia Unirea Brăila', 'Roménia', 'ACS Dacia Unirea Brăila'),
  ('ASA Târgu Mureș', 'Roménia', 'ASA Tîrgu Mureş | ASA Targu Mures | Maris Târgu Mureş | Maris Târgu Mureș | ASA Târgu Mureş | ASA 1962 Târgu Mureș'),
  ('CFR Cluj', 'Roménia', null::text),
  ('Club Atletic Oradea', 'Roménia', 'CAO'),
  ('CS Concordia Chiajna', 'Roménia', null::text),
  ('CS Gaz Metan Mediaș', 'Roménia', null::text),
  ('CS Inter Ilfov', 'Roménia', 'FC Clinceni | ACS Buftea | FC Academica Argeș | Academica Clinceni | Fotbal Club Academica Clinceni | LPS HD Clinceni | Inter Ilfov | Inter Ilfov Clinceni'),
  ('CS Pandurii Târgu Jiu', 'Roménia', 'CS Pandurii Targu Jiu'),
  ('CS Universitatea Craiova', 'Roménia', 'Universitatea Craiova | CS U Craiova | U Craiova | Știința Craiova | U CRAIOVA 1948 CLUB SPORTIV SA | CS Craiova | CSU Craiova'),
  ('CSM Ceahlăul Piatra Neamț', 'Roménia', null::text),
  ('CSM Politehnica Iași', 'Roménia', null::text),
  ('CSM Reșița', 'Roménia', 'CSM Școlar Reșița'),
  ('CSM Unirea Alba Iulia', 'Roménia', null::text),
  ('Daco-Getica', 'Roménia', 'Juventus București | Juventus Colentina | Juventus Colentina București | Daco-Getica București | ACS Daco-Getica București'),
  ('FC Argeș', 'Roménia', 'Dinamo Piteşti | Argeş Piteşti'),
  ('FC Astra Giurgiu', 'Roménia', 'Fotbal Club Astra Giurgiu'),
  ('FC Bihor Oradea', 'Roménia', null::text),
  ('FC Botoșani', 'Roménia', 'Fotbal Club Botoșani | FCBT'),
  ('FC Corvinul Hunedoara', 'Roménia', null::text),
  ('FC Dinamo Bucharest', 'Roménia', 'FC Dinamo București'),
  ('FC Dunărea Călărași', 'Roménia', 'Fotbal Club Dunărea Călărași | Dunărea Călărași | Dunarea Calarasi'),
  ('FC Hermannstadt', 'Roménia', null::text),
  ('FC Jiul Petroșani', 'Roménia', 'Jiul Petroșani'),
  ('FC Olt Scornicești', 'Roménia', null::text),
  ('FC Petrolul Ploiești', 'Roménia', 'Petrolul Ploiesti'),
  ('FC Rapid București', 'Roménia', 'FC Rapid 1923 | Vulturii Vișinii'),
  ('FC Ripensia Timișoara', 'Roménia', null::text),
  ('FC U Craiova 1948', 'Roménia', 'Fotbal Club U Craiova 1948 | FCU Craiova | FC Universitatea 1948'),
  ('FC Unirea Slobozia', 'Roménia', null::text),
  ('FC Unirea Urziceni', 'Roménia', 'Fotbal Club Unirea Urziceni'),
  ('FC Universitatea Cluj', 'Roménia', null::text),
  ('FC UTA Arad', 'Roménia', 'UTA Arad'),
  ('FC Voluntari', 'Roménia', null::text),
  ('FCSB', 'Roménia', 'Steaua Bucureşti | Steaua | Fotbal Club FCSB'),
  ('FK Csíkszereda', 'Roménia', 'Csíkszereda Miercurea Ciuc | Miercurea Ciuc'),
  ('SC Oțelul Galați', 'Roménia', 'ASC Oțelul Galați'),
  ('Sepsi OSK Sfântu Gheorghe', 'Roménia', 'Sepsi Sfântu Gheorghe | Sepsi OSK'),
  ('SSC Farul Constanța', 'Roménia', null::text),
  ('Venus București', 'Roménia', 'AS Venus București'),
  ('Amagaju', 'Ruanda', null::text),
  ('Armée Patriotique Rwandaise FC', 'Ruanda', 'Armée Patriotique Rwandaise F.C. | APR FC | APR FC Kigali | Armee Patriotique Rwandaise F.C. | Armee Patriotique Rwandaise FC | A.P.R.'),
  ('AS Kigali', 'Ruanda', 'Association Sportive de Kigali'),
  ('Electrogaz FC', 'Ruanda', null::text),
  ('Espoir FC', 'Ruanda', 'Espoir F.C.'),
  ('Etincelles FC', 'Ruanda', 'Etincelles F.C.'),
  ('Gicumbi FC', 'Ruanda', null::text),
  ('Gorilla FC', 'Ruanda', 'Gorilla F.C.'),
  ('Marines FC', 'Ruanda', null::text),
  ('Mukungwa', 'Ruanda', null::text),
  ('Mukura Victory Sports FC', 'Ruanda', 'Mukura Victory Sports F.C.'),
  ('Musanze FC', 'Ruanda', null::text),
  ('Panthères Noires', 'Ruanda', null::text),
  ('Police FC', 'Ruanda', 'Police F.C. | National Police FC'),
  ('Rayon Sports FC', 'Ruanda', 'Rayon Sports F.C. | Southern province,'),
  ('Rutsiro FC', 'Ruanda', 'Rutsiro Football Club'),
  ('SC Kiyovu Sports', 'Ruanda', 'S.C. Kiyovu Sports'),
  ('Baltika-BFU', 'Rússia', 'FC Baltika-2 Kaliningrad'),
  ('FC Akademiya Futbola Rostov-on-Don', 'Rússia', null::text),
  ('FC Akhmat Grozny', 'Rússia', 'FC Terek Grozny'),
  ('FC Akron Tolyatti', 'Rússia', null::text),
  ('FC Alania Vladikavkaz', 'Rússia', null::text),
  ('FC Amkar Perm', 'Rússia', null::text),
  ('FC Arsenal Tula', 'Rússia', 'Football Club Arsenal Tula'),
  ('FC Arsenal-2 Tula', 'Rússia', null::text),
  ('FC Astrakhan', 'Rússia', null::text),
  ('FC Avangard Kursk', 'Rússia', null::text),
  ('FC Avtodor Vladikavkaz', 'Rússia', null::text),
  ('FC Baikal Irkutsk', 'Rússia', null::text),
  ('FC Balashikha', 'Rússia', null::text),
  ('FC Baltika Kaliningrad', 'Rússia', null::text),
  ('FC Biolog-Novokubansk Progress', 'Rússia', null::text),
  ('FC Chayka Peschanokopskoye', 'Rússia', null::text),
  ('FC Chelyabinsk', 'Rússia', null::text),
  ('FC Chernomorets Novorossiysk', 'Rússia', null::text),
  ('FC Chertanovo Moscow', 'Rússia', null::text),
  ('FC Chita', 'Rússia', null::text),
  ('FC Dinamo Moscow', 'Rússia', 'FC Dinamo-Moskva | Dinamo Moscow'),
  ('FC Dnepr Smolensk', 'Rússia', null::text),
  ('FC Domodedovo Moscow', 'Rússia', null::text),
  ('FC Druzhba Maykop', 'Rússia', null::text),
  ('FC Dynamo Barnaul', 'Rússia', null::text),
  ('FC Dynamo Bryansk', 'Rússia', null::text),
  ('FC Dynamo Kirov', 'Rússia', null::text),
  ('FC Dynamo Makhachkala', 'Rússia', null::text),
  ('FC Dynamo Saint Petersburg', 'Rússia', 'FC Dinamo Saint Petersburg'),
  ('FC Dynamo Vladivostok', 'Rússia', null::text),
  ('FC Dynamo-2 Moscow', 'Rússia', null::text),
  ('FC Elista', 'Rússia', null::text),
  ('FC Energiya Volzhsky', 'Rússia', null::text),
  ('FC Fakel Voronezh', 'Rússia', 'Fakel Voronezh Logo'),
  ('FC Forte Taganrog', 'Rússia', null::text),
  ('FC Irtysh Omsk', 'Rússia', null::text),
  ('FC Iskra Novoaleksandrovsk', 'Rússia', null::text),
  ('FC Kaluga', 'Rússia', null::text),
  ('FC KAMAZ Naberezhnye Chelny', 'Rússia', null::text),
  ('FC Khimik Dzerzhinsk', 'Rússia', null::text),
  ('FC Khimik-Arsenal', 'Rússia', null::text),
  ('FC Khimik-Avgust', 'Rússia', null::text),
  ('FC Khimki', 'Rússia', null::text),
  ('FC Kolomna', 'Rússia', null::text),
  ('FC Kolos Krasnodar', 'Rússia', null::text),
  ('FC Krasnodar', 'Rússia', null::text),
  ('FC Krylia Sovetov Samara', 'Rússia', 'PFC Krylia Sovetov'),
  ('FC Kuban Holding', 'Rússia', null::text),
  ('FC Kuban-2 Krasnodar', 'Rússia', null::text),
  ('FC Leningradets Leningrad Oblast', 'Rússia', null::text),
  ('FC Leon Saturn', 'Rússia', 'FC Saturn Moscow Oblast'),
  ('FC Lokomotiv Moscow', 'Rússia', 'Lokomotiv Moscow'),
  ('FC Lokomotiv Nizhny Novgorod', 'Rússia', null::text),
  ('FC Luki-SKIF Velikiye Luki', 'Rússia', null::text),
  ('FC Mashuk-KMV Pyatigorsk', 'Rússia', null::text),
  ('FC Metallurg Lipetsk', 'Rússia', null::text),
  ('FC Murom', 'Rússia', null::text),
  ('FC MVO Moscow', 'Rússia', null::text),
  ('FC Neftekhimik Nizhnekamsk', 'Rússia', null::text),
  ('FC Neftyanik Uray', 'Rússia', null::text),
  ('FC Nizhny Novgorod', 'Rússia', 'FC Olimpiyets Nizhny Novgorod'),
  ('FC Nosta Novotroitsk', 'Rússia', null::text),
  ('FC Olimpia Volgograd', 'Rússia', null::text),
  ('FC Orenburg', 'Rússia', 'FC Gazovik Orenburg'),
  ('FC Peresvet Podolsk', 'Rússia', null::text),
  ('FC Petrotrest Saint Petersburg', 'Rússia', null::text),
  ('FC Rodina Moscow', 'Rússia', null::text),
  ('FC Rostov', 'Rússia', null::text),
  ('FC Rotor Volgograd', 'Rússia', 'Football Club Rotor Volgograd'),
  ('FC Rotor-2 Volgograd', 'Rússia', null::text),
  ('FC Rubin Yalta', 'Rússia', null::text),
  ('FC Ryazan', 'Rússia', null::text),
  ('FC Sakhalinets', 'Rússia', null::text),
  ('FC Salyut Belgorod', 'Rússia', null::text),
  ('FC Saturn-2 Moscow Region', 'Rússia', null::text),
  ('FC Shakhtyor Prokopyevsk', 'Rússia', null::text),
  ('FC Shinnik Yaroslavl', 'Rússia', null::text),
  ('FC Sibir', 'Rússia', 'FC Novosibirsk'),
  ('FC SKA Rostov-on-Don', 'Rússia', null::text),
  ('FC SKA-Energiya Khabarovsk', 'Rússia', null::text),
  ('FC SKChF Sevastopol', 'Rússia', null::text),
  ('FC Smolensk', 'Rússia', null::text),
  ('FC Sokol Saratov', 'Rússia', 'PFC Sokol'),
  ('FC Spartak Kostroma', 'Rússia', null::text),
  ('FC Spartak Shchyolkovo', 'Rússia', null::text),
  ('FC Spartak Tambov', 'Rússia', null::text),
  ('FC Spartak Tuymazy', 'Rússia', null::text),
  ('FC Spartak Yoshkar-Ola', 'Rússia', null::text),
  ('FC Spartak-2 Moscow', 'Rússia', 'Spartak 2'),
  ('FC Spartak-Peresvet Bryansk', 'Rússia', null::text),
  ('FC Strogino Moscow', 'Rússia', null::text),
  ('FC Syzran-2003', 'Rússia', null::text),
  ('FC Tekstilshchik Ivanovo', 'Rússia', null::text),
  ('FC Tekstilshchik Kamyshin', 'Rússia', null::text),
  ('FC Tom Tomsk', 'Rússia', null::text),
  ('FC Torpedo Armavir', 'Rússia', null::text),
  ('FC Torpedo Moscow', 'Rússia', null::text),
  ('FC Torpedo-ZIL Moscow', 'Rússia', null::text),
  ('FC Tuapse', 'Rússia', null::text),
  ('FC Tver', 'Rússia', null::text),
  ('FC Ufa', 'Rússia', null::text),
  ('FC Ural Yekaterinburg', 'Rússia', 'Football Club Ural Sverdlovsk Oblast | FC Ural Sverdlovsk Oblast | Ural Yekaterinburg'),
  ('FC Ural-2 Yekaterinburg', 'Rússia', null::text),
  ('FC Veles Moscow', 'Rússia', null::text),
  ('FC Vityaz Podolsk', 'Rússia', null::text),
  ('FC Volga Ulyanovsk', 'Rússia', null::text),
  ('FC Volgar Astrakhan', 'Rússia', null::text),
  ('FC Volgograd', 'Rússia', null::text),
  ('FC Volna Nizhny Novgorod Oblast', 'Rússia', 'FC Volna Kovernino'),
  ('FC Volochanin-Ratmir Vyshny Volochyok', 'Rússia', null::text),
  ('FC Yadro Saint-Petersburg', 'Rússia', null::text),
  ('FC Yenisey Krasnoyarsk', 'Rússia', null::text),
  ('FC Yenisey-2 Krasnoyarsk', 'Rússia', null::text),
  ('FC Yessentuki', 'Rússia', null::text),
  ('FC Zenit Penza', 'Rússia', null::text),
  ('FC Zenit Saint Petersburg', 'Rússia', 'FC Zenit | Zenit Saint Petersburg | Football Club Zenit | VC Zenit Saint Petersburg'),
  ('FC Zenit-Izhevsk Izhevsk', 'Rússia', null::text),
  ('FC Zhemchuzhina-Sochi', 'Rússia', null::text),
  ('FC Znamya Truda', 'Rússia', 'FC Znamya Truda Orekhovo-Zuyevo'),
  ('PFC CSKA Moscow', 'Rússia', null::text),
  ('PFC Kuban Krasnodar', 'Rússia', null::text),
  ('PFC Sochi', 'Rússia', 'FC Sochi'),
  ('PFC Spartak Nalchik', 'Rússia', null::text),
  ('Rubin Kazan', 'Rússia', 'FC Rubin Kazan'),
  ('Spartak Moscow', 'Rússia', 'FC Spartak Moscow'),
  ('Torpedo Olleart FC', 'Rússia', 'Football Club Torpedo Vladimir | Traktor'),
  ('ZFK Dynamo Moscow', 'Rússia', null::text),
  ('Zvezda', 'Rússia', null::text),
  ('Kiwi FC', 'Samoa', 'Kiwi F.C.'),
  ('Vaivase-tai', 'Samoa', null::text),
  ('AC Juvenes/Dogana', 'San Marino', 'A.C. Juvenes/Dogana'),
  ('AC Libertas', 'San Marino', 'A.C. Libertas | A C Libertas | A. C. Libertas'),
  ('AC Virtus', 'San Marino', 'A.C. Virtus'),
  ('FC Domagnano', 'San Marino', 'F.C. Domagnano'),
  ('FC Fiorentino', 'San Marino', 'F.C. Fiorentino'),
  ('gil paja', 'San Marino', 'los pajeros asociason'),
  ('San Marino Calcio', 'San Marino', 'Victor San Marino'),
  ('SC Faetano', 'San Marino', 'S.C. Faetano'),
  ('SP Cailungo', 'San Marino', 'S.P. Cailungo'),
  ('SP La Fiorita', 'San Marino', 'S.P. La Fiorita'),
  ('SS Cosmos', 'San Marino', 'S.S. Cosmos'),
  ('SS Folgore Falciano Calcio', 'San Marino', 'S.S. Folgore Falciano Calcio'),
  ('SS Murata', 'San Marino', 'S.S. Murata'),
  ('SS Pennarossa', 'San Marino', 'S.S. Pennarossa'),
  ('SS San Giovanni', 'San Marino', 'S.S. San Giovanni'),
  ('Tre Fiori Football Club', 'San Marino', 'Societa Polisportiva Tre Fiori'),
  ('La Passe FC', 'Seicheles', 'La Passe Football Club'),
  ('Saint Louis Suns United', 'Seicheles', null::text),
  ('St Michel United FC', 'Seicheles', null::text),
  ('AS Douanes', 'Senegal', null::text),
  ('AS Pikine', 'Senegal', null::text),
  ('ASC HLM', 'Senegal', null::text),
  ('ASC Jaraaf', 'Senegal', null::text),
  ('ASC Jeanne d''Arc', 'Senegal', null::text),
  ('ASC Port Autonome', 'Senegal', 'UCST Port Autonome | Port Autonome'),
  ('ASC Yakaar', 'Senegal', null::text),
  ('ASC Yeggo', 'Senegal', null::text),
  ('ASCE La Linguère', 'Senegal', 'ASCE La Linguere'),
  ('ASFA Dakar', 'Senegal', null::text),
  ('Association sportive Cambérène', 'Senegal', 'AS Cambérène'),
  ('Association sportive et culturelle SONACOS', 'Senegal', 'ASC SONACOS'),
  ('Casa Sports', 'Senegal', null::text),
  ('Compagnie Sucrière Sénégalaise', 'Senegal', 'Compagnie Sucriere Senegalaise | ASC CS Sucrière'),
  ('Dakar UC', 'Senegal', null::text),
  ('Diambars FC', 'Senegal', null::text),
  ('Génération Foot', 'Senegal', null::text),
  ('Guédiawaye FC', 'Senegal', 'Guediawaye FC'),
  ('Niary Tally', 'Senegal', null::text),
  ('Olympique de Ngor', 'Senegal', null::text),
  ('Stade Mbour', 'Senegal', null::text),
  ('Teungueth FC', 'Senegal', null::text),
  ('Touré Kunda Footpro', 'Senegal', 'Toure Kunda Footpro | Mbour Petite-Côte FC'),
  ('US Gorée', 'Senegal', 'US Goree'),
  ('US Ouakam', 'Senegal', null::text),
  ('Diamond Stars FC', 'Serra Leoa', 'Diamond Stars F.C. | Diamond Stars Football Club'),
  ('East End Lions FC', 'Serra Leoa', 'East End Lions F.C.'),
  ('FC Kallon', 'Serra Leoa', null::text),
  ('FK BASK', 'Sérvia', 'FK BASK TEK'),
  ('FK Bečej', 'Sérvia', null::text),
  ('FK Bežanija', 'Sérvia', null::text),
  ('FK Bor', 'Sérvia', 'FK Bor 1919'),
  ('FK Borac Čačak', 'Sérvia', null::text),
  ('FK BSK Borča', 'Sérvia', null::text),
  ('FK Budućnost Banatski Dvor', 'Sérvia', null::text),
  ('FK Crvena zvezda', 'Sérvia', 'Crvena zvezda | F.K. Crvena zvezda | Red Star Belgrade | FC Red Star | F.C. Red Star | FC Red Star Belgrade | Red Star of Belgrade'),
  ('FK ČSK Čelarevo', 'Sérvia', 'FK ČSK Pivara | CSK Pivara'),
  ('FK Čukarički', 'Sérvia', null::text),
  ('FK Dinamo Vranje', 'Sérvia', null::text),
  ('FK Donji Srem', 'Sérvia', null::text),
  ('FK Inđija', 'Sérvia', null::text),
  ('FK Jagodina', 'Sérvia', 'Fudbalski klub Jagodina'),
  ('FK Javor Ivanjica', 'Sérvia', 'Fudbalski klub Javor Ivanjica | Fk Javor Matis'),
  ('FK Jedinstvo Ub', 'Sérvia', null::text),
  ('FK Kolubara', 'Sérvia', 'Fudbalski klub Kolubara'),
  ('FK Mačva Šabac', 'Sérvia', null::text),
  ('FK Metalac Gornji Milanovac', 'Sérvia', null::text),
  ('FK Mladost Apatin', 'Sérvia', 'OFK Mladost'),
  ('FK Mladost Lučani', 'Sérvia', null::text),
  ('FK Napredak Kruševac', 'Sérvia', null::text),
  ('FK Naša Krila Zemun', 'Sérvia', 'FK Naša krila'),
  ('FK Novi Pazar', 'Sérvia', 'Fudbalski klub Novi Pazar'),
  ('FK Obilić', 'Sérvia', 'FK Obilić Belgrade'),
  ('FK Partizan', 'Sérvia', 'Partizan | Partizan Belgrade'),
  ('FK Proleter Novi Sad', 'Sérvia', null::text),
  ('FK Proleter Zrenjanin', 'Sérvia', null::text),
  ('FK Rad', 'Sérvia', 'FK Rad Belgrade'),
  ('FK Radnički 1923', 'Sérvia', 'FK Radnički Kragujevac'),
  ('FK Radnički Beograd', 'Sérvia', 'FK Radnički Novi Beograd'),
  ('FK Radnički Niš', 'Sérvia', null::text),
  ('FK Radnički Obrenovac', 'Sérvia', null::text),
  ('FK Radnik Surdulica', 'Sérvia', null::text),
  ('FK Sloboda Užice', 'Sérvia', null::text),
  ('FK Smederevo 1924', 'Sérvia', 'Fudbalski klub Smederevo 1924'),
  ('FK Spartak Subotica', 'Sérvia', null::text),
  ('FK Srem', 'Sérvia', null::text),
  ('FK Teleoptik', 'Sérvia', null::text),
  ('FK TSC', 'Sérvia', 'Fudbalski klub TSC | FK TSC Bačka Topola | TSC Bačka Topola | FK Bačka Topola | Fudbalski Klub Topolya Sport Club | TSC | TSC Backa Topola'),
  ('FK Vojvodina', 'Sérvia', 'FK Vojvodina Novi Sad | Fudbalski klub Vojvodina'),
  ('FK Voždovac', 'Sérvia', null::text),
  ('FK Železničar Pančevo', 'Sérvia', null::text),
  ('FK Zemun', 'Sérvia', 'Fudbalski klub Zemun'),
  ('FK Zlatibor Čajetina', 'Sérvia', null::text),
  ('OFK Bačka', 'Sérvia', 'FK Bačka Bačka Palanka'),
  ('OFK Beograd', 'Sérvia', 'OFK Belgrade'),
  ('RFK Novi Sad 1921', 'Sérvia', null::text),
  ('Albirex Niigata FC', 'Singapura', null::text),
  ('Balestier Khalsa FC', 'Singapura', 'Balestier Khalsa Football Club'),
  ('Étoile FC', 'Singapura', 'Etoile FC'),
  ('Geylang United FC', 'Singapura', 'Geylang International Football Club | Geylang International FC'),
  ('Hougang United FC', 'Singapura', 'Hougang United Football Club'),
  ('Lion City Sailors FC', 'Singapura', 'Lion City Sailors F.C. | Home United F.C. | Police SA'),
  ('Sinchi FC', 'Singapura', null::text),
  ('Super Reds FC', 'Singapura', null::text),
  ('Tampines Rovers FC', 'Singapura', 'BG Tampines Rovers FC'),
  ('Tanjong Pagar United FC', 'Singapura', 'Tanjong Pagar United'),
  ('Warriors FC', 'Singapura', 'Warriors F.C. | Warriors Football Club'),
  ('Young Lions', 'Singapura', 'Young Lions FC | Garena Young Lions Football Club'),
  ('Afrin SC', 'Síria', null::text),
  ('Ahli of Aleppo SC', 'Síria', 'Al Ittihad of Aleppo | Al-Ittihad Sports Club of Aleppo'),
  ('Al-Fotuwa SC', 'Síria', null::text),
  ('Al-Herafyeen SC', 'Síria', null::text),
  ('Al-Horgelah SC', 'Síria', null::text),
  ('Al-Jazeera SC Hasakah', 'Síria', null::text),
  ('Al-Karamah SC', 'Síria', 'Al-Karamah Sporting Club | Al-Karamah Sports Club'),
  ('Al-Muhafaza', 'Síria', null::text),
  ('Al-Sahel SC', 'Síria', null::text),
  ('Al-Shorta SC', 'Síria', null::text),
  ('Al-Wahda SC Damascus', 'Síria', 'Al-Wahda Sports Club'),
  ('Al-Wathba SC', 'Síria', null::text),
  ('Al-wathbaa', 'Síria', 'Al-wathba Sports Club'),
  ('Baniyas Refinery SC', 'Síria', null::text),
  ('Damascus Al-Ahli Club', 'Síria', null::text),
  ('Hurriya SC', 'Síria', null::text),
  ('Hutteen SC', 'Síria', 'Hutteen Sporting Club'),
  ('Jableh SC', 'Síria', 'Jableh Sporting Club'),
  ('Nawair SC', 'Síria', null::text),
  ('Taliya SC', 'Síria', null::text),
  ('Tishreen SC', 'Síria', null::text),
  ('AC Mogadiscio', 'Somália', null::text),
  ('Alba CF', 'Somália', null::text),
  ('Badbaado', 'Somália', null::text),
  ('Brothers Somali Fc', 'Somália', 'Naadiga Walaalaha Soomaliyeed'),
  ('Dekedaha FC', 'Somália', null::text),
  ('Elman FC', 'Somália', null::text),
  ('Feynuus FC', 'Somália', null::text),
  ('Gaadiidka FC', 'Somália', null::text),
  ('Jamhuuriya TB', 'Somália', null::text),
  ('Jeenyo United FC', 'Somália', 'Jeenyo United F.C.'),
  ('Marine Club FC', 'Somália', 'Marine Club'),
  ('Mogadishu City Club', 'Somália', 'Banaadir Telecom FC | Banaadir SC | Banaadir Sports Club | Banaadir Telecom Football Club'),
  ('Mogadishu Municipality', 'Somália', null::text),
  ('Savana FC', 'Somália', null::text),
  ('SITT Daallo', 'Somália', null::text),
  ('Somali Police FC', 'Somália', null::text),
  ('Super Shell', 'Somália', null::text),
  ('Al Ahli Club (Merowe)', 'Sudão', 'Al Ahli Merowe | Al-Ahli Club Merowe | Al Ahly Club (Merowe) | Al-Ahly SC (Merowe)'),
  ('Al Ahli SC (Khartoum)', 'Sudão', null::text),
  ('Al Mirghani ESC', 'Sudão', null::text),
  ('Al Nile SC', 'Sudão', null::text),
  ('Al Rabita Kosti', 'Sudão', null::text),
  ('Al-Ahli Club (Atbara)', 'Sudão', null::text),
  ('Al-Ahli SC', 'Sudão', null::text),
  ('Al-Ahly Shendi', 'Sudão', null::text),
  ('Alamal SC Atbara', 'Sudão', null::text),
  ('Al-Hilal Club', 'Sudão', 'Al-Hilal (Omdurman)'),
  ('Al-Hilal SC (Al-Ubayyid)', 'Sudão', null::text),
  ('Al-Hilal SC Kadougli', 'Sudão', null::text),
  ('Al-Ittihad SC', 'Sudão', null::text),
  ('Al-Merreikh Al-Thagher', 'Sudão', 'Merreikh Port Sudan'),
  ('Al-Merreikh SC (Al-Fasher)', 'Sudão', null::text),
  ('Al-Merrikh SC', 'Sudão', null::text),
  ('Al-Mourada SC', 'Sudão', 'Al-Mawrada (Omdurman)'),
  ('Al-Nsoor', 'Sudão', null::text),
  ('Al-Shamali AC', 'Sudão', null::text),
  ('Hay el-Arab SC', 'Sudão', null::text),
  ('Jazeerat Al-Feel SC', 'Sudão', null::text),
  ('Khartoum NC', 'Sudão', null::text),
  ('Wad Nobawi SC', 'Sudão', 'Wad Nubawi'),
  ('AFC Eskilstuna', 'Suécia', 'Athletic Football Club Eskilstuna'),
  ('AIK Fotboll', 'Suécia', 'AIK Stockholm | AIK Solna'),
  ('Ängelholms FF', 'Suécia', 'ÄFF'),
  ('Assyriska FF', 'Suécia', null::text),
  ('Assyriska IK', 'Suécia', null::text),
  ('Åtvidabergs FF', 'Suécia', null::text),
  ('BK Häcken', 'Suécia', 'Häcken | Häcken Gothenburg | Bollklubben Häcken | Getingarna'),
  ('Brynäs IF', 'Suécia', 'BIF | Brynäs Idrottsförening'),
  ('Carlstad United BK', 'Suécia', null::text),
  ('Dalkurd FF', 'Suécia', 'Dalkurd F.F. | DFF'),
  ('Degerfors IF', 'Suécia', 'Degerfors I.F.'),
  ('Djurgårdens IF Fotboll', 'Suécia', null::text),
  ('Falkenbergs FF', 'Suécia', null::text),
  ('FC Rosengård 1917', 'Suécia', 'FCR'),
  ('GAIS', 'Suécia', 'Göteborgs Atlet- och Idrottssällskap'),
  ('Gefle IF', 'Suécia', 'Gefle Idrottsförening'),
  ('GIF Sundsvall', 'Suécia', 'G.I.F. Sundsvall | Giffarna | Norrlandslaget'),
  ('Halmstads BK', 'Suécia', 'HBK | Halmstads Bollklubb'),
  ('Hammarby Fotboll', 'Suécia', 'Hammarby IF | Bajen'),
  ('Helsingborgs IF', 'Suécia', 'HIF'),
  ('Husqvarna FF', 'Suécia', 'Huskvarna FF | HFF'),
  ('IF Brommapojkarna', 'Suécia', 'BP | IF BP'),
  ('IF Elfsborg', 'Suécia', 'IFE'),
  ('IF Väster', 'Suécia', null::text),
  ('IFK Eskilstuna', 'Suécia', null::text),
  ('IFK Göteborg', 'Suécia', 'Blåvitt | Änglarna | IFK Göteborg Fotboll'),
  ('IFK Haninge/Brandbergen', 'Suécia', null::text),
  ('IFK Luleå', 'Suécia', 'Luleåkamraterna'),
  ('IFK Malmö', 'Suécia', 'I.F.K. Malmö'),
  ('IFK Norrköping', 'Suécia', 'Idrottsföreningen kamraterna Norrköping | Snoka'),
  ('IFK Sundsvall', 'Suécia', 'Sundsvallskamraterna'),
  ('IFK Värnamo', 'Suécia', null::text),
  ('IK Brage', 'Suécia', 'I.K. Brage | IKB | Idrottsklubben Brage'),
  ('IK Frej', 'Suécia', null::text),
  ('IK Oddevold', 'Suécia', 'IKO'),
  ('IK Sirius FK', 'Suécia', null::text),
  ('IK Sleipner', 'Suécia', null::text),
  ('Jönköpings Södra IF', 'Suécia', null::text),
  ('Kalmar FF', 'Suécia', 'KFF'),
  ('KSF Prespa Birlik', 'Suécia', null::text),
  ('Landskrona BoIS', 'Suécia', 'Landskrona B.o.I.S. | Landskrona Boll och Idrottssällskap | BoIS'),
  ('Ljungskile SK', 'Suécia', 'LSK'),
  ('Lunds BK', 'Suécia', null::text),
  ('Malmö FF', 'Suécia', 'Malmö F.F. | MFF | Malmo FF | Malmo F.F. | Malmö Fotbollförening | Malmo Fotbollforening'),
  ('Mjällby AIF', 'Suécia', 'MAIF'),
  ('Norrby IF', 'Suécia', null::text),
  ('Nyköpings BIS', 'Suécia', null::text),
  ('Örebro SK', 'Suécia', null::text),
  ('Örgryte IS', 'Suécia', 'Orgryte IS | Örgryte I.S. | ÖIS'),
  ('Östers IF', 'Suécia', 'Osters IF | Öster | ÖIF | Östers FF | ÖFF'),
  ('Östersunds FK', 'Suécia', 'Ostersunds FK | OFK Ostersund | ÖFK | Östersunds fotbollsklubb | Östersund'),
  ('Qviding FIF', 'Suécia', 'Qviding Fräntorps Idrottsförening | Fräntorps IF'),
  ('Råå IF', 'Suécia', null::text),
  ('Sandvikens IF', 'Suécia', null::text),
  ('Selånger FK', 'Suécia', null::text),
  ('Skövde AIK', 'Suécia', null::text),
  ('Sollentuna FK', 'Suécia', null::text),
  ('Syrianska FC', 'Suécia', 'Syrianska F.C. | Syrianska Football Club | Suryoyo SK'),
  ('Trelleborgs FF', 'Suécia', 'TFF'),
  ('Tvååkers IF', 'Suécia', null::text),
  ('Umeå FC', 'Suécia', null::text),
  ('Utsiktens BK', 'Suécia', null::text),
  ('Vänersborgs IF', 'Suécia', null::text),
  ('Varbergs BoIS FC', 'Suécia', null::text),
  ('Vasalunds IF', 'Suécia', null::text),
  ('Västerås SK Fotboll', 'Suécia', null::text),
  ('AC Bellinzona', 'Suíça', null::text),
  ('Anglo-American Club Zürich', 'Suíça', null::text),
  ('BSC Old Boys', 'Suíça', 'Basler Sportclub Old Boys | Old Boys Basel'),
  ('BSC Young Boys', 'Suíça', 'Berner Sport Club Young Boys | Young Boys | B.S.C. Young Boys | BSCYB | B.S.C.Y.B. | BSC YB | B.S.C. Y.B.'),
  ('CS Chênois', 'Suíça', 'CS Chenois'),
  ('Étoile Carouge FC', 'Suíça', 'Etoile Carouge FC'),
  ('FC Aarau', 'Suíça', 'Fussballclub Aarau 1902'),
  ('FC Baden', 'Suíça', null::text),
  ('FC Balzers', 'Suíça', null::text),
  ('FC Basel', 'Suíça', 'FCB | F.C.B. | FCB 1893 | Football Club Basel 1893 | Football Club Basel | FCB1893 | FC Basel 1893'),
  ('FC Baulmes', 'Suíça', null::text),
  ('FC Bern', 'Suíça', null::text),
  ('FC Biel-Bienne', 'Suíça', 'FC Biel/Bienne | Fussball Club Biel/Bienne'),
  ('FC Bulle', 'Suíça', null::text),
  ('FC Chiasso', 'Suíça', null::text),
  ('FC Concordia Basel', 'Suíça', 'Fussball Club Concordia Basel'),
  ('FC Fribourg', 'Suíça', null::text),
  ('FC Gossau', 'Suíça', 'Fussball Club Gossau'),
  ('FC Grenchen', 'Suíça', null::text),
  ('FC La Chaux-de-Fonds', 'Suíça', 'Football Club La Chaux-de-Fonds'),
  ('FC Lausanne-Sport', 'Suíça', 'F.C. Lausanne-Sport | Lausanne-Sport'),
  ('FC Le Mont', 'Suíça', null::text),
  ('FC Locarno', 'Suíça', 'Football Club Locarno'),
  ('FC Lugano', 'Suíça', 'Football Club Lugano | F.C. Lugano | Lugano Football Club'),
  ('FC Luzern', 'Suíça', 'Fussball Club Luzern | F.C. Luzern'),
  ('FC Nordstern Basel', 'Suíça', null::text),
  ('FC Rapperswil-Jona', 'Suíça', 'Fussball Club Rapperswil-Jona'),
  ('FC Schaffhausen', 'Suíça', 'Fussball Club Schaffhausen'),
  ('FC Sion', 'Suíça', 'Football Club Sion | Football Club of Sion | F.C. Sion | FCSion'),
  ('FC St. Gallen', 'Suíça', 'Fussballclub St. Gallen 1879 | FC St. Gallen 1879 | F.C. St. Gallen 1879 | F.C. St. Gallen'),
  ('FC Stade Lausanne-Ouchy', 'Suíça', null::text),
  ('FC Stade Nyonnais', 'Suíça', 'Football Club Stade Nyonnais'),
  ('FC Thun', 'Suíça', null::text),
  ('FC Wettingen', 'Suíça', null::text),
  ('FC Wil 1900', 'Suíça', 'Fussbal Club Wil | FC Wil'),
  ('FC Winterthur', 'Suíça', 'Fussball Club Winterthur'),
  ('FC Wohlen', 'Suíça', null::text),
  ('FC Zürich', 'Suíça', 'FC Zurich | F.C. Zürich | F.C. Zurich'),
  ('Grasshopper Club Zürich', 'Suíça', 'Grasshoppers | GC | Grasshopper Club Zurich | Grasshoppers Zürich | Grasshoppers Zurich'),
  ('Neuchâtel Xamax FCS', 'Suíça', 'Neuchatel Xamax | Neuchâtel Xamax | NeuchatelXamax | Neuchâtel Xamax F.C.S. | Xamax'),
  ('SC Brühl', 'Suíça', null::text),
  ('SC Kriens', 'Suíça', null::text),
  ('SC Veltheim', 'Suíça', null::text),
  ('SC Young Fellows Juventus', 'Suíça', null::text),
  ('Servette FC', 'Suíça', 'Servette F.C. | Servette Football Club | Servette'),
  ('Yverdon-Sport FC', 'Suíça', 'Yverdon FC | Yverdon Sport | Yverdon Sport Football Club | Yverdon Sport FC | Yverdon Sport F.C. | Yverdon-Sport F.C.'),
  ('Zug 94', 'Suíça', null::text),
  ('Inter Moengotapoe', 'Suriname', null::text),
  ('SV Robinhood', 'Suriname', 'S.V. Robinhood'),
  ('SV Transvaal', 'Suriname', 'S.V. Transvaal'),
  ('Bangkok United FC', 'Tailândia', 'Bangkok United F.C. | Bangkok United'),
  ('BBCU FC', 'Tailândia', 'BBCU F.C.'),
  ('BG Pathum United FC', 'Tailândia', 'BG Pathum United F.C. | Bangkok Glass F.C.'),
  ('Buriram United FC', 'Tailândia', 'Buriram United F.C.'),
  ('Chainat Hornbill FC', 'Tailândia', 'Chainat Hornbill F.C. | Chainat Hornbill Football Club'),
  ('Chiangmai United FC', 'Tailândia', 'Chiangmai United F.C. | JL Chiangmai United F.C.'),
  ('Chiangrai United FC', 'Tailândia', 'Chiangrai United F.C. | Chiangrai United Football Club'),
  ('Chonburi FC', 'Tailândia', 'Chonburi F.C.'),
  ('Jumpasri United FC', 'Tailândia', 'Jumpasri United F.C.'),
  ('Muangthong United FC', 'Tailândia', 'Muangthong United F.C.'),
  ('Nakhon Ratchasima FC', 'Tailândia', 'Nakhon Ratchasima F.C. | Nakhon Ratchasima Football Club'),
  ('Pattaya United FC', 'Tailândia', 'Pattaya United F.C. | Samut Prakan City F.C. | Pattaya United Football Club'),
  ('Police Tebrau FC', 'Tailândia', 'Police Tebrau F.C. | BEC Tero Sasana Football Club | BEC Tero Sasana F.C.'),
  ('Port FC', 'Tailândia', 'Port F.C. | Singhtarua F.C.'),
  ('Prachuap FC', 'Tailândia', 'Prachuap F.C. | PT Prachuap F.C.'),
  ('Rasisalai United FC', 'Tailândia', 'Rasisalai United F.C.'),
  ('Ratchaburi Mitr Phol FC', 'Tailândia', 'Ratchaburi Mitr Phol F.C. | Ratchaburi Football Club | Ratchaburi F.C.'),
  ('Rayong FC', 'Tailândia', 'Rayong F.C.'),
  ('Samut Prakan City FC', 'Tailândia', 'Samut Prakan City F.C.'),
  ('Samut Songkhram FC', 'Tailândia', 'Samut Songkhram F.C.'),
  ('Sisaket FC', 'Tailândia', 'Sisaket F.C.'),
  ('Sukhothai FC', 'Tailândia', 'Sukhothai F.C.'),
  ('Suphanburi FC', 'Tailândia', 'Suphanburi F.C. | Suphanburi Football Club | Suphanburi'),
  ('Trat FC', 'Tailândia', 'Trat F.C. | Trat Football Club'),
  ('Ubon UMT United FC', 'Tailândia', 'Ubon UMT United F.C. | Ubon UMT United Football Club'),
  ('Uthai Thani FC', 'Tailândia', 'Uthai Thani F.C.'),
  ('Wuachon United FC', 'Tailândia', 'Wuachon United F.C.'),
  ('Taichung Futuro FC', 'Taiwan', 'Taichung Futuro F.C. | Taichung Futuro Football Academy'),
  ('Tainan City FC', 'Taiwan', 'Tainan City F.C. | Taiwan Steel Group | Taiwan Steel Group FC | Taiwan Steel Group F.C. | Tainan City Taiwan Steel'),
  ('Taiwan Power Company FC', 'Taiwan', 'Taiwan Power Company F.C. | Taipower | Taipower FC'),
  ('Tatung FC', 'Taiwan', 'Tatung F.C. | Leopard Cat F.C.'),
  ('Dynamo Dushanbe', 'Tajiquistão', null::text),
  ('Energetik Dushanbe', 'Tajiquistão', 'Barķi Toçik | Barki Tajik | Barqi Tojik'),
  ('FC Panjshir', 'Tajiquistão', null::text),
  ('FK Daleron-Uroteppa', 'Tajiquistão', null::text),
  ('FK Istaravshan', 'Tajiquistão', null::text),
  ('FK Khujand', 'Tajiquistão', null::text),
  ('FK Spitamen', 'Tajiquistão', null::text),
  ('Guardia Dushanbe', 'Tajiquistão', null::text),
  ('Hima Dushanbe', 'Tajiquistão', null::text),
  ('Istiqlol Dushanbe', 'Tajiquistão', null::text),
  ('Khatlon Qurghonteppa', 'Tajiquistão', 'FC Vakhsh'),
  ('Khayr Vahdat FK', 'Tajiquistão', null::text),
  ('Khosilot Farkhor', 'Tajiquistão', null::text),
  ('Kuktosh Rudaki', 'Tajiquistão', null::text),
  ('Olimi Karimzod Mastchoh', 'Tajiquistão', null::text),
  ('Parvoz Bobojon Ghafurov', 'Tajiquistão', null::text),
  ('Ravshan Kulob', 'Tajiquistão', null::text),
  ('Saroykamar Panj', 'Tajiquistão', null::text),
  ('Shodmon Ghissar', 'Tajiquistão', null::text),
  ('Tajik Telecom Qurghonteppa', 'Tajiquistão', null::text),
  ('Zarafshon Pendjikent', 'Tajiquistão', null::text),
  ('African Lyon FC', 'Tanzânia', 'African Lyon F.C. | African Lyon'),
  ('African Sports', 'Tanzânia', 'African Sports Club'),
  ('Alliance Schools FC', 'Tanzânia', null::text),
  ('Azam FC', 'Tanzânia', 'Azam F.C.'),
  ('Bandari FC', 'Tanzânia', 'Bandari F.C.'),
  ('Coastal Union', 'Tanzânia', null::text),
  ('JKT Mgambo', 'Tanzânia', null::text),
  ('JKT Oljoro FC', 'Tanzânia', null::text),
  ('JKT Ruvu Stars', 'Tanzânia', null::text),
  ('Kagera Sugar FC', 'Tanzânia', null::text),
  ('KenGold FC', 'Tanzânia', null::text),
  ('Kinondoni Municipal Council F. C.', 'Tanzânia', null::text),
  ('Maji Maji FC', 'Tanzânia', null::text),
  ('Mbao FC', 'Tanzânia', null::text),
  ('Mbeya City FC', 'Tanzânia', 'Mbeya City F.C.'),
  ('Moro United FC', 'Tanzânia', 'Moro United F.C.'),
  ('Mtibwa Sugar FC', 'Tanzânia', 'Mtibwa Sugar F.C.'),
  ('Ndanda FC', 'Tanzânia', 'Ndanda F.C.'),
  ('Pan African FC', 'Tanzânia', null::text),
  ('Polisi Dodoma', 'Tanzânia', null::text),
  ('Polisi Morogoro', 'Tanzânia', null::text),
  ('Prisons FC (Tanzania)', 'Tanzânia', 'Tanzania Prisons S.C'),
  ('Rhino Rangers FC', 'Tanzânia', 'Rhino Rangers F.C.'),
  ('Ruvu Shooting', 'Tanzânia', null::text),
  ('Simba Sports Club', 'Tanzânia', null::text),
  ('Singida Fountain Gate FC', 'Tanzânia', 'Singida Fountain Gate F.C.'),
  ('Stand United FC', 'Tanzânia', 'Stand United F.C.'),
  ('Tabora United', 'Tanzânia', 'Kilimanjaro Talented Youth Centre | Kitayosce'),
  ('Toto African', 'Tanzânia', 'Toto African SC'),
  ('Villa Squad', 'Tanzânia', null::text),
  ('Young Africans SC', 'Tanzânia', 'Young Africans S.C. | Young Africans Sports Club | Yanga | Timu ya wananchi | Yanga SC | Young africans S.C | Watoto wa Jangwani'),
  ('Karketu Dili', 'Timor-Leste', null::text),
  ('Dynamic Togolais', 'Togo', null::text),
  ('Étoile Filante (Lomé)', 'Togo', 'Etoile Filante de Lomé | Étoile filante de Lomé | Etoile Filante de Lome | Etoile filante | Etoile Filante (Lome)'),
  ('Kozah Football Club Sports Association', 'Togo', 'ASKO F.C.'),
  ('Central FC', 'Trindade e Tobago', 'Central F.C. | Central Football Club'),
  ('Club Sando FC', 'Trindade e Tobago', 'Club Sando F.C. | Club Sando Football Club'),
  ('Defence Force FC', 'Trindade e Tobago', 'Defence Force F.C.'),
  ('Joe Public FC', 'Trindade e Tobago', 'Joe Public F.C.'),
  ('La Horquetta Rangers FC', 'Trindade e Tobago', 'La Horquetta Rangers F.C. | St. Ann''s Rangers'),
  ('Ma Pau SC', 'Trindade e Tobago', null::text),
  ('Morvant Caledonia United', 'Trindade e Tobago', 'Caledonia AIA'),
  ('North East Stars', 'Trindade e Tobago', 'North East Stars Football Club'),
  ('Point Fortin Civic FC', 'Trindade e Tobago', 'Point Fortin Civic F.C. | Point Fortin Civic Football Club'),
  ('Police FC', 'Trindade e Tobago', 'Police F.C.'),
  ('San Juan Jabloteh', 'Trindade e Tobago', null::text),
  ('T&TEC SC', 'Trindade e Tobago', null::text),
  ('W Connection FC', 'Trindade e Tobago', 'W Connection F.C.'),
  ('AS Gabès', 'Tunísia', 'AS Gabes'),
  ('AS Marsa', 'Tunísia', null::text),
  ('AS Rejiche', 'Tunísia', null::text),
  ('CA Bizertine', 'Tunísia', null::text),
  ('Club Africain', 'Tunísia', null::text),
  ('CS Hammam-Lif', 'Tunísia', null::text),
  ('CS Sfaxien', 'Tunísia', null::text),
  ('EGS Gafsa', 'Tunísia', null::text),
  ('EO Sidi Bouzid', 'Tunísia', null::text),
  ('ES Beni-Khalled', 'Tunísia', null::text),
  ('ES Hammam-Sousse', 'Tunísia', null::text),
  ('ES Zarzis', 'Tunísia', null::text),
  ('Espérance Sportive de Tunis', 'Tunísia', 'EST | ES Tunis | Espérance Tunis | Espérance de Tunis'),
  ('Etoile Sportive de Metlaoui', 'Tunísia', 'Étoile Sportive de Métlaoui | ES Métlaoui'),
  ('Étoile Sportive du Sahel', 'Tunísia', 'ES Sahel | Etoile du Sahel'),
  ('JS Kairouan', 'Tunísia', null::text),
  ('Olympique Béja', 'Tunísia', 'Olympique Beja'),
  ('Sfax Railways Sports', 'Tunísia', null::text),
  ('Stade Gabèsien', 'Tunísia', 'Stade Gabesien'),
  ('Stade Tunisien', 'Tunísia', 'Stade'),
  ('US Ben Guerdane', 'Tunísia', null::text),
  ('US Monastir', 'Tunísia', null::text),
  ('US Tataouine', 'Tunísia', null::text),
  ('FC Ahal', 'Turquemenistão', null::text),
  ('FC Altyn Asyr', 'Turquemenistão', null::text),
  ('FC Aşgabat', 'Turquemenistão', null::text),
  ('FC Balkan', 'Turquemenistão', 'Balkan FK | Nebitçi Football Team'),
  ('FC Daşoguz', 'Turquemenistão', null::text),
  ('FC Energetik Türkmebaşy', 'Turquemenistão', null::text),
  ('FC Gara Altyn', 'Turquemenistão', null::text),
  ('FC Lebap', 'Turquemenistão', null::text),
  ('FC Merw', 'Turquemenistão', null::text),
  ('FC Şagadam', 'Turquemenistão', null::text),
  ('FC Talyp Sporty', 'Turquemenistão', null::text),
  ('FK Arkadag', 'Turquemenistão', null::text),
  ('HTTU Aşgabat', 'Turquemenistão', null::text),
  ('Köpetdag Aşgabat', 'Turquemenistão', null::text),
  ('Nisa Aşgabat', 'Turquemenistão', null::text),
  ('1461 Trabzon', 'Turquia', null::text),
  ('Adana Demirspor', 'Turquia', null::text),
  ('Adanaspor', 'Turquia', null::text),
  ('Akhisar Belediyespor', 'Turquia', 'Akhisar Belediye ve Gençlik Spor | Akhisarspor | Akhisar Belediye Gençlik ve Spor Kulübü'),
  ('Alanyaspor', 'Turquia', null::text),
  ('Altay SK', 'Turquia', 'Altay S.K.'),
  ('Altınordu FK', 'Turquia', 'Altınordu F.K.'),
  ('Amed SFK', 'Turquia', 'Amed S.F.K. | Diyarbakır Büyükşehir Belediyespor'),
  ('Ankara Keçiörengücü SK', 'Turquia', 'Ankara Keçiörengücü S.K. | Hacettepe Gençlik Kulübü'),
  ('Ankaraspor', 'Turquia', 'Osmanlıspor'),
  ('Antalyaspor', 'Turquia', 'Antalyaspor Kulübü'),
  ('Bakırköyspor', 'Turquia', null::text),
  ('Balıkesirspor', 'Turquia', null::text),
  ('Bandırmaspor', 'Turquia', null::text),
  ('Beşiktaş JK', 'Turquia', 'Beşiktaş J.K. | BJK | Besiktas | Beşiktaş Jimnastik Kulübü | Besiktas J.K. | Besiktas JK | Beşiktaş | Besiktas Jimnastik Kulubu | B.J.K.'),
  ('Bodrum FK', 'Turquia', 'Bodrumspor'),
  ('Boluspor', 'Turquia', null::text),
  ('Bucaspor', 'Turquia', null::text),
  ('Bursaspor', 'Turquia', null::text),
  ('Çaykur Rizespor', 'Turquia', 'Caykur Rizespor | Rizespor'),
  ('Çorum FK', 'Turquia', null::text),
  ('Denizlispor', 'Turquia', null::text),
  ('Elazığspor', 'Turquia', 'Çimentaş Elazığspor'),
  ('Erzurumspor FK', 'Turquia', 'Erzurumspor F.K.'),
  ('Eskişehirspor', 'Turquia', null::text),
  ('Eyüpspor', 'Turquia', null::text),
  ('Fatih Karagümrük SK', 'Turquia', 'Fatih Karagümrük S.K. | Centone Karagümrük'),
  ('Fenerbahçe Istanbul', 'Turquia', 'Fenerbahce | Fenerbahce S.K. | Fenerbahce SK | Fenerbahçe Spor Kulübü | Fenerbahce Spor Kulubu | Fenerbahçe Sports Club | Fenerbahce Sports Club | Fenerbahçe SK Football'),
  ('Galatasaray SK', 'Turquia', 'Galatasaray S.K. | Galatasaray Spor Kulübü | Galatasaray AŞ | Galatasaray | Galatasaray Sports Club | GS'),
  ('Gaziantep ALG SK', 'Turquia', 'Gaziantep ALG Spor'),
  ('Gaziantep FK', 'Turquia', 'Gaziantep F.K.'),
  ('Gençlerbirliği SK', 'Turquia', 'Gençlerbirliği S.K. | Gençlerbirliği | Gençlerbirliği Spor Kulübü'),
  ('Gençlerbirliği Sports Club', 'Turquia', 'Gençlerbirliği'),
  ('Giresunspor', 'Turquia', null::text),
  ('Göztepe SK', 'Turquia', 'Göztepe S.K. | Goztepe Izmir'),
  ('Hacettepe SK', 'Turquia', 'Hacettepe S.K.'),
  ('Hatayspor', 'Turquia', null::text),
  ('İstanbul Başakşehir FK', 'Turquia', 'İstanbul Başakşehir F.K. | İBFK | ibfk | İstanbul Başakşehir | Başakşehir F.K.'),
  ('İstanbulspor A.Ş.', 'Turquia', null::text),
  ('Kahramanmaraşspor', 'Turquia', 'Kahramanmaraş Spor Kulübü'),
  ('Kardemir Karabükspor', 'Turquia', null::text),
  ('Kartal SK', 'Turquia', 'Kartal S.K.'),
  ('Kasımpaşa SK', 'Turquia', 'Kasımpaşa S.K. | Kasımpaşa Spor Kulübü'),
  ('Kayseri Erciyesspor', 'Turquia', null::text),
  ('Kayserispor', 'Turquia', 'Kayseri Spor Kulübü'),
  ('Kocaelispor', 'Turquia', null::text),
  ('Konyaspor', 'Turquia', null::text),
  ('Malatyaspor', 'Turquia', 'Malatya SK'),
  ('Manisa FK', 'Turquia', 'Manisa Büyükşehir Belediye SK'),
  ('Manisaspor', 'Turquia', null::text),
  ('Mersin İdmanyurdu', 'Turquia', null::text),
  ('MKE Ankaragücü', 'Turquia', 'Ankaragücü SK'),
  ('MKE Kırıkkalespor', 'Turquia', null::text),
  ('Orduspor', 'Turquia', null::text),
  ('Oyak Renault', 'Turquia', null::text),
  ('Pendikspor', 'Turquia', null::text),
  ('Sakaryaspor', 'Turquia', null::text),
  ('Samsunspor FC', 'Turquia', null::text),
  ('Şanlıurfaspor', 'Turquia', null::text),
  ('Sarıyer GK', 'Turquia', 'Sarıyer G.K.'),
  ('Sivasspor', 'Turquia', null::text),
  ('TKİ Tavşanlı Linyitspor', 'Turquia', null::text),
  ('Trabzonspor', 'Turquia', null::text),
  ('Ümraniyespor', 'Turquia', null::text),
  ('Vefa SC', 'Turquia', null::text),
  ('Yeni Malatyaspor', 'Turquia', null::text),
  ('Zeytinburnuspor', 'Turquia', null::text),
  ('FC Ahrobiznes Volochysk', 'Ucrânia', 'Ahrobiznes Volochysk'),
  ('FC Alians Lypova Dolyna', 'Ucrânia', null::text),
  ('FC Arsenal-Kyivshchyna Bila Tserkva', 'Ucrânia', null::text),
  ('FC Avanhard Kramatorsk', 'Ucrânia', null::text),
  ('FC Cherkashchyna', 'Ucrânia', 'FC Slavutych Cherkasy'),
  ('FC Chornomorets Odesa', 'Ucrânia', null::text),
  ('FC Desna Chernihiv', 'Ucrânia', 'SFC Desna Chernihiv'),
  ('FC Dynamo Kyiv', 'Ucrânia', 'Dynamo Kyiv | Football Club Dynamo Kyiv'),
  ('FC Enerhetyk Burshtyn', 'Ucrânia', null::text),
  ('FC Epitsentr Kamianets-Podilskyi', 'Ucrânia', 'Epitsentr Kamianets-Podilskyi | FC Epitsentr Dunaivtsi'),
  ('FC Helios Kharkiv', 'Ucrânia', null::text),
  ('FC Ihroservice Simferopol', 'Ucrânia', null::text),
  ('FC Inhulets Petrove', 'Ucrânia', null::text),
  ('FC Karpaty Lviv', 'Ucrânia', 'FC Karpaty Lviv (2020)'),
  ('FC Knyazha Shchaslyve', 'Ucrânia', null::text),
  ('FC Kolos Kovalivka', 'Ucrânia', null::text),
  ('FC Komunalnyk Luhansk', 'Ucrânia', null::text),
  ('FC Krymteplytsia Molodizhne', 'Ucrânia', null::text),
  ('FC Kryvbas Kryvyi Rih', 'Ucrânia', null::text),
  ('FC Kudrivka', 'Ucrânia', null::text),
  ('FC Livyi Bereh Kyiv', 'Ucrânia', null::text),
  ('FC LNZ Cherkasy', 'Ucrânia', 'LNZ Cherkasy'),
  ('FC Lviv', 'Ucrânia', null::text),
  ('FC Metal Kharkiv', 'Ucrânia', null::text),
  ('FC Metalist 1925 Kharkiv', 'Ucrânia', 'Football Club Metalist 1925 Kharkiv | Metalist 1925 Kharkiv'),
  ('FC Metalist Kharkiv', 'Ucrânia', 'FC Metalist Kharkov | F.C. Metalist Kharkov | Metalist Kharkov | F.C. Metalist Kharkiv'),
  ('FC Minaj', 'Ucrânia', 'FC Mynai'),
  ('FC Naftovyk-Ukrnafta Okhtyrka', 'Ucrânia', null::text),
  ('FC Nyva Bershad', 'Ucrânia', null::text),
  ('FC Nyva Ternopil', 'Ucrânia', 'Football Club Nyva Ternopil'),
  ('FC Obolon Kyiv', 'Ucrânia', null::text),
  ('FC Oleksandriya', 'Ucrânia', 'PFC Oleksandria | PFK Oleksandria'),
  ('FC Olimpik Donetsk', 'Ucrânia', null::text),
  ('FC Polissya Zhytomyr', 'Ucrânia', 'Football Club Polissya Zhytomyr | Polissya Zhytomyr'),
  ('FC Poltava', 'Ucrânia', null::text),
  ('FC Rubin Yalta', 'Ucrânia', null::text),
  ('FC Rukh Lviv', 'Ucrânia', 'FC Rukh Vynnyky'),
  ('FC Shakhtar Donetsk', 'Ucrânia', 'Shakhtar Donetsk | Shakhtar'),
  ('FC Sirius Zhovti Vody', 'Ucrânia', null::text),
  ('FC Spartak Sumy', 'Ucrânia', null::text),
  ('FC Temp Shepetivka', 'Ucrânia', null::text),
  ('FC Uzhhorod', 'Ucrânia', null::text),
  ('FC Volyn Lutsk', 'Ucrânia', null::text),
  ('FC Vorskla Poltava', 'Ucrânia', 'Vorskla Poltava'),
  ('FC VPK-Ahro Shevchenkivka', 'Ucrânia', null::text),
  ('FC Zirka Kropyvnytskyi', 'Ucrânia', null::text),
  ('FC Zorya Luhansk', 'Ucrânia', null::text),
  ('FSC Bukovyna Chernivtsi', 'Ucrânia', 'Football Sports Club Bukovyna Chernivtsi | FSC | Football Club Bukovyna Chernivtsi | FC Bukovyna Chernivtsi'),
  ('MFC Mykolaiv', 'Ucrânia', null::text),
  ('NK Veres Rivne', 'Ucrânia', 'FC Veres Rivne'),
  ('PFC Nyva Vinnytsia', 'Ucrânia', null::text),
  ('SC Poltava', 'Ucrânia', null::text),
  ('BUL FC', 'Uganda', 'Bidco Uganda Limited Football Club | Bidco Uganda Limited FC | Bull FC | BUL football club'),
  ('Busoga United Football Club', 'Uganda', 'Kirinya–Jinja Senior Secondary School FC | Busoga United FC | Kirinya Jinja SS'),
  ('Coffee Kakira SC', 'Uganda', 'Coffee United FC | Coffee SC | Kakira Coffee SC | Coffee United Sports Club | Coffee Kakira F.C | Coffee Kakira football club | Coffee Kakira sports club'),
  ('CRO FC', 'Uganda', 'Child Restoration Outreach Football Club | Child Restoration Outreach FC | Child Restoration Outreach F.C | CRO football club'),
  ('Express FC', 'Uganda', 'Express F.C. | Express Red Eagles FC | Mukwano Gw’abangi | Express football club'),
  ('Gaddafi FC', 'Uganda', 'Gadafi FC | Gadaffi FC | Gaddafi Football Club'),
  ('Jinja Municipal Hippos FC', 'Uganda', 'JMC Hippos | Jinja Municipal Hippos | Jinja Municipal Council Football Club | Jinja Municipal Council FC | Jinja Municipal Council Hippos FC | Jinja Municipal Hippos sports club | Jinja Municipal Hippos football club'),
  ('KCCA FC', 'Uganda', 'Kampala City Council Football Club | Kampala City Council FC | Kampala Capital City Authority FC | Kasasiro boys | KCCA football club'),
  ('Kiira Young FC', 'Uganda', 'Kiira Young football club'),
  ('Kitara FC', 'Uganda', 'The Royals | The pride of Bunyoro | Kitara football club'),
  ('Lugazi FC', 'Uganda', 'Lugazi Football Club | Kampala University FC'),
  ('Lweza FC', 'Uganda', 'Lweza football club'),
  ('Makerere University WFC', 'Uganda', 'Makerere University Women FC | Makerere University Women Football Club | Makerere University W football club'),
  ('Maroons FC', 'Uganda', 'Maroons F.C. | Maroons FC. | Prisons FC | Maroons football club'),
  ('Masaka Local Council FC', 'Uganda', 'Masaka Local Council football club'),
  ('Mbarara City FC', 'Uganda', 'Mbarara City F.C. | Mbarara City Football Club | The Ankole lions | Ankole lions'),
  ('NEC FC', 'Uganda', 'NEC F.C. | National Enterprises Corporation FC | NEC football club'),
  ('Nyamityobora FC', 'Uganda', 'Nyamityobora football club'),
  ('Onduparaka FC', 'Uganda', 'Onduparaka football club'),
  ('Paidha Black Angels FC', 'Uganda', 'Paidha Black Angels football club | Paidha black angels | The black angels'),
  ('Police FC', 'Uganda', 'The Cops | Police Football Club'),
  ('Proline FC', 'Uganda', 'Proline football club | Ploline football club | Plorine football club | Proline sports club'),
  ('SC Villa', 'Uganda', 'Sports Club Villa | Villa SC | Villa FC | Jogo | ssalongo | Nakivubo Boys FC | Nakivubo Villa FC'),
  ('Simba FC (Uganda)', 'Uganda', 'Simba F.C. (Uganda) | Simba FC | Simba FC Uganda | Army FC Uganda | Army FC | Simba football club | UPDF FC | UPDF Football club'),
  ('SOLTILO Bright Stars FC', 'Uganda', 'Bright Stars FC | SOLTILO Bright Stars football club'),
  ('Tooro United FC', 'Uganda', 'Tooro United football club'),
  ('Uganda Revenue Authority SC', 'Uganda', 'URA SC | URA FC | Uganda Revenue Authority sports club'),
  ('Victoria University SC', 'Uganda', 'Victoria University Soccer Club | Victoria University Sports Club | Victoria University FC | Victoria University football club'),
  ('Victors FC', 'Uganda', 'Victors football club'),
  ('Vipers SC', 'Uganda', 'Bunamwaya S.C. | Vipers Sports Club | The Venoms | Vipers FC | Vipers F.C. | SC Vipers'),
  ('Albion FC', 'Uruguai', 'Albion F.C. | Albion Football Club'),
  ('Atenas de San Carlos', 'Uruguai', 'Club Atlético Atenas'),
  ('Boston River', 'Uruguai', null::text),
  ('CA Bella Vista', 'Uruguai', 'C.A. Bella Vista | Club Atlético Bella Vista'),
  ('CA Cerro', 'Uruguai', 'C.A. Cerro | Cerro'),
  ('CA Progreso', 'Uruguai', 'C.A. Progreso'),
  ('CA Rentistas', 'Uruguai', 'C.A. Rentistas'),
  ('Central Español', 'Uruguai', null::text),
  ('Centro Atlético Fénix', 'Uruguai', 'Centro Atletico Fenix'),
  ('Cerro Largo FC', 'Uruguai', 'Cerro'),
  ('Club Atlético Peñarol', 'Uruguai', 'CA Peñarol | Club Atletico Peñarol | Peñarol de Montevideo | Peñarol | Peñarol Montevideo'),
  ('Club Atlético River Plate', 'Uruguai', 'River Plate Montevideo'),
  ('Club Nacional de Football', 'Uruguai', 'Nacional | Club Nacional | Club Nacional de F. | Nacional de Football | C.N. de F. | C. Nacional de F. | Nacional Montevideo | Nacional of Montevideo'),
  ('Club Sportivo Cerrito', 'Uruguai', null::text),
  ('Colón FC', 'Uruguai', 'Colón F.C. | Colon F.C.'),
  ('CSD Villa Española', 'Uruguai', 'C.S.D. Villa Española'),
  ('Danubio FC', 'Uruguai', 'Danubio F.C. | Danubio Fútbol Club'),
  ('Defensor Sporting Club', 'Uruguai', 'Defensor Sporting'),
  ('Deportivo Colonia', 'Uruguai', null::text),
  ('Deportivo Maldonado', 'Uruguai', null::text),
  ('El Tanque Sisley', 'Uruguai', 'El tanque'),
  ('Juventud de Las Piedras', 'Uruguai', null::text),
  ('Liverpool FC (Montevideo)', 'Uruguai', 'Liverpool F.C. (Montevideo) | Liverpool Fútbol Club'),
  ('Miramar Misiones', 'Uruguai', null::text),
  ('Montevideo City Torque', 'Uruguai', null::text),
  ('Montevideo Wanderers Fútbol Club', 'Uruguai', 'Montevideo Wanderers Futbol Club'),
  ('Plaza Colonia', 'Uruguai', null::text),
  ('Racing Club de Montevideo', 'Uruguai', null::text),
  ('Rampla Juniors Football Club', 'Uruguai', 'Rampla Juniors FC'),
  ('Rocha FC', 'Uruguai', 'Rocha F.C.'),
  ('Sud América', 'Uruguai', 'IASA'),
  ('Tacuarembó FC', 'Uruguai', 'Tacuarembó F.C.'),
  ('Universal Football Club', 'Uruguai', null::text),
  ('Uruguay Athletic Club', 'Uruguai', null::text),
  ('Uruguay Montevideo FC', 'Uruguai', 'Uruguay Montevideo F.C. | Uruguay Montevideo Football Club | UMFC | U.M.F.C.'),
  ('FC AGMK', 'Usbequistão', 'FC Olmaliq | Olmaliq FK'),
  ('FC Bunyodkor', 'Usbequistão', 'F.C. Bunyodkor'),
  ('FC Khorazm', 'Usbequistão', 'Xorazm Football Club'),
  ('FC Neftchi Fergana', 'Usbequistão', 'Neftchi Farg''ona | F.C. Neftchi Fergana'),
  ('FC Shurtan Guzar', 'Usbequistão', null::text),
  ('FC Surkhon Termez', 'Usbequistão', null::text),
  ('FK Andijan', 'Usbequistão', null::text),
  ('FK Buxoro', 'Usbequistão', 'FJ Buxoro | PFK Buxoro'),
  ('FK Dinamo Samarqand', 'Usbequistão', null::text),
  ('FK Mash''al Mubarek', 'Usbequistão', null::text),
  ('Kokand 1912', 'Usbequistão', null::text),
  ('Lokomotiv Tashkent', 'Usbequistão', 'Lokomotiv Tashkent FC'),
  ('Metallurg Bekabad', 'Usbequistão', 'PFC Metallurg Bekabad'),
  ('MHSK Tashkent', 'Usbequistão', 'M.H.S.K. Tashkent'),
  ('Nasaf Qarshi', 'Usbequistão', 'Nasaf Qarshi FK | Nasaf Qarshi FC'),
  ('Navbahor Namangan', 'Usbequistão', null::text),
  ('Pakhtakor Tashkent FK', 'Usbequistão', 'FC Pakhtakor Tashkent | F.C. Pakhtakor Tashkent'),
  ('PFK Qizilqum', 'Usbequistão', null::text),
  ('Sogdiana Jizzakh', 'Usbequistão', 'Sogdiyona Jizzakh'),
  ('Topalang Sariosiyo', 'Usbequistão', null::text),
  ('Vobkent FK', 'Usbequistão', null::text),
  ('Amicale FC', 'Vanuatu', 'Amicale F.C.'),
  ('Tafea FC', 'Vanuatu', 'Tafea F.C.'),
  ('Academia Puerto Cabello', 'Venezuela', null::text),
  ('América Fútbol Club', 'Venezuela', 'America Futbol Club'),
  ('Aragua Fútbol Club', 'Venezuela', null::text),
  ('Asociación Civil Deportivo Lara', 'Venezuela', 'Red and Black | Twilighters'),
  ('Asociación Civil Mineros de Guayana', 'Venezuela', 'Mineros de Guayana | Mineros | AC Mineros de Guayana | Club Deportivo Mineros de Guayana | Atlético Club Mineros de Guayana'),
  ('Atlético El Vigía', 'Venezuela', 'Atletico El Vigia'),
  ('Atlético Venezuela', 'Venezuela', 'Atlético Venezuela Club de Fútbol'),
  ('Banco Obrero Fútbol Club', 'Venezuela', null::text),
  ('Carabobo FC', 'Venezuela', 'Carabobo F.C. | El Granate | Carabobo Fútbol Club | La Vinotinto Regional | Padre del Aragua Fc'),
  ('Caracas Fútbol Club', 'Venezuela', 'Caracas FC | los hijos de tachira'),
  ('Caroní Fútbol Club', 'Venezuela', 'Caroni Futbol Club | Caroní FC | Caroni FC'),
  ('Centro Atlético Sport Club', 'Venezuela', 'Centro Atletico Sport Club'),
  ('Deportivo Anzoátegui', 'Venezuela', 'Deportivo Anzoategui'),
  ('Deportivo JBL del Zulia', 'Venezuela', null::text),
  ('Deportivo La Guaira FC', 'Venezuela', 'Deportivo La Guaira F.C. | Deportivo La Guaira'),
  ('Deportivo Lara Fútbol Club', 'Venezuela', 'Deportivo Lara'),
  ('Deportivo Petare FC', 'Venezuela', 'Deportivo Petare F.C.'),
  ('Deportivo Vasco', 'Venezuela', null::text),
  ('Deportivo Venezuela', 'Venezuela', null::text),
  ('Dos Caminos Sport Club', 'Venezuela', null::text),
  ('Estrella Roja FC', 'Venezuela', null::text),
  ('Estudiantes de Mérida', 'Venezuela', null::text),
  ('Guaros Fútbol Club', 'Venezuela', 'Guaros FC | Guaros F.C.'),
  ('Internacional de Bogotá', 'Venezuela', 'Deportivo Táchira / aurinegro'),
  ('La Salle FC', 'Venezuela', null::text),
  ('Lala Fútbol Club', 'Venezuela', null::text),
  ('Litoral de Cochabamba', 'Venezuela', null::text),
  ('Litoral Sport Club', 'Venezuela', null::text),
  ('Loyola Sport Club', 'Venezuela', null::text),
  ('Metropolitanos FC', 'Venezuela', null::text),
  ('Monagas Sport Club', 'Venezuela', null::text),
  ('Portuguesa FC', 'Venezuela', null::text),
  ('Trujillanos FC', 'Venezuela', null::text),
  ('Unión Lara', 'Venezuela', 'Union Lara'),
  ('Venzóleo', 'Venezuela', 'Venzoleo'),
  ('Yaracuyanos FC', 'Venezuela', null::text),
  ('Zamora FC', 'Venezuela', 'Zamora F.C.'),
  ('Zulia FC', 'Venezuela', null::text),
  ('Becamex Binh Duong FC', 'Vietname', 'Becamex Binh Duong F.C.'),
  ('Cong An Ha Noi FC', 'Vietname', 'The Public Security''s Team | CAHN | The Wall | The Hourses | FC Hoang Dieu | The Imperial Citadel | CAH'),
  ('Cong An Ho Chi Minh City FC', 'Vietname', null::text),
  ('Đồng Tâm Long An FC', 'Vietname', 'Đồng Tâm Long An F.C.'),
  ('Haiphong Football Club', 'Vietname', null::text),
  ('Hanoi FC', 'Vietname', 'Hanoi F.C.'),
  ('Hoang Anh Gia Lai FC', 'Vietname', 'Hoang Anh Gia Lai F.C.'),
  ('Hong Linh Ha Tinh FC', 'Vietname', 'Hong Linh Ha Tinh F.C. | Hà Nội B F.C.'),
  ('MerryLand Quy Nhon Binh Dinh FC', 'Vietname', 'Bình Định F.C. | Binh Dinh FC | Topenland Binh Dinh'),
  ('Nam Dinh FC', 'Vietname', 'Nam Dinh F.C.'),
  ('QNK Quang Nam FC', 'Vietname', 'QNK Quang Nam F.C. | QNK Quang Nam Football Club'),
  ('Quang Ninh Charcoal FC', 'Vietname', 'Quang Ninh Charcoal F.C. | Than Quang Ninh Football Club'),
  ('Sài Gòn FC', 'Vietname', 'Sài Gòn F.C. | Hà Nội F.C. | Sài Gòn Football Club'),
  ('Sanna Khanh Hoa FC', 'Vietname', 'Sanna Khanh Hoa F.C. | Sanna Khanh Hoa BVN Football Club | Câu lạc bộ bóng đá Sanna Khánh Hòa BVN'),
  ('SHB Da Nang FC', 'Vietname', 'SHB Da Nang F.C.'),
  ('Sông Lam Nghệ An FC', 'Vietname', 'Sông Lam Nghệ An F.C.'),
  ('Thanh Hóa FC', 'Vietname', 'Thanh Hóa F.C. | FLC Thanh Hóa Football Club | Thanh Hóa Football Club'),
  ('Thể Công–Viettel FC', 'Vietname', 'Viettel FC | Viettel F.C. | Thể Công'),
  ('Buildcon FC', 'Zâmbia', 'Buildcon F.C.'),
  ('Forest Rangers FC', 'Zâmbia', 'Forest Rangers F.C.'),
  ('Green Buffaloes FC', 'Zâmbia', 'Green Buffaloes F.C.'),
  ('Green Eagles', 'Zâmbia', 'Choma Eagles Football Club | Eagles Football Club | Eagles F.C.'),
  ('Kabwe Warriors FC', 'Zâmbia', 'Kabwe Warriors F.C. | Kabwe Warriors'),
  ('Konkola Blades FC', 'Zâmbia', 'Konkola Blades F.C.'),
  ('Konkola Mine Police FC', 'Zâmbia', 'Konkola Mine Police F.C.'),
  ('Lime Hotspurs Football Club', 'Zâmbia', null::text),
  ('Lusaka Dynamos FC', 'Zâmbia', 'Lusaka Dynamos F.C.'),
  ('Maestro United Zambia FC', 'Zâmbia', 'Maestro United Zambia F.C. | Maestro United Zambia Football Club | MUZA FC'),
  ('Mines United FC', 'Zâmbia', 'Mines United F.C. | MineBola'),
  ('Mufulira Wanderers FC', 'Zâmbia', 'Mufulira Wanderers F.C.'),
  ('Mutondo Stars Football Club', 'Zâmbia', 'Mutondo Stars F.C. | Evergreen'),
  ('Nakambala Leopards FC', 'Zâmbia', 'Nakambala Leopards F.C.'),
  ('NAPSA Stars FC', 'Zâmbia', 'NAPSA Stars F.C.'),
  ('National Assembly FC', 'Zâmbia', 'National Assembly F.C.'),
  ('Nchanga Rangers FC', 'Zâmbia', 'Nchanga Rangers F.C.'),
  ('Nkana FC', 'Zâmbia', 'Nkana F.C.'),
  ('Nkwazi FC', 'Zâmbia', 'Nkwazi F.C.'),
  ('Power Dynamos FC', 'Zâmbia', 'Power Dynamos F.C.'),
  ('Red Arrows FC', 'Zâmbia', 'Red Arrows F.C. | Red Arrows Football Club'),
  ('Roan United FC', 'Zâmbia', 'Roan United F.C.'),
  ('Trident Football Club', 'Zâmbia', 'Trident F.C.'),
  ('Zanaco FC', 'Zâmbia', 'Zanaco F.C.'),
  ('ZESCO United FC', 'Zâmbia', 'ZESCO United F.C.'),
  ('Amazulu FC Zimbabwe', 'Zimbabué', null::text),
  ('Bantu Tshintsha Guluva Rovers FC', 'Zimbabué', 'Bantu Tshintsha Guluva Rovers F.C.'),
  ('Black Mambas FC', 'Zimbabué', 'Black Mambas F.C. | Black Mambas Football Club'),
  ('Black Rhinos FC', 'Zimbabué', 'Black Rhinos F.C.'),
  ('Blackpool FC Harare', 'Zimbabué', 'Blackpool FC (Harare)'),
  ('Buffaloes FC', 'Zimbabué', 'Buffaloes F.C.'),
  ('Cachetitos fc', 'Zimbabué', null::text),
  ('CAPS FC', 'Zimbabué', 'CAPS F.C.'),
  ('CAPS United FC', 'Zimbabué', 'CAPS United F.C.'),
  ('Chapungu United FC', 'Zimbabué', 'Chapungu United F.C.'),
  ('Chicken Inn FC', 'Zimbabué', 'Chicken Inn F.C.'),
  ('Chiredzi FC', 'Zimbabué', null::text),
  ('Dynamos FC', 'Zimbabué', 'Dynamos F.C. | Dynamos Football Club'),
  ('FC Platinum', 'Zimbabué', null::text),
  ('Gunners FC', 'Zimbabué', 'Gunners F.C.'),
  ('Harare City FC', 'Zimbabué', 'Harare City F.C.'),
  ('Highlanders FC', 'Zimbabué', 'Highlanders F.C.'),
  ('Highway FC', 'Zimbabué', 'Highway F.C.'),
  ('How Mine FC', 'Zimbabué', null::text),
  ('Hwange Colliery FC', 'Zimbabué', 'Hwange Colliery F.C.'),
  ('Kiglon FC', 'Zimbabué', 'Kiglon F.C.'),
  ('Lancashire Steel FC', 'Zimbabué', 'Lancashire Steel F.C.'),
  ('Lengthens FC', 'Zimbabué', 'Lengthens F.C.'),
  ('Masvingo United FC', 'Zimbabué', 'Masvingo United F.C.'),
  ('Monomotapa United FC', 'Zimbabué', 'Monomotapa United F.C.'),
  ('Ngezi Platinum FC', 'Zimbabué', 'Ngezi Platinum F.C.'),
  ('Njube Sundowns FC', 'Zimbabué', 'Njube Sundowns F.C.'),
  ('Shabanie Mine FC', 'Zimbabué', 'Shabanie Mine F.C.'),
  ('Triangle United', 'Zimbabué', null::text),
  ('Triple B FC', 'Zimbabué', null::text),
  ('Underhill FC', 'Zimbabué', 'Underhill F.C.'),
  ('Zimbabwe Saints FC', 'Zimbabué', 'Zimbabwe Saints F.C.'),
  ('ZPC Kariba', 'Zimbabué', null::text)
) as v(name, country, aliases)
join countries c on c.name = v.country
on conflict (name, country_id) do update set aliases = coalesce(teams.aliases, excluded.aliases);
