-- Leagues and cups from Wikidata (CC0) plus the international competitions under Mundo. Safe to re-run.
-- Run 0023_uk_countries.sql first.
insert into competitions (name, country_id)
select v.name, c.id
from (values
  ('Afghan Premier League', 'Afeganistão'),
  ('Nedbank Cup', 'África do Sul'),
  ('Premier Soccer League', 'África do Sul'),
  ('South African Premier Division', 'África do Sul'),
  ('Albanian Cup', 'Albânia'),
  ('Albanian First Division', 'Albânia'),
  ('2. Bundesliga', 'Alemanha'),
  ('3. Liga', 'Alemanha'),
  ('DFB-Pokal', 'Alemanha'),
  ('Fußball-Oberliga', 'Alemanha'),
  ('Regionalliga', 'Alemanha'),
  ('Copa Constitució', 'Andorra'),
  ('Primera Divisió', 'Andorra'),
  ('Segona Divisió', 'Andorra'),
  ('Angolan football cup', 'Angola'),
  ('Girabola', 'Angola'),
  ('King Cup of Champions', 'Arábia Saudita'),
  ('Saudi First Division League', 'Arábia Saudita'),
  ('Saudi Pro League', 'Arábia Saudita'),
  ('Algerian Cup', 'Argélia'),
  ('Algerian Ligue Professionnelle 1', 'Argélia'),
  ('Argentine Primera División', 'Argentina'),
  ('Primera Nacional', 'Argentina'),
  ('Armenian First League', 'Arménia'),
  ('Armenian Independence Cup', 'Arménia'),
  ('Armenian Premier League', 'Arménia'),
  ('Aruban Division di Honor', 'Aruba'),
  ('A-League Men', 'Austrália'),
  ('Australia Cup', 'Austrália'),
  ('Austrian Cup', 'Áustria'),
  ('Austrian Football Second League', 'Áustria'),
  ('Austrian Regional League', 'Áustria'),
  ('Bundesliga', 'Áustria'),
  ('Azerbaijan Cup', 'Azerbaijão'),
  ('Azerbaijan First Division', 'Azerbaijão'),
  ('Azerbaijan Premier League', 'Azerbaijão'),
  ('Bangladesh Premier League', 'Bangladeche'),
  ('Bahraini Premier League', 'Barém'),
  ('Belgian Cup', 'Bélgica'),
  ('Belgian First Division B', 'Bélgica'),
  ('Belgian Pro League', 'Bélgica'),
  ('Challenger Pro League', 'Bélgica'),
  ('Benin Premier League', 'Benim'),
  ('Belarusian Cup', 'Bielorrússia'),
  ('Belarusian First League', 'Bielorrússia'),
  ('Belarusian Premier League', 'Bielorrússia'),
  ('Bosnia and Herzegovina Football Cup', 'Bósnia e Herzegovina'),
  ('First League of the Federation of Bosnia and Herzegovina', 'Bósnia e Herzegovina'),
  ('First League of the Republika Srpska', 'Bósnia e Herzegovina'),
  ('Premier League of Bosnia and Herzegovina', 'Bósnia e Herzegovina'),
  ('Botswana Premier League', 'Botsuana'),
  ('FA Challenge Cup', 'Botsuana'),
  ('Campeonato Alagoano', 'Brasil'),
  ('Campeonato Brasileiro Série A', 'Brasil'),
  ('Campeonato Brasileiro Série B', 'Brasil'),
  ('Campeonato Brasileiro Série C', 'Brasil'),
  ('Campeonato Brasileiro Série D', 'Brasil'),
  ('Campeonato Cearense', 'Brasil'),
  ('Campeonato Mineiro', 'Brasil'),
  ('Campeonato Paranaense', 'Brasil'),
  ('Campeonato Paulista de Futebol', 'Brasil'),
  ('Copa do Brasil', 'Brasil'),
  ('Copa Rio', 'Brasil'),
  ('Bulgarian B Professional Football Group', 'Bulgária'),
  ('Bulgarian Cup', 'Bulgária'),
  ('First Professional Football League', 'Bulgária'),
  ('Burkinabé Premier League', 'Burquina Faso'),
  ('Burundi Premier League', 'Burundi'),
  ('A-Division', 'Butão'),
  ('Bhutan National League', 'Butão'),
  ('Campeonato Nacional de Cabo Verde', 'Cabo Verde'),
  ('Cameroonian Cup', 'Camarões'),
  ('Elite One', 'Camarões'),
  ('Cambodian Premier League', 'Camboja'),
  ('Hun Sen Cup', 'Camboja'),
  ('Canadian Championship', 'Canadá'),
  ('Canadian Premier League', 'Canadá'),
  ('Canadian Soccer League', 'Canadá'),
  ('Major League Soccer', 'Canadá'),
  ('North American Soccer League', 'Canadá'),
  ('USL Championship', 'Canadá'),
  ('Emir Cup', 'Catar'),
  ('Qatar Stars League', 'Catar'),
  ('Kazakhstan Cup', 'Cazaquistão'),
  ('Kazakhstan First League', 'Cazaquistão'),
  ('Kazakhstan Premier League', 'Cazaquistão'),
  ('Chad Premier League', 'Chade'),
  ('Chilean Primera División', 'Chile'),
  ('Copa Chile', 'Chile'),
  ('China League One', 'China'),
  ('Chinese FA Cup', 'China'),
  ('Hong Kong First Division League', 'China'),
  ('Hong Kong Premier League', 'China'),
  ('Liga de Elite', 'China'),
  ('Cypriot Cup', 'Chipre'),
  ('Cypriot First Division', 'Chipre'),
  ('Cypriot Second Division', 'Chipre'),
  ('Categoría Primera A', 'Colômbia'),
  ('Categoría Primera B', 'Colômbia'),
  ('Copa Colombia', 'Colômbia'),
  ('Congo Premier League', 'Congo'),
  ('DPR Korea Premier Football League', 'Coreia do Norte'),
  ('K League', 'Coreia do Sul'),
  ('K League 1', 'Coreia do Sul'),
  ('K League 2', 'Coreia do Sul'),
  ('Korea Cup', 'Coreia do Sul'),
  ('Coupe de Côte d''Ivoire de football', 'Costa do Marfim'),
  ('Ligue 1', 'Costa do Marfim'),
  ('Liga FPD', 'Costa Rica'),
  ('Croatian Cup', 'Croácia'),
  ('Prva nogometna liga', 'Croácia'),
  ('Liga Nacional de Fútbol de Cuba', 'Cuba'),
  ('Curaçao League', 'Curaçau'),
  ('A-Liga', 'Dinamarca'),
  ('Danish 1st Division', 'Dinamarca'),
  ('Danish 2nd Division', 'Dinamarca'),
  ('Danish Cup', 'Dinamarca'),
  ('Danish Superliga', 'Dinamarca'),
  ('Faroe Islands Cup', 'Dinamarca'),
  ('Faroe Islands Premier League', 'Dinamarca'),
  ('Egypt Cup', 'Egito'),
  ('Egyptian Premier League', 'Egito'),
  ('Tercera División de El Salvador', 'El Salvador'),
  ('UAE President''s Cup', 'Emirados Árabes Unidos'),
  ('UAE Pro League', 'Emirados Árabes Unidos'),
  ('Eritrean Premier League', 'Eritreia'),
  ('Scottish Championship', 'Escócia'),
  ('Scottish Cup', 'Escócia'),
  ('Scottish League Cup', 'Escócia'),
  ('Scottish League One', 'Escócia'),
  ('Scottish Premiership', 'Escócia'),
  ('Slovak Cup', 'Eslováquia'),
  ('Slovak First Football League', 'Eslováquia'),
  ('Slovak Second Football League', 'Eslováquia'),
  ('Slovenian Football Cup', 'Eslovénia'),
  ('Slovenian PrvaLiga', 'Eslovénia'),
  ('Slovenian Second League', 'Eslovénia'),
  ('Copa del Rey', 'Espanha'),
  ('Kings League', 'Espanha'),
  ('La Liga', 'Espanha'),
  ('LaLiga 2', 'Espanha'),
  ('Liga F', 'Espanha'),
  ('Primera Federación', 'Espanha'),
  ('Segunda División B', 'Espanha'),
  ('Tercera División', 'Espanha'),
  ('Tercera Federación', 'Espanha'),
  ('Eswatini Premier League', 'Essuatíni'),
  ('Guam Men''s Soccer League', 'Estados Unidos'),
  ('Major League Soccer', 'Estados Unidos'),
  ('North American Soccer League', 'Estados Unidos'),
  ('U.S. Open Cup', 'Estados Unidos'),
  ('USL Championship', 'Estados Unidos'),
  ('Esiliiga', 'Estónia'),
  ('Estonian Cup', 'Estónia'),
  ('Meistriliiga', 'Estónia'),
  ('Ethiopian Premier League', 'Etiópia'),
  ('Fiji Football Association Cup Tournament', 'Fiji'),
  ('Fiji National Football League', 'Fiji'),
  ('Finnish Cup', 'Finlândia'),
  ('Kansallinen Liiga', 'Finlândia'),
  ('Veikkausliiga', 'Finlândia'),
  ('Ykkönen', 'Finlândia'),
  ('Championnat National 1', 'França'),
  ('Championnat National 3', 'França'),
  ('Coupe Charles Drago', 'França'),
  ('Coupe de France', 'França'),
  ('Coupe de France Féminine', 'França'),
  ('Ligue 1', 'França'),
  ('Ligue 2', 'França'),
  ('Ligue 3', 'França'),
  ('Première Ligue', 'França'),
  ('Tahiti First Division', 'França'),
  ('Gabon Championnat National D1', 'Gabão'),
  ('GFA League First Division', 'Gâmbia'),
  ('Erovnuli Liga', 'Geórgia'),
  ('Erovnuli Liga 2', 'Geórgia'),
  ('Georgian Cup', 'Geórgia'),
  ('Gibraltar National League', 'Gibraltar'),
  ('Football League', 'Grécia'),
  ('Greek Football Cup', 'Grécia'),
  ('Liga Nacional de Fútbol de Guatemala', 'Guatemala'),
  ('Guinée Championnat National', 'Guiné'),
  ('Campeonato Nacional da Guiné-Bissau', 'Guiné-Bissau'),
  ('Ligue Haïtienne', 'Haiti'),
  ('Magyar Kupa', 'Hungria'),
  ('Nemzeti Bajnokság I', 'Hungria'),
  ('Nemzeti Bajnokság II', 'Hungria'),
  ('Yemeni League', 'Iémen'),
  ('1. deild', 'Ilhas Faroé'),
  ('Solomon Islands National Club Championship', 'Ilhas Salomão'),
  ('Durand Cup', 'Índia'),
  ('Indian Football League', 'Índia'),
  ('Piala Indonesia', 'Indonésia'),
  ('EFL Championship', 'Inglaterra'),
  ('EFL Cup', 'Inglaterra'),
  ('EFL League One', 'Inglaterra'),
  ('EFL League Two', 'Inglaterra'),
  ('FA Community Shield', 'Inglaterra'),
  ('FA Cup', 'Inglaterra'),
  ('FA Trophy', 'Inglaterra'),
  ('National League', 'Inglaterra'),
  ('National League North', 'Inglaterra'),
  ('National League South', 'Inglaterra'),
  ('Northern Premier League', 'Inglaterra'),
  ('Premier League', 'Inglaterra'),
  ('Southern Football League', 'Inglaterra'),
  ('Azadegan League', 'Irão'),
  ('Hazfi Cup', 'Irão'),
  ('Persian Gulf Pro League', 'Irão'),
  ('Iraq FA Cup', 'Iraque'),
  ('Iraq Stars League', 'Iraque'),
  ('FAI Cup', 'Irlanda'),
  ('League of Ireland', 'Irlanda'),
  ('League of Ireland First Division', 'Irlanda'),
  ('League of Ireland Premier Division', 'Irlanda'),
  ('Irish Cup', 'Irlanda do Norte'),
  ('NIFL Premiership', 'Irlanda do Norte'),
  ('Northern Ireland Football League Cup', 'Irlanda do Norte'),
  ('1. deild karla', 'Islândia'),
  ('Besta deild karla', 'Islândia'),
  ('Besta deild kvenna', 'Islândia'),
  ('Icelandic Cup', 'Islândia'),
  ('Israel State Cup', 'Israel'),
  ('Israeli Premier League', 'Israel'),
  ('Liga Leumit', 'Israel'),
  ('Coppa Italia', 'Itália'),
  ('Coppa Italia Serie C', 'Itália'),
  ('Eccellenza', 'Itália'),
  ('Serie B', 'Itália'),
  ('Serie C', 'Itália'),
  ('Serie C1', 'Itália'),
  ('Serie C2', 'Itália'),
  ('Serie D', 'Itália'),
  ('National Premier League', 'Jamaica'),
  ('Emperor''s Cup', 'Japão'),
  ('J.League', 'Japão'),
  ('J1 League', 'Japão'),
  ('J2 League', 'Japão'),
  ('J3 League', 'Japão'),
  ('Japan Football League', 'Japão'),
  ('Nadeshiko League', 'Japão'),
  ('Djibouti Premier League', 'Jibuti'),
  ('Jordan FA Cup', 'Jordânia'),
  ('Jordan Premier League', 'Jordânia'),
  ('Football Superleague of Kosovo', 'Kosovo'),
  ('Kosovar Cup', 'Kosovo'),
  ('Kuwait Emir Cup', 'Kuwait'),
  ('Kuwaiti Premier League', 'Kuwait'),
  ('Lao League 1', 'Laos'),
  ('Lesotho Premier League', 'Lesoto'),
  ('Latvian First League', 'Letónia'),
  ('Latvian Football Cup', 'Letónia'),
  ('Latvian Higher League', 'Letónia'),
  ('Lebanese Premier League', 'Líbano'),
  ('Liberian Premier League', 'Libéria'),
  ('Libyan Premier League', 'Líbia'),
  ('Liechtenstein Football Cup', 'Listenstaine'),
  ('First League', 'Lituânia'),
  ('Lithuanian Football Cup', 'Lituânia'),
  ('TOPLYGA', 'Lituânia'),
  ('Luxembourg Cup (men''s football)', 'Luxemburgo'),
  ('Luxembourg National Division', 'Luxemburgo'),
  ('Macedonian Cup', 'Macedónia do Norte'),
  ('Macedonian Second Football League', 'Macedónia do Norte'),
  ('Orange Pro League', 'Madagáscar'),
  ('FA Cup Malaysia', 'Malásia'),
  ('Malawi Premier Division', 'Malawi'),
  ('Malian Première Division', 'Mali'),
  ('Maltese FA Trophy', 'Malta'),
  ('Maltese Premier League', 'Malta'),
  ('Botola Pro 1', 'Marrocos'),
  ('Mauritanian Premier League', 'Mauritânia'),
  ('Ascenso MX', 'México'),
  ('Copa MX', 'México'),
  ('Liga MX', 'México'),
  ('Myanmar National League', 'Mianmar'),
  ('Moçambola', 'Moçambique'),
  ('Moldovan Cup', 'Moldávia'),
  ('Moldovan National Division', 'Moldávia'),
  ('Mongolian Premier League', 'Mongólia'),
  ('Montenegrin Cup', 'Montenegro'),
  ('Montenegrin First League', 'Montenegro'),
  ('Montenegrin Second League', 'Montenegro'),
  ('Amigáveis Internacionais', 'Mundo'),
  ('Campeonato do Mundo', 'Mundo'),
  ('Copa América', 'Mundo'),
  ('Eurocopa', 'Mundo'),
  ('Leagues Cup', 'Mundo'),
  ('Liga Conferência', 'Mundo'),
  ('Liga das Nações', 'Mundo'),
  ('Liga das Nações da CONCACAF', 'Mundo'),
  ('Liga dos Campeões', 'Mundo'),
  ('Liga dos Campeões Africana', 'Mundo'),
  ('Liga dos Campeões da Ásia', 'Mundo'),
  ('Liga dos Campeões da CONCACAF', 'Mundo'),
  ('Liga Europa', 'Mundo'),
  ('Mundial de Clubes', 'Mundo'),
  ('Qualificação para a Eurocopa', 'Mundo'),
  ('Qualificação para o Campeonato do Mundo', 'Mundo'),
  ('Recopa Sul-Americana', 'Mundo'),
  ('Supertaça Europeia', 'Mundo'),
  ('Taça das Confederações da CAF', 'Mundo'),
  ('Taça das Nações Africanas', 'Mundo'),
  ('Taça das Nações Asiáticas', 'Mundo'),
  ('Taça de Ouro da CONCACAF', 'Mundo'),
  ('Taça Intercontinental', 'Mundo'),
  ('Taça Libertadores', 'Mundo'),
  ('Taça Sul-Americana', 'Mundo'),
  ('Torneio Olímpico de Futebol', 'Mundo'),
  ('Namibia Premier League', 'Namíbia'),
  ('Martyr''s Memorial A-Division League', 'Nepal'),
  ('Liga Primera', 'Nicarágua'),
  ('Niger Premier League', 'Níger'),
  ('Nigeria Premier Football League', 'Nigéria'),
  ('Nigerian FA Cup', 'Nigéria'),
  ('1. divisjon football', 'Noruega'),
  ('Eliteserien', 'Noruega'),
  ('Norwegian Football Cup', 'Noruega'),
  ('A-League Men', 'Nova Zelândia'),
  ('Chatham Cup', 'Nova Zelândia'),
  ('Cook Islands Round Cup', 'Nova Zelândia'),
  ('New Zealand Football Championship', 'Nova Zelândia'),
  ('Oman Professional League', 'Omã'),
  ('Sultan Qaboos Cup', 'Omã'),
  ('Cymru Premier', 'País de Gales'),
  ('Welsh Cup', 'País de Gales'),
  ('Derde Divisie', 'Países Baixos'),
  ('Eerste Divisie', 'Países Baixos'),
  ('Eredivisie', 'Países Baixos'),
  ('KNVB Cup', 'Países Baixos'),
  ('Vrouwen Eredivisie', 'Países Baixos'),
  ('Gaza Strip Premier League', 'Palestina'),
  ('West Bank Premier League', 'Palestina'),
  ('Liga Panameña de Fútbol', 'Panamá'),
  ('Papua New Guinea National Soccer League', 'Papua-Nova Guiné'),
  ('Pakistan Premier League', 'Paquistão'),
  ('Paraguayan Primera División', 'Paraguai'),
  ('Ekstraklasa', 'Polónia'),
  ('I liga', 'Polónia'),
  ('II liga', 'Polónia'),
  ('Polish Cup', 'Polónia'),
  ('Liga 3', 'Portugal'),
  ('Liga Portugal 2', 'Portugal'),
  ('Primeira Liga', 'Portugal'),
  ('Taça de Portugal', 'Portugal'),
  ('Kenyan Premier League', 'Quénia'),
  ('Kyrgyzstan Cup', 'Quirguistão'),
  ('Kyrgyzstan League', 'Quirguistão'),
  ('Czech Cup', 'República Checa'),
  ('Czech First Division', 'República Checa'),
  ('Czech First League', 'República Checa'),
  ('Czech FNL', 'República Checa'),
  ('Coupe du Congo', 'República Democrática do Congo'),
  ('Linafoot', 'República Democrática do Congo'),
  ('Cupa României', 'Roménia'),
  ('Liga I', 'Roménia'),
  ('Liga II', 'Roménia'),
  ('Rwanda Premier League', 'Ruanda'),
  ('Russian Cup', 'Rússia'),
  ('Russian First League', 'Rússia'),
  ('Russian Premier League', 'Rússia'),
  ('Russian Second League', 'Rússia'),
  ('Samoa National League', 'Samoa'),
  ('Campionato Sammarinese di Calcio', 'San Marino'),
  ('Coppa Titano', 'San Marino'),
  ('Seychelles First Division', 'Seicheles'),
  ('Senegal Premier League', 'Senegal'),
  ('Sierra Leone National Premier League', 'Serra Leoa'),
  ('Serbian Cup', 'Sérvia'),
  ('Serbian First League', 'Sérvia'),
  ('Serbian SuperLiga', 'Sérvia'),
  ('Singapore Cup', 'Singapura'),
  ('Singapore Premier League', 'Singapura'),
  ('Syrian Cup', 'Síria'),
  ('Syrian Premier League', 'Síria'),
  ('Somali First Division', 'Somália'),
  ('Sudan Cup', 'Sudão'),
  ('Sudani Premier League', 'Sudão'),
  ('Allsvenskan', 'Suécia'),
  ('Ettan Fotboll', 'Suécia'),
  ('Superettan', 'Suécia'),
  ('Svenska Cupen', 'Suécia'),
  ('Challenge League', 'Suíça'),
  ('Swiss Cup', 'Suíça'),
  ('Thai FA Cup', 'Tailândia'),
  ('Thai League 1', 'Tailândia'),
  ('Taiwan Football Premier League', 'Taiwan'),
  ('Tajik Cup', 'Tajiquistão'),
  ('Tajik League', 'Tajiquistão'),
  ('Tanzanian Premier League', 'Tanzânia'),
  ('Togolese Championnat National', 'Togo'),
  ('TT Premier Football League', 'Trindade e Tobago'),
  ('Tunisian Cup', 'Tunísia'),
  ('Tunisian Ligue Professionnelle 1', 'Tunísia'),
  ('Turkmenistan Cup', 'Turquemenistão'),
  ('Ýokary Liga', 'Turquemenistão'),
  ('Süper Lig', 'Turquia'),
  ('TFF First League', 'Turquia'),
  ('Turkish Cup', 'Turquia'),
  ('Premier League', 'Ucrânia'),
  ('Ukrainian Cup', 'Ucrânia'),
  ('Ukrainian First League', 'Ucrânia'),
  ('Ukrainian Second League', 'Ucrânia'),
  ('Uganda Premier League', 'Uganda'),
  ('Uruguayan Primera División', 'Uruguai'),
  ('Uruguayan Segunda División', 'Uruguai'),
  ('Uzbekistan Cup', 'Usbequistão'),
  ('Copa Venezuela', 'Venezuela'),
  ('Venezuelan Primera División', 'Venezuela'),
  ('V.League 1', 'Vietname'),
  ('Vietnamese National Football Cup', 'Vietname'),
  ('Zimbabwe Premier Soccer League', 'Zimbabué')
) as v(name, country)
join countries c on c.name = v.country
on conflict (name, country_id) do nothing;
