-- Football clubs from Wikidata (CC0), part 1 of 4. Safe to re-run: existing name+country pairs are skipped.
-- Run 0023_uk_countries.sql first (it creates Inglaterra, Escocia, etc.).
insert into teams (name, country_id)
select v.name, c.id
from (values
  ('Ariana Kabul FC', 'Afeganistão'),
  ('Attack Energy SC', 'Afeganistão'),
  ('De Abasin Sape FC', 'Afeganistão'),
  ('De Maiwand Atalan FC', 'Afeganistão'),
  ('De Spin Ghar Bazan FC', 'Afeganistão'),
  ('Hakim Sanayi Kabul FC', 'Afeganistão'),
  ('Javan Azadi Kabul FC', 'Afeganistão'),
  ('Kabul Bank FC', 'Afeganistão'),
  ('Kandahar Aryan', 'Afeganistão'),
  ('Maiwand Kabul FC', 'Afeganistão'),
  ('Mawjhai Amu FC', 'Afeganistão'),
  ('Oqaban Hindukush FC', 'Afeganistão'),
  ('Ordu Kabul FC', 'Afeganistão'),
  ('Pamir Kabul FC', 'Afeganistão'),
  ('Real Afghan Kabul', 'Afeganistão'),
  ('Sabawoon Kabul FC', 'Afeganistão'),
  ('Sarmi Yashy Kabul FC', 'Afeganistão'),
  ('Seramiasht FC', 'Afeganistão'),
  ('Shaheen Asmayee FC', 'Afeganistão'),
  ('Simorgh Alborz FC', 'Afeganistão'),
  ('Toofaan Harirod FC', 'Afeganistão'),
  ('AmaZulu FC', 'África do Sul'),
  ('Baroka FC', 'África do Sul'),
  ('Bidvest Wits FC', 'África do Sul'),
  ('Black Leopards FC', 'África do Sul'),
  ('Bloemfontein Celtic FC', 'África do Sul'),
  ('Bush Bucks FC', 'África do Sul'),
  ('Cape Town City FC', 'África do Sul'),
  ('Cape Town Spurs FC', 'África do Sul'),
  ('Chippa United FC', 'África do Sul'),
  ('Free State Stars FC', 'África do Sul'),
  ('Jomo Cosmos FC', 'África do Sul'),
  ('Kaizer Chiefs FC', 'África do Sul'),
  ('Lamontville Golden Arrows FC', 'África do Sul'),
  ('Mamelodi Sundowns FC', 'África do Sul'),
  ('Manning Rangers FC', 'África do Sul'),
  ('Maritzburg United FC', 'África do Sul'),
  ('Moroka Swallows FC', 'África do Sul'),
  ('Orlando Pirates FC', 'África do Sul'),
  ('Platinum Stars FC', 'África do Sul'),
  ('Polokwane City FC', 'África do Sul'),
  ('Santos FC', 'África do Sul'),
  ('SuperSport United FC', 'África do Sul'),
  ('TS Galaxy FC', 'África do Sul'),
  ('University of Pretoria FC', 'África do Sul'),
  ('AF Elbasani', 'Albânia'),
  ('Apolonia Fier', 'Albânia'),
  ('Besëlidhja Lezhë', 'Albânia'),
  ('FK Apolonia', 'Albânia'),
  ('FK Kukësi', 'Albânia'),
  ('FK Shënkolli', 'Albânia'),
  ('FK Skrapari', 'Albânia'),
  ('FK Tomori', 'Albânia'),
  ('FK Vora', 'Albânia'),
  ('Flamurtari Vlorë', 'Albânia'),
  ('K.FAda Velipojë', 'Albânia'),
  ('KF Adriatiku Mamurrasi', 'Albânia'),
  ('KF Besa Kavajë', 'Albânia'),
  ('KF Butrinti', 'Albânia'),
  ('KF Egnatia', 'Albânia'),
  ('KF Erzeni', 'Albânia'),
  ('KF Laçi', 'Albânia'),
  ('KF Memaliaj', 'Albânia'),
  ('KF Skënderbeu', 'Albânia'),
  ('KF Spartaku Tiranë', 'Albânia'),
  ('KF Teuta Durrës', 'Albânia'),
  ('KF Tirana', 'Albânia'),
  ('KF Vlora', 'Albânia'),
  ('Korabi', 'Albânia'),
  ('KS Burreli', 'Albânia'),
  ('KS Bylis Ballsh', 'Albânia'),
  ('KS Devolli', 'Albânia'),
  ('KS Dinamo Tirana', 'Albânia'),
  ('KS Elbasani', 'Albânia'),
  ('KS Iliria', 'Albânia'),
  ('KS Kamza', 'Albânia'),
  ('KS Kastrioti', 'Albânia'),
  ('KS Lushnja', 'Albânia'),
  ('KS Pogradeci', 'Albânia'),
  ('KS Turbina', 'Albânia'),
  ('KS Vllaznia Shkodër', 'Albânia'),
  ('Luftëtari Gjirokastër', 'Albânia'),
  ('Naftëtari', 'Albânia'),
  ('Partizani Tirana', 'Albânia'),
  ('Partizani Tirana B', 'Albânia'),
  ('Shkumbini Peqin', 'Albânia'),
  ('1. FC Frankfurt', 'Alemanha'),
  ('1. FC Heidenheim 1846', 'Alemanha'),
  ('1. FC Kaiserslautern', 'Alemanha'),
  ('1. FC Köln', 'Alemanha'),
  ('1. FC Magdeburg', 'Alemanha'),
  ('1. FC Nürnberg', 'Alemanha'),
  ('1. FC Saarbrücken', 'Alemanha'),
  ('1. FC Union Berlin', 'Alemanha'),
  ('1. FC Union Berlin II', 'Alemanha'),
  ('1. FSV Mainz 05', 'Alemanha'),
  ('Alemannia Aachen', 'Alemanha'),
  ('Altonaer FC von 1893', 'Alemanha'),
  ('Arminia Bielefeld', 'Alemanha'),
  ('Bayer 04 Leverkusen', 'Alemanha'),
  ('Berliner AK 07', 'Alemanha'),
  ('BFC Dynamo', 'Alemanha'),
  ('Blumenthaler SV', 'Alemanha'),
  ('Bonner SC', 'Alemanha'),
  ('Borussia Dortmund', 'Alemanha'),
  ('Borussia Mönchengladbach', 'Alemanha'),
  ('Borussia Neunkirchen', 'Alemanha'),
  ('BV Cloppenburg', 'Alemanha'),
  ('Chemnitzer FC', 'Alemanha'),
  ('Dynamo Dresden', 'Alemanha'),
  ('Eintracht Braunschweig', 'Alemanha'),
  ('Eintracht Frankfurt', 'Alemanha'),
  ('FC 08 Homburg', 'Alemanha'),
  ('FC Augsburg', 'Alemanha'),
  ('FC Bayern Alzenau', 'Alemanha'),
  ('FC Bayern Munich', 'Alemanha'),
  ('FC Carl Zeiss Jena', 'Alemanha'),
  ('FC Energie Cottbus', 'Alemanha'),
  ('FC Gütersloh 2000', 'Alemanha'),
  ('FC Hansa Rostock', 'Alemanha'),
  ('FC Ingolstadt 04', 'Alemanha'),
  ('FC Oberneuland', 'Alemanha'),
  ('FC Rot-Weiß Erfurt', 'Alemanha'),
  ('FC St. Pauli', 'Alemanha'),
  ('FC Stahl Brandenburg', 'Alemanha'),
  ('FC Viktoria 1889 Berlin', 'Alemanha'),
  ('FC Viktoria Köln', 'Alemanha'),
  ('FK Pirmasens', 'Alemanha'),
  ('Fortuna Düsseldorf', 'Alemanha'),
  ('Freiburger FC', 'Alemanha'),
  ('FSV Frankfurt', 'Alemanha'),
  ('FSV Salmrohr', 'Alemanha'),
  ('FSV Zwickau', 'Alemanha'),
  ('Hallescher FC', 'Alemanha'),
  ('Hamburger SV', 'Alemanha'),
  ('Hannover 96', 'Alemanha'),
  ('Hertha BSC', 'Alemanha'),
  ('Holstein Kiel', 'Alemanha'),
  ('Karlsruher FV', 'Alemanha'),
  ('Karlsruher SC', 'Alemanha'),
  ('KFC Uerdingen 05', 'Alemanha'),
  ('Kickers Emden', 'Alemanha'),
  ('Kickers Offenbach', 'Alemanha'),
  ('KSV Hessen Kassel', 'Alemanha'),
  ('MSV Duisburg', 'Alemanha'),
  ('RB Leipzig', 'Alemanha'),
  ('RB Leipzig (women)', 'Alemanha'),
  ('Rot Weiss Ahlen', 'Alemanha'),
  ('Rot-Weiss Essen', 'Alemanha'),
  ('Rot-Weiß Oberhausen', 'Alemanha'),
  ('SC Fortuna Köln', 'Alemanha'),
  ('SC Freiburg', 'Alemanha'),
  ('SC Paderborn 07', 'Alemanha'),
  ('SC Preußen Münster', 'Alemanha'),
  ('SC Verl', 'Alemanha'),
  ('SC Victoria Hamburg', 'Alemanha'),
  ('Schalke 04', 'Alemanha'),
  ('Schwarz-Weiß Essen', 'Alemanha'),
  ('SG Sonnenhof Großaspach', 'Alemanha'),
  ('SG Wattenscheid 09', 'Alemanha'),
  ('Sportfreunde Lotte', 'Alemanha'),
  ('Sportfreunde Siegen', 'Alemanha'),
  ('SpVgg Bayreuth', 'Alemanha'),
  ('SpVgg Greuther Fürth', 'Alemanha'),
  ('SpVgg Unterhaching', 'Alemanha'),
  ('SSV Jahn Regensburg', 'Alemanha'),
  ('SSV Reutlingen 05', 'Alemanha'),
  ('SSV Ulm 1846 Fußball', 'Alemanha'),
  ('Stuttgarter Kickers', 'Alemanha'),
  ('SV Babelsberg 03', 'Alemanha'),
  ('SV Darmstadt 98', 'Alemanha'),
  ('SV Eintracht Trier 05', 'Alemanha'),
  ('SV Elversberg', 'Alemanha'),
  ('SV Meppen', 'Alemanha'),
  ('SV Sandhausen', 'Alemanha'),
  ('SV Türkgücü-Ataspor München', 'Alemanha'),
  ('SV Waldhof Mannheim', 'Alemanha'),
  ('SV Wehen Wiesbaden', 'Alemanha'),
  ('SV Werder Bremen', 'Alemanha'),
  ('SV Wilhelmshaven', 'Alemanha'),
  ('Tennis Borussia Berlin', 'Alemanha'),
  ('TSG 1899 Hoffenheim', 'Alemanha'),
  ('TSG Neustrelitz', 'Alemanha'),
  ('TSV 1860 München', 'Alemanha'),
  ('TSV Havelse', 'Alemanha'),
  ('Türkiyemspor Berlin', 'Alemanha'),
  ('TuS Koblenz', 'Alemanha'),
  ('VfB Lübeck', 'Alemanha'),
  ('VfB Oldenburg', 'Alemanha'),
  ('VfB Stuttgart', 'Alemanha'),
  ('VfL Bochum', 'Alemanha'),
  ('VfL Osnabrück', 'Alemanha'),
  ('VfL Wolfsburg', 'Alemanha'),
  ('VfR Aalen', 'Alemanha'),
  ('VfR Mannheim', 'Alemanha'),
  ('Viktoria Aschaffenburg', 'Alemanha'),
  ('Wormatia Worms', 'Alemanha'),
  ('Wuppertaler SV', 'Alemanha'),
  ('Würzburger Kickers', 'Alemanha'),
  ('Atlètic Club d''Escaldes', 'Andorra'),
  ('CE Benito', 'Andorra'),
  ('CE Carroi', 'Andorra'),
  ('CF Atlètic Amèrica', 'Andorra'),
  ('CF Esperança d''Andorra', 'Andorra'),
  ('Deportivo La Massana', 'Andorra'),
  ('FC Andorra', 'Andorra'),
  ('FC Andorra Veterans', 'Andorra'),
  ('FC Encamp', 'Andorra'),
  ('FC Ordino', 'Andorra'),
  ('FC Pas de la Casa', 'Andorra'),
  ('FC Rànger''s', 'Andorra'),
  ('FC Santa Coloma', 'Andorra'),
  ('FS La Massana', 'Andorra'),
  ('Futbol Club Penya d''Andorra', 'Andorra'),
  ('GALAXY FCI JENLAI', 'Andorra'),
  ('Inter Club d''Escaldes', 'Andorra'),
  ('UE Engordany', 'Andorra'),
  ('UE Extremenya', 'Andorra'),
  ('UE Sant Julià', 'Andorra'),
  ('UE Santa Coloma', 'Andorra'),
  ('Académica Petróleo Kwanda Soyo', 'Angola'),
  ('Académica Petróleos do Lobito', 'Angola'),
  ('Atlético Petróleos do Huambo', 'Angola'),
  ('Atlético Petróleos do Namibe', 'Angola'),
  ('Atlético Petróleos Luanda', 'Angola'),
  ('Atlético Sport Aviação', 'Angola'),
  ('CD Huíla', 'Angola'),
  ('CD São Salvador', 'Angola'),
  ('Clube Atlético de Luanda', 'Angola'),
  ('Clube Desportivo Primeiro de Agosto', 'Angola'),
  ('CR Caála', 'Angola'),
  ('CRD Libolo', 'Angola'),
  ('Domant FC', 'Angola'),
  ('Estrela Clube Primeiro de Maio', 'Angola'),
  ('FC Casa Militar', 'Angola'),
  ('FC Desportivo 4 de Abril', 'Angola'),
  ('FC Luanda', 'Angola'),
  ('FC Onze Bravos', 'Angola'),
  ('GD Interclube', 'Angola'),
  ('GD Sagrada Esperança', 'Angola'),
  ('Grupo Desportivo Atlético Juventude do Moxico', 'Angola'),
  ('Guelson F. C.', 'Angola'),
  ('Isaac de Benguela F. C.', 'Angola'),
  ('JGM ASC Huambo', 'Angola'),
  ('Kabuscorp SC', 'Angola'),
  ('Porcelana Futebol Clube do Cazengo', 'Angola'),
  ('Progresso Associação do Sambizanga', 'Angola'),
  ('Progresso da Lunda Sul', 'Angola'),
  ('Real M''buco', 'Angola'),
  ('Redonda FC', 'Angola'),
  ('Santa Rita de Cássia FC', 'Angola'),
  ('Santos Futebol Clube de Angola', 'Angola'),
  ('SL Benfica', 'Angola'),
  ('Sporting Clube de Luanda', 'Angola'),
  ('Sporting Clube Petróleos de Cabinda', 'Angola'),
  ('União Sport Clube do Uíge', 'Angola'),
  ('Abha', 'Arábia Saudita'),
  ('Al Ahli FC', 'Arábia Saudita'),
  ('Al Fateh SC', 'Arábia Saudita'),
  ('Al Hazem SC', 'Arábia Saudita'),
  ('Al Hilal SFC', 'Arábia Saudita'),
  ('Al Ittihad FC', 'Arábia Saudita'),
  ('Al Jabalain', 'Arábia Saudita'),
  ('Al Okhdood Club', 'Arábia Saudita'),
  ('Al Qadsiah FC', 'Arábia Saudita'),
  ('Al Wehda FC', 'Arábia Saudita'),
  ('Al-Adalh FC', 'Arábia Saudita'),
  ('Al-Ain FC', 'Arábia Saudita'),
  ('Al-Ansar', 'Arábia Saudita'),
  ('Al-Batin', 'Arábia Saudita'),
  ('Al-Diriyah Club', 'Arábia Saudita'),
  ('Al-Ettifaq FC', 'Arábia Saudita'),
  ('Al-Faisaly FC', 'Arábia Saudita'),
  ('Al-Feiha FC', 'Arábia Saudita'),
  ('Al-Khaleej FC', 'Arábia Saudita'),
  ('Al-Kholood', 'Arábia Saudita'),
  ('Al-Najma', 'Arábia Saudita'),
  ('Al-Nassr', 'Arábia Saudita'),
  ('Al-Orobah FC', 'Arábia Saudita'),
  ('Al-Raed FC', 'Arábia Saudita'),
  ('Al-Riyadh SC', 'Arábia Saudita'),
  ('Al-Shabab Football Club', 'Arábia Saudita'),
  ('Al-Shoalah', 'Arábia Saudita'),
  ('Al-Taawon FC', 'Arábia Saudita'),
  ('Al-Tai FC', 'Arábia Saudita'),
  ('Al-Zulfi FC', 'Arábia Saudita'),
  ('Damac Club', 'Arábia Saudita'),
  ('Hajer Club', 'Arábia Saudita'),
  ('Najran SC', 'Arábia Saudita'),
  ('Neom SC', 'Arábia Saudita'),
  ('Ohod Club', 'Arábia Saudita'),
  ('AS Khroub', 'Argélia'),
  ('ASM Oran', 'Argélia'),
  ('ASO Chlef', 'Argélia'),
  ('CA Batna', 'Argélia'),
  ('CA Bordj Bou Arréridj', 'Argélia'),
  ('CMB Thénia', 'Argélia'),
  ('CR Belouizdad', 'Argélia'),
  ('CS Constantine', 'Argélia'),
  ('DRB Tadjenanet', 'Argélia'),
  ('ES Sétif', 'Argélia'),
  ('JS Kabylie', 'Argélia'),
  ('JS Saoura', 'Argélia'),
  ('JSM Béjaïa', 'Argélia'),
  ('MC Algiers', 'Argélia'),
  ('MC El Eulma', 'Argélia'),
  ('MC Saïda', 'Argélia'),
  ('Medea Olympic', 'Argélia'),
  ('MO Béjaïa', 'Argélia'),
  ('MO Constantine', 'Argélia'),
  ('Mouloudia Club of Oran', 'Argélia'),
  ('NA Hussein Dey', 'Argélia'),
  ('NC Magra', 'Argélia'),
  ('Paradou AC', 'Argélia'),
  ('RC Kouba', 'Argélia'),
  ('Union Sportive Madinet El Harrach', 'Argélia'),
  ('US Souf', 'Argélia'),
  ('USM Alger', 'Argélia'),
  ('USM Bel-Abbès', 'Argélia'),
  ('USM Blida', 'Argélia'),
  ('WA Tlemcen', 'Argélia'),
  ('Argentino de Quilmes', 'Argentina'),
  ('Argentinos Juniors', 'Argentina'),
  ('Atlético Tucumán', 'Argentina'),
  ('Club Agropecuario Argentino', 'Argentina'),
  ('Club Almagro', 'Argentina'),
  ('Club Almirante Brown', 'Argentina'),
  ('Club Atlético Aldosivi', 'Argentina'),
  ('Club Atlético Argentino del Sud', 'Argentina'),
  ('Club Atlético Atlanta', 'Argentina'),
  ('Club Atlético Banfield', 'Argentina'),
  ('Club Atlético Brown', 'Argentina'),
  ('Club Atlético Chaco For Ever', 'Argentina'),
  ('Club Atlético Colón', 'Argentina'),
  ('Club Atlético Huracán', 'Argentina'),
  ('Club Atlético Independiente', 'Argentina'),
  ('Club Atlético Juventud Unida Universitario', 'Argentina'),
  ('Club Atlético Lanús', 'Argentina'),
  ('Club Atlético Los Andes', 'Argentina'),
  ('Club Atlético Mitre', 'Argentina'),
  ('Club Atlético Nueva Chicago', 'Argentina'),
  ('Club Atlético River Plate', 'Argentina'),
  ('Club Atlético Rosario Central', 'Argentina'),
  ('Club Atlético Talleres de Remedios de Escalada', 'Argentina'),
  ('Club Atlético Tigre', 'Argentina'),
  ('Club Atlético Vélez Sarsfield', 'Argentina'),
  ('Club Deportivo Morón', 'Argentina'),
  ('Club Social y Atlético Guillermo Brown', 'Argentina'),
  ('Club Social y Deportivo Flandria', 'Argentina'),
  ('Club Tristán Suárez', 'Argentina'),
  ('Club y Biblioteca Ramón Santamarina', 'Argentina'),
  ('Crucero del Norte Mutual Club', 'Argentina'),
  ('Defensa y Justicia', 'Argentina'),
  ('Defensores Unidos', 'Argentina'),
  ('Deportivo Armenio', 'Argentina'),
  ('Deportivo Español', 'Argentina'),
  ('Deportivo Riestra', 'Argentina'),
  ('Estudiantes de La Plata', 'Argentina'),
  ('Ferro Carril Oeste', 'Argentina'),
  ('Gimnasia y Esgrima de Jujuy', 'Argentina'),
  ('Gimnasia y Esgrima de Mendoza', 'Argentina'),
  ('Godoy Cruz Antonio Tomba', 'Argentina'),
  ('Independiente Rivadavia', 'Argentina'),
  ('Instituto Atlético Central Córdoba', 'Argentina'),
  ('Juventud Unida de Gualeguaychú', 'Argentina'),
  ('Newell''s Old Boys', 'Argentina'),
  ('Quilmes Atlético Club', 'Argentina'),
  ('Racing Club', 'Argentina'),
  ('Racing de Córdoba', 'Argentina'),
  ('Real Madrid', 'Argentina'),
  ('San Martín de San Juan', 'Argentina'),
  ('Sarmiento', 'Argentina'),
  ('Sportivo Dock Sud', 'Argentina'),
  ('Talleres de Córdoba', 'Argentina'),
  ('Tiro al aire', 'Argentina'),
  ('Unión de Santa Fe', 'Argentina'),
  ('Villa Dálmine', 'Argentina'),
  ('Alashkert FC', 'Arménia'),
  ('BKMA Yerevan', 'Arménia'),
  ('FC Ararat Yerevan', 'Arménia'),
  ('FC Ararat-Armenia', 'Arménia'),
  ('FC Mika', 'Arménia'),
  ('FC Noah', 'Arménia'),
  ('FC Pyunik', 'Arménia'),
  ('FC Urartu', 'Arménia'),
  ('FC Van', 'Arménia'),
  ('FC West Armenia', 'Arménia'),
  ('Gandzasar-Kapan FC', 'Arménia'),
  ('Junior Sevan FC', 'Arménia'),
  ('Lernayin Artsakh Stepanakert', 'Arménia'),
  ('Noravank SC', 'Arménia'),
  ('Shirak FC', 'Arménia'),
  ('SV River Plate Aruba', 'Aruba'),
  ('Adelaide City Football Club', 'Austrália'),
  ('Adelaide United FC', 'Austrália'),
  ('Adelaide United Football Club', 'Austrália'),
  ('APIA Leichhardt', 'Austrália'),
  ('Brisbane Roar FC', 'Austrália'),
  ('Central Coast Mariners FC', 'Austrália'),
  ('Gold Coast United FC', 'Austrália'),
  ('Macarthur FC', 'Austrália'),
  ('Marconi Stallions FC', 'Austrália'),
  ('Melbourne City FC', 'Austrália'),
  ('Melbourne Knights Football Club', 'Austrália'),
  ('Melbourne Victory FC', 'Austrália'),
  ('Newcastle Jets FC', 'Austrália'),
  ('Perth Glory FC', 'Austrália'),
  ('South Melbourne Football Club', 'Austrália'),
  ('Sydney FC', 'Austrália'),
  ('Sydney Olympic FC', 'Austrália'),
  ('Sydney United FC', 'Austrália'),
  ('Western Sydney Wanderers FC', 'Austrália'),
  ('Western United FC', 'Austrália'),
  ('Wollongong Wolves FC', 'Austrália'),
  ('1. Simmeringer SC', 'Áustria'),
  ('Admira Wacker', 'Áustria'),
  ('Brigittenauer AC', 'Áustria'),
  ('DSV Leoben', 'Áustria'),
  ('FC Blau-Weiß Linz', 'Áustria'),
  ('FC Gratkorn', 'Áustria'),
  ('FC Juniors OÖ', 'Áustria'),
  ('FC Liefering', 'Áustria'),
  ('FC Lustenau 07', 'Áustria'),
  ('FC Red Bull Salzburg', 'Áustria'),
  ('FC Wacker Innsbruck', 'Áustria'),
  ('FC Wien', 'Áustria'),
  ('First Vienna FC', 'Áustria'),
  ('FK Austria Wien', 'Áustria'),
  ('Floridsdorfer AC', 'Áustria'),
  ('Grazer AK', 'Áustria'),
  ('Kapfenberger SV', 'Áustria'),
  ('Kremser SC', 'Áustria'),
  ('LASK Linz', 'Áustria'),
  ('SC Austria Lustenau', 'Áustria'),
  ('SC Rheindorf Altach', 'Áustria'),
  ('SC Schwarz-Weiß Bregenz', 'Áustria'),
  ('SC Wacker Wien', 'Áustria'),
  ('SC Wiener Neustadt', 'Áustria'),
  ('SK Admira Wien', 'Áustria'),
  ('SK Austria Klagenfurt', 'Áustria'),
  ('SK Rapid Wien', 'Áustria'),
  ('SK Sturm Graz', 'Áustria'),
  ('SK Vorwärts Steyr', 'Áustria'),
  ('SKN St. Pölten', 'Áustria'),
  ('SV Austria Salzburg', 'Áustria'),
  ('SV Grödig', 'Áustria'),
  ('SV Horn', 'Áustria'),
  ('SV Lafnitz', 'Áustria'),
  ('SV Ried', 'Áustria'),
  ('TSV Hartberg', 'Áustria'),
  ('Union Kleinmünchen Linz', 'Áustria'),
  ('Vienna Cricket and Football-Club', 'Áustria'),
  ('VSE St. Pölten', 'Áustria'),
  ('Wiener Sport-Club', 'Áustria'),
  ('Wolfsberger AC', 'Áustria'),
  ('WSG Tirol', 'Áustria'),
  ('Young Violets Austria Wien', 'Áustria'),
  ('Ağsu FK', 'Azerbaijão'),
  ('Araz PFK', 'Azerbaijão'),
  ('Araz Saatli', 'Azerbaijão'),
  ('Avtomobilçi Yevlax FK', 'Azerbaijão'),
  ('Azeri Baku FK', 'Azerbaijão'),
  ('Bakili Baku', 'Azerbaijão'),
  ('Baku Sporting', 'Azerbaijão'),
  ('Bine FK', 'Azerbaijão'),
  ('Çıraqqala Siyəzən FK', 'Azerbaijão'),
  ('Difai FK', 'Azerbaijão'),
  ('Energetik FC', 'Azerbaijão'),
  ('FC Absheron', 'Azerbaijão'),
  ('FC Shahdag Qusar', 'Azerbaijão'),
  ('FK Daşqın Zaqatala', 'Azerbaijão'),
  ('FK Gänclärbirliyi Sumqayit', 'Azerbaijão'),
  ('FK Göyazan Qazax', 'Azerbaijão'),
  ('FK Karvan', 'Azerbaijão'),
  ('FK Keşla-2', 'Azerbaijão'),
  ('FK Masallı', 'Azerbaijão'),
  ('FK MKT Araz', 'Azerbaijão'),
  ('FK Neftqaz Bakı', 'Azerbaijão'),
  ('FK Pambiqci Neftcala', 'Azerbaijão'),
  ('FK Qaradağ', 'Azerbaijão'),
  ('FK Sabah-2', 'Azerbaijão'),
  ('FK Sabail-2', 'Azerbaijão'),
  ('FK Şərurspor', 'Azerbaijão'),
  ('FK Shamkir', 'Azerbaijão'),
  ('FK Zira-2', 'Azerbaijão'),
  ('Gabala FC', 'Azerbaijão'),
  ('Ganjabasar FC', 'Azerbaijão'),
  ('Imishli', 'Azerbaijão'),
  ('Kapaz PFC', 'Azerbaijão'),
  ('Kürmük Qakh FK', 'Azerbaijão'),
  ('MOIK Baku', 'Azerbaijão'),
  ('Neftchi Baku PFC', 'Azerbaijão'),
  ('PFK Neftçi-2', 'Azerbaijão'),
  ('Plastik Salyan FK', 'Azerbaijão'),
  ('Qarabağ FK', 'Azerbaijão'),
  ('Ravan Baku FC', 'Azerbaijão'),
  ('Sabah Football Club', 'Azerbaijão'),
  ('Səbail FK', 'Azerbaijão'),
  ('Shamakhi FK', 'Azerbaijão'),
  ('Sharurspor PFK', 'Azerbaijão'),
  ('Shirvan FK', 'Azerbaijão'),
  ('Şirvan Kürdəmir FK', 'Azerbaijão'),
  ('Şirvan Şamaxı FK', 'Azerbaijão'),
  ('Sumgayit PFC', 'Azerbaijão'),
  ('Turan Tovuz PFK', 'Azerbaijão'),
  ('Ümid FK', 'Azerbaijão'),
  ('Zagatala PFK', 'Azerbaijão'),
  ('Zira FK', 'Azerbaijão'),
  ('Abahani Limited Dhaka', 'Bangladeche'),
  ('Arambagh Krira Sangha', 'Bangladeche'),
  ('Bashundhara Kings', 'Bangladeche'),
  ('Brothers Union', 'Bangladeche'),
  ('Chittagong Mohammedan SC', 'Bangladeche'),
  ('Feni Soccer Club', 'Bangladeche'),
  ('Mohammedan SC', 'Bangladeche'),
  ('Muktijoddha Sangsad KC', 'Bangladeche'),
  ('Narayanganj Suktara Sangsad', 'Bangladeche'),
  ('Rahmatganj MFS', 'Bangladeche'),
  ('Saif Sporting Club', 'Bangladeche'),
  ('Sheikh Jamal Dhanmondi Club', 'Bangladeche'),
  ('Sheikh Russel KC', 'Bangladeche'),
  ('Team BJMC', 'Bangladeche'),
  ('Uttar Baridhara SC', 'Bangladeche'),
  ('Al Ettihad Club', 'Barém'),
  ('Al Hala SC', 'Barém'),
  ('Al-Khaldiya SC', 'Barém'),
  ('Al-Muharraq SC', 'Barém'),
  ('Al-Najma', 'Barém'),
  ('Al-Shabab Club', 'Barém'),
  ('Bahrain SC', 'Barém'),
  ('Busaiteen Club', 'Barém'),
  ('East Riffa Club', 'Barém'),
  ('Hidd SCC', 'Barém'),
  ('Malkiya Club', 'Barém'),
  ('Manama Club', 'Barém'),
  ('Riffa SC', 'Barém'),
  ('Cercle Brugge KSV', 'Bélgica'),
  ('Club Brugge KV', 'Bélgica'),
  ('FC Verbroedering Dender Eendracht Hekelgem', 'Bélgica'),
  ('K Beerschot VA', 'Bélgica'),
  ('K. Berchem Sport', 'Bélgica'),
  ('K. Patro Eisden Maasmechelen', 'Bélgica'),
  ('K. Tubantia Borgerhout VK', 'Bélgica'),
  ('KAA Gent', 'Bélgica'),
  ('KAS Eupen', 'Bélgica'),
  ('KRC Genk', 'Bélgica'),
  ('KRC Mechelen', 'Bélgica'),
  ('KSV Roeselare', 'Bélgica'),
  ('KV Kortrijk', 'Bélgica'),
  ('KV Mechelen', 'Bélgica'),
  ('KV Oostende', 'Bélgica'),
  ('KVC Westerlo', 'Bélgica'),
  ('Lommel SK', 'Bélgica'),
  ('Oud-Heverlee Leuven', 'Bélgica'),
  ('RAAL La Louvière', 'Bélgica'),
  ('RE Virton', 'Bélgica'),
  ('RFC de Liège', 'Bélgica'),
  ('RFC Seraing', 'Bélgica'),
  ('RFC Tournai', 'Bélgica'),
  ('ROC de Charleroi-Marchienne', 'Bélgica'),
  ('Royal Antwerp FC', 'Bélgica'),
  ('Royal Charleroi SC', 'Bélgica'),
  ('Royale Union Saint-Gilloise', 'Bélgica'),
  ('Royale Union Tubize-Braine', 'Bélgica'),
  ('RSC Anderlecht', 'Bélgica'),
  ('RWDM Brussels', 'Bélgica'),
  ('SC Eendracht Aalst', 'Bélgica'),
  ('Sint-Truidense VV', 'Bélgica'),
  ('Sportkring Beveren', 'Bélgica'),
  ('Standard Liège', 'Bélgica'),
  ('SV Zulte Waregem', 'Bélgica'),
  ('Ajijas Cotonou', 'Benim'),
  ('Akanké FC', 'Benim'),
  ('AS Cotonou', 'Benim'),
  ('AS Dragons FC de l''Ouémé', 'Benim'),
  ('AS Police', 'Benim'),
  ('AS Tonnerre de Bohicon', 'Benim'),
  ('ASPAC FC', 'Benim'),
  ('Association Sportive Oussou Saka', 'Benim'),
  ('Avrankou Omnisport FC', 'Benim'),
  ('Ayema FC', 'Benim'),
  ('Béké Bembèrèkè', 'Benim'),
  ('Buffles du Borgou FC', 'Benim'),
  ('Dynamo Abomey FC', 'Benim'),
  ('Dynamo Unacob FC de Parakou', 'Benim'),
  ('Energie FC', 'Benim'),
  ('ESAE FC', 'Benim'),
  ('Espoir FC', 'Benim'),
  ('Etoile Sportive Porto-Novo', 'Benim'),
  ('Forces Armées', 'Benim'),
  ('Hodio FC', 'Benim'),
  ('JA Plateau', 'Benim'),
  ('Lions de l''Atakory', 'Benim'),
  ('Mambas Noirs FC', 'Benim'),
  ('Mogas 90 FC', 'Benim'),
  ('Panthères FC', 'Benim'),
  ('Postel Sport FC', 'Benim'),
  ('Requins de l''Atlantique FC', 'Benim'),
  ('Soleil FC', 'Benim'),
  ('Toffa Cotonou', 'Benim'),
  ('Université Nationale du Bénin FC', 'Benim'),
  ('USS Kraké', 'Benim'),
  ('ABFF U-19', 'Bielorrússia'),
  ('Bumprom Gomel', 'Bielorrússia'),
  ('FC Arsenal Dzerzhinsk', 'Bielorrússia'),
  ('FC Astraviec', 'Bielorrússia'),
  ('FC Baranovichi', 'Bielorrússia'),
  ('FC BATE Borisov', 'Bielorrússia'),
  ('FC BATE-2 Borisov', 'Bielorrússia'),
  ('FC Belshina Bobruisk', 'Bielorrússia'),
  ('FC Dinamo Minsk', 'Bielorrússia'),
  ('FC Dinamo-2 Minsk', 'Bielorrússia'),
  ('FC Dinamo-Juni Minsk', 'Bielorrússia'),
  ('FC Dnepr Mogilev', 'Bielorrússia'),
  ('FC DSK Gomel', 'Bielorrússia'),
  ('FC Dynamo Brest', 'Bielorrússia'),
  ('FC Gomel', 'Bielorrússia'),
  ('FC Granit Mikashevichi', 'Bielorrússia'),
  ('FC Homieĺ-2', 'Bielorrússia'),
  ('FC Isloch Minsk Raion', 'Bielorrússia'),
  ('FC Khimik Svetlogorsk', 'Bielorrússia'),
  ('FC Klechesk Kletsk', 'Bielorrússia'),
  ('FC Kobrin', 'Bielorrússia'),
  ('FC Krumkačy Miensk', 'Bielorrússia'),
  ('FC Lida', 'Bielorrússia'),
  ('FC Luninets', 'Bielorrússia'),
  ('FC Maladziečna', 'Bielorrússia'),
  ('FC Maxline Viciebsk', 'Bielorrússia'),
  ('FC Minsk', 'Bielorrússia'),
  ('FC Minsk-2', 'Bielorrússia'),
  ('FC Naftan Novopolotsk', 'Bielorrússia'),
  ('FC Neman Grodno', 'Bielorrússia'),
  ('FC Niva Doŭbizna', 'Bielorrússia'),
  ('FC Orsha', 'Bielorrússia'),
  ('FC Oshmyany', 'Bielorrússia'),
  ('FC Osipovichi', 'Bielorrússia'),
  ('FC Salihorsk', 'Bielorrússia'),
  ('FC Shakhtyor Salihorsk', 'Bielorrússia'),
  ('FC SKA-1938', 'Bielorrússia'),
  ('FC Slavia-Mozyr', 'Bielorrússia'),
  ('FC Slonim', 'Bielorrússia'),
  ('FC Slutsk-2024', 'Bielorrússia'),
  ('FC Smolevichi', 'Bielorrússia'),
  ('FC Smorgon', 'Bielorrússia'),
  ('FC Torpedo-BelAZ Zhodino', 'Bielorrússia'),
  ('FC Torpedo-BelAZ-2', 'Bielorrússia'),
  ('FC Torpedo-Kadino Mogilev', 'Bielorrússia'),
  ('FC Torpedo-MAZ Minsk', 'Bielorrússia'),
  ('FC UAS Zhitkovichi', 'Bielorrússia'),
  ('FC Underdog Chist', 'Bielorrússia'),
  ('FC Unixlabs', 'Bielorrússia'),
  ('FC Vitebsk', 'Bielorrússia'),
  ('FC Volna Pinsk', 'Bielorrússia'),
  ('FC ZLiN Gomel', 'Bielorrússia'),
  ('FK Shakhtyor-2 Salihorsk', 'Bielorrússia'),
  ('AMORETTI', 'Bolívia'),
  ('CD Jorge Wilstermann', 'Bolívia'),
  ('CD San Antonio Bulo Bulo', 'Bolívia'),
  ('CD San José', 'Bolívia'),
  ('Chaco Petrolero', 'Bolívia'),
  ('Club 31 de Octubre', 'Bolívia'),
  ('Club Always Ready', 'Bolívia'),
  ('Club Aurora', 'Bolívia'),
  ('Club Blooming', 'Bolívia'),
  ('Club Bolívar', 'Bolívia'),
  ('Club Deportivo Petrolero', 'Bolívia'),
  ('Club Destroyers', 'Bolívia'),
  ('Club Real Potosí', 'Bolívia'),
  ('Club Universitario', 'Bolívia'),
  ('Deportivo Municipal de La Paz', 'Bolívia'),
  ('Guabirá', 'Bolívia'),
  ('Litoral de Cochabamba', 'Bolívia'),
  ('Municipal Real Mamoré', 'Bolívia'),
  ('Nacional Potosí', 'Bolívia'),
  ('Oriente Petrolero', 'Bolívia'),
  ('Sport Boys Warnes', 'Bolívia'),
  ('The Strongest', 'Bolívia'),
  ('Universitario de La Paz', 'Bolívia'),
  ('Universitario de Pando', 'Bolívia'),
  ('FK Borac Banja Luka', 'Bósnia e Herzegovina'),
  ('FK Borac Šamac', 'Bósnia e Herzegovina'),
  ('FK BSK Banja Luka', 'Bósnia e Herzegovina'),
  ('FK Budućnost Banovići', 'Bósnia e Herzegovina'),
  ('FK Drina HE Višegrad', 'Bósnia e Herzegovina'),
  ('FK Drina Zvornik', 'Bósnia e Herzegovina'),
  ('FK Famos Vojkovići', 'Bósnia e Herzegovina'),
  ('FK Igman Konjic', 'Bósnia e Herzegovina'),
  ('FK Kozara Gradiška', 'Bósnia e Herzegovina'),
  ('FK Krupa', 'Bósnia e Herzegovina'),
  ('FK Laktaši', 'Bósnia e Herzegovina'),
  ('FK Leotar', 'Bósnia e Herzegovina'),
  ('FK Ljubić Prnjavor', 'Bósnia e Herzegovina'),
  ('FK Mladost Doboj Kakanj', 'Bósnia e Herzegovina'),
  ('FK Mladost Gacko', 'Bósnia e Herzegovina'),
  ('FK Mladost Velika Obarska', 'Bósnia e Herzegovina'),
  ('FK Modriča', 'Bósnia e Herzegovina'),
  ('FK Podrinje Janja', 'Bósnia e Herzegovina'),
  ('FK Proleter Teslić', 'Bósnia e Herzegovina'),
  ('FK Radnik Bijeljina', 'Bósnia e Herzegovina'),
  ('FK Rudar Kakanj', 'Bósnia e Herzegovina'),
  ('FK Rudar Prijedor', 'Bósnia e Herzegovina'),
  ('FK Rudar Ugljevik', 'Bósnia e Herzegovina'),
  ('FK Sarajevo', 'Bósnia e Herzegovina'),
  ('FK Slavija Istočno Sarajevo', 'Bósnia e Herzegovina'),
  ('FK Sloboda Mrkonjić Grad', 'Bósnia e Herzegovina'),
  ('FK Sloboda Novi Grad', 'Bósnia e Herzegovina'),
  ('FK Sloboda Tuzla', 'Bósnia e Herzegovina'),
  ('FK Sloga Doboj', 'Bósnia e Herzegovina'),
  ('FK Sutjeska Foča', 'Bósnia e Herzegovina'),
  ('FK Tekstilac Derventa', 'Bósnia e Herzegovina'),
  ('FK Tuzla City', 'Bósnia e Herzegovina'),
  ('FK Velež Mostar', 'Bósnia e Herzegovina'),
  ('FK Željezničar Sarajevo', 'Bósnia e Herzegovina'),
  ('FK Zvijezda 09', 'Bósnia e Herzegovina'),
  ('HNK Brotnjo Čitluk', 'Bósnia e Herzegovina'),
  ('HNK Orašje', 'Bósnia e Herzegovina'),
  ('HNK Sloga Uskoplje', 'Bósnia e Herzegovina'),
  ('HŠK Posušje', 'Bósnia e Herzegovina'),
  ('HŠK Zrinjski Mostar', 'Bósnia e Herzegovina'),
  ('NK Bosna Visoko', 'Bósnia e Herzegovina'),
  ('NK Čelik Zenica', 'Bósnia e Herzegovina'),
  ('NK GOŠK Gabela', 'Bósnia e Herzegovina'),
  ('NK Iskra Bugojno', 'Bósnia e Herzegovina'),
  ('NK Jedinstvo Bihać', 'Bósnia e Herzegovina'),
  ('NK Metalleghe-BSI', 'Bósnia e Herzegovina'),
  ('NK SAŠK Napredak', 'Bósnia e Herzegovina'),
  ('NK Široki Brijeg', 'Bósnia e Herzegovina'),
  ('NK Travnik', 'Bósnia e Herzegovina'),
  ('NK Vitez', 'Bósnia e Herzegovina'),
  ('NK Žepče', 'Bósnia e Herzegovina'),
  ('NK Zvijezda Gradačac', 'Bósnia e Herzegovina'),
  ('OFK Gradina', 'Bósnia e Herzegovina'),
  ('Black Forest FC', 'Botsuana'),
  ('Botswana Defence Force XI FC', 'Botsuana'),
  ('Botswana Meat Commission FC', 'Botsuana'),
  ('Botswana Railways Highlanders', 'Botsuana'),
  ('ECCO City Green', 'Botsuana'),
  ('Extension Gunners FC', 'Botsuana'),
  ('FC Satmos', 'Botsuana'),
  ('Gaborone United SC', 'Botsuana'),
  ('Great North Tigers FC', 'Botsuana'),
  ('Jwaneng Galaxy FC', 'Botsuana'),
  ('Matebele FC', 'Botsuana'),
  ('Miscellaneous SC Serowe', 'Botsuana'),
  ('Mochudi Centre Chiefs', 'Botsuana'),
  ('Mogoditshane Fighters', 'Botsuana'),
  ('Motlakase Power Dynamos', 'Botsuana'),
  ('Nico United', 'Botsuana'),
  ('Notwane FC', 'Botsuana'),
  ('Orapa United FC', 'Botsuana'),
  ('Police XI', 'Botsuana'),
  ('Sankoyo Bush Bucks', 'Botsuana'),
  ('Sharps Shooting Stars FC', 'Botsuana'),
  ('TAFIC FC', 'Botsuana'),
  ('TASC FC', 'Botsuana'),
  ('Township Rollers FC', 'Botsuana'),
  ('Uniao Flamengo Santos FC', 'Botsuana'),
  ('Wonder Sporting Club', 'Botsuana'),
  ('Academia Desportiva Manthiqueira Futebol', 'Brasil'),
  ('Agremiação Sportiva Arapiraquense', 'Brasil'),
  ('Águia de Marabá Futebol Clube', 'Brasil'),
  ('Amazonas Futebol Clube', 'Brasil'),
  ('America Football Club', 'Brasil'),
  ('América Futebol Clube', 'Brasil'),
  ('Americano Futebol Clube', 'Brasil'),
  ('Anápolis Futebol Clube', 'Brasil'),
  ('Associação Atlética Anapolina', 'Brasil'),
  ('Associação Atlética Caldense', 'Brasil'),
  ('Associação Atlética Coruripe', 'Brasil'),
  ('Associação Atlética Internacional', 'Brasil'),
  ('Associação Atlética Ponte Preta', 'Brasil'),
  ('Associação Atlética Portuguesa', 'Brasil'),
  ('Associação Chapecoense de Futebol', 'Brasil'),
  ('Associação Cultural Esporte Clube Baraúnas', 'Brasil'),
  ('Associação Desportiva Bahia de Feira', 'Brasil'),
  ('Associação Desportiva Cabofriense', 'Brasil'),
  ('Associação Desportiva Confiança', 'Brasil'),
  ('Associação Desportiva Ferroviária', 'Brasil'),
  ('Associação Desportiva Recreativa e Cultural Icasa', 'Brasil'),
  ('Associação Desportiva São Caetano', 'Brasil'),
  ('Associação Ferroviária de Esportes', 'Brasil'),
  ('Associação Portuguesa de Desportos', 'Brasil'),
  ('Atlético Acreano', 'Brasil'),
  ('Atlético Clube Goianiense', 'Brasil'),
  ('Audax São Paulo Esporte Clube', 'Brasil'),
  ('Avaí Futebol Clube', 'Brasil'),
  ('Bangu Atlético Clube', 'Brasil'),
  ('Boa Esporte Clube', 'Brasil'),
  ('Boavista Sport Club', 'Brasil'),
  ('Bonsucesso Futebol Clube', 'Brasil'),
  ('Botafogo FR', 'Brasil'),
  ('Botafogo Futebol Clube', 'Brasil'),
  ('Brasília Futebol Clube', 'Brasil'),
  ('Brasiliense Futebol Clube', 'Brasil'),
  ('Brasilis Futebol Clube', 'Brasil'),
  ('CA Estudantes de São Paulo', 'Brasil'),
  ('Campinas FC', 'Brasil'),
  ('Campinense Clube', 'Brasil'),
  ('Campo Grande AC', 'Brasil'),
  ('Ceará Sporting Club', 'Brasil'),
  ('Central Sport Club', 'Brasil'),
  ('Centro Sportivo Alagoano', 'Brasil'),
  ('Club Athletico Paranaense', 'Brasil'),
  ('Club Sportivo Sergipe', 'Brasil'),
  ('Clube Atlético Juventus', 'Brasil'),
  ('Clube Atlético Linense', 'Brasil'),
  ('Clube Atlético Metropolitano', 'Brasil'),
  ('Clube Atlético Mineiro', 'Brasil'),
  ('Clube Atlético Paulistinha', 'Brasil'),
  ('Clube Atlético Penapolense', 'Brasil'),
  ('Clube Atlético Sorocaba', 'Brasil'),
  ('Clube de Regatas Brasil', 'Brasil'),
  ('Clube de Regatas do Flamengo', 'Brasil'),
  ('Clube do Remo', 'Brasil'),
  ('Clube Esportivo Lajeadense', 'Brasil'),
  ('Clube Esportivo Nova Esperança', 'Brasil'),
  ('Clube Náutico Capibaribe', 'Brasil'),
  ('Colo Colo de Futebol e Regatas', 'Brasil'),
  ('Comercial Futebol Clube', 'Brasil'),
  ('Coritiba FC', 'Brasil'),
  ('CR Vasco da Gama', 'Brasil'),
  ('Criciúma Esporte Clube', 'Brasil'),
  ('Cruzeiro EC', 'Brasil'),
  ('Cuiabá Esporte Clube', 'Brasil'),
  ('Deportivo La Coruña Brasil Futebol Clube', 'Brasil'),
  ('Duque de Caxias Futebol Clube', 'Brasil'),
  ('EC Vitória', 'Brasil'),
  ('Esporte Clube Águia Negra', 'Brasil'),
  ('Esporte Clube Bahia', 'Brasil'),
  ('Esporte Clube Comercial', 'Brasil'),
  ('Esporte Clube Democrata', 'Brasil'),
  ('Esporte Clube Flamengo', 'Brasil'),
  ('Esporte Clube Juventude', 'Brasil'),
  ('Esporte Clube Noroeste', 'Brasil'),
  ('Esporte Clube Novo Hamburgo', 'Brasil'),
  ('Esporte Clube Primeiro Passo Vitória da Conquista', 'Brasil'),
  ('Esporte Clube Santo André', 'Brasil'),
  ('Esporte Clube São Bento', 'Brasil'),
  ('Esporte Clube São Luiz', 'Brasil'),
  ('Esporte Clube XV de Novembro', 'Brasil'),
  ('Ferroviário Atlético Clube', 'Brasil'),
  ('Figueirense Futebol Clube', 'Brasil'),
  ('Fluminense de Feira Futebol Clube', 'Brasil'),
  ('Fluminense FC', 'Brasil'),
  ('Fortaleza EC', 'Brasil'),
  ('Friburguense Atlético Clube', 'Brasil'),
  ('Galícia Esporte Clube', 'Brasil'),
  ('Globo Futebol Clube', 'Brasil'),
  ('Goiânia Esporte Clube', 'Brasil'),
  ('Goiás Esporte Clube', 'Brasil'),
  ('Goytacaz Futebol Clube', 'Brasil'),
  ('Grêmio Barueri Futebol', 'Brasil'),
  ('Grêmio Esportivo Brasil', 'Brasil'),
  ('Grêmio FBPA', 'Brasil'),
  ('Grêmio Novorizontino', 'Brasil'),
  ('Guarani Futebol Clube', 'Brasil'),
  ('Guarany Sporting Club', 'Brasil'),
  ('Guaratinguetá Futebol', 'Brasil'),
  ('Ipatinga Futebol Clube', 'Brasil'),
  ('Ituano Futebol Clube', 'Brasil'),
  ('Joinville Esporte Clube', 'Brasil'),
  ('Londrina EC', 'Brasil'),
  ('Luverdense Esporte Clube', 'Brasil'),
  ('Macaé Esporte Futebol Clube', 'Brasil'),
  ('Madureira Esporte Clube', 'Brasil'),
  ('Marília Atlético Clube', 'Brasil'),
  ('Mirassol Futebol Clube', 'Brasil'),
  ('Mixto Esporte Clube', 'Brasil'),
  ('Mogi Mirim Esporte Clube', 'Brasil'),
  ('Moto Club de São Luís', 'Brasil'),
  ('Nacional Atlético Clube', 'Brasil'),
  ('Nacional Futebol Clube', 'Brasil'),
  ('Niteroiense FC', 'Brasil'),
  ('Nova Iguaçu Futebol Clube', 'Brasil'),
  ('Oeste Futebol Clube', 'Brasil'),
  ('Olaria Atlético Clube', 'Brasil'),
  ('Operário Ferroviário Esporte Clube', 'Brasil'),
  ('Operário Futebol Clube', 'Brasil'),
  ('Paraná Clube', 'Brasil'),
  ('Paulínia FC', 'Brasil'),
  ('Paulista Futebol Clube', 'Brasil'),
  ('Paysandu Sport Club', 'Brasil'),
  ('Porto Alegre Futebol Clube', 'Brasil'),
  ('Red Bull Bragantino', 'Brasil'),
  ('Red Bull Bragantino II', 'Brasil'),
  ('Rio Branco Atlético Clube', 'Brasil'),
  ('Rio Branco Esporte Clube', 'Brasil'),
  ('Rio Branco Football Club', 'Brasil'),
  ('Rio Claro Futebol Clube', 'Brasil'),
  ('River Atlético Clube', 'Brasil'),
  ('Salgueiro Atlético Clube', 'Brasil'),
  ('Sampaio Corrêa FC', 'Brasil'),
  ('Santa Cruz Futebol Clube', 'Brasil'),
  ('Santos FC', 'Brasil'),
  ('Santos Futebol Clube Amapá', 'Brasil'),
  ('São Bernardo Futebol Clube', 'Brasil'),
  ('São Carlos FC', 'Brasil'),
  ('São Cristóvão de Futebol e Regatas', 'Brasil'),
  ('São José Esporte Clube', 'Brasil'),
  ('São Paulo Athletic Club', 'Brasil'),
  ('São Paulo FC', 'Brasil'),
  ('São Raimundo Esporte Clube', 'Brasil'),
  ('SC Corinthians Paulista', 'Brasil'),
  ('SC Internacional', 'Brasil'),
  ('Sertãozinho Futebol Clube', 'Brasil'),
  ('Social Futebol Clube', 'Brasil'),
  ('Sociedade Desportiva Juazeirense', 'Brasil'),
  ('Sociedade Esportiva do Gama', 'Brasil'),
  ('Sociedade Esportiva e Recreativa Caxias do Sul', 'Brasil'),
  ('Sociedade Esportiva Palmeiras', 'Brasil'),
  ('Sociedade Esportiva Palmeiras B', 'Brasil'),
  ('Sociedade Imperatriz de Desportos', 'Brasil'),
  ('Sport Club Corinthians Alagoano', 'Brasil'),
  ('Sport Club Corinthians Paulista', 'Brasil'),
  ('Sport Club do Recife', 'Brasil'),
  ('Sumaré Atlético Clube', 'Brasil'),
  ('Tocantinópolis Esporte Clube', 'Brasil'),
  ('Tombense Futebol Clube', 'Brasil'),
  ('Treze Futebol Clube', 'Brasil'),
  ('Tuna Luso Brasileira', 'Brasil'),
  ('Tupi Football Club', 'Brasil'),
  ('Uberaba Sport Club', 'Brasil'),
  ('Uberlândia EC', 'Brasil'),
  ('União São João EC', 'Brasil'),
  ('Vila Nova Futebol Clube', 'Brasil'),
  ('Villa Nova Atlético Clube', 'Brasil'),
  ('Vitória Futebol Clube', 'Brasil'),
  ('Volta Redonda Futebol Clube', 'Brasil'),
  ('Ypiranga Clube', 'Brasil'),
  ('Ypiranga Futebol Clube', 'Brasil'),
  ('Duli Pengiran Muda Mahkota Football Club', 'Brunei'),
  ('Akademik Sofia', 'Bulgária'),
  ('Botev Plovdiv', 'Bulgária'),
  ('FC Arda', 'Bulgária'),
  ('FC CSKA 1948 Sofia', 'Bulgária'),
  ('FC Dunav Ruse', 'Bulgária'),
  ('FC Haskovo', 'Bulgária'),
  ('FC Hebar 1918', 'Bulgária'),
  ('FC Lokomotiv 1929 Sofia', 'Bulgária'),
  ('FC Lokomotiv Gorna Oryahovitsa', 'Bulgária'),
  ('FC Maritsa Plovdiv', 'Bulgária'),
  ('FC Pirin Blagoevgrad', 'Bulgária'),
  ('FC Tsarsko Selo', 'Bulgária'),
  ('FC Vereya', 'Bulgária'),
  ('FC Vihren Sandanski', 'Bulgária'),
  ('FC Vitosha Bistritsa', 'Bulgária'),
  ('FK Krumovgrad', 'Bulgária'),
  ('Lyubimetz 2007', 'Bulgária'),
  ('OFC Etar Veliko Tarnovo', 'Bulgária'),
  ('OFC Sliven 2000', 'Bulgária'),
  ('PFC Belasitsa Petrich', 'Bulgária'),
  ('PFC Beroe Stara Zagora', 'Bulgária'),
  ('PFC Cherno More Varna', 'Bulgária'),
  ('PFC CSKA Sofia', 'Bulgária'),
  ('PFC Dobrudzha Dobrich', 'Bulgária'),
  ('PFC Kaliakra Kavarna', 'Bulgária'),
  ('PFC Levski Sofia', 'Bulgária'),
  ('PFC Lokomotiv Mezdra', 'Bulgária'),
  ('PFC Lokomotiv Plovdiv', 'Bulgária'),
  ('PFC Ludogorets 1945', 'Bulgária'),
  ('PFC Marek Dupnitsa', 'Bulgária'),
  ('PFC Minyor Pernik', 'Bulgária'),
  ('PFC Montana', 'Bulgária'),
  ('PFC Naftex Burgas', 'Bulgária'),
  ('PFC Neftochimic Burgas', 'Bulgária'),
  ('PFC Pirin Gotse Delchev', 'Bulgária'),
  ('PFC Shumen 2010', 'Bulgária'),
  ('PFC Slavia Sofia', 'Bulgária'),
  ('PFC Spartak Varna', 'Bulgária'),
  ('PFC Svetkavitsa', 'Bulgária'),
  ('PFC Velbazhd Kyustendil', 'Bulgária'),
  ('POFC Botev Vratsa', 'Bulgária'),
  ('PSFC Chernomorets Burgas', 'Bulgária'),
  ('Septemvri Sofia PFC', 'Bulgária'),
  ('AS Maya', 'Burquina Faso'),
  ('AS SONABEL', 'Burquina Faso'),
  ('ASEC Koudougou', 'Burquina Faso'),
  ('ASF Bobo', 'Burquina Faso'),
  ('ASFA Yennenga', 'Burquina Faso'),
  ('Bobo Sport', 'Burquina Faso'),
  ('Bouloumpoukou FC', 'Burquina Faso'),
  ('Commune FC', 'Burquina Faso'),
  ('Étoile Filante de Ouagadougou', 'Burquina Faso'),
  ('Jeunesse Club de Bobo Dioulasso', 'Burquina Faso'),
  ('KOZAF', 'Burquina Faso'),
  ('Majestic FC', 'Burquina Faso'),
  ('Rahimo FC', 'Burquina Faso'),
  ('Rail Club du Kadiogo', 'Burquina Faso'),
  ('RC Bobo', 'Burquina Faso'),
  ('Salimata et Taséré FC', 'Burquina Faso'),
  ('Santos FC', 'Burquina Faso'),
  ('Silures Bobo-Dioulasso', 'Burquina Faso'),
  ('Sourou Sport de Tougan', 'Burquina Faso'),
  ('Union Sportive des Forces Armées', 'Burquina Faso'),
  ('US FRAN', 'Burquina Faso'),
  ('US Ouagadougou', 'Burquina Faso'),
  ('US Yatenga', 'Burquina Faso'),
  ('USCO Banfora', 'Burquina Faso'),
  ('Académie Tchité FC', 'Burundi'),
  ('Aigle Noir Makamba FC', 'Burundi'),
  ('AS Inter Star', 'Burundi'),
  ('Atlético Olympic FC', 'Burundi'),
  ('Burundi Sport Dynamik New Look', 'Burundi'),
  ('Espoir de Mutimbuzi', 'Burundi'),
  ('Flambeau de l’Est', 'Burundi'),
  ('Guêpiers du Lac', 'Burundi'),
  ('Le Messager FC de Bujumbara', 'Burundi'),
  ('Le Messager Ngozi FC', 'Burundi'),
  ('LLB Amasipiri FC', 'Burundi'),
  ('Lydia Ludic Burundi Académic', 'Burundi'),
  ('Maniema FC', 'Burundi'),
  ('Muzinga FC', 'Burundi'),
  ('Nyanza United', 'Burundi'),
  ('Olympique Star', 'Burundi'),
  ('Prince Louis FC', 'Burundi'),
  ('Royal FC de Muramvya', 'Burundi'),
  ('Rusizi FC', 'Burundi'),
  ('Tigre Noir Ruyigi', 'Burundi'),
  ('Vital''O FC', 'Burundi'),
  ('Volontaires FC', 'Burundi'),
  ('Bhutan Clearing FC', 'Butão'),
  ('Paro FC', 'Butão'),
  ('Phuentsholing United FC', 'Butão'),
  ('Tensung FC', 'Butão'),
  ('Thimphu City FC', 'Butão'),
  ('Transport United', 'Butão'),
  ('Ugyen Academy FC', 'Butão'),
  ('Yeedzin FC', 'Butão'),
  ('CS Mindelense', 'Cabo Verde'),
  ('Sporting Clube da Praia', 'Cabo Verde'),
  ('APEJES Academy', 'Camarões'),
  ('AS Lausanne de Yaoundé', 'Camarões'),
  ('AS Matelots', 'Camarões'),
  ('Astres FC', 'Camarões'),
  ('Bamboutos FC', 'Camarões'),
  ('Botafogo FC', 'Camarões'),
  ('Caïman Douala', 'Camarões'),
  ('Canon Yaoundé', 'Camarões'),
  ('Cosmos de Bafia', 'Camarões'),
  ('Coton Sport FC de Garoua', 'Camarões'),
  ('Danay FC', 'Camarões'),
  ('Dragon Club', 'Camarões'),
  ('Dynamo Douala', 'Camarões'),
  ('Eding Sport FC', 'Camarões'),
  ('Fovu Club', 'Camarões'),
  ('Gazelle FA', 'Camarões'),
  ('Impôts FC', 'Camarões'),
  ('Kadji Sports Academy', 'Camarões'),
  ('Lion Blessé', 'Camarões'),
  ('Mount Cameroon FC', 'Camarões'),
  ('New Star de Douala', 'Camarões'),
  ('Njala Quan Sports Academy', 'Camarões'),
  ('Oryx Douala', 'Camarões'),
  ('Panthère du Ndé', 'Camarões'),
  ('Racing FC Bafoussam', 'Camarões'),
  ('Renaissance FC de Ngoumou', 'Camarões'),
  ('Sable FC', 'Camarões'),
  ('Scorpion de Bey', 'Camarões'),
  ('Tiko United FC', 'Camarões'),
  ('Tonnerre Yaoundé', 'Camarões'),
  ('UMS de Loum', 'Camarões'),
  ('Union Douala', 'Camarões'),
  ('Unisport Bafang', 'Camarões'),
  ('Université FC de Ngaoundéré', 'Camarões'),
  ('Young Sports Academy Bamenda', 'Camarões'),
  ('Angkor Tiger FC', 'Camboja'),
  ('Asia Euro United', 'Camboja'),
  ('Boeung Ket FC', 'Camboja'),
  ('Build Bright University FC', 'Camboja'),
  ('Cambodian Army Association FC', 'Camboja'),
  ('CMAC FC', 'Camboja'),
  ('Electricite du Cambodge FC', 'Camboja'),
  ('Khemara Keila FC', 'Camboja'),
  ('Kirivong Sok Sen Chey FC', 'Camboja'),
  ('Life FC', 'Camboja'),
  ('Military Police', 'Camboja'),
  ('Naga World FC', 'Camboja'),
  ('National Police Commissary FC', 'Camboja'),
  ('Phnom Penh Crown FC', 'Camboja'),
  ('Post Tel Club', 'Camboja'),
  ('Preah Khan Reach Svay Rieng FC', 'Camboja'),
  ('Royal Cambodian Air Force FC', 'Camboja'),
  ('Soltilo Angkor FC', 'Camboja'),
  ('Visakha AFC', 'Camboja'),
  ('Wat Phnom FC', 'Camboja'),
  ('Western University FC', 'Camboja'),
  ('Atlético Ottawa', 'Canadá'),
  ('Brampton United', 'Canadá'),
  ('Brantford Galaxy', 'Canadá'),
  ('Burlington SC', 'Canadá'),
  ('Caribbean Selects', 'Canadá'),
  ('Cavalry FC', 'Canadá'),
  ('CF Montréal', 'Canadá'),
  ('Durham Flames', 'Canadá'),
  ('FC Continentals', 'Canadá'),
  ('FC Supra du Québec', 'Canadá'),
  ('FC Ukraine United', 'Canadá'),
  ('Forge FC', 'Canadá'),
  ('Hamilton City Soccer Club', 'Canadá'),
  ('HFX Wanderers FC', 'Canadá'),
  ('Inter Toronto FC', 'Canadá'),
  ('Kingsman SC', 'Canadá'),
  ('Kingston FC', 'Canadá'),
  ('London City Soccer Club', 'Canadá'),
  ('Mississauga Eagles FC', 'Canadá'),
  ('Montreal Impact Academy', 'Canadá'),
  ('Niagara United', 'Canadá'),
  ('Pacific FC', 'Canadá'),
  ('SC Toronto', 'Canadá'),
  ('SC Waterloo Region', 'Canadá'),
  ('Scarborough SC', 'Canadá'),
  ('Serbian White Eagles FC', 'Canadá'),
  ('Toronto Atomic FC', 'Canadá'),
  ('Toronto Croatia', 'Canadá'),
  ('Toronto FC', 'Canadá'),
  ('Trois-Rivières Attak', 'Canadá'),
  ('Valour FC', 'Canadá'),
  ('Vancouver FC', 'Canadá'),
  ('Vancouver Whitecaps FC', 'Canadá'),
  ('Windsor Stars', 'Canadá'),
  ('York Region Shooters', 'Canadá'),
  ('Al Ahli SC', 'Catar'),
  ('Al Kharaitiyat SC', 'Catar'),
  ('Al Sadd Sports Club', 'Catar'),
  ('Al-Arabi SC', 'Catar'),
  ('Al-Duhail SC', 'Catar'),
  ('Al-Gharafa SC', 'Catar'),
  ('Al-Khor Sports Club', 'Catar'),
  ('Al-Markhiya Sports Club', 'Catar'),
  ('Al-Mesaimeer Sports Club', 'Catar'),
  ('Al-Mu''aidar Sports Club', 'Catar'),
  ('Al-Rayyan', 'Catar'),
  ('Al-Sailiya Sports Club', 'Catar'),
  ('Al-Shahaniya Sports Club', 'Catar'),
  ('Al-Shamal Sports Club', 'Catar'),
  ('Al-Wakrah Sports Club', 'Catar'),
  ('El Jaish SC', 'Catar'),
  ('Qatar SC', 'Catar'),
  ('Umm Salal SC', 'Catar'),
  ('FC Aksu', 'Cazaquistão'),
  ('FC Aktobe', 'Cazaquistão'),
  ('FC Akzhayik', 'Cazaquistão'),
  ('FC Alma-Ata', 'Cazaquistão'),
  ('FC Altai Semey', 'Cazaquistão'),
  ('FC Arman', 'Cazaquistão'),
  ('FC Astana', 'Cazaquistão'),
  ('FC Atyrau', 'Cazaquistão'),
  ('FC Azhar', 'Cazaquistão'),
  ('FC Dinamo Almaty', 'Cazaquistão'),
  ('FC Dostyk', 'Cazaquistão'),
  ('FC Ekibastuzets', 'Cazaquistão'),
  ('FC Irtysh Pavlodar', 'Cazaquistão'),
  ('FC Kairat', 'Cazaquistão'),
  ('FC Kaisar', 'Cazaquistão'),
  ('FC Kyzylzhar', 'Cazaquistão'),
  ('FC Maktaaral', 'Cazaquistão'),
  ('FC Megasport', 'Cazaquistão'),
  ('FC Okzhetpes', 'Cazaquistão'),
  ('FC Ordabasy', 'Cazaquistão'),
  ('FC Shakhter Karagandy', 'Cazaquistão'),
  ('FC Taraz', 'Cazaquistão'),
  ('FC Tobol', 'Cazaquistão'),
  ('FC Turan', 'Cazaquistão'),
  ('FC Ulytau', 'Cazaquistão'),
  ('FC Vostok', 'Cazaquistão'),
  ('FC Yelimay', 'Cazaquistão'),
  ('FC Zhenis', 'Cazaquistão'),
  ('FC Zhetysu', 'Cazaquistão'),
  ('Kaspii Aqtau', 'Cazaquistão'),
  ('Gazelle FC', 'Chade'),
  ('Tourbillon FC', 'Chade'),
  ('AC Barnechea City', 'Chile'),
  ('Audax Italiano', 'Chile'),
  ('CCD Arturo Fernández Vial', 'Chile'),
  ('CD Palestino', 'Chile'),
  ('CD Universidad de Concepción', 'Chile'),
  ('CDP Curi', 'Chile'),
  ('Club de Deportes Green Cross', 'Chile'),
  ('Club de Deportes Limache', 'Chile'),
  ('Club Deportes Antofagasta', 'Chile'),
  ('Club Deportes Concepción', 'Chile'),
  ('Club Deportes La Serena', 'Chile'),
  ('Club Deportivo Huachipato', 'Chile'),
  ('Club Deportivo Magallanes', 'Chile'),
  ('Club Deportivo Ñublense', 'Chile'),
  ('Club Deportivo Universidad Católica', 'Chile'),
  ('Club Social de Deportes Rangers', 'Chile'),
  ('Club Social y Deportivo Colo Colo', 'Chile'),
  ('Club Universidad de Chile', 'Chile'),
  ('Cobreloa', 'Chile'),
  ('Cobresal', 'Chile'),
  ('Coquimbo Unido', 'Chile'),
  ('Deportes Copiapó', 'Chile'),
  ('Deportes Iquique', 'Chile'),
  ('Deportes Melipilla', 'Chile'),
  ('Deportes Puerto Montt', 'Chile'),
  ('Deportes Temuco', 'Chile'),
  ('Everton de Viña del Mar', 'Chile'),
  ('Lota Schwager', 'Chile'),
  ('O''Higgins FC', 'Chile'),
  ('San Luis de Quillota', 'Chile'),
  ('San Marcos de Arica', 'Chile'),
  ('Santiago Morning', 'Chile'),
  ('Santiago Wanderers', 'Chile'),
  ('Unión Española', 'Chile'),
  ('Unión La Calera', 'Chile'),
  ('Unión San Felipe', 'Chile'),
  ('Anhui Jiufang FC', 'China'),
  ('Baoding Yingli Yitong', 'China'),
  ('Beijing Guoan FC', 'China'),
  ('Beijing Guoan Talent Singapore FC', 'China'),
  ('Beijing Hongdeng FC', 'China'),
  ('Beijing Institute of Technology FC', 'China'),
  ('Beijing Sport University FC', 'China'),
  ('Cangzhou Mighty Lions FC', 'China'),
  ('CD Monte Carlo', 'China'),
  ('Changchun Yatai FC', 'China'),
  ('Chao Pak Kei', 'China'),
  ('Chengdu Rongcheng FC', 'China'),
  ('Chuac Lun', 'China'),
  ('Citizen AA', 'China'),
  ('Dalian Shide Siwu FC', 'China'),
  ('Dalian Transcendence FC', 'China'),
  ('Dreams Football Club', 'China'),
  ('Eastern FC', 'China'),
  ('FC Porto de Macau', 'China'),
  ('GD Lam Pak', 'China'),
  ('Guangdong Hongyuan FC', 'China'),
  ('Guangdong Sunray Cave FC', 'China'),
  ('Guangzhou FC', 'China'),
  ('Guizhou FC', 'China'),
  ('Guizhou Renhe FC', 'China'),
  ('Happy Valley AA', 'China'),
  ('Harbin Yiteng FC', 'China'),
  ('Henan FC', 'China'),
  ('Heng Tai', 'China'),
  ('HKFC Soccer Section', 'China'),
  ('Hohhot Black Horse', 'China'),
  ('Hoi Fan', 'China'),
  ('Hong Kong Pegasus FC', 'China'),
  ('Hong Kong Rangers FC', 'China'),
  ('Hong Ngai', 'China'),
  ('Hunan Billows FC', 'China'),
  ('Kei Cheong', 'China'),
  ('Kei Lun', 'China'),
  ('Kuan Tai', 'China'),
  ('Kunshan FC', 'China'),
  ('Lai Chi', 'China'),
  ('Lam Ieng', 'China'),
  ('Liaoning FC', 'China'),
  ('Liaoning Guangyuan FC', 'China'),
  ('Meizhou Hakka FC', 'China'),
  ('MFA Develop', 'China'),
  ('Polícia de Segurança Pública', 'China'),
  ('Qingdao FC', 'China'),
  ('Qingdao Hainiu FC', 'China'),
  ('Qingdao Qingchundao FC', 'China'),
  ('R&F (Hong Kong)', 'China'),
  ('Shaanxi Guoli FC', 'China'),
  ('Shandong Taishan FC', 'China'),
  ('Shanghai Port FC', 'China'),
  ('Shanghai Pudong Zobon FC', 'China'),
  ('Shanghai Shenhua FC', 'China'),
  ('Shanghai Shenxin FC', 'China'),
  ('Shenyang Shenbei FC', 'China'),
  ('Shenzhen Peng City FC', 'China'),
  ('SL Benfica de Macau', 'China'),
  ('South China AA', 'China'),
  ('Southern District FC', 'China'),
  ('Sporting Clube de Macau', 'China'),
  ('Sun Hei SC', 'China'),
  ('Tai Po FC', 'China'),
  ('Taiyuan Zhongyou Jiayi FC', 'China'),
  ('Windsor Arch Ka I', 'China'),
  ('Wuhan Three Towns FC', 'China'),
  ('Xinjiang Tianshan Leopard FC', 'China'),
  ('Yanbian Funde FC', 'China'),
  ('Yuen Long FC', 'China'),
  ('Yunnan Feihu FC', 'China'),
  ('Yunnan Yukun FC', 'China'),
  ('Zhejiang Professional FC', 'China'),
  ('AC Omonia', 'Chipre'),
  ('AEK Kouklia FC', 'Chipre'),
  ('AEK Larnaca FC', 'Chipre'),
  ('AEL Limassol FC', 'Chipre'),
  ('AEZ Zakakiou', 'Chipre'),
  ('Akritas Chlorakas', 'Chipre'),
  ('Alki Oroklini FC', 'Chipre'),
  ('Anorthosis Famagusta FC', 'Chipre'),
  ('APEP FC', 'Chipre'),
  ('Apollon Limassol FC', 'Chipre'),
  ('Aris Limassol FC', 'Chipre'),
  ('ASIL Lysi', 'Chipre'),
  ('Ayia Napa FC', 'Chipre'),
  ('Digenis Akritas Morphou FC', 'Chipre'),
  ('Doxa Katokopias FC', 'Chipre'),
  ('Enosis Neon Paralimni FC', 'Chipre'),
  ('Ermis Aradippou FC', 'Chipre'),
  ('Ethnikos Achna FC', 'Chipre'),
  ('Karmiotissa Pano Polemidion', 'Chipre'),
  ('Nea Salamis Famagusta FC', 'Chipre'),
  ('Olympiakos Nicosia FC', 'Chipre'),
  ('Omonia Aradippou', 'Chipre'),
  ('Othellos Athienou FC', 'Chipre'),
  ('Pafos FC', 'Chipre'),
  ('América de Cali', 'Colômbia'),
  ('Atlético Bucaramanga', 'Colômbia'),
  ('Atlético Huila', 'Colômbia'),
  ('Atlético Nacional', 'Colômbia'),
  ('Boyacá Chicó FC', 'Colômbia'),
  ('Boyacá Patriotas', 'Colômbia'),
  ('Cortuluá', 'Colômbia'),
  ('Cúcuta Deportivo', 'Colômbia'),
  ('Deportes Quindío', 'Colômbia'),
  ('Deportes Tolima', 'Colômbia'),
  ('Deportivo Cali', 'Colômbia'),
  ('Deportivo Independiente Medellín', 'Colômbia'),
  ('Deportivo Pasto', 'Colômbia'),
  ('Deportivo Pereira', 'Colômbia'),
  ('Deportivo Unicosta', 'Colômbia'),
  ('Envigado Fútbol Club', 'Colômbia'),
  ('Fortaleza Fútbol Club', 'Colômbia'),
  ('Gold Eagles', 'Colômbia'),
  ('Huracán de Medellín', 'Colômbia'),
  ('Independiente Santa Fe', 'Colômbia'),
  ('Internacional de Bogotá', 'Colômbia'),
  ('Jaguares de Córdoba', 'Colômbia'),
  ('Junior de Barranquilla', 'Colômbia'),
  ('La Equidad', 'Colômbia'),
  ('Leones FC', 'Colômbia'),
  ('Millonarios', 'Colômbia'),
  ('Once Caldas', 'Colômbia'),
  ('Real Cartagena', 'Colômbia'),
  ('Real Santander', 'Colômbia'),
  ('Tigres Fútbol Club', 'Colômbia'),
  ('Unión Magdalena', 'Colômbia'),
  ('AC Léopards', 'Congo'),
  ('CARA Brazzaville', 'Congo'),
  ('Diables Noirs', 'Congo'),
  ('Étoile du Congo', 'Congo'),
  ('Amnokgang Sports Club', 'Coreia do Norte'),
  ('April 25 Sports Club', 'Coreia do Norte'),
  ('Chadongcha Sports Club', 'Coreia do Norte'),
  ('Chandongja Sports Club', 'Coreia do Norte'),
  ('Hwaebul Sports Club', 'Coreia do Norte'),
  ('Jebi Sports Club', 'Coreia do Norte'),
  ('Kigwancha Sports Club', 'Coreia do Norte'),
  ('Kyonggongop Sports Club', 'Coreia do Norte'),
  ('Moranbong Sports Club', 'Coreia do Norte'),
  ('Pyongyang City Sports Club', 'Coreia do Norte'),
  ('Rimyongsu Sports Club', 'Coreia do Norte'),
  ('Rodongja Sports Club', 'Coreia do Norte'),
  ('Ryongnamsan Sports Club', 'Coreia do Norte'),
  ('Sobaeksu Sports Club', 'Coreia do Norte'),
  ('Unpasan Sports Club', 'Coreia do Norte'),
  ('Wolmido Sports Club', 'Coreia do Norte'),
  ('Ansan Greeners FC', 'Coreia do Sul'),
  ('Bucheon FC 1995', 'Coreia do Sul'),
  ('Busan IPark FC', 'Coreia do Sul'),
  ('Cheonan City FC', 'Coreia do Sul'),
  ('Chungbuk Cheongju FC', 'Coreia do Sul'),
  ('Chungnam Asan FC', 'Coreia do Sul'),
  ('Daegu FC', 'Coreia do Sul'),
  ('Daejeon Hana Citizen FC', 'Coreia do Sul'),
  ('FC Anyang', 'Coreia do Sul'),
  ('FC Pohang Steelers', 'Coreia do Sul'),
  ('FC Seoul', 'Coreia do Sul'),
  ('Gangwon FC', 'Coreia do Sul'),
  ('Gimcheon Sangmu FC', 'Coreia do Sul'),
  ('Gimhae FC 2008', 'Coreia do Sul'),
  ('Gimpo FC', 'Coreia do Sul'),
  ('Gwangju FC', 'Coreia do Sul'),
  ('Gyeongnam FC', 'Coreia do Sul'),
  ('Hwaseong FC', 'Coreia do Sul'),
  ('Incheon Hyundai Steel Red Angels WFC', 'Coreia do Sul'),
  ('Incheon United FC', 'Coreia do Sul'),
  ('Jeju SK FC', 'Coreia do Sul'),
  ('Jeonbuk Hyundai Motors FC', 'Coreia do Sul'),
  ('Jeonnam Dragons FC', 'Coreia do Sul'),
  ('Paju Frontier FC', 'Coreia do Sul'),
  ('Seongnam FC', 'Coreia do Sul'),
  ('Seoul E-Land FC', 'Coreia do Sul'),
  ('Suwon FC', 'Coreia do Sul'),
  ('Suwon Samsung Bluewings FC', 'Coreia do Sul'),
  ('Ulsan HD FC', 'Coreia do Sul'),
  ('Yongin FC', 'Coreia do Sul'),
  ('Academie de Foot Amadou Diallo', 'Costa do Marfim'),
  ('Africa Sports d''Abidjan', 'Costa do Marfim'),
  ('AS Denguélé', 'Costa do Marfim'),
  ('AS Indenié Abengourou', 'Costa do Marfim'),
  ('ASC Ouragahio', 'Costa do Marfim'),
  ('ASEC Mimosas', 'Costa do Marfim'),
  ('Association Sportive Tanda', 'Costa do Marfim'),
  ('Bouaké FC', 'Costa do Marfim'),
  ('CO Korhogo', 'Costa do Marfim'),
  ('ES Bingerville', 'Costa do Marfim'),
  ('FC Hiré', 'Costa do Marfim'),
  ('FC Mouna', 'Costa do Marfim'),
  ('FC San Pédro', 'Costa do Marfim'),
  ('Issia Wazi FC', 'Costa do Marfim'),
  ('Jeunesse Club d''Abidjan', 'Costa do Marfim'),
  ('Moossou FC', 'Costa do Marfim'),
  ('RC Daloa', 'Costa do Marfim'),
  ('Séwé FC', 'Costa do Marfim'),
  ('Société Omnisports de l''Armée', 'Costa do Marfim'),
  ('Sporting Club de Gagnoa', 'Costa do Marfim'),
  ('Stade d''Abidjan', 'Costa do Marfim'),
  ('Stella Club d''Adjamé', 'Costa do Marfim'),
  ('USC Bassam', 'Costa do Marfim'),
  ('Williamsville AC', 'Costa do Marfim'),
  ('AD Belén', 'Costa Rica'),
  ('AD Guanacasteca', 'Costa Rica'),
  ('Asociación Deportiva Carmelita', 'Costa Rica'),
  ('Asociación Deportiva San Carlos', 'Costa Rica'),
  ('Club Sport Uruguay de Coronado', 'Costa Rica'),
  ('CS Cartaginés', 'Costa Rica'),
  ('CS Herediano', 'Costa Rica'),
  ('Deportivo Saprissa', 'Costa Rica'),
  ('Guadalupe Fútbol Club', 'Costa Rica'),
  ('La U Universitarios', 'Costa Rica'),
  ('Liga Deportiva Alajuelense', 'Costa Rica'),
  ('Municipal Liberia', 'Costa Rica'),
  ('Municipal Pérez Zeledón', 'Costa Rica'),
  ('Puntarenas FC', 'Costa Rica'),
  ('Santos de Guápiles', 'Costa Rica'),
  ('GNK Dinamo Zagreb', 'Croácia'),
  ('HAŠK', 'Croácia'),
  ('HNK Cibalia', 'Croácia'),
  ('HNK Gorica', 'Croácia'),
  ('HNK Hajduk Split', 'Croácia'),
  ('HNK Rijeka', 'Croácia'),
  ('HNK Segesta', 'Croácia'),
  ('HNK Šibenik', 'Croácia'),
  ('HNK Vukovar 1991', 'Croácia'),
  ('NK Belišće', 'Croácia'),
  ('NK Bistra', 'Croácia'),
  ('NK Dugopolje', 'Croácia'),
  ('NK HAŠK 1903', 'Croácia'),
  ('NK Hrvatski Dragovoljac', 'Croácia'),
  ('NK Imotski', 'Croácia'),
  ('NK Inter Zaprešić', 'Croácia'),
  ('NK Istra 1961', 'Croácia'),
  ('NK Kustošija Zagreb', 'Croácia'),
  ('NK Lokomotiva', 'Croácia'),
  ('NK Lučko', 'Croácia'),
  ('NK Marsonia', 'Croácia'),
  ('NK Međimurje', 'Croácia'),
  ('NK Mosor', 'Croácia'),
  ('NK Novigrad', 'Croácia'),
  ('NK Osijek', 'Croácia'),
  ('NK Primorac 1929', 'Croácia'),
  ('NK Radnik Sesvete', 'Croácia'),
  ('NK Rudeš', 'Croácia'),
  ('NK Slaven Belupo', 'Croácia'),
  ('NK Solin', 'Croácia'),
  ('NK Trešnjevka', 'Croácia'),
  ('NK Varaždin ŠN', 'Croácia'),
  ('NK Zadar', 'Croácia'),
  ('NK Zagreb', 'Croácia'),
  ('NK Zelina', 'Croácia'),
  ('RNK Split', 'Croácia'),
  ('CF Granma', 'Cuba'),
  ('Ciudad de La Habana', 'Cuba'),
  ('FC Artemisa', 'Cuba'),
  ('FC Camagüey', 'Cuba'),
  ('FC Ciego de Ávila', 'Cuba'),
  ('FC Cienfuegos', 'Cuba'),
  ('FC Guantánamo', 'Cuba'),
  ('FC Industriales', 'Cuba'),
  ('FC Isla de La Juventud', 'Cuba'),
  ('FC La Habana', 'Cuba'),
  ('FC Las Tunas', 'Cuba'),
  ('FC Matanzas', 'Cuba'),
  ('FC Mayabeque', 'Cuba'),
  ('FC Pinar del Río', 'Cuba'),
  ('FC Santiago de Cuba', 'Cuba'),
  ('FC Villa Clara', 'Cuba'),
  ('Holguín FC', 'Cuba'),
  ('Sancti Spíritus FC', 'Cuba'),
  ('CRKSV Jong Colombia', 'Curaçau'),
  ('CRKSV Jong Holland', 'Curaçau'),
  ('AaB Fodbold', 'Dinamarca'),
  ('Aarhus Gymnastikforening', 'Dinamarca'),
  ('AC Horsens', 'Dinamarca'),
  ('Akademisk Boldklub', 'Dinamarca'),
  ('Boldklubben 1903', 'Dinamarca'),
  ('Boldklubben 1909', 'Dinamarca'),
  ('Boldklubben 1913', 'Dinamarca'),
  ('Boldklubben af 1893', 'Dinamarca'),
  ('Boldklubben Frem', 'Dinamarca'),
  ('Brøndby IF', 'Dinamarca'),
  ('Brønshøj Boldklub', 'Dinamarca'),
  ('Esbjerg fB', 'Dinamarca'),
  ('FC Copenhagen', 'Dinamarca'),
  ('FC Fredericia', 'Dinamarca'),
  ('FC Helsingør', 'Dinamarca'),
  ('FC Midtjylland', 'Dinamarca'),
  ('FC Nordsjælland', 'Dinamarca'),
  ('FC Roskilde', 'Dinamarca'),
  ('Fremad Amager', 'Dinamarca')
) as v(name, country)
join countries c on c.name = v.country
on conflict (name, country_id) do nothing;
