-- Football clubs from Wikidata (CC0), part 2 of 4. Safe to re-run: existing name+country pairs are skipped.
-- Run 0023_uk_countries.sql first (it creates Inglaterra, Escocia, etc.).
insert into teams (name, country_id)
select v.name, c.id
from (values
  ('HB Køge', 'Dinamarca'),
  ('Hellerup IK', 'Dinamarca'),
  ('Herfølge Boldklub', 'Dinamarca'),
  ('Hillerød Fodbold', 'Dinamarca'),
  ('Hobro IK', 'Dinamarca'),
  ('Holbæk B&I', 'Dinamarca'),
  ('Hvidovre IF', 'Dinamarca'),
  ('Ikast FS', 'Dinamarca'),
  ('Jammerbugt FC', 'Dinamarca'),
  ('Køge Boldklub', 'Dinamarca'),
  ('Lyngby Boldklub', 'Dinamarca'),
  ('Næstved BK', 'Dinamarca'),
  ('Nykøbing FC', 'Dinamarca'),
  ('Odense Boldklub', 'Dinamarca'),
  ('Ølstykke FC', 'Dinamarca'),
  ('Randers FC', 'Dinamarca'),
  ('Silkeborg IF', 'Dinamarca'),
  ('Skive IK', 'Dinamarca'),
  ('Sønderjyske Fodbold', 'Dinamarca'),
  ('Thisted FC', 'Dinamarca'),
  ('Vanløse IF', 'Dinamarca'),
  ('Vejle Boldklub', 'Dinamarca'),
  ('Vendsyssel FF', 'Dinamarca'),
  ('Viborg FF', 'Dinamarca'),
  ('VSK Aarhus', 'Dinamarca'),
  ('Al Ahly SC', 'Egito'),
  ('Al Ittihad Alexandria Club', 'Egito'),
  ('Al Masry SC', 'Egito'),
  ('Al Nasr Lel Taa''den SC', 'Egito'),
  ('Aswan SC', 'Egito'),
  ('Ceramica Cleopatra FC', 'Egito'),
  ('Eastern Company SC', 'Egito'),
  ('El Dakhleya', 'Egito'),
  ('El Gouna FC', 'Egito'),
  ('El Raja Marsa Matruh', 'Egito'),
  ('El-Entag El-Harby', 'Egito'),
  ('El-Olympi', 'Egito'),
  ('ENPPI SC', 'Egito'),
  ('Ghazl El Mahalla SC', 'Egito'),
  ('Haras El-Hodood SC', 'Egito'),
  ('Ismaily SC', 'Egito'),
  ('Ittihad El-Shorta', 'Egito'),
  ('Misr Lel Makkasa SC', 'Egito'),
  ('Modern SC', 'Egito'),
  ('National Bank of Egypt SC', 'Egito'),
  ('Nogoom FC', 'Egito'),
  ('Petrojet FC', 'Egito'),
  ('Pyramids FC', 'Egito'),
  ('Smouha SC', 'Egito'),
  ('Tala''ea El-Gaish SC', 'Egito'),
  ('Telephonat Bani Sweif', 'Egito'),
  ('Tersana SC', 'Egito'),
  ('Wadi Degla SC', 'Egito'),
  ('Zamalek SC', 'Egito'),
  ('ZED FC', 'Egito'),
  ('AD Isidro Metapán', 'El Salvador'),
  ('Alianza Fútbol Cub', 'El Salvador'),
  ('CD Águila', 'El Salvador'),
  ('CD Atlético Marte', 'El Salvador'),
  ('CD FAS', 'El Salvador'),
  ('CD Luis Ángel Firpo', 'El Salvador'),
  ('Ajman Club', 'Emirados Árabes Unidos'),
  ('Al Ain FC', 'Emirados Árabes Unidos'),
  ('Al Dhafra Club', 'Emirados Árabes Unidos'),
  ('Al Jazira Club', 'Emirados Árabes Unidos'),
  ('Al Wasl FC', 'Emirados Árabes Unidos'),
  ('Al-Fujairah FC', 'Emirados Árabes Unidos'),
  ('Al-Shaab CSC', 'Emirados Árabes Unidos'),
  ('Alshariqa', 'Emirados Árabes Unidos'),
  ('Al-Wahda SCC', 'Emirados Árabes Unidos'),
  ('Baniyas SC', 'Emirados Árabes Unidos'),
  ('Dibba Club', 'Emirados Árabes Unidos'),
  ('Dubai CSC', 'Emirados Árabes Unidos'),
  ('Emirates Club', 'Emirados Árabes Unidos'),
  ('Hatta Club', 'Emirados Árabes Unidos'),
  ('Kalba FC', 'Emirados Árabes Unidos'),
  ('Khor Fakkan Club', 'Emirados Árabes Unidos'),
  ('Palm City FC', 'Emirados Árabes Unidos'),
  ('Shabab AlAhli Dubai Club', 'Emirados Árabes Unidos'),
  ('Sharjah FC', 'Emirados Árabes Unidos'),
  ('Barcelona SC', 'Equador'),
  ('Bonita Banana Fútbol Club', 'Equador'),
  ('CD Cuenca', 'Equador'),
  ('Centro Deportivo Olmedo', 'Equador'),
  ('Club 9 de Octubre', 'Equador'),
  ('Club Deportivo El Nacional', 'Equador'),
  ('Club Deportivo ESPOLI', 'Equador'),
  ('Club Deportivo Politécnico', 'Equador'),
  ('Club Deportivo Quevedo', 'Equador'),
  ('Club Social y Deportivo Macará', 'Equador'),
  ('Club Sport Emelec', 'Equador'),
  ('Delfín Sporting Club', 'Equador'),
  ('Fuerza Amarilla Sporting Club', 'Equador'),
  ('Guayaquil City FC', 'Equador'),
  ('Imbabura Sporting Club', 'Equador'),
  ('Independiente del Valle', 'Equador'),
  ('Liga Deportiva Universitaria de Loja', 'Equador'),
  ('Liga Deportiva Universitaria de Portoviejo', 'Equador'),
  ('Liga Deportiva Universitaria de Quito', 'Equador'),
  ('Manta Fútbol Club', 'Equador'),
  ('Mushuc Runa Sporting Club', 'Equador'),
  ('SD Quito', 'Equador'),
  ('Sociedad Deportiva Aucas', 'Equador'),
  ('Técnico Universitario', 'Equador'),
  ('Universidad Católica del Ecuador', 'Equador'),
  ('Red Sea FC', 'Eritreia'),
  ('Aberdeen', 'Escócia'),
  ('Airdrieonians', 'Escócia'),
  ('Albion Rovers', 'Escócia'),
  ('Alloa Athletic', 'Escócia'),
  ('Annan Athletic', 'Escócia'),
  ('Arbroath', 'Escócia'),
  ('Arthurlie', 'Escócia'),
  ('Ayr United', 'Escócia'),
  ('Brechin City', 'Escócia'),
  ('Celtic', 'Escócia'),
  ('Clyde', 'Escócia'),
  ('Cove Rangers', 'Escócia'),
  ('Cowdenbeath', 'Escócia'),
  ('Dumbarton', 'Escócia'),
  ('Dundee', 'Escócia'),
  ('Dundee United', 'Escócia'),
  ('Dundee Wanderers', 'Escócia'),
  ('Dunfermline Athletic', 'Escócia'),
  ('East Fife', 'Escócia'),
  ('East Stirlingshire', 'Escócia'),
  ('Edinburgh City', 'Escócia'),
  ('Elgin City', 'Escócia'),
  ('Falkirk', 'Escócia'),
  ('Forfar Athletic', 'Escócia'),
  ('Greenock Morton', 'Escócia'),
  ('Hamilton Academical', 'Escócia'),
  ('Heart of Midlothian', 'Escócia'),
  ('Hibernian', 'Escócia'),
  ('Inverness Caledonian Thistle', 'Escócia'),
  ('Kelty Hearts', 'Escócia'),
  ('Kilmarnock', 'Escócia'),
  ('Livingston', 'Escócia'),
  ('Montrose', 'Escócia'),
  ('Motherwell', 'Escócia'),
  ('Partick Thistle', 'Escócia'),
  ('Peebles Rovers', 'Escócia'),
  ('Peterhead', 'Escócia'),
  ('Queen of the South', 'Escócia'),
  ('Queen''s Park', 'Escócia'),
  ('Raith Rovers', 'Escócia'),
  ('Rangers', 'Escócia'),
  ('Ross County', 'Escócia'),
  ('Shawfield', 'Escócia'),
  ('St Johnstone', 'Escócia'),
  ('St. Mirren', 'Escócia'),
  ('Stenhousemuir', 'Escócia'),
  ('Stirling Albion', 'Escócia'),
  ('Stranraer', 'Escócia'),
  ('Vale of Leven', 'Escócia'),
  ('1. FC Tatran Prešov', 'Eslováquia'),
  ('FC DAC 1904 Dunajská Streda', 'Eslováquia'),
  ('FC Košice', 'Eslováquia'),
  ('FC Lokomotíva Košice', 'Eslováquia'),
  ('FC Nitra', 'Eslováquia'),
  ('FC Petržalka', 'Eslováquia'),
  ('FC Spartak Trnava', 'Eslováquia'),
  ('FC VSS Košice', 'Eslováquia'),
  ('FC Zlaté Moravce', 'Eslováquia'),
  ('FK AS Trenčín', 'Eslováquia'),
  ('FK Inter Bratislava', 'Eslováquia'),
  ('FK Pohronie', 'Eslováquia'),
  ('FK Púchov', 'Eslováquia'),
  ('FK Senica', 'Eslováquia'),
  ('KFC Komárno', 'Eslováquia'),
  ('MFK Dubnica', 'Eslováquia'),
  ('MFK Ružomberok', 'Eslováquia'),
  ('MFK Skalica', 'Eslováquia'),
  ('MFK Tatran Liptovský Mikuláš', 'Eslováquia'),
  ('MFK Zemplín Michalovce', 'Eslováquia'),
  ('MŠK Rimavská Sobota', 'Eslováquia'),
  ('MŠK Žilina', 'Eslováquia'),
  ('ŠK Slovan Bratislava', 'Eslováquia'),
  ('ŠKF Sereď', 'Eslováquia'),
  ('Spartak Myjava', 'Eslováquia'),
  ('ŽP Šport Podbrezová', 'Eslováquia'),
  ('DNŠ Primorje', 'Eslovénia'),
  ('FC Koper', 'Eslovénia'),
  ('ND Gorica', 'Eslovénia'),
  ('ND Ilirija Ljubljana', 'Eslovénia'),
  ('ND Slovan', 'Eslovénia'),
  ('NK Aluminij', 'Eslovénia'),
  ('NK Bela Krajina', 'Eslovénia'),
  ('NK Bravo', 'Eslovénia'),
  ('NK Celje', 'Eslovénia'),
  ('NK Domžale', 'Eslovénia'),
  ('NK Dravograd', 'Eslovénia'),
  ('NK Interblock', 'Eslovénia'),
  ('NK Krka', 'Eslovénia'),
  ('NK Krško', 'Eslovénia'),
  ('NK Ljubljana', 'Eslovénia'),
  ('NK Maribor', 'Eslovénia'),
  ('NK Olimpija Ljubljana', 'Eslovénia'),
  ('NK Primorje', 'Eslovénia'),
  ('NK Radomlje', 'Eslovénia'),
  ('NK Rogaška', 'Eslovénia'),
  ('NK Rudar Velenje', 'Eslovénia'),
  ('NK Tabor Sežana', 'Eslovénia'),
  ('NK Triglav Kranj', 'Eslovénia'),
  ('NK Zavrč', 'Eslovénia'),
  ('ŠD NŠ Mura 05', 'Eslovénia'),
  ('ACD San Marcial', 'Espanha'),
  ('AD Alcorcón', 'Espanha'),
  ('AD Alcorcón B', 'Espanha'),
  ('AD Almudévar', 'Espanha'),
  ('AD Cerro de Reyes', 'Espanha'),
  ('AD Ceuta FC', 'Espanha'),
  ('AD Colmenar Viejo', 'Espanha'),
  ('AD Parla', 'Espanha'),
  ('AD Sabiñánigo', 'Espanha'),
  ('AD San Juan', 'Espanha'),
  ('AD Unión Adarve Barrio del Pilar', 'Espanha'),
  ('AD Universidad de Oviedo', 'Espanha'),
  ('AD Villaviciosa de Odón', 'Espanha'),
  ('AE Prat', 'Espanha'),
  ('Águilas FC', 'Espanha'),
  ('Albacete Balompié', 'Espanha'),
  ('Albacete Balompié B', 'Espanha'),
  ('Alcobendas CF', 'Espanha'),
  ('Algeciras CF', 'Espanha'),
  ('Alhaurín de la Torre CF', 'Espanha'),
  ('Alondras CF', 'Espanha'),
  ('Amurrio Club', 'Espanha'),
  ('Andorra CF', 'Espanha'),
  ('Antequera CF', 'Espanha'),
  ('Aravaca CF', 'Espanha'),
  ('Arcos CF EL LAPILLA', 'Espanha'),
  ('Arenas CD', 'Espanha'),
  ('Arenas Club de Getxo', 'Espanha'),
  ('Arosa SC', 'Espanha'),
  ('Arroyo CP', 'Espanha'),
  ('Arucas CF', 'Espanha'),
  ('Athletic Bilbao B', 'Espanha'),
  ('Athletic Club', 'Espanha'),
  ('Atlétich Chichizola', 'Espanha'),
  ('Atlético Arteixo', 'Espanha'),
  ('Atlético Astorga FC', 'Espanha'),
  ('Atlético Calatayud', 'Espanha'),
  ('Atlético Granadilla', 'Espanha'),
  ('Atlético Levante UD', 'Espanha'),
  ('Atlético Madrid', 'Espanha'),
  ('Atlético Madrid B', 'Espanha'),
  ('Atlético Malagueño', 'Espanha'),
  ('Atlético Mancha Real', 'Espanha'),
  ('Atlético Saguntino', 'Espanha'),
  ('Atlético Sanluqueño CF', 'Espanha'),
  ('Atlético Tordesillas', 'Espanha'),
  ('Atzeneta UE', 'Espanha'),
  ('Ayamonte CF', 'Espanha'),
  ('Barakaldo CF', 'Espanha'),
  ('Benalup CF', 'Espanha'),
  ('Bergantiños FC', 'Espanha'),
  ('Betanzos CF', 'Espanha'),
  ('Betis', 'Espanha'),
  ('Burgos CF', 'Espanha'),
  ('Burgos CF Promesas', 'Espanha'),
  ('C.D BURGALÉS', 'Espanha'),
  ('CA Antoniano', 'Espanha'),
  ('CA Artajonés', 'Espanha'),
  ('CA Cirbonero', 'Espanha'),
  ('CA Pinto', 'Espanha'),
  ('CA Pulpileño', 'Espanha'),
  ('CA River Ebro', 'Espanha'),
  ('CA Vianés', 'Espanha'),
  ('Cádiz', 'Espanha'),
  ('Cádiz CF B', 'Espanha'),
  ('Candás CF', 'Espanha'),
  ('CAP Ciudad de Murcia', 'Espanha'),
  ('Casalarreina CF', 'Espanha'),
  ('Castillo CF', 'Espanha'),
  ('Castro FC', 'Espanha'),
  ('Caudal Deportivo', 'Espanha'),
  ('CCD Alberite', 'Espanha'),
  ('CCD Cerceda', 'Espanha'),
  ('CD Agoncillo', 'Espanha'),
  ('CD Albacete', 'Espanha'),
  ('CD Alcalá', 'Espanha'),
  ('CD Alcoyano', 'Espanha'),
  ('CD Aldeano', 'Espanha'),
  ('CD Alfaro', 'Espanha'),
  ('CD Alfaro B', 'Espanha'),
  ('CD Alhaurino', 'Espanha'),
  ('CD Altorricón', 'Espanha'),
  ('CD Aluvión', 'Espanha'),
  ('CD Anguiano', 'Espanha'),
  ('CD Aoiz', 'Espanha'),
  ('CD Arenas de Frajanas', 'Espanha'),
  ('CD Arenteiro', 'Espanha'),
  ('CD Arnedo', 'Espanha'),
  ('CD As Pontes', 'Espanha'),
  ('CD Atlético Baleares', 'Espanha'),
  ('CD Aurrerá de Vitoria', 'Espanha'),
  ('CD Aurrerá Ondarroa', 'Espanha'),
  ('CD Azkoyen', 'Espanha'),
  ('CD Azuqueca', 'Espanha'),
  ('CD Badajoz B', 'Espanha'),
  ('CD Bala Azul', 'Espanha'),
  ('CD Barco', 'Espanha'),
  ('CD Baskonia', 'Espanha'),
  ('CD Becerril', 'Espanha'),
  ('CD Beniel', 'Espanha'),
  ('CD Berceo', 'Espanha'),
  ('CD Berio FT', 'Espanha'),
  ('CD Beti Onak', 'Espanha'),
  ('CD Binéfar', 'Espanha'),
  ('CD Binissalem', 'Espanha'),
  ('CD Brea', 'Espanha'),
  ('CD Bullense', 'Espanha'),
  ('CD Burriana', 'Espanha'),
  ('CD Calahorra', 'Espanha'),
  ('CD Carranque', 'Espanha'),
  ('CD Castellón', 'Espanha'),
  ('CD Cayón', 'Espanha'),
  ('CD Cebrereña', 'Espanha'),
  ('CD Cenicero', 'Espanha'),
  ('CD Choco', 'Espanha'),
  ('CD Cieza', 'Espanha'),
  ('CD Colindres', 'Espanha'),
  ('CD Colonia Moscardó', 'Espanha'),
  ('CD Colunga', 'Espanha'),
  ('CD Comarca de Níjar', 'Espanha'),
  ('CD Corellano', 'Espanha'),
  ('CD Coria', 'Espanha'),
  ('CD Corralejo', 'Espanha'),
  ('CD Cortes', 'Espanha'),
  ('CD Covadonga', 'Espanha'),
  ('CD Cristo Atlético', 'Espanha'),
  ('CD Cuarte', 'Espanha'),
  ('CD Cultural Areas', 'Espanha'),
  ('CD Dénia', 'Espanha'),
  ('CD Don Benito', 'Espanha'),
  ('CD Ebro', 'Espanha'),
  ('CD Egüés', 'Espanha'),
  ('CD El Álamo', 'Espanha'),
  ('CD El Ejido 2012', 'Espanha'),
  ('CD El Palo', 'Espanha'),
  ('CD Eldense', 'Espanha'),
  ('CD Elgoibar', 'Espanha'),
  ('CD Ferriolense', 'Espanha'),
  ('CD Getxo', 'Espanha'),
  ('CD Griñón', 'Espanha'),
  ('CD Guadalcacín', 'Espanha'),
  ('CD Guarnizo', 'Espanha'),
  ('CD Huétor Tájar', 'Espanha'),
  ('CD Ibiza Islas Pitiusas', 'Espanha'),
  ('CD Idoya', 'Espanha'),
  ('CD Illescas', 'Espanha'),
  ('CD Íscar', 'Espanha'),
  ('CD Itaroa Huarte', 'Espanha'),
  ('CD Izarra', 'Espanha'),
  ('CD La Virgen del Camino', 'Espanha'),
  ('CD Lagun Onak', 'Espanha'),
  ('CD Laudio', 'Espanha'),
  ('CD Leganés', 'Espanha'),
  ('CD Leganés B', 'Espanha'),
  ('CD Llanes', 'Espanha'),
  ('CD Llosetense', 'Espanha'),
  ('CD Madalena de Morcín', 'Espanha'),
  ('CD Madridejos', 'Espanha'),
  ('CD Mairena', 'Espanha'),
  ('CD Manacor', 'Espanha'),
  ('CD Manchego C.Real', 'Espanha'),
  ('CD Marchamalo', 'Espanha'),
  ('CD Mariño', 'Espanha'),
  ('CD Masnou', 'Espanha'),
  ('CD Mendi', 'Espanha'),
  ('CD Mensajero', 'Espanha'),
  ('CD Minera', 'Espanha'),
  ('CD Mirandés', 'Espanha'),
  ('CD Mirandés B', 'Espanha'),
  ('CD Mosconia', 'Espanha'),
  ('CD Naval', 'Espanha'),
  ('CD Numancia B', 'Espanha'),
  ('CD Olímpic de Xàtiva', 'Espanha'),
  ('CD Palencia Balompié', 'Espanha'),
  ('CD Peña Azagresa', 'Espanha'),
  ('CD Plus Ultra', 'Espanha'),
  ('CD Pontejos', 'Espanha'),
  ('CD Pozoblanco', 'Espanha'),
  ('CD Praviano', 'Espanha'),
  ('CD Quintanar del Rey', 'Espanha'),
  ('CD Revilla', 'Espanha'),
  ('CD River Ega', 'Espanha'),
  ('CD Roces', 'Espanha'),
  ('CD Roda', 'Espanha'),
  ('CD Ronda', 'Espanha'),
  ('CD San Isidro', 'Espanha'),
  ('CD San Roque de Lepe', 'Espanha'),
  ('CD Santa Amalia', 'Espanha'),
  ('CD Santanyí', 'Espanha'),
  ('CD Sariñena', 'Espanha'),
  ('CD Siete Villas', 'Espanha'),
  ('CD Tedeón EF', 'Espanha'),
  ('CD Tenerife', 'Espanha'),
  ('CD Tenerife B', 'Espanha'),
  ('CD Teruel', 'Espanha'),
  ('CD Tineo', 'Espanha'),
  ('CD Toledo', 'Espanha'),
  ('CD Toledo B', 'Espanha'),
  ('CD Torrijos', 'Espanha'),
  ('CD Tropezón', 'Espanha'),
  ('CD Tudelano', 'Espanha'),
  ('CD Tuilla', 'Espanha'),
  ('CD Utiel', 'Espanha'),
  ('CD Utrera', 'Espanha'),
  ('CD Valdefierro', 'Espanha'),
  ('CD Valdelacalzada', 'Espanha'),
  ('CD Varea', 'Espanha'),
  ('CD Villegas', 'Espanha'),
  ('CD Vitoria', 'Espanha'),
  ('CDFC La Calzada', 'Espanha'),
  ('CE Alaior', 'Espanha'),
  ('CE Andratx', 'Espanha'),
  ('CE Campos', 'Espanha'),
  ('CE Constància', 'Espanha'),
  ('CE Europa', 'Espanha'),
  ('CE Mercadal', 'Espanha'),
  ('CE Sabadell FC B', 'Espanha'),
  ('Céltiga FC', 'Espanha'),
  ('Centre d''Esports Sabadell Futbol Club', 'Espanha'),
  ('Cerdanyola del Vallès FC', 'Espanha'),
  ('CF Ardoi FE', 'Espanha'),
  ('CF Badalona', 'Espanha'),
  ('CF Badalona Futur', 'Espanha'),
  ('CF Borriol', 'Espanha'),
  ('CF Calamocha', 'Espanha'),
  ('CF Fuenlabrada', 'Espanha'),
  ('CF Fuenlabrada Promesas Madrid 2021', 'Espanha'),
  ('CF Gandía', 'Espanha'),
  ('CF Gimnástico Alcázar', 'Espanha'),
  ('CF Illueca', 'Espanha'),
  ('CF Intercity', 'Espanha'),
  ('CF La Nucía', 'Espanha'),
  ('CF Lorca Deportiva', 'Espanha'),
  ('CF Montañesa', 'Espanha'),
  ('CF Motril', 'Espanha'),
  ('CF Panadería Pulido', 'Espanha'),
  ('CF Peralada', 'Espanha'),
  ('CF Platges de Calvià', 'Espanha'),
  ('CF Pozuelo de Alarcón', 'Espanha'),
  ('CF Rápid', 'Espanha'),
  ('CF Rayo Majadahonda', 'Espanha'),
  ('CF Ribamontán al Mar', 'Espanha'),
  ('CF San Rafael', 'Espanha'),
  ('CF Sóller', 'Espanha'),
  ('CF Talavera de la Reina', 'Espanha'),
  ('CF Trival Valderas.', 'Espanha'),
  ('CF Trujillo', 'Espanha'),
  ('CF Unión Viera', 'Espanha'),
  ('CF Villanovense', 'Espanha'),
  ('CF Vimenor', 'Espanha'),
  ('Ciudad Rodrigo CF', 'Espanha'),
  ('Club Atlético Osasuna', 'Espanha'),
  ('Club Deportivo Badajoz', 'Espanha'),
  ('Club Deportivo Betoño-Elgorriaga', 'Espanha'),
  ('Club Deportivo Guadalajara', 'Espanha'),
  ('Club Deportivo Lugo', 'Espanha'),
  ('Club Deportivo Numancia de Soria', 'Espanha'),
  ('Club Deportivo Pamplona', 'Espanha'),
  ('Club Español de Madrid', 'Espanha'),
  ('Club Esportiu Almassora', 'Espanha'),
  ('Club Lleida Esportiu', 'Espanha'),
  ('Club Marino de Luanco', 'Espanha'),
  ('Club Olímpico de Totana', 'Espanha'),
  ('Club Portugalete', 'Espanha'),
  ('Club Recreativo Granada', 'Espanha'),
  ('Condal Club', 'Espanha'),
  ('Conil CF', 'Espanha'),
  ('Córdoba CF', 'Espanha'),
  ('Córdoba CF B', 'Espanha'),
  ('Coria CF', 'Espanha'),
  ('Coruxo FC', 'Espanha'),
  ('CP Amanecer', 'Espanha'),
  ('CP Cacereño', 'Espanha'),
  ('CP Calasancio', 'Espanha'),
  ('CP Sanvicenteño', 'Espanha'),
  ('CP Villarrobledo', 'Espanha'),
  ('Crevillente Deportivo', 'Espanha'),
  ('CU Collado Villalba', 'Espanha'),
  ('Cultural y Deportiva Leonesa B', 'Espanha'),
  ('DAV Santa Ana', 'Espanha'),
  ('Deportivo Alavés', 'Espanha'),
  ('Deportivo Alavés B', 'Espanha'),
  ('Deportivo Alavés C', 'Espanha'),
  ('Deportivo Aragón', 'Espanha'),
  ('Deportivo de A Coruña', 'Espanha'),
  ('Deportivo Dorneda CF', 'Espanha'),
  ('Deportivo Fabril', 'Espanha'),
  ('Deportivo Rayo Cantabria', 'Espanha'),
  ('Écija Balompié', 'Espanha'),
  ('EI San Martín', 'Espanha'),
  ('El Palmar CF', 'Espanha'),
  ('Elche CF', 'Espanha'),
  ('Elche CF Ilicitano', 'Espanha'),
  ('FC Ascó', 'Espanha'),
  ('FC Barcelona Atlètic', 'Espanha'),
  ('FC Cartagena', 'Espanha'),
  ('FC Jove Español San Vicente', 'Espanha'),
  ('FC Jumilla', 'Espanha'),
  ('FC Torrevieja', 'Espanha'),
  ('Formac Villarrubia CF', 'Espanha'),
  ('Gernika Club', 'Espanha'),
  ('Getafe CF', 'Espanha'),
  ('Getafe CF B', 'Espanha'),
  ('Gimnàstic de Tarragona', 'Espanha'),
  ('Gimnástica Arandina CF', 'Espanha'),
  ('Gimnástica de Torrelavega', 'Espanha'),
  ('Gimnástica Segoviana CF', 'Espanha'),
  ('Girona FC', 'Espanha'),
  ('Granada CF', 'Espanha'),
  ('Guadix CF', 'Espanha'),
  ('Haro Deportivo', 'Espanha'),
  ('Hellín CF', 'Espanha'),
  ('Hércules CF', 'Espanha'),
  ('Huércal-Overa CF', 'Espanha'),
  ('Internacional de Madrid CF', 'Espanha'),
  ('Jerez CF', 'Espanha'),
  ('Jerez Industrial CF', 'Espanha'),
  ('Juventud de Torremolinos CF', 'Espanha'),
  ('La Gineta CF', 'Espanha'),
  ('La Roda CF', 'Espanha'),
  ('Laracha CF', 'Espanha'),
  ('Las Rozas CF', 'Espanha'),
  ('L''Entregu CF', 'Espanha'),
  ('Levante UD', 'Espanha'),
  ('Linares Deportivo', 'Espanha'),
  ('Loja CD', 'Espanha'),
  ('Lorca FC B', 'Espanha'),
  ('Málaga CF', 'Espanha'),
  ('Manzanares CF', 'Espanha'),
  ('Martos CD', 'Espanha'),
  ('Mérida AD', 'Espanha'),
  ('México FC SAD', 'Espanha'),
  ('Mora CF', 'Espanha'),
  ('Moralo CP', 'Espanha'),
  ('Murchante FC', 'Espanha'),
  ('Muro CF', 'Espanha'),
  ('Narón BP', 'Espanha'),
  ('Náxara CD', 'Espanha'),
  ('Novelda CF', 'Espanha'),
  ('Olivenza FC', 'Espanha'),
  ('Orihuela CF', 'Espanha'),
  ('Osasuna B', 'Espanha'),
  ('Palamós CF', 'Espanha'),
  ('Pasaia KE', 'Espanha'),
  ('Paterna CF', 'Espanha'),
  ('PD Santa Eulalia', 'Espanha'),
  ('Peña Sport FC', 'Espanha'),
  ('Peñarroya-Porronuevo', 'Espanha'),
  ('Pobla de Mafumet CF', 'Espanha'),
  ('Pontevedra CF', 'Espanha'),
  ('Racing Cartagena Mar Menor FC', 'Espanha'),
  ('Racing Club de Ferrol', 'Espanha'),
  ('Racing Club Portuense', 'Espanha'),
  ('Racing de Santander', 'Espanha'),
  ('Racing Lermeño', 'Espanha'),
  ('Rápido de Bouzas', 'Espanha'),
  ('Rayo Cantabria', 'Espanha'),
  ('Rayo Vallecano', 'Espanha'),
  ('Rayo Vallecano B', 'Espanha'),
  ('RB Linense', 'Espanha'),
  ('RC Celta de Vigo', 'Espanha'),
  ('RC Celta Fortuna', 'Espanha'),
  ('RC Villalbés', 'Espanha'),
  ('RCD Carabanchel', 'Espanha'),
  ('RCD Espanyol B', 'Espanha'),
  ('RCD Espanyol de Barcelona', 'Espanha'),
  ('RCD Mallorca', 'Espanha'),
  ('Real Aranjuez CF', 'Espanha'),
  ('Real Ávila CF', 'Espanha'),
  ('Real Avilés B', 'Espanha'),
  ('Real Avilés CF', 'Espanha'),
  ('Real Betis B', 'Espanha'),
  ('Real Betis Balompié', 'Espanha'),
  ('Real Burgos CF', 'Espanha'),
  ('Real Jaén', 'Espanha'),
  ('Real Madrid', 'Espanha'),
  ('Real Murcia', 'Espanha'),
  ('Real Murcia Imperial', 'Espanha'),
  ('Real Oviedo', 'Espanha'),
  ('Real Oviedo Vetusta', 'Espanha'),
  ('Real Sociedad', 'Espanha'),
  ('Real Sociedad B', 'Espanha'),
  ('Real Sporting San José', 'Espanha'),
  ('Real Tapia CF', 'Espanha'),
  ('Real Unión', 'Espanha'),
  ('Real Valladolid', 'Espanha'),
  ('Real Valladolid B', 'Espanha'),
  ('Real Zaragoza', 'Espanha'),
  ('Recreativo de Huelva', 'Espanha'),
  ('Recreativo de Huelva B', 'Espanha'),
  ('Ribadumia CF', 'Espanha'),
  ('Ribarroja CF', 'Espanha'),
  ('RSD Alcalá', 'Espanha'),
  ('Salamanca CF UDS', 'Espanha'),
  ('Santa Teresa CD', 'Espanha'),
  ('Santfeliuenc FC', 'Espanha'),
  ('Santoña CF', 'Espanha'),
  ('SCD Durango', 'Espanha'),
  ('SD Almazán', 'Espanha'),
  ('SD Amorebieta', 'Espanha'),
  ('SD Atlético Albericia', 'Espanha'),
  ('SD Balmaseda FC', 'Espanha'),
  ('SD Barreda Balompié', 'Espanha'),
  ('SD Beasain', 'Espanha'),
  ('SD Borja', 'Espanha'),
  ('SD Buelna', 'Espanha'),
  ('SD Compostela', 'Espanha'),
  ('SD Deusto', 'Espanha'),
  ('SD Eibar', 'Espanha'),
  ('SD Ejea', 'Espanha'),
  ('SD Erandio Club', 'Espanha'),
  ('SD Formentera', 'Espanha'),
  ('SD Lagunak', 'Espanha'),
  ('SD Laredo', 'Espanha'),
  ('SD Leioa', 'Espanha'),
  ('SD Logroñés', 'Espanha'),
  ('SD Navarro CF', 'Espanha'),
  ('SD Negreira', 'Espanha'),
  ('SD Oyonesa', 'Espanha'),
  ('SD Tarazona', 'Espanha'),
  ('SD Tenisca', 'Espanha'),
  ('SD Textil Escudo', 'Espanha'),
  ('Selaya FC', 'Espanha'),
  ('Sestao River Club', 'Espanha'),
  ('Sevilla FC', 'Espanha'),
  ('Sevilla FC C', 'Espanha'),
  ('Silva SD', 'Espanha'),
  ('Sociedad Deportiva Huesca', 'Espanha'),
  ('Sociedad Deportiva Ponferradina', 'Espanha'),
  ('Solares SD', 'Espanha'),
  ('Sporting de Gijón', 'Espanha'),
  ('Sporting de Gijón B', 'Espanha'),
  ('Sporting Villanueva Promesas', 'Espanha'),
  ('SR Villaverde Boetticher CF', 'Espanha'),
  ('Terrassa FC', 'Espanha'),
  ('Tolosa CF', 'Espanha'),
  ('UB Conquense', 'Espanha'),
  ('Úbeda', 'Espanha'),
  ('UC Ceares', 'Espanha'),
  ('UCAM Murcia CF', 'Espanha'),
  ('UCD Burladés', 'Espanha'),
  ('UD Almansa', 'Espanha'),
  ('UD Almería B', 'Espanha'),
  ('UD Alzira', 'Espanha'),
  ('UD Barbadás', 'Espanha'),
  ('UD Barbastro', 'Espanha'),
  ('UD Ciudad de Torredonjimeno', 'Espanha'),
  ('UD Collerense', 'Espanha'),
  ('UD Gijón Industrial', 'Espanha'),
  ('UD Ibiza', 'Espanha'),
  ('UD Juventud Barrio del Cristo', 'Espanha'),
  ('UD Lanzarote', 'Espanha'),
  ('UD Las Palmas', 'Espanha'),
  ('UD Las Palmas Atlético', 'Espanha'),
  ('UD Las Zocas', 'Espanha'),
  ('UD Llanera', 'Espanha'),
  ('UD Logroñés', 'Espanha'),
  ('UD Los Barrios', 'Espanha'),
  ('UD Los Llanos', 'Espanha'),
  ('UD Maracena', 'Espanha'),
  ('UD Marbella', 'Espanha'),
  ('UD Melilla', 'Espanha'),
  ('UD Montijo', 'Espanha'),
  ('UD Mutilvera', 'Espanha'),
  ('UD Poblense', 'Espanha'),
  ('UD Puçol', 'Espanha'),
  ('UD Realejos', 'Espanha'),
  ('UD San Claudio', 'Espanha'),
  ('UD San Pedro', 'Espanha'),
  ('UD San Sebastián de los Reyes', 'Espanha'),
  ('UD Santa Marta', 'Espanha'),
  ('UD Socuéllamos', 'Espanha'),
  ('UD Somozas', 'Espanha'),
  ('UD Talavera', 'Espanha'),
  ('UD Tijarafe', 'Espanha'),
  ('UD Villa de Santa Brígida', 'Espanha'),
  ('UDC Chantrea', 'Espanha'),
  ('UE Castelldefels', 'Espanha'),
  ('UE Cornellá', 'Espanha'),
  ('UE Figueres', 'Espanha'),
  ('UE Olot', 'Espanha'),
  ('UE Rapitenca', 'Espanha'),
  ('UE Rubí', 'Espanha'),
  ('UE Sant Andreu', 'Espanha'),
  ('UE Vilassar de Mar', 'Espanha'),
  ('UM Escobedo', 'Espanha'),
  ('Unami Club Polideportivo', 'Espanha'),
  ('Unión Deportiva Almería', 'Espanha'),
  ('Unión Deportiva Ibarra', 'Espanha'),
  ('Unión Molinense C.F', 'Espanha'),
  ('Unión Popular de Langreo', 'Espanha'),
  ('Unionistas de Salamanca CF', 'Espanha'),
  ('UP Plasencia', 'Espanha'),
  ('Urraca CF', 'Espanha'),
  ('Utebo FC', 'Espanha'),
  ('Valencia CF', 'Espanha'),
  ('Valencia CF Mestalla', 'Espanha'),
  ('Velarde CF', 'Espanha'),
  ('Villalonga FC', 'Espanha'),
  ('Villanueva CF', 'Espanha'),
  ('Villarreal CF', 'Espanha'),
  ('Villarreal CF B', 'Espanha'),
  ('Villarreal CF C', 'Espanha'),
  ('Xerez CD', 'Espanha'),
  ('Xerez Deportivo Fútbol Club', 'Espanha'),
  ('Xuventú Sanxenxo', 'Espanha'),
  ('Yagüe CF', 'Espanha'),
  ('Zalla UC', 'Espanha'),
  ('Zamora CF', 'Espanha'),
  ('Zamudio SD', 'Espanha'),
  ('Zarautz KE', 'Espanha'),
  ('Green Mamba FC', 'Essuatíni'),
  ('Manzini Wanderers FC', 'Essuatíni'),
  ('Mbabane Highlanders FC', 'Essuatíni'),
  ('Mbabane Swallows FC', 'Essuatíni'),
  ('Royal Leopards FC', 'Essuatíni'),
  ('Young Buffaloes FC', 'Essuatíni'),
  ('Atlanta United FC', 'Estados Unidos'),
  ('Atlético Dallas', 'Estados Unidos'),
  ('Austin Aztex', 'Estados Unidos'),
  ('Austin Bold FC', 'Estados Unidos'),
  ('Austin FC', 'Estados Unidos'),
  ('Bay FC', 'Estados Unidos'),
  ('Birmingham Legion FC', 'Estados Unidos'),
  ('Boston Legacy FC', 'Estados Unidos'),
  ('Buffalo Pro Soccer', 'Estados Unidos'),
  ('Charleston Battery', 'Estados Unidos'),
  ('Charlotte FC', 'Estados Unidos'),
  ('Charlotte Independence', 'Estados Unidos'),
  ('Chicago Fire FC', 'Estados Unidos'),
  ('Chicago Stars FC', 'Estados Unidos'),
  ('Colorado Rapids', 'Estados Unidos'),
  ('Colorado Springs Switchbacks FC', 'Estados Unidos'),
  ('Columbus Crew', 'Estados Unidos'),
  ('Columbus NWSL team', 'Estados Unidos'),
  ('DC United', 'Estados Unidos'),
  ('Denver Summit FC', 'Estados Unidos'),
  ('Detroit City FC', 'Estados Unidos'),
  ('El Paso Locomotive FC', 'Estados Unidos'),
  ('FC Cincinnati', 'Estados Unidos'),
  ('FC Dallas', 'Estados Unidos'),
  ('FC Tulsa', 'Estados Unidos'),
  ('Hartford Athletic', 'Estados Unidos'),
  ('Houston Dynamo FC', 'Estados Unidos'),
  ('Indy Eleven', 'Estados Unidos'),
  ('Inter Miami CF', 'Estados Unidos'),
  ('Jacksonville Armada FC', 'Estados Unidos'),
  ('LA Galaxy', 'Estados Unidos'),
  ('Las Vegas Lights FC', 'Estados Unidos'),
  ('Los Angeles FC', 'Estados Unidos'),
  ('Loudoun United FC', 'Estados Unidos'),
  ('Louisville City FC', 'Estados Unidos'),
  ('Memphis 901 FC', 'Estados Unidos'),
  ('Miami FC', 'Estados Unidos'),
  ('Minnesota United FC', 'Estados Unidos'),
  ('Nashville SC', 'Estados Unidos'),
  ('New England Revolution', 'Estados Unidos'),
  ('New Mexico United', 'Estados Unidos'),
  ('New York City FC', 'Estados Unidos'),
  ('North Carolina FC', 'Estados Unidos'),
  ('Oakland Roots SC', 'Estados Unidos'),
  ('OKC Energy FC', 'Estados Unidos'),
  ('Orange County SC', 'Estados Unidos'),
  ('Orlando City SC', 'Estados Unidos'),
  ('Pago Youth FC', 'Estados Unidos'),
  ('Philadelphia Fury', 'Estados Unidos'),
  ('Philadelphia Union', 'Estados Unidos'),
  ('Phoenix Rising FC', 'Estados Unidos'),
  ('Pittsburgh Riverhounds SC', 'Estados Unidos'),
  ('Portland Timbers', 'Estados Unidos'),
  ('Puerto Rico United', 'Estados Unidos'),
  ('Queensboro FC', 'Estados Unidos'),
  ('Real Salt Lake', 'Estados Unidos'),
  ('Red Bull New York', 'Estados Unidos'),
  ('Rhode Island FC', 'Estados Unidos'),
  ('Richmond Kickers', 'Estados Unidos'),
  ('Rio Grande Valley FC Toros', 'Estados Unidos'),
  ('Sacramento Republic FC', 'Estados Unidos'),
  ('San Antonio FC', 'Estados Unidos'),
  ('San Diego FC', 'Estados Unidos'),
  ('San Jose Earthquakes', 'Estados Unidos'),
  ('Seattle Sounders FC', 'Estados Unidos'),
  ('Sporting Kansas City', 'Estados Unidos'),
  ('St. Louis City SC', 'Estados Unidos'),
  ('Tampa Bay Rowdies', 'Estados Unidos'),
  ('USL Chicago', 'Estados Unidos'),
  ('FC Ajax Lasnamäe', 'Estónia'),
  ('FC Flora Tallinn', 'Estónia'),
  ('FC Infonet', 'Estónia'),
  ('FC Kuressaare', 'Estónia'),
  ('FC Lootus Kohtla-Järve', 'Estónia'),
  ('FC Nikol Tallinn', 'Estónia'),
  ('FC Nõmme United', 'Estónia'),
  ('FC Santos Tartu', 'Estónia'),
  ('FC Warrior Valga', 'Estónia'),
  ('FCI Levadia Tallinn', 'Estónia'),
  ('Harju JK Laagri', 'Estónia'),
  ('JK Maag Tammeka Tartu', 'Estónia'),
  ('JK Narva Trans', 'Estónia'),
  ('JK Sillamäe Kalev', 'Estónia'),
  ('JK Tallinna Kalev', 'Estónia'),
  ('JK Tallinna Sadam', 'Estónia'),
  ('JK Tammeka Tartu', 'Estónia'),
  ('Jõhvi FC Phoenix', 'Estónia'),
  ('Maardu Linnameeskond', 'Estónia'),
  ('Nõmme Kalju FC', 'Estónia'),
  ('Paide Linnameeskond', 'Estónia'),
  ('Pärnu JK Vaprus', 'Estónia'),
  ('Rakvere JK Tarvas', 'Estónia'),
  ('Tallinna JK', 'Estónia'),
  ('Tallinna JK Dünamo', 'Estónia'),
  ('Tallinna JK Legion', 'Estónia'),
  ('Viljandi JK Tulevik', 'Estónia'),
  ('Adama City FC', 'Etiópia'),
  ('Arba Minch FC', 'Etiópia'),
  ('Awassa City FC', 'Etiópia'),
  ('Bahir Dar Kenema FC', 'Etiópia'),
  ('CBE SA', 'Etiópia'),
  ('Cotton Factory Club', 'Etiópia'),
  ('Dashen Beer FC', 'Etiópia'),
  ('Dedebit', 'Etiópia'),
  ('Defence FC', 'Etiópia'),
  ('Dire Dawa City', 'Etiópia'),
  ('EEPCO FC', 'Etiópia'),
  ('Ethiopian Coffee FC', 'Etiópia'),
  ('Ethiopian Insurance FC', 'Etiópia'),
  ('Fasil Kenema SC', 'Etiópia'),
  ('Guna Trading FC', 'Etiópia'),
  ('Harrar Beer Bottling FC', 'Etiópia'),
  ('Lideta Nyala', 'Etiópia'),
  ('Medr Babur', 'Etiópia'),
  ('Mekelle 70 Enderta FC', 'Etiópia'),
  ('Metehara Sugar', 'Etiópia'),
  ('Muger Cement', 'Etiópia'),
  ('Nyala SC', 'Etiópia'),
  ('Ogaden Anbassa', 'Etiópia'),
  ('Saint George SC', 'Etiópia'),
  ('Sebeta City', 'Etiópia'),
  ('Sidama Coffee', 'Etiópia'),
  ('Southern Police', 'Etiópia'),
  ('Tikur Abay Transport', 'Etiópia'),
  ('Trans Ethiopia', 'Etiópia'),
  ('Weha Serawoch', 'Etiópia'),
  ('Welwalo Adigrat University FC', 'Etiópia'),
  ('Wolayta Dicha', 'Etiópia'),
  ('Woldia City', 'Etiópia'),
  ('Wolkite City FC', 'Etiópia'),
  ('Ba FC', 'Fiji'),
  ('Lautoka FC', 'Fiji'),
  ('Nadi FC', 'Fiji'),
  ('Rewa FC', 'Fiji'),
  ('Suva FC', 'Fiji'),
  ('Davao Aguilas FC', 'Filipinas'),
  ('Dynamic Herb Cebu FC', 'Filipinas'),
  ('Global Cebu FC', 'Filipinas'),
  ('Ilocos United FC', 'Filipinas'),
  ('Kaya FC', 'Filipinas'),
  ('Manila Digger FC', 'Filipinas'),
  ('One Taguig FC', 'Filipinas'),
  ('Stallion–Laguna FC', 'Filipinas'),
  ('United City FC', 'Filipinas'),
  ('AC Oulu', 'Finlândia'),
  ('Atlantis FC', 'Finlândia'),
  ('FC Haka', 'Finlândia'),
  ('FC Hämeenlinna', 'Finlândia'),
  ('FC Honka', 'Finlândia'),
  ('FC Ilves', 'Finlândia'),
  ('FC Inter Turku', 'Finlândia'),
  ('FC Jazz', 'Finlândia'),
  ('FC Kuusysi', 'Finlândia'),
  ('FC Lahti', 'Finlândia'),
  ('FC Viikingit', 'Finlândia'),
  ('FF Jaro', 'Finlândia'),
  ('Helsingin Jalkapalloklubi', 'Finlândia'),
  ('Helsingin Palloseura', 'Finlândia'),
  ('HIFK Fotboll', 'Finlândia'),
  ('IF Gnistan', 'Finlândia'),
  ('IFK Mariehamn', 'Finlândia'),
  ('JJK Jyväskylä', 'Finlândia'),
  ('Kokkolan Palloveikot', 'Finlândia'),
  ('Kotkan Työväen Palloilijat', 'Finlândia'),
  ('Kuopion Palloseura', 'Finlândia'),
  ('Mikkelin Palloilijat', 'Finlândia'),
  ('MYPA', 'Finlândia'),
  ('Oulun Palloseura', 'Finlândia'),
  ('Palloseura Kemi Kings', 'Finlândia'),
  ('RoPS', 'Finlândia'),
  ('Seinäjoen Jalkapallokerho', 'Finlândia'),
  ('Tampere United', 'Finlândia'),
  ('Tampereen Pallo-Veikot', 'Finlândia'),
  ('TPS Turku', 'Finlândia'),
  ('Unitas Sports Club', 'Finlândia'),
  ('Vaasan Palloseura', 'Finlândia'),
  ('AC Ajaccio', 'França'),
  ('AC Arles', 'França'),
  ('AF Bobigny', 'França'),
  ('AF Lozère', 'França'),
  ('AFC Compiègne', 'França'),
  ('Ain Sud', 'França'),
  ('AJ Auxerre', 'França'),
  ('AJSS Saintes', 'França'),
  ('Amiens AC', 'França'),
  ('Amiens SC', 'França'),
  ('Angers SCO', 'França'),
  ('Angoulême Charente FC', 'França'),
  ('Arras Football', 'França'),
  ('AS Aix-en-Provence', 'França'),
  ('AS Beauvais Oise', 'França'),
  ('AS Béziers', 'França'),
  ('AS Cannes', 'França'),
  ('AS Cherbourg Football', 'França'),
  ('AS Dragon', 'França'),
  ('AS Foot Les Verchers-Saint-Georges-sur-Layon', 'França'),
  ('AS Furiani-Agliani', 'França'),
  ('AS Gardanne', 'França'),
  ('AS Illzach Modenheim', 'França'),
  ('AS Jeunes Tahitiens', 'França'),
  ('AS La Châtaigneraie', 'França'),
  ('AS Magenta', 'França'),
  ('AS Manu-Ura', 'França'),
  ('AS Marck', 'França'),
  ('AS Mont-Dore', 'França'),
  ('AS Moulins', 'França'),
  ('AS Nancy-Lorraine', 'França'),
  ('AS Ornans', 'França'),
  ('AS Pirae', 'França'),
  ('AS Poissy', 'França'),
  ('AS Roniu', 'França'),
  ('AS Saint-Étienne', 'França'),
  ('AS Saint-Priest', 'França'),
  ('AS Tamarii Faa''a', 'França'),
  ('AS Tefana', 'França'),
  ('AS Tournefeuille', 'França'),
  ('AS Valence', 'França'),
  ('AS Vénus', 'França'),
  ('AS Vitré', 'França'),
  ('AS Yzeure', 'França'),
  ('ASA Issy', 'França'),
  ('ASC Biesheim', 'França'),
  ('ASF Andrézieux', 'França'),
  ('ASG Juventus de Sainte-Anne', 'França'),
  ('ASJ Soyaux', 'França'),
  ('ASM Belfort', 'França'),
  ('ASPTT Albi', 'França'),
  ('ASPV Strasbourg', 'França'),
  ('Association Sportive Central Sport', 'França'),
  ('Aurillac FC2A', 'França'),
  ('Avignon Foot 84', 'França'),
  ('Aviron Bayonnais FC', 'França'),
  ('Balma SC', 'França'),
  ('Beaune FC', 'França'),
  ('Bergerac Périgord FC', 'França'),
  ('Besançon RC', 'França'),
  ('Blagnac FC', 'França'),
  ('Blois Football 41', 'França'),
  ('C'' Chartres Football', 'França'),
  ('CA Paris-Charenton', 'França'),
  ('CA Pontarlier', 'França'),
  ('Canet Roussillon Football Club', 'França'),
  ('Chaumont FC', 'França'),
  ('Clermont Foot 63', 'França'),
  ('Club Français', 'França'),
  ('Club Franciscain', 'França'),
  ('CMS Oissel', 'França'),
  ('CO Les Ulis', 'França'),
  ('CS Avion', 'França'),
  ('CS Louhans-Cuiseaux', 'França'),
  ('CS Moulien', 'França'),
  ('CS Sedan Ardennes', 'França'),
  ('CSO Amnéville', 'França'),
  ('Dijon FCO', 'França'),
  ('Dinan-Léhon FC', 'França'),
  ('ÉDS Montluçon', 'França'),
  ('ÉF Reims-Champagne', 'França'),
  ('En Avant de Guingamp', 'França'),
  ('Entente Feignies Aulnoye FC', 'França'),
  ('Entente SSG', 'França'),
  ('EP Manosque', 'França'),
  ('ES Bonchamp', 'França'),
  ('ES Cannet Rocheville', 'França'),
  ('ES Paulhan-Pézenas', 'França'),
  ('ES Thaon', 'França'),
  ('ES Troyes AC', 'França'),
  ('ES Uzès Pont du Gard', 'França'),
  ('ES Viry-Châtillon', 'França'),
  ('ES Wasquehal', 'França'),
  ('ESM Gonfreville', 'França'),
  ('ESOF Vendée La Roche-sur-Yon', 'França'),
  ('Étoile Fréjus Saint-Raphaël', 'França'),
  ('Evian Thonon Gaillard FC', 'França'),
  ('Évreux FC 27', 'França'),
  ('FAIRM Île-Rousse Monticello', 'França'),
  ('FC Annecy', 'França'),
  ('FC Antibes', 'França'),
  ('FC Bagnols Pont', 'França'),
  ('FC Bassin d''Arcachon', 'França'),
  ('FC Bastia-Borgo', 'França'),
  ('FC Chambly', 'França'),
  ('FC Cournon-d''Auvergne', 'França'),
  ('FC Dieppe', 'França'),
  ('FC Drouais', 'França'),
  ('FC Échirolles', 'França'),
  ('FC Fleury 91', 'França'),
  ('FC Girondins de Bordeaux', 'França'),
  ('FC Gueugnon', 'França'),
  ('FC Istres', 'França'),
  ('FC Les Lilas', 'França'),
  ('FC Libourne', 'França'),
  ('FC Libourne-Saint-Seurin', 'França'),
  ('FC Lorient', 'França'),
  ('FC Mantes', 'França'),
  ('FC Marmande', 'França'),
  ('FC Martigues', 'França'),
  ('FC Metz', 'França'),
  ('FC Montceau', 'França'),
  ('FC Mulhouse', 'França'),
  ('FC Nantes', 'França'),
  ('FC Rouen', 'França'),
  ('FC Saint-Jean-le-Blanc', 'França'),
  ('FC Saint-Lô Manche', 'França'),
  ('FC Saint-Louis Neuweg', 'França'),
  ('FC Sens', 'França'),
  ('FC Sète', 'França'),
  ('FC Sochaux-Montbéliard', 'França'),
  ('FC Vendenheim', 'França'),
  ('FC Versailles', 'França'),
  ('FCA Calvi', 'França'),
  ('FCM Aubervilliers', 'França'),
  ('FCSR Haguenau', 'França'),
  ('FCSR Obernai', 'França'),
  ('FF Yzeure Allier Auvergne', 'França'),
  ('Football Bourg-en-Bresse Péronnas 01', 'França'),
  ('Football Club Villefranche Beaujolais', 'França'),
  ('FR Saint Marcel', 'França'),
  ('Gap FC', 'França'),
  ('Gazélec Ajaccio', 'França'),
  ('Genêts Anglet', 'França'),
  ('Girondins de Bordeaux', 'França'),
  ('Grand Ouest Association Lyonnaise Football Club', 'França'),
  ('Grenoble Foot 38', 'França'),
  ('GS Neuves-Maisons', 'França'),
  ('GSI Pontivy', 'França'),
  ('Hauts Lyonnais', 'França'),
  ('Hienghène Sport', 'França'),
  ('Hyères FC', 'França'),
  ('IC Croix', 'França'),
  ('INF Clairefontaine', 'França'),
  ('J3S Amilly', 'França'),
  ('JA Drancy', 'França'),
  ('JS Saint-Pierroise', 'França'),
  ('Jura Dolois Foot', 'França'),
  ('Jura Sud Foot', 'França'),
  ('La Roche VF', 'França'),
  ('La Vitréenne FC', 'França'),
  ('Lannion FC', 'França'),
  ('LB Châteauroux', 'França'),
  ('Le Havre AC', 'França'),
  ('Le Mans FC', 'França'),
  ('Le Puy Foot 43 Auvergne', 'França'),
  ('Les Herbiers VF', 'França'),
  ('Les Marseillaises', 'França'),
  ('Lille OSC', 'França'),
  ('Lille OSC II', 'França'),
  ('Limoges Football', 'França'),
  ('Montpellier Hérault Sport Club', 'França'),
  ('Nîmes Olympique', 'França'),
  ('OGC Nice', 'França'),
  ('Olympique Alès', 'França'),
  ('Olympique de Marseille', 'França'),
  ('Olympique Grande-Synthe', 'França'),
  ('Olympique Lyonnais', 'França'),
  ('Olympique Noisy-le-Sec', 'França'),
  ('Olympique Saint-Quentin', 'França'),
  ('Olympique Saumur FC', 'França'),
  ('Pacy Ménilles RC', 'França'),
  ('Paris 13 Atletico', 'França'),
  ('Paris FC', 'França'),
  ('Paris Saint-Germain FC', 'França'),
  ('Paris So Cœur', 'França'),
  ('Pau Football Club', 'França'),
  ('Poitiers FC', 'França'),
  ('Quimper Kerfeunteun FC', 'França'),
  ('Racing Club de France', 'França'),
  ('Racing Club de Grasse', 'França'),
  ('Rapid de Menton', 'França'),
  ('RC Lens', 'França'),
  ('RC Strasbourg Alsace', 'França'),
  ('RCO Agde', 'França'),
  ('Red Star FC', 'França'),
  ('Rodez AF', 'França'),
  ('SA Thiers', 'França'),
  ('Sablé FC', 'França'),
  ('Saint-Alban Aucamville FC', 'França'),
  ('Sainte-Geneviève Sports', 'França'),
  ('Saint-Pryve Saint-Hilaire FC', 'França'),
  ('Sarreguemines FC', 'França'),
  ('SAS Épinal', 'França'),
  ('SC Bastia', 'França'),
  ('SC Fives', 'França'),
  ('SC Hazebrouck', 'França'),
  ('SC Marnaval', 'França'),
  ('SC Schiltigheim', 'França'),
  ('SC Selongey', 'França'),
  ('SO Chambéry Foot', 'França'),
  ('SO Châtellerault', 'França'),
  ('SO Cholet', 'França'),
  ('SO Romorantin', 'França'),
  ('Sporting Club Lyon', 'França'),
  ('Sporting Toulon Var', 'França'),
  ('SR Colmar', 'França'),
  ('Stade Beaucairois FC', 'França'),
  ('Stade Bordelais', 'França'),
  ('Stade Brestois 29', 'França'),
  ('Stade Briochin', 'França'),
  ('Stade de Reims', 'França'),
  ('Stade Français Football', 'França'),
  ('Stade Lavallois', 'França'),
  ('Stade Malherbe Caen', 'França'),
  ('Stade Montois', 'França'),
  ('Stade Plabennecois', 'França'),
  ('Stade Rennais FC', 'França'),
  ('Standard Athletic Club', 'França'),
  ('SU Agen Football', 'França'),
  ('SU Dives', 'França'),
  ('Tarbes Pyrénées Football', 'França'),
  ('Thouars Foot 79', 'França'),
  ('Toulouse FC', 'França'),
  ('Tours FC.', 'França'),
  ('Trélissac FC', 'França'),
  ('Trinité Sport Football Club', 'França'),
  ('UA Cognac', 'França'),
  ('UA Valettoise', 'França'),
  ('UJA Maccabi Paris Métropole', 'França'),
  ('Union sportive de Forbach', 'França'),
  ('US Albi', 'França'),
  ('US Alençon', 'França'),
  ('US Avranches', 'França'),
  ('US Boulogne', 'França'),
  ('US Changé', 'França'),
  ('US Chantilly', 'França'),
  ('US Colomiers Football', 'França'),
  ('US Concarneau', 'França'),
  ('US Créteil-Lusitanos', 'França'),
  ('US de Lège-Cap-Ferret', 'França'),
  ('US Feurs', 'França'),
  ('US Granville', 'França'),
  ('US Gravelines Foot', 'França'),
  ('US Le Pontet', 'França'),
  ('US Lesquin', 'França'),
  ('US Lusitanos Saint-Maur', 'França'),
  ('US Luzenac', 'França'),
  ('US Marignane', 'França'),
  ('US Marseille Endoume', 'França'),
  ('US Montagnarde', 'França'),
  ('US municipale senlisienne', 'França'),
  ('US Orléans', 'França'),
  ('US Quevilly', 'França'),
  ('US Raon-l''Étape', 'França'),
  ('US Roye-Noyon', 'França'),
  ('US Saint-Malo', 'França'),
  ('US Saint-Omer', 'França'),
  ('US Sarre-Union', 'França'),
  ('US Sénart-Moissy', 'França'),
  ('US Tourcoing', 'França'),
  ('USC Corte', 'França'),
  ('USE Avoine', 'França'),
  ('USJA Carquefou', 'França'),
  ('USL Dunkerque', 'França'),
  ('USM Montargis', 'França'),
  ('USON Mondeville', 'França'),
  ('USSA Vertou', 'França'),
  ('Valenciennes FC', 'França'),
  ('Vannes OC', 'França'),
  ('Vendée Fontenay Foot', 'França'),
  ('Vendée Luçon Football', 'França'),
  ('Vendée Poiré sur Vie Football', 'França'),
  ('Vesoul Haute-Saône', 'França'),
  ('Vie au grand air de Saint-Maur', 'França'),
  ('Vierzon FC', 'França'),
  ('Villemomble Sports', 'França'),
  ('Voltigeurs de Châteaubriant', 'França'),
  ('AS Mangasport', 'Gabão'),
  ('CF Mounana', 'Gabão'),
  ('FC 105 Libreville', 'Gabão'),
  ('US Bitam', 'Gabão'),
  ('Gambia Ports Authority FC', 'Gâmbia'),
  ('Real de Banjul FC', 'Gâmbia'),
  ('Wallidan FC', 'Gâmbia'),
  ('Accra Great Olympics FC', 'Gana'),
  ('Accra Hearts of Oak SC', 'Gana'),
  ('Aduana Stars', 'Gana'),
  ('All Blacks FC', 'Gana'),
  ('Asante Kotoko FC', 'Gana'),
  ('Ashanti Gold SC', 'Gana'),
  ('BA Stars', 'Gana'),
  ('Basake Holy Stars Football Club', 'Gana'),
  ('Bechem United', 'Gana'),
  ('Berekum Arsenal', 'Gana'),
  ('Berekum Chelsea FC', 'Gana'),
  ('Bibiani Gold Stars FC', 'Gana'),
  ('Cornerstones', 'Gana'),
  ('Dreams FC', 'Gana'),
  ('Ebusua Dwarfs', 'Gana'),
  ('Elmina Sharks FC', 'Gana'),
  ('Heart of Lions FC', 'Gana'),
  ('Hohoe United FC', 'Gana'),
  ('International Allies FC', 'Gana'),
  ('Karela United FC', 'Gana'),
  ('King Faisal Babes', 'Gana'),
  ('Legon Cities FC', 'Gana'),
  ('Liberty Professionals FC', 'Gana'),
  ('Medeama SC', 'Gana'),
  ('Nations FC', 'Gana'),
  ('New Edubiase United', 'Gana'),
  ('Real Republicans', 'Gana'),
  ('Real Sportive', 'Gana'),
  ('Real Tamale United', 'Gana'),
  ('Samartex', 'Gana'),
  ('Sekondi Hasaacas FC', 'Gana'),
  ('Tamale City Football Club', 'Gana'),
  ('Techiman Eleven Wonders FC', 'Gana'),
  ('Tema Youth', 'Gana'),
  ('Wassaman United', 'Gana'),
  ('West African Football Academy', 'Gana'),
  ('FC Baia Zugdidi', 'Geórgia'),
  ('FC Borjomi', 'Geórgia'),
  ('FC Chikhura Sachkhere', 'Geórgia'),
  ('FC Dila Gori', 'Geórgia'),
  ('FC Dinamo Batumi', 'Geórgia'),
  ('FC Dinamo Tbilisi', 'Geórgia'),
  ('FC Gagra', 'Geórgia'),
  ('FC Guria Lanchkhuti', 'Geórgia'),
  ('FC Iberia 1999', 'Geórgia'),
  ('FC Kakheti Telavi', 'Geórgia'),
  ('FC Kolkheti-1913 Poti', 'Geórgia'),
  ('FC Lokomotivi Tbilisi', 'Geórgia'),
  ('FC Merani Martvili', 'Geórgia'),
  ('FC Merani Tbilisi', 'Geórgia'),
  ('FC Meskheti Akhaltsikhe', 'Geórgia'),
  ('FC Mglebi Zugdidi', 'Geórgia'),
  ('FC Milani Tsnori', 'Geórgia'),
  ('FC Rustavi', 'Geórgia'),
  ('FC Samgurali Tskhaltubo', 'Geórgia'),
  ('FC Samtredia', 'Geórgia'),
  ('FC Sapovnela Terjola', 'Geórgia'),
  ('FC Shukura Kobuleti', 'Geórgia'),
  ('FC Sioni Bolnisi', 'Geórgia'),
  ('FC Spaeri', 'Geórgia'),
  ('FC Spartaki Tbilisi', 'Geórgia'),
  ('FC Telavi', 'Geórgia'),
  ('FC Torpedo Kutaisi', 'Geórgia'),
  ('FC Tskhinvali', 'Geórgia'),
  ('FC WIT Georgia', 'Geórgia'),
  ('FC Zestaponi', 'Geórgia'),
  ('Meshakhte Tkibuli', 'Geórgia'),
  ('TSU Tbilisi', 'Geórgia'),
  ('Lincoln Red Imps FC', 'Gibraltar'),
  ('AE Kifisia FC', 'Grécia'),
  ('AO Kerkyra', 'Grécia'),
  ('APO Akratitos Ano Liosia', 'Grécia'),
  ('APS Panthrakikos', 'Grécia'),
  ('Asteras Tripoli FC', 'Grécia'),
  ('Athinaikos FC', 'Grécia'),
  ('Athlitiki Enosi Larissa FC', 'Grécia'),
  ('Atromitos FC', 'Grécia'),
  ('Diagoras Rodos FC', 'Grécia'),
  ('Doxa Drama FC', 'Grécia'),
  ('Ergotelis FC', 'Grécia'),
  ('Ionikos Nikaia FC', 'Grécia'),
  ('Kalamata FC', 'Grécia'),
  ('Kalloni SC', 'Grécia'),
  ('Levadiakos FC', 'Grécia'),
  ('MGS Apollon Kalamarias (association football)', 'Grécia'),
  ('Panathinaikos FC', 'Grécia'),
  ('Panetolikos FC', 'Grécia'),
  ('Panionios FC', 'Grécia'),
  ('PAS Lamia 1964', 'Grécia'),
  ('Platanias Chania FC', 'Grécia'),
  ('Thrasyvoulos FC', 'Grécia'),
  ('Volos NFC', 'Grécia'),
  ('Xanthi FC', 'Grécia'),
  ('Antigua GFC', 'Guatemala'),
  ('Aurora FC', 'Guatemala'),
  ('CD Suchitepéquez', 'Guatemala'),
  ('Club Deportivo Malacateco', 'Guatemala'),
  ('Cobán Imperial', 'Guatemala'),
  ('Comunicaciones FC', 'Guatemala'),
  ('CSD Municipal', 'Guatemala'),
  ('CSD Xelajú MC', 'Guatemala'),
  ('Deportivo Chiantla', 'Guatemala'),
  ('Deportivo Marquense', 'Guatemala'),
  ('Deportivo Mictlán', 'Guatemala'),
  ('Deportivo Petapa', 'Guatemala'),
  ('Deportivo Siquinalá', 'Guatemala'),
  ('Deportivo Xinabajul', 'Guatemala'),
  ('Deportivo Zacapa', 'Guatemala'),
  ('Halcones Fútbol Club', 'Guatemala'),
  ('Heredia Jaguares de Peten', 'Guatemala'),
  ('IRCA (football club)', 'Guatemala'),
  ('Juventud Escuintleca', 'Guatemala'),
  ('Universidad SC', 'Guatemala'),
  ('AS Ashanti Golden Boys', 'Guiné'),
  ('AS Batè Nafadji', 'Guiné'),
  ('AS Kaloum Star', 'Guiné'),
  ('ASFAG', 'Guiné'),
  ('Athlético de Coléah', 'Guiné'),
  ('Baraka Djoma SSG', 'Guiné'),
  ('Club Industriel de Kamsar', 'Guiné'),
  ('Espoir de Labé', 'Guiné'),
  ('Étoile de Guinée', 'Guiné'),
  ('FC Séquence de Dixinn', 'Guiné'),
  ('Fello Star', 'Guiné'),
  ('Flamme Olympique FC', 'Guiné'),
  ('Gangan FC', 'Guiné'),
  ('Hafia Football Club', 'Guiné'),
  ('Horoya AC', 'Guiné'),
  ('Sankaran FC', 'Guiné'),
  ('Santoba FC', 'Guiné'),
  ('Satellite FC', 'Guiné'),
  ('Soumba FC', 'Guiné'),
  ('Tabounsou FC', 'Guiné'),
  ('Wakriya AC', 'Guiné'),
  ('Akonangui FC', 'Guiné Equatorial'),
  ('CD Elá Nguema', 'Guiné Equatorial'),
  ('Clube de Futebol "Os Balantas"', 'Guiné-Bissau'),
  ('Sport Bissau e Benfica', 'Guiné-Bissau'),
  ('Sporting Clube de Bissau', 'Guiné-Bissau'),
  ('Aigle Noir AC', 'Haiti'),
  ('RC Haïtien', 'Haiti'),
  ('Violette AC', 'Haiti'),
  ('CD Atlético Español', 'Honduras'),
  ('CD Choloma', 'Honduras'),
  ('CD Marathón', 'Honduras'),
  ('CD Olimpia', 'Honduras'),
  ('CD Petrotela', 'Honduras'),
  ('CD Real Juventud', 'Honduras'),
  ('CD Real Sociedad', 'Honduras'),
  ('CD Verdún', 'Honduras'),
  ('CDS Vida', 'Honduras'),
  ('Club Deportivo Victoria', 'Honduras'),
  ('FC Motagua', 'Honduras'),
  ('Hispano FC', 'Honduras'),
  ('Honduras Salzburg', 'Honduras'),
  ('Platense FC', 'Honduras'),
  ('Real CD España', 'Honduras'),
  ('Savio Fútbol Club', 'Honduras'),
  ('Social Sol', 'Honduras'),
  ('Tegucigalpa FC', 'Honduras'),
  ('Kitchee SC', 'Hong Kong'),
  ('Lee Man FC', 'Hong Kong'),
  ('Balatonlelle SE', 'Hungria'),
  ('Békéscsaba 1912 Előre SE', 'Hungria'),
  ('BFC Siófok', 'Hungria'),
  ('Budafoki MTE', 'Hungria'),
  ('Budapest Honvéd FC', 'Hungria'),
  ('Budapesti TC', 'Hungria'),
  ('Budapesti VSC', 'Hungria'),
  ('Csepel SC', 'Hungria'),
  ('Debreceni VSC', 'Hungria'),
  ('Diósgyőri VTK', 'Hungria'),
  ('Dorogi FC', 'Hungria'),
  ('Dunaújváros FC', 'Hungria'),
  ('Egri FC', 'Hungria'),
  ('Fehérvár FC', 'Hungria'),
  ('Ferenc Puskás Football Academy', 'Hungria'),
  ('Ferencvárosi TC', 'Hungria'),
  ('Gyirmót FC Győr', 'Hungria'),
  ('Győri ETO FC', 'Hungria'),
  ('III. Kerületi TUE', 'Hungria'),
  ('Kaposvári Rákóczi FC', 'Hungria'),
  ('Kazincbarcikai SC', 'Hungria'),
  ('Kecskeméti TE', 'Hungria'),
  ('Kisvárda FC', 'Hungria'),
  ('Komlói Bányász SK', 'Hungria'),
  ('Körmendi FC', 'Hungria'),
  ('Lombard-Pápa TFC', 'Hungria'),
  ('Mezőkövesd-Zsóry SE', 'Hungria'),
  ('MTK Budapest FC', 'Hungria'),
  ('Nyíregyháza Spartacus FC', 'Hungria'),
  ('Paksi FC', 'Hungria'),
  ('Pécs-Baranya FC', 'Hungria'),
  ('Pécsi MFC', 'Hungria'),
  ('Salgótarjáni BTC', 'Hungria'),
  ('Szolnoki MÁV FC', 'Hungria'),
  ('Szombathelyi Haladás', 'Hungria'),
  ('Tatabányai SC', 'Hungria'),
  ('Újpest FC', 'Hungria'),
  ('Vác FC', 'Hungria'),
  ('Vasas FC', 'Hungria'),
  ('Zalaegerszegi TE', 'Hungria'),
  ('Al-Ahli Club Sana''a', 'Iémen'),
  ('Al-Saqr', 'Iémen'),
  ('Al-Tilal SC', 'Iémen'),
  ('07 Vestur', 'Ilhas Faroé'),
  ('Argja Bóltfelag', 'Ilhas Faroé'),
  ('B36 Tórshavn', 'Ilhas Faroé'),
  ('B68 Toftir', 'Ilhas Faroé'),
  ('B71 Sandoy', 'Ilhas Faroé'),
  ('EB/Streymur', 'Ilhas Faroé'),
  ('FC Suðuroy', 'Ilhas Faroé'),
  ('Havnar Bóltfelag', 'Ilhas Faroé'),
  ('ÍF Fuglafjørður', 'Ilhas Faroé'),
  ('KÍ Klaksvík', 'Ilhas Faroé'),
  ('MB Miðvágur', 'Ilhas Faroé'),
  ('NSÍ Runavík', 'Ilhas Faroé'),
  ('Royn Hvalba', 'Ilhas Faroé'),
  ('SÍ Sørvágur', 'Ilhas Faroé'),
  ('Skála ÍF', 'Ilhas Faroé'),
  ('TB Tvøroyri', 'Ilhas Faroé'),
  ('TB/FC Suðuroy/Royn', 'Ilhas Faroé'),
  ('Víkingur Gøta', 'Ilhas Faroé'),
  ('Koloale FC', 'Ilhas Salomão'),
  ('Kossa FC', 'Ilhas Salomão'),
  ('Marist FC', 'Ilhas Salomão'),
  ('Solomon Warriors FC', 'Ilhas Salomão'),
  ('Aizawl FC', 'Índia'),
  ('Bengaluru FC', 'Índia'),
  ('Chennaiyin FC', 'Índia'),
  ('Churchill Brothers SC', 'Índia'),
  ('Dempo SC', 'Índia'),
  ('East Bengal FC', 'Índia'),
  ('FC Goa', 'Índia'),
  ('FC Pune City', 'Índia'),
  ('Gokulam Kerala FC', 'Índia'),
  ('Hyderabad FC', 'Índia'),
  ('Jamshedpur FC', 'Índia'),
  ('Kerala Blasters FC', 'Índia'),
  ('Mohammedan Sporting Club', 'Índia'),
  ('Mohun Bagan AC', 'Índia'),
  ('Mohun Bagan Super Giant', 'Índia'),
  ('Mumbai City FC', 'Índia'),
  ('Mumbai FC', 'Índia'),
  ('NEROCA FC', 'Índia'),
  ('NorthEast United FC', 'Índia'),
  ('Odisha FC', 'Índia'),
  ('Pune FC', 'Índia'),
  ('Punjab FC', 'Índia'),
  ('Salgaocar FC', 'Índia'),
  ('Sporting Clube de Goa', 'Índia'),
  ('Arema FC', 'Indonésia'),
  ('Bali United FC', 'Indonésia'),
  ('Bhayangkara FC', 'Indonésia'),
  ('Borneo FC Samarinda', 'Indonésia'),
  ('Deltras FC', 'Indonésia'),
  ('Dewa United FC', 'Indonésia'),
  ('Madura United FC', 'Indonésia'),
  ('Mitra Kukar FC', 'Indonésia'),
  ('Persebaya Surabaya', 'Indonésia'),
  ('Persegres Gresik United', 'Indonésia'),
  ('Persela Lamongan', 'Indonésia'),
  ('Persepam Madura United', 'Indonésia'),
  ('Persib Bandung', 'Indonésia'),
  ('Persiba Balikpapan', 'Indonésia'),
  ('Persidafon Dafonsoro', 'Indonésia'),
  ('Persija Jakarta', 'Indonésia'),
  ('Persik Kediri', 'Indonésia'),
  ('Persikabo 1973', 'Indonésia'),
  ('Persipura Jayapura', 'Indonésia'),
  ('Persiram Raja Ampat', 'Indonésia'),
  ('Persita Tangerang', 'Indonésia'),
  ('Persiwa Wamena', 'Indonésia'),
  ('PS Barito Putera', 'Indonésia'),
  ('PSAP Sigli', 'Indonésia'),
  ('PSIS Semarang', 'Indonésia'),
  ('PSM Makassar', 'Indonésia'),
  ('PSMS Medan', 'Indonésia'),
  ('PSPS Riau', 'Indonésia'),
  ('PSS Sleman', 'Indonésia'),
  ('Semen Padang FC', 'Indonésia'),
  ('Sriwijaya FC', 'Indonésia'),
  ('Accrington Stanley', 'Inglaterra'),
  ('AFC Bournemouth', 'Inglaterra'),
  ('AFC Hayes', 'Inglaterra'),
  ('AFC Telford United', 'Inglaterra'),
  ('AFC Wimbledon', 'Inglaterra'),
  ('Aldershot Town', 'Inglaterra'),
  ('Alfreton Town', 'Inglaterra'),
  ('Altrincham', 'Inglaterra'),
  ('Arsenal', 'Inglaterra'),
  ('Ashton United', 'Inglaterra'),
  ('Aston Villa', 'Inglaterra'),
  ('Barnet', 'Inglaterra'),
  ('Barnsley', 'Inglaterra'),
  ('Barrow', 'Inglaterra'),
  ('Basingstoke Town', 'Inglaterra'),
  ('Bath City', 'Inglaterra'),
  ('Berwick Rangers', 'Inglaterra'),
  ('Bideford', 'Inglaterra'),
  ('Billericay Town', 'Inglaterra'),
  ('Birmingham City', 'Inglaterra'),
  ('Bishop''s Stortford', 'Inglaterra'),
  ('Blackburn Rovers', 'Inglaterra'),
  ('Blackpool', 'Inglaterra'),
  ('Blyth Spartans', 'Inglaterra')
) as v(name, country)
join countries c on c.name = v.country
on conflict (name, country_id) do nothing;
