-- Football clubs from Wikidata (CC0), part 3 of 4. Safe to re-run: existing name+country pairs are skipped.
-- Run 0023_uk_countries.sql first (it creates Inglaterra, Escocia, etc.).
insert into teams (name, country_id)
select v.name, c.id
from (values
  ('Bognor Regis Town', 'Inglaterra'),
  ('Bolton Wanderers', 'Inglaterra'),
  ('Boreham Wood', 'Inglaterra'),
  ('Boston United', 'Inglaterra'),
  ('Bradford (Park Avenue)', 'Inglaterra'),
  ('Bradford City', 'Inglaterra'),
  ('Braintree Town', 'Inglaterra'),
  ('Brentford', 'Inglaterra'),
  ('Brighton & Hove Albion', 'Inglaterra'),
  ('Bristol City', 'Inglaterra'),
  ('Bristol Rovers', 'Inglaterra'),
  ('Bromley', 'Inglaterra'),
  ('Burnley', 'Inglaterra'),
  ('Burton Albion', 'Inglaterra'),
  ('Bury', 'Inglaterra'),
  ('Bury Town', 'Inglaterra'),
  ('Cambridge United', 'Inglaterra'),
  ('Canvey Island', 'Inglaterra'),
  ('Carlisle United', 'Inglaterra'),
  ('Charlton Athletic', 'Inglaterra'),
  ('Chelmsford City', 'Inglaterra'),
  ('Chelsea FC Development Squad and Academy', 'Inglaterra'),
  ('Cheltenham Town', 'Inglaterra'),
  ('Chester', 'Inglaterra'),
  ('Chesterfield', 'Inglaterra'),
  ('Chorley', 'Inglaterra'),
  ('Colchester United', 'Inglaterra'),
  ('Congleton Town', 'Inglaterra'),
  ('Corinthian Casuals', 'Inglaterra'),
  ('Coventry City', 'Inglaterra'),
  ('Crawley Town', 'Inglaterra'),
  ('Cray Wanderers', 'Inglaterra'),
  ('Crewe Alexandra', 'Inglaterra'),
  ('Crystal Palace', 'Inglaterra'),
  ('Dagenham & Redbridge', 'Inglaterra'),
  ('Darlington', 'Inglaterra'),
  ('Dartford', 'Inglaterra'),
  ('Derby County', 'Inglaterra'),
  ('Doncaster Rovers', 'Inglaterra'),
  ('Dorchester Town', 'Inglaterra'),
  ('Dorking Wanderers', 'Inglaterra'),
  ('Dover Athletic', 'Inglaterra'),
  ('Droylsden', 'Inglaterra'),
  ('Dulwich Hamlet', 'Inglaterra'),
  ('Eastbourne Borough', 'Inglaterra'),
  ('Eastbourne Town', 'Inglaterra'),
  ('Eastleigh', 'Inglaterra'),
  ('Ebbsfleet United', 'Inglaterra'),
  ('Enfield Town', 'Inglaterra'),
  ('Everton', 'Inglaterra'),
  ('Exeter City', 'Inglaterra'),
  ('Farnborough', 'Inglaterra'),
  ('Farsley Celtic', 'Inglaterra'),
  ('FC Halifax Town', 'Inglaterra'),
  ('FC United of Manchester', 'Inglaterra'),
  ('Fleetwood Town', 'Inglaterra'),
  ('Folkestone Invicta', 'Inglaterra'),
  ('Forest Green Rovers', 'Inglaterra'),
  ('Fulham', 'Inglaterra'),
  ('Gainsborough Trinity', 'Inglaterra'),
  ('Gateshead', 'Inglaterra'),
  ('Gillingham', 'Inglaterra'),
  ('Glossop North End', 'Inglaterra'),
  ('Gloucester City', 'Inglaterra'),
  ('Goole', 'Inglaterra'),
  ('Grays Athletic', 'Inglaterra'),
  ('Grimsby Town', 'Inglaterra'),
  ('Guildford City', 'Inglaterra'),
  ('Guiseley', 'Inglaterra'),
  ('Hallam', 'Inglaterra'),
  ('Harrogate Town', 'Inglaterra'),
  ('Harrow Borough', 'Inglaterra'),
  ('Hartlepool United', 'Inglaterra'),
  ('Hastings United', 'Inglaterra'),
  ('Havant & Waterlooville', 'Inglaterra'),
  ('Hayes & Yeading United', 'Inglaterra'),
  ('Hereford', 'Inglaterra'),
  ('Histon', 'Inglaterra'),
  ('Hucknall Town', 'Inglaterra'),
  ('Huddersfield Town', 'Inglaterra'),
  ('Hull City', 'Inglaterra'),
  ('Hyde United', 'Inglaterra'),
  ('Ilford', 'Inglaterra'),
  ('Ipswich Town', 'Inglaterra'),
  ('Ipswich Town FC Women', 'Inglaterra'),
  ('Kendal Town', 'Inglaterra'),
  ('Kettering Town', 'Inglaterra'),
  ('Kidderminster Harriers', 'Inglaterra'),
  ('King''s Lynn Town', 'Inglaterra'),
  ('Kingstonian', 'Inglaterra'),
  ('Leeds United', 'Inglaterra'),
  ('Leek Town', 'Inglaterra'),
  ('Leicester City', 'Inglaterra'),
  ('Lewes', 'Inglaterra'),
  ('Leyton Orient', 'Inglaterra'),
  ('Lincoln City', 'Inglaterra'),
  ('Lincoln United', 'Inglaterra'),
  ('Liverpool', 'Inglaterra'),
  ('Loughborough Dynamo', 'Inglaterra'),
  ('Luton Town', 'Inglaterra'),
  ('Maidenhead United', 'Inglaterra'),
  ('Maidstone United', 'Inglaterra'),
  ('Manchester City', 'Inglaterra'),
  ('Manchester United', 'Inglaterra'),
  ('Manchester United FC Reserves and Academy', 'Inglaterra'),
  ('Manchester United WFC', 'Inglaterra'),
  ('Mansfield Town', 'Inglaterra'),
  ('Margate', 'Inglaterra'),
  ('Middlesbrough', 'Inglaterra'),
  ('Millwall', 'Inglaterra'),
  ('Milton Keynes Dons', 'Inglaterra'),
  ('Morecambe', 'Inglaterra'),
  ('Newcastle United', 'Inglaterra'),
  ('Northampton Town', 'Inglaterra'),
  ('Northwich Victoria', 'Inglaterra'),
  ('Norwich City', 'Inglaterra'),
  ('Nottingham Forest', 'Inglaterra'),
  ('Notts County', 'Inglaterra'),
  ('Nuneaton Town', 'Inglaterra'),
  ('Old Carthusians', 'Inglaterra'),
  ('Old Etonians', 'Inglaterra'),
  ('Oldham Athletic', 'Inglaterra'),
  ('Ossett Albion', 'Inglaterra'),
  ('Oswestry Town', 'Inglaterra'),
  ('Oxford United', 'Inglaterra'),
  ('Oxford University', 'Inglaterra'),
  ('Peterborough United', 'Inglaterra'),
  ('Plymouth Argyle', 'Inglaterra'),
  ('Port Vale', 'Inglaterra'),
  ('Portsmouth', 'Inglaterra'),
  ('Prescot Cables', 'Inglaterra'),
  ('Preston North End', 'Inglaterra'),
  ('Queens Park Rangers', 'Inglaterra'),
  ('Radcliffe', 'Inglaterra'),
  ('Reading', 'Inglaterra'),
  ('Redditch United', 'Inglaterra'),
  ('Rochdale', 'Inglaterra'),
  ('Rotherham United', 'Inglaterra'),
  ('Royal Engineers', 'Inglaterra'),
  ('Rugby Town', 'Inglaterra'),
  ('Salford City', 'Inglaterra'),
  ('Salisbury', 'Inglaterra'),
  ('Scarborough Athletic', 'Inglaterra'),
  ('Scunthorpe United', 'Inglaterra'),
  ('Sheffield', 'Inglaterra'),
  ('Sheffield United', 'Inglaterra'),
  ('Sheffield Wednesday', 'Inglaterra'),
  ('Shrewsbury Town', 'Inglaterra'),
  ('Sittingbourne', 'Inglaterra'),
  ('Skelmersdale United', 'Inglaterra'),
  ('Slough Town', 'Inglaterra'),
  ('Solihull Moors', 'Inglaterra'),
  ('Southampton', 'Inglaterra'),
  ('Southend United', 'Inglaterra'),
  ('Southport', 'Inglaterra'),
  ('St Albans City', 'Inglaterra'),
  ('Stafford Rangers', 'Inglaterra'),
  ('Stalybridge Celtic', 'Inglaterra'),
  ('Stevenage', 'Inglaterra'),
  ('Stockport County', 'Inglaterra'),
  ('Stoke City', 'Inglaterra'),
  ('Stourbridge', 'Inglaterra'),
  ('Sunderland', 'Inglaterra'),
  ('Sutton United', 'Inglaterra'),
  ('Swindon Town', 'Inglaterra'),
  ('Tamworth', 'Inglaterra'),
  ('Taunton Town', 'Inglaterra'),
  ('Thamesmead Town', 'Inglaterra'),
  ('The New Saints', 'Inglaterra'),
  ('Tilbury', 'Inglaterra'),
  ('Tonbridge Angels', 'Inglaterra'),
  ('Tooting & Mitcham United', 'Inglaterra'),
  ('Torquay United', 'Inglaterra'),
  ('Tottenham Hotspur', 'Inglaterra'),
  ('Tranmere Rovers', 'Inglaterra'),
  ('Truro City', 'Inglaterra'),
  ('Walsall', 'Inglaterra'),
  ('Walthamstow', 'Inglaterra'),
  ('Walton & Hersham', 'Inglaterra'),
  ('Watford', 'Inglaterra'),
  ('Wealdstone', 'Inglaterra'),
  ('Welling United', 'Inglaterra'),
  ('West Bromwich Albion', 'Inglaterra'),
  ('West Ham United', 'Inglaterra'),
  ('Weymouth', 'Inglaterra'),
  ('Wigan Athletic', 'Inglaterra'),
  ('Woking', 'Inglaterra'),
  ('Wolverhampton Wanderers', 'Inglaterra'),
  ('Worcester City', 'Inglaterra'),
  ('Workington', 'Inglaterra'),
  ('Worthing', 'Inglaterra'),
  ('Wycombe Wanderers', 'Inglaterra'),
  ('York City', 'Inglaterra'),
  ('Aluminium Arak FC', 'Irão'),
  ('Aluminium Hormozgan FC', 'Irão'),
  ('Bargh Shiraz FC', 'Irão'),
  ('Esteghlal Ahvaz FC', 'Irão'),
  ('Esteghlal FC', 'Irão'),
  ('Esteghlal Khuzestan FC', 'Irão'),
  ('Fajr Sepasi FC', 'Irão'),
  ('FC Pars Jonoubi Jam', 'Irão'),
  ('Foolad FC', 'Irão'),
  ('Gahar Zagros FC', 'Irão'),
  ('Gol Gohar FC', 'Irão'),
  ('Gostaresh Foolad FC', 'Irão'),
  ('Havadar SC', 'Irão'),
  ('Machine Sazi FC', 'Irão'),
  ('Malavan FC', 'Irão'),
  ('Mes Rafsanjan FC', 'Irão'),
  ('Naft Masjed Soleyman FC', 'Irão'),
  ('Naft Tehran FC', 'Irão'),
  ('Nassaji Mazandaran FC', 'Irão'),
  ('Pas Hamedan FC', 'Irão'),
  ('Paykan FC', 'Irão'),
  ('Persepolis FC', 'Irão'),
  ('Rah Ahan FC', 'Irão'),
  ('Saba Qom FC', 'Irão'),
  ('Saipa FC', 'Irão'),
  ('Sanat Mes Kerman FC', 'Irão'),
  ('Sanat Naft FC', 'Irão'),
  ('SC Damash', 'Irão'),
  ('Sepahan FC', 'Irão'),
  ('Shahin Bushehr FC', 'Irão'),
  ('Shahr Khodro FC', 'Irão'),
  ('Shahrdari Tabriz FC', 'Irão'),
  ('Shams Azar FC', 'Irão'),
  ('Steel Azin FC', 'Irão'),
  ('Tarbiat Yazd FC', 'Irão'),
  ('Tractor F.C', 'Irão'),
  ('Zob Ahan FC', 'Irão'),
  ('Al Etisalat', 'Iraque'),
  ('Al-Adala', 'Iraque'),
  ('Al-Bahri SC', 'Iraque'),
  ('Al-Diwaniya FC', 'Iraque'),
  ('Al-Forat FC', 'Iraque'),
  ('Al-Hudod SC', 'Iraque'),
  ('Al-Hussein SC', 'Iraque'),
  ('Al-Kahraba', 'Iraque'),
  ('Al-Karkh SC', 'Iraque'),
  ('Al-Mina''a SC', 'Iraque'),
  ('Al-Naft', 'Iraque'),
  ('Al-Quwa Al-Jawiya', 'Iraque'),
  ('Al-Rasheed SC', 'Iraque'),
  ('Al-Shabab SC', 'Iraque'),
  ('Al-Shorta Baghdad', 'Iraque'),
  ('Al-Shuala', 'Iraque'),
  ('Al-Sinaa', 'Iraque'),
  ('Al-Sinaat Al-Kahrabaiya', 'Iraque'),
  ('Al-Zawra''a SC', 'Iraque'),
  ('Baghdad FC', 'Iraque'),
  ('Duhok SC', 'Iraque'),
  ('Erbil SC', 'Iraque'),
  ('Karbalaa FC', 'Iraque'),
  ('Kirkuk FC', 'Iraque'),
  ('Kufa FC', 'Iraque'),
  ('Masafi Al-Wasat', 'Iraque'),
  ('Mosul FC', 'Iraque'),
  ('Naft Al-Janoob', 'Iraque'),
  ('Naft Al-Wasat SC', 'Iraque'),
  ('Naft Maysan', 'Iraque'),
  ('Najaf FC', 'Iraque'),
  ('Nassriya FC', 'Iraque'),
  ('New Sirwan', 'Iraque'),
  ('Peris FC', 'Iraque'),
  ('Samawa FC', 'Iraque'),
  ('Shatra FC', 'Iraque'),
  ('Sulaymaniya FC', 'Iraque'),
  ('Talaba SC', 'Iraque'),
  ('Zakho SC', 'Iraque'),
  ('Albert Rovers', 'Irlanda'),
  ('Athlone Town', 'Irlanda'),
  ('Bohemian', 'Irlanda'),
  ('Bray Wanderers', 'Irlanda'),
  ('Brideville', 'Irlanda'),
  ('Brooklyn', 'Irlanda'),
  ('Cabinteely', 'Irlanda'),
  ('Cobh Ramblers', 'Irlanda'),
  ('Cork', 'Irlanda'),
  ('Cork Bohemians', 'Irlanda'),
  ('Cork Celtic', 'Irlanda'),
  ('Cork City', 'Irlanda'),
  ('Derry City', 'Irlanda'),
  ('Dolphin', 'Irlanda'),
  ('Drogheda United', 'Irlanda'),
  ('Dundalk', 'Irlanda'),
  ('Finn Harps', 'Irlanda'),
  ('Fordsons', 'Irlanda'),
  ('Frankfort', 'Irlanda'),
  ('Galway', 'Irlanda'),
  ('Galway United', 'Irlanda'),
  ('Home Farm', 'Irlanda'),
  ('Jacobs', 'Irlanda'),
  ('Kerry', 'Irlanda'),
  ('Limerick', 'Irlanda'),
  ('Longford Town', 'Irlanda'),
  ('Mervue United', 'Irlanda'),
  ('Midland Athletic', 'Irlanda'),
  ('Monaghan United', 'Irlanda'),
  ('Rathmines Athletic', 'Irlanda'),
  ('Reds United', 'Irlanda'),
  ('Salthill Devon', 'Irlanda'),
  ('Shamrock Rovers', 'Irlanda'),
  ('Shelbourne', 'Irlanda'),
  ('Shelbourne United', 'Irlanda'),
  ('Sligo Rovers', 'Irlanda'),
  ('St Francis', 'Irlanda'),
  ('St Patrick''s Athletic', 'Irlanda'),
  ('Thurles Town', 'Irlanda'),
  ('Transport', 'Irlanda'),
  ('Treaty United', 'Irlanda'),
  ('University College Dublin', 'Irlanda'),
  ('Waterford United', 'Irlanda'),
  ('Wexford Youths', 'Irlanda'),
  ('Ards', 'Irlanda do Norte'),
  ('Ballinamallard United', 'Irlanda do Norte'),
  ('Ballymena United', 'Irlanda do Norte'),
  ('Bangor', 'Irlanda do Norte'),
  ('Carrick Rangers', 'Irlanda do Norte'),
  ('Cliftonville', 'Irlanda do Norte'),
  ('Coleraine', 'Irlanda do Norte'),
  ('Crusaders', 'Irlanda do Norte'),
  ('Donegal Celtic', 'Irlanda do Norte'),
  ('Dungannon Swifts', 'Irlanda do Norte'),
  ('Glenavon', 'Irlanda do Norte'),
  ('Glentoran', 'Irlanda do Norte'),
  ('Institute', 'Irlanda do Norte'),
  ('Larne', 'Irlanda do Norte'),
  ('Limavady United', 'Irlanda do Norte'),
  ('Linfield', 'Irlanda do Norte'),
  ('Lisburn Distillery', 'Irlanda do Norte'),
  ('Loughgall', 'Irlanda do Norte'),
  ('Portadown', 'Irlanda do Norte'),
  ('Warrenpoint Town', 'Irlanda do Norte'),
  ('Breiðablik men''s football', 'Islândia'),
  ('FH men''s football', 'Islândia'),
  ('Fimleikafélag Hafnarfjarðar', 'Islândia'),
  ('Fylkir', 'Islândia'),
  ('Haukar', 'Islândia'),
  ('Íþróttabandalag Akraness', 'Islândia'),
  ('Íþróttabandalag Vestmannaeyja', 'Islândia'),
  ('Keflavík Football Club', 'Islândia'),
  ('Knattspyrnudeild UMFG', 'Islândia'),
  ('Knattspyrnufélag Akureyrar', 'Islândia'),
  ('Knattspyrnufélag Fjallabyggðar', 'Islândia'),
  ('Knattspyrnufélagið Fram', 'Islândia'),
  ('Knattspyrnufélagið Víkingur', 'Islândia'),
  ('KR Reykjavík', 'Islândia'),
  ('Leiknir Reykjavík', 'Islândia'),
  ('Stjarnan', 'Islândia'),
  ('Ungmennafélagið Afturelding', 'Islândia'),
  ('Ungmennafélagið Fjölnir', 'Islândia'),
  ('Ungmennafélagið Víkingur', 'Islândia'),
  ('Valur', 'Islândia'),
  ('Vestri', 'Islândia'),
  ('Beitar Jerusalem FC', 'Israel'),
  ('Beitar Tel Aviv FC', 'Israel'),
  ('Bnei Sakhnin FC', 'Israel'),
  ('Bnei Yehuda Tel Aviv FC', 'Israel'),
  ('FC Ashdod', 'Israel'),
  ('Hakoah Amidar Ramat Gan FC', 'Israel'),
  ('Hapoel Acre FC', 'Israel'),
  ('Hapoel Be''er Sheva FC', 'Israel'),
  ('Hapoel Hadera FC', 'Israel'),
  ('Hapoel Haifa FC', 'Israel'),
  ('Hapoel Jerusalem FC', 'Israel'),
  ('Hapoel Kfar Saba FC', 'Israel'),
  ('Hapoel Nof HaGalil FC', 'Israel'),
  ('Hapoel Petah Tikva FC', 'Israel'),
  ('Hapoel Ra''anana AFC', 'Israel'),
  ('Hapoel Ramat Gan Giv''atayim FC', 'Israel'),
  ('Hapoel Rishon LeZion FC', 'Israel'),
  ('Hapoel Tel Aviv FC', 'Israel'),
  ('Ironi Kiryat Shmona FC', 'Israel'),
  ('Ironi Nir Ramat HaSharon FC', 'Israel'),
  ('Ironi Tiberias FC', 'Israel'),
  ('Maccabi Ahi Nazareth FC', 'Israel'),
  ('Maccabi Bnei Reineh FC', 'Israel'),
  ('Maccabi Haifa FC', 'Israel'),
  ('Maccabi Herzliya FC', 'Israel'),
  ('Maccabi Ironi Ashdod FC', 'Israel'),
  ('Maccabi Netanya FC', 'Israel'),
  ('Maccabi Petah Tikva FC', 'Israel'),
  ('Maccabi Tel Aviv FC', 'Israel'),
  ('2020–21 Ternana Calcio season', 'Itália'),
  ('2020–21 Unione Sportiva Catanzaro season', 'Itália'),
  ('Abano Calcio', 'Itália'),
  ('AC Bastia 1924', 'Itália'),
  ('AC Belluno 1905', 'Itália'),
  ('AC Bra', 'Itália'),
  ('AC Calenzano', 'Itália'),
  ('AC Carpi', 'Itália'),
  ('AC Castellana Calcio', 'Itália'),
  ('AC Castellettese', 'Itália'),
  ('AC ChievoVerona', 'Itália'),
  ('AC Crema 1908', 'Itália'),
  ('AC Cuneo 1905 Olmo', 'Itália'),
  ('AC Este', 'Itália'),
  ('AC Fanfulla 1874', 'Itália'),
  ('AC Fidenza 1922', 'Itália'),
  ('AC Formigine ASD', 'Itália'),
  ('AC Gozzano', 'Itália'),
  ('AC Horatiana Venosa ASD', 'Itália'),
  ('AC Isola Liri', 'Itália'),
  ('AC Juvenes/Dogana', 'Itália'),
  ('AC Legnano', 'Itália'),
  ('AC Lumezzane', 'Itália'),
  ('AC Merate', 'Itália'),
  ('AC Mezzocorona', 'Itália'),
  ('AC Milan', 'Itália'),
  ('AC Monza', 'Itália'),
  ('AC Palazzolo 1913', 'Itália'),
  ('AC Pavia 1911', 'Itália'),
  ('AC Perugia Calcio', 'Itália'),
  ('AC Petacciato', 'Itália'),
  ('AC Ponte San Pietro', 'Itália'),
  ('AC Porto Torres', 'Itália'),
  ('AC Prato', 'Itália'),
  ('AC Reggiana 1919', 'Itália'),
  ('AC Renate', 'Itália'),
  ('AC Sambonifacese', 'Itália'),
  ('ACD Campodarsego', 'Itália'),
  ('ACD Città di Vittoria', 'Itália'),
  ('ACD Pro Dronero', 'Itália'),
  ('ACD Torgiano', 'Itália'),
  ('ACF Brescia Calcio Femminile', 'Itália'),
  ('ACF Fiorentina', 'Itália'),
  ('Acireale Football Club', 'Itália'),
  ('Acqui US 1911', 'Itália'),
  ('ACR Messina', 'Itália'),
  ('ACRD Acicatena', 'Itália'),
  ('ACSD Saluzzo', 'Itália'),
  ('AD Voluntas Calcio Spoleto', 'Itália'),
  ('ADC Ars et Labor Grottaglie', 'Itália'),
  ('Aglianese Calcio 1923', 'Itália'),
  ('Alcione Milano 1952', 'Itália'),
  ('Anzio Calcio 1924', 'Itália'),
  ('APD Leonfortese', 'Itália'),
  ('APD Ribelle 1927', 'Itália'),
  ('APD Tortona Villalvernia', 'Itália'),
  ('Armando Picchi Calcio', 'Itália'),
  ('Ars et Labor Ferrara Calcio', 'Itália'),
  ('AS Bisceglie Calcio 1913', 'Itália'),
  ('AS Deruta', 'Itália'),
  ('AS Fasano', 'Itália'),
  ('AS Fiumicino 1926', 'Itália'),
  ('AS Giana Erminio', 'Itália'),
  ('AS Gubbio 1910', 'Itália'),
  ('AS Ippogrifo Sarno ASD', 'Itália'),
  ('AS Martina Franca 1947', 'Itália'),
  ('AS Morolo Calcio', 'Itália'),
  ('AS Ostiamare 1945', 'Itália'),
  ('AS Pro Gorizia', 'Itália'),
  ('AS Pro Piacenza 1919', 'Itália'),
  ('AS Reggina 1914', 'Itália'),
  ('AS Roma', 'Itália'),
  ('AS Sancolombano Calcio', 'Itália'),
  ('AS Sestese Calcio', 'Itália'),
  ('AS Union Quinto', 'Itália'),
  ('ASC St. Georgen', 'Itália'),
  ('Ascoli Calcio 1898 FC', 'Itália'),
  ('ASD Akragas 2018', 'Itália'),
  ('ASD Albese Calcio', 'Itália'),
  ('ASD Angelo Cristofaro', 'Itália'),
  ('ASD Astrea', 'Itália'),
  ('ASD Athletic Club Palermo', 'Itália'),
  ('ASD Atletico Castenaso Van Goof', 'Itália'),
  ('ASD Atletico Elmas', 'Itália'),
  ('ASD Barletta 1922', 'Itália'),
  ('ASD Battipagliese', 'Itália'),
  ('ASD Biellese 1902', 'Itália'),
  ('ASD Boca Ascesa Val Liona', 'Itália'),
  ('ASD Cagliese Calcio', 'Itália'),
  ('ASD Calcio Chieri 1955', 'Itália'),
  ('ASD Casacastalda', 'Itália'),
  ('ASD Cascina Calcio', 'Itália'),
  ('ASD Casertana Calcio', 'Itália'),
  ('ASD Casoli Calcio', 'Itália'),
  ('ASD Cassino Calcio 1924', 'Itália'),
  ('ASD Castel di Sangro Calcio', 'Itália'),
  ('ASD Cecina', 'Itália'),
  ('ASD Centese 1913', 'Itália'),
  ('ASD Cerea 1912', 'Itália'),
  ('ASD Cervia 1920', 'Itália'),
  ('ASD Civitavecchia 1920', 'Itália'),
  ('ASD Club Calcio San Gregorio', 'Itália'),
  ('ASD Comunale Fontanafredda', 'Itália'),
  ('ASD CTL Campania Piscinola', 'Itália'),
  ('ASD Cynthia 1920', 'Itália'),
  ('ASD Elpidiense Cascinare', 'Itália'),
  ('ASD Fersina Perginese', 'Itália'),
  ('ASD Flaminia Civita Castellana', 'Itália'),
  ('ASD Fortis Juventus 1909', 'Itália'),
  ('ASD Francavilla', 'Itália'),
  ('ASD Gallipoli Calcio', 'Itália'),
  ('ASD Gelbison Cilento Vallo della Lucania', 'Itália'),
  ('ASD Giallo-Blu Figline', 'Itália'),
  ('ASD Gioiese 1918', 'Itália'),
  ('ASD Giorgione Calcio 2000', 'Itália'),
  ('ASD Igea Virtus Barcellona', 'Itália'),
  ('ASD Jolly Montemurlo', 'Itália'),
  ('ASD Lanciotto Campi Bisenzio', 'Itália'),
  ('ASD Manfredonia Calcio 1932', 'Itália'),
  ('ASD MapelloBonate Calcio', 'Itália'),
  ('ASD Mestrina 1929', 'Itália'),
  ('ASD Mezzolara', 'Itália'),
  ('ASD Miglianico Calcio', 'Itália'),
  ('ASD Modica Calcio', 'Itália'),
  ('ASD Mori Santo Stefano', 'Itália'),
  ('ASD Narnese Calcio', 'Itália'),
  ('ASD Nerostellati Frattese', 'Itália'),
  ('ASD Nocerina 1910', 'Itália'),
  ('ASD Nuova Santa Maria delle Mole Marino', 'Itália'),
  ('ASD Olimpia Colligiana', 'Itália'),
  ('ASD Penne Calcio', 'Itália'),
  ('ASD Pierantonio Calcio 1965', 'Itália'),
  ('ASD Polisportiva Tamai', 'Itália'),
  ('ASD Pontevecchio', 'Itália'),
  ('ASD Ponziana', 'Itália'),
  ('ASD Porfido Albiano', 'Itália'),
  ('ASD Pro Settimo & Eureka', 'Itália'),
  ('ASD Quarto', 'Itália'),
  ('ASD Ragusa Calcio', 'Itália'),
  ('ASD Real Metapontino', 'Itália'),
  ('ASD Real SM Hyria Nola 2012', 'Itália'),
  ('ASD Riccione 1929', 'Itália'),
  ('ASD Rivignano', 'Itália'),
  ('ASD Roccella', 'Itália'),
  ('ASD Sacilese Calcio', 'Itália'),
  ('ASD Sambiase 1962', 'Itália'),
  ('ASD San Cesareo Calcio', 'Itália'),
  ('ASD Sant''Angelo', 'Itália'),
  ('ASD Santhià Calcio', 'Itália'),
  ('ASD Sanvitese', 'Itália'),
  ('ASD Sarnese 1926', 'Itália'),
  ('ASD Sarone', 'Itália'),
  ('ASD Selargius Calcio', 'Itália'),
  ('ASD SF Gladiator', 'Itália'),
  ('ASD Sicula Leonzio', 'Itália'),
  ('ASD Soccer Trani', 'Itália'),
  ('ASD Sporting Club Trestina', 'Itália'),
  ('ASD Sulmona Calcio', 'Itália'),
  ('ASD Termoli Calcio 1920', 'Itália'),
  ('ASD Tiger Brolo', 'Itália'),
  ('ASD Todi', 'Itália'),
  ('ASD Torrecuso Calcio', 'Itália'),
  ('ASD Trezzano Calcio', 'Itália'),
  ('ASD Union ArzignanoChiampo', 'Itália'),
  ('ASD US Scafatese Calcio', 'Itália'),
  ('ASD Verucchio', 'Itália'),
  ('ASD Villabiagio', 'Itália'),
  ('ASD Virtus Pavullese', 'Itália'),
  ('ASD Vittorio Falmec San Martino Colle', 'Itália'),
  ('ASDC Ba.Se. 96 Seveso', 'Itália'),
  ('ASDC Borgomanero', 'Itália'),
  ('ASDC Canelli', 'Itália'),
  ('ASDC Magenta', 'Itália'),
  ('ASDC Pomigliano', 'Itália'),
  ('ASDC Verbania', 'Itália'),
  ('ASDP Ciliverghe di Mazzano', 'Itália'),
  ('Associazione Calcio Codogno 1908', 'Itália'),
  ('Associazione Calcio La Dominante', 'Itália'),
  ('Associazione Sportiva Casatese', 'Itália'),
  ('Associazione Sportiva Cittadella', 'Itália'),
  ('Associazione Sportiva Dilettantistica Baia Alassio Calcio', 'Itália'),
  ('Atalanta BC', 'Itália'),
  ('Atalanta Bergamasca Calcio U23', 'Itália'),
  ('Aurora Pro Patria 1919', 'Itália'),
  ('AZ Picerno', 'Itália'),
  ('Benevento Calcio', 'Itália'),
  ('Bologna FC 1909', 'Itália'),
  ('Borgosesia Calcio', 'Itália'),
  ('Brera Calcio', 'Itália'),
  ('Brescia Calcio', 'Itália'),
  ('Budoni Calcio', 'Itália'),
  ('Cagliari Calcio', 'Itália'),
  ('Calcio Foggia 1920', 'Itália'),
  ('Calcio Lecco 1912', 'Itália'),
  ('Calcio Montebelluna 1919', 'Itália'),
  ('Calcio Portogruaro Summaga', 'Itália'),
  ('Camaiore Calcio ASD', 'Itália'),
  ('Campobasso FC', 'Itália'),
  ('Carrarese Calcio', 'Itália'),
  ('Casale FBC', 'Itália'),
  ('Catania FC', 'Itália'),
  ('Cattolica Calcio 1923', 'Itália'),
  ('Cavese 1919', 'Itália'),
  ('Celano FC Marsica', 'Itália'),
  ('Cesena FC', 'Itália'),
  ('Civitanovese Calcio', 'Itália'),
  ('Cjarlins Muzane', 'Itália'),
  ('Clodiense SSD', 'Itália'),
  ('Colleferro Calcio 1937', 'Itália'),
  ('Como 1907', 'Itália'),
  ('Comprensorio Normanno', 'Itália'),
  ('Cosenza Calcio', 'Itália'),
  ('Delfino Pescara 1936', 'Itália'),
  ('Empoli FC', 'Itália'),
  ('Faenza Calcio', 'Itália'),
  ('FB Brindisi 1912', 'Itália'),
  ('FC AlzanoCene 1909', 'Itália'),
  ('FC Aprilia Racing Club', 'Itália'),
  ('FC Bolzano 1996', 'Itália'),
  ('FC Calcio Acri', 'Itália'),
  ('FC Crotone', 'Itália'),
  ('FC Francavilla', 'Itália'),
  ('FC Legnago Salus SSD', 'Itália'),
  ('FC Matera', 'Itália'),
  ('FC Ponsacco 1920 SSD', 'Itália'),
  ('FC Rieti 1936', 'Itália'),
  ('FC Rossanese 1909 ASD', 'Itália'),
  ('FC Sant''Antonio Abate', 'Itália'),
  ('FC Sporting Genzano', 'Itália'),
  ('FC Südtirol', 'Itália'),
  ('FC Torinese', 'Itália'),
  ('FC Trapani 1905', 'Itália'),
  ('FC Union Pro Mogliano-Preganziol ASD', 'Itália'),
  ('FC Vado', 'Itália'),
  ('FC Verbano Calcio', 'Itália'),
  ('FC Vittoria', 'Itália'),
  ('FCD Altovicentino', 'Itália'),
  ('FCD Conegliano Calcio 1907', 'Itália'),
  ('FCD Lottogiaveno', 'Itália'),
  ('FCD Pro Vasto', 'Itália'),
  ('Feralpisalò', 'Itália'),
  ('Fidelis Andria 2018', 'Itália'),
  ('Foligno Calcio', 'Itália'),
  ('Football Club Lumezzane', 'Itália'),
  ('Forza e Coraggio Avezzano', 'Itália'),
  ('Frosinone Calcio', 'Itália'),
  ('FS Sestrese Calcio 1919', 'Itália'),
  ('Genoa CFC', 'Itália'),
  ('Ghiviborgo VDS', 'Itália'),
  ('Giarre FC', 'Itália'),
  ('GS Bagnolese', 'Itália'),
  ('GSD Castelfidardo Calcio', 'Itália'),
  ('GSD RapalloBogliasco', 'Itália'),
  ('GSD Rosignano Sei Rose', 'Itália'),
  ('Guidonia Montecelio 1937 FC', 'Itália'),
  ('Hellas Verona FC', 'Itália'),
  ('Imolese Calcio 1919', 'Itália'),
  ('Inter Milan', 'Itália'),
  ('Inter Milan Under-23', 'Itália'),
  ('Inter Women', 'Itália'),
  ('Internapoli FC', 'Itália'),
  ('Isernia FC', 'Itália'),
  ('Juventus FC', 'Itália'),
  ('Juventus FC Next Gen', 'Itália'),
  ('Lanciano Calcio 1920', 'Itália'),
  ('L''Aquila Calcio 1927', 'Itália'),
  ('Latina Calcio 1932', 'Itália'),
  ('Lentigione Calcio', 'Itália'),
  ('LR Vicenza', 'Itália'),
  ('Lucchese 1905', 'Itália'),
  ('Mantova 1911', 'Itália'),
  ('Marsala Football Club', 'Itália'),
  ('Milan Futuro', 'Itália'),
  ('Modena FC', 'Itália'),
  ('Molinella Calcio 1911', 'Itália'),
  ('Morro d''Oro Calcio', 'Itália'),
  ('NFC Orlandina ASD', 'Itália'),
  ('NK Kras ASD', 'Itália'),
  ('Novara Calcio', 'Itália'),
  ('Nuorese Calcio', 'Itália'),
  ('Paganese Calcio 1926', 'Itália'),
  ('Palermo FC', 'Itália'),
  ('Parma Calcio 1913', 'Itália'),
  ('Pinerolo Football Club', 'Itália'),
  ('Piovese Calcio 1919', 'Itália'),
  ('Pisa SC', 'Itália'),
  ('Pistoiese FC', 'Itália'),
  ('Pol. Arzachena', 'Itália'),
  ('Pol. Bisaccese', 'Itália'),
  ('Pol. Maccarese Giada', 'Itália'),
  ('Pol. Olympia Agnonese', 'Itália'),
  ('Pol. Virtus Castelfranco Calcio', 'Itália'),
  ('Pordenone FC', 'Itália'),
  ('Potenza Calcio', 'Itália'),
  ('Pro Sesto 1913', 'Itália'),
  ('Progetto Calcio Sant''Elia', 'Itália'),
  ('Real Giulianova', 'Itália'),
  ('Real Marcianise Calcio', 'Itália'),
  ('Renato Curi Angolana', 'Itália'),
  ('Rende Calcio 1968', 'Itália'),
  ('Rimini FC', 'Itália'),
  ('Roma City FC', 'Itália'),
  ('San Donato Tavarnelle', 'Itália'),
  ('Sangimignanosport', 'Itália'),
  ('Savoia 1908 FC', 'Itália'),
  ('Savona FBC', 'Itália'),
  ('SC Caronnese', 'Itália'),
  ('SC Ravenna Sport', 'Itália'),
  ('Scandicci Calcio', 'Itália'),
  ('SEF Torres 1903', 'Itália'),
  ('SF Aversa Normanna', 'Itália'),
  ('SG Gallaratese ASD', 'Itália'),
  ('Siena FC', 'Itália'),
  ('Siracusa Calcio 1924', 'Itália'),
  ('Società Calcistica Gela', 'Itália'),
  ('Società Ginnastica di Torino', 'Itália'),
  ('Sondrio Calcio', 'Itália'),
  ('Sorrento Calcio 1945', 'Itália'),
  ('SP Grottammare 1899', 'Itália'),
  ('SP Reno Centese ASD', 'Itália'),
  ('SPD Amiternina', 'Itália'),
  ('Spezia Calcio', 'Itália'),
  ('Sport Club Ligorna 1922', 'Itália'),
  ('SS Arezzo', 'Itália'),
  ('SS Chieti Calcio', 'Itália'),
  ('SS Comprensorio Montalto Uffugo Calcio', 'Itália'),
  ('SS Juve Stabia', 'Itália'),
  ('SS Lazio', 'Itália'),
  ('SS Maceratese 1922', 'Itália'),
  ('SS Matelica Calcio', 'Itália'),
  ('SS Monopoli 1966', 'Itália'),
  ('SS Romulea', 'Itália'),
  ('SS Sambenedettese Calcio', 'Itália'),
  ('SS San Giovanni', 'Itália'),
  ('SS Teramo Calcio', 'Itália'),
  ('SS Turris Calcio', 'Itália'),
  ('SSC Ancona', 'Itália'),
  ('SSC Bari', 'Itália'),
  ('SSC Giugliano', 'Itália'),
  ('SSC Gragnano', 'Itália'),
  ('SSC Napoli', 'Itália'),
  ('SSD Casarano Calcio', 'Itália'),
  ('SSD Centobuchi', 'Itália'),
  ('SSD Città di Messina', 'Itália'),
  ('SSD Correggese Calcio 1948', 'Itália'),
  ('SSD Domegliara', 'Itália'),
  ('SSD Ischia Isolaverde', 'Itália'),
  ('SSD Jesina Calcio', 'Itália'),
  ('SSD Licata 1931', 'Itália'),
  ('SSD Massese', 'Itália'),
  ('SSD Puteolana 1902 Internapoli', 'Itália'),
  ('SSD San Nicolò Calcio', 'Itália'),
  ('SSD Sansepolcro Calcio', 'Itália'),
  ('Sulmona Calcio 1921', 'Itália'),
  ('Suzzara Calcio 2000', 'Itália'),
  ('Taranto Sport', 'Itália'),
  ('Tau', 'Itália'),
  ('Ternana Calcio', 'Itália'),
  ('Terracina Calcio 1925', 'Itália'),
  ('Torino FC', 'Itália'),
  ('Trastevere Calcio', 'Itália'),
  ('Trento Calcio 1921', 'Itália'),
  ('Treviso FBC 1993', 'Itália'),
  ('UC AlbinoLeffe', 'Itália'),
  ('UC Sampdoria', 'Itália'),
  ('Udinese Calcio', 'Itália'),
  ('UFM Monfalcone', 'Itália'),
  ('Unione Sportiva Brescello', 'Itália'),
  ('Unione Sportiva Catanzaro', 'Itália'),
  ('US Adriese', 'Itália'),
  ('US Agropoli 1921', 'Itália'),
  ('US Alessandria Calcio 1912', 'Itália'),
  ('US Alta Vallagarina', 'Itália'),
  ('US Angri Calcio 1927 ASD', 'Itália'),
  ('US Avellino 1912', 'Itália'),
  ('US Bitonto', 'Itália'),
  ('US Castelnuovo Garfagnana', 'Itália'),
  ('US Castrovillari Calcio', 'Itália'),
  ('US Ciserano', 'Itália'),
  ('US Città di Pontedera SSD', 'Itália'),
  ('US Comacchio Lidi', 'Itália'),
  ('US Cremonese', 'Itália'),
  ('US Darfo Boario SSD', 'Itália'),
  ('US Dro', 'Itália'),
  ('US Fermana', 'Itália'),
  ('US Fiorenzuola 1922', 'Itália'),
  ('US Folgore Caratese ASD', 'Itália'),
  ('US Forcoli Calcio 1921 ASD', 'Itália'),
  ('US Grosseto 1912', 'Itália'),
  ('US Lecce', 'Itália'),
  ('US Livorno 1915', 'Itália'),
  ('US Olbia 1905', 'Itália'),
  ('US Opitergina', 'Itália'),
  ('US Palestrina 1919', 'Itália'),
  ('US Palmese 1912', 'Itália'),
  ('US Pergolese', 'Itália'),
  ('US Pergolettese 1932', 'Itália'),
  ('US Pianese', 'Itália'),
  ('US Poseidon 1958', 'Itália'),
  ('US Salernitana 1919', 'Itália'),
  ('US Sassuolo Calcio', 'Itália'),
  ('US Sestri Levante', 'Itália'),
  ('US Tolentino', 'Itália'),
  ('US Triestina Calcio 1918', 'Itália'),
  ('US Vibonese Calcio', 'Itália'),
  ('US Vigor Senigallia', 'Itália'),
  ('USD 1913 Seregno Calcio', 'Itália'),
  ('USD Atletico Catania', 'Itália'),
  ('USD Calcio Delta Porto Tolle', 'Itália'),
  ('USD Calcio Rudianese', 'Itália'),
  ('USD Caravaggio', 'Itália'),
  ('USD Castelsardo', 'Itália'),
  ('USD Cirié Calcio', 'Itália'),
  ('USD FiesoleCaldine', 'Itália'),
  ('USD Forte dei Marmi', 'Itália'),
  ('USD Latte Dolce', 'Itália'),
  ('USD Noto Calcio', 'Itália'),
  ('USD Novese', 'Itália'),
  ('USD Olginatese', 'Itália'),
  ('USD Palmese', 'Itália'),
  ('USD Recanatese 1923', 'Itália'),
  ('USD San Severo', 'Itália'),
  ('USD Sebinia Alto Sebino', 'Itália'),
  ('Valdinievole Montecatini', 'Itália'),
  ('Venezia FC', 'Itália'),
  ('Viareggio Calcio', 'Itália'),
  ('Vico Equense Calcio 1958', 'Itália'),
  ('Vigontina San Paolo FC', 'Itália'),
  ('Virtus Entella', 'Itália'),
  ('Virtus Francavilla', 'Itália'),
  ('Virtus Verona', 'Itália'),
  ('Vis Pesaro dal 1898', 'Itália'),
  ('Arnett Gardens FC', 'Jamaica'),
  ('August Town FC', 'Jamaica'),
  ('Benfica FC', 'Jamaica'),
  ('Boys'' Town FC', 'Jamaica'),
  ('Cavalier FC', 'Jamaica'),
  ('Harbour View FC', 'Jamaica'),
  ('Highgate United FC', 'Jamaica'),
  ('Humble Lions FC', 'Jamaica'),
  ('Montego Bay United FC', 'Jamaica'),
  ('Portmore United FC', 'Jamaica'),
  ('Reno FC', 'Jamaica'),
  ('Sandals South Coast FC', 'Jamaica'),
  ('Sporting Central Academy', 'Jamaica'),
  ('St. George''s SC', 'Jamaica'),
  ('Tivoli Gardens FC', 'Jamaica'),
  ('UWI FC', 'Jamaica'),
  ('Village United FC', 'Jamaica'),
  ('Waterhouse FC', 'Jamaica'),
  ('AC Nagano Parceiro', 'Japão'),
  ('Albirex Niigata', 'Japão'),
  ('Avispa Fukuoka', 'Japão'),
  ('Azul Claro Numazu', 'Japão'),
  ('Blaublitz Akita', 'Japão'),
  ('Cerezo Osaka', 'Japão'),
  ('Ehime FC', 'Japão'),
  ('Fagiano Okayama', 'Japão'),
  ('FC Gifu', 'Japão'),
  ('FC Imabari', 'Japão'),
  ('FC Machida Zelvia', 'Japão'),
  ('FC Osaka', 'Japão'),
  ('FC Ryukyu Okinawa', 'Japão'),
  ('FC Tokyo', 'Japão'),
  ('Fujieda MYFC', 'Japão'),
  ('Fukushima United FC', 'Japão'),
  ('Gainare Tottori', 'Japão'),
  ('Gamba Osaka', 'Japão'),
  ('Giravanz Kitakyushu', 'Japão'),
  ('Hokkaido Consadole Sapporo', 'Japão'),
  ('Honda FC', 'Japão'),
  ('Iwaki FC', 'Japão'),
  ('Iwate Grulla Morioka', 'Japão'),
  ('JEF United Chiba', 'Japão'),
  ('Júbilo Iwata', 'Japão'),
  ('Kagoshima United FC', 'Japão'),
  ('Kamatamare Sanuki', 'Japão'),
  ('Kashima Antlers', 'Japão'),
  ('Kashiwa Reysol', 'Japão'),
  ('Kataller Toyama', 'Japão'),
  ('Kawasaki Frontale', 'Japão'),
  ('Kyoto Sanga FC', 'Japão'),
  ('Matsumoto Yamaga FC', 'Japão'),
  ('Mito HollyHock', 'Japão'),
  ('Montedio Yamagata', 'Japão'),
  ('Nagoya Grampus', 'Japão'),
  ('Nara Club', 'Japão'),
  ('Oita Trinita', 'Japão'),
  ('RB Omiya Ardija', 'Japão'),
  ('Reilac Shiga FC', 'Japão'),
  ('Renofa Yamaguchi FC', 'Japão'),
  ('Roasso Kumamoto', 'Japão'),
  ('Sagan Tosu', 'Japão'),
  ('Sanfrecce Hiroshima', 'Japão'),
  ('SC Sagamihara', 'Japão'),
  ('Shimizu S-Pulse', 'Japão'),
  ('Shonan Bellmare', 'Japão'),
  ('Tegevajaro Miyazaki', 'Japão'),
  ('Thespa Gunma', 'Japão'),
  ('Tochigi City FC', 'Japão'),
  ('Tochigi SC', 'Japão'),
  ('Tokushima Vortis', 'Japão'),
  ('Tokyo Verdy', 'Japão'),
  ('Urawa Red Diamonds', 'Japão'),
  ('Vanraure Hachinohe', 'Japão'),
  ('Vegalta Sendai', 'Japão'),
  ('Ventforet Kofu', 'Japão'),
  ('Vissel Kobe', 'Japão'),
  ('V-Varen Nagasaki', 'Japão'),
  ('Yokohama F. Marinos', 'Japão'),
  ('Yokohama FC', 'Japão'),
  ('YSCC Yokohama', 'Japão'),
  ('Zweigen Kanazawa', 'Japão'),
  ('Arta/Solar7', 'Jibuti'),
  ('AS Ali Sabieh Djibouti Télécom', 'Jibuti'),
  ('Al-Ahli', 'Jordânia'),
  ('Al-Aqaba SC', 'Jordânia'),
  ('Al-Arabi', 'Jordânia'),
  ('Al-Baqa''a SC', 'Jordânia'),
  ('Al-Faisaly SC', 'Jordânia'),
  ('Al-Hussein SC', 'Jordânia'),
  ('Al-Jalil', 'Jordânia'),
  ('Al-Jazeera', 'Jordânia'),
  ('Al-Ramtha SC', 'Jordânia'),
  ('Al-Salt SC', 'Jordânia'),
  ('Al-Sareeh SC', 'Jordânia'),
  ('Al-Sheikh Hussein FC', 'Jordânia'),
  ('Al-Wehdat SC', 'Jordânia'),
  ('Al-Yarmouk FC', 'Jordânia'),
  ('Etehad Al Zarqah', 'Jordânia'),
  ('Ittihad Al-Ramtha', 'Jordânia'),
  ('Kufrsoum SC', 'Jordânia'),
  ('Ma''an SC', 'Jordânia'),
  ('Manshia Bani Hassan', 'Jordânia'),
  ('Sahab SC', 'Jordânia'),
  ('Shabab Al-Hussein SC', 'Jordânia'),
  ('Shabab Al-Ordon Club', 'Jordânia'),
  ('That Ras Club', 'Jordânia'),
  ('FC Ferizaj', 'Kosovo'),
  ('FC Prishtina', 'Kosovo'),
  ('KF 2 Korriku', 'Kosovo'),
  ('KF Ballkani', 'Kosovo'),
  ('KF Besa', 'Kosovo'),
  ('KF Drenica', 'Kosovo'),
  ('KF Drita', 'Kosovo'),
  ('KF Dukagjini', 'Kosovo'),
  ('KF Feronikeli', 'Kosovo'),
  ('KF Flamurtari', 'Kosovo'),
  ('KF Gjilani', 'Kosovo'),
  ('KF Hajvalia', 'Kosovo'),
  ('KF Hysi', 'Kosovo'),
  ('KF Istogu', 'Kosovo'),
  ('KF KEK', 'Kosovo'),
  ('KF Liria', 'Kosovo'),
  ('KF Llapi', 'Kosovo'),
  ('KF Malisheva', 'Kosovo'),
  ('KF Prishtina e Re', 'Kosovo'),
  ('KF Trepça', 'Kosovo'),
  ('KF Trepça ''89', 'Kosovo'),
  ('KF Ulpiana', 'Kosovo'),
  ('KF Vëllaznimi', 'Kosovo'),
  ('KF Vllaznia Pozheran', 'Kosovo'),
  ('KF Vushtrria', 'Kosovo'),
  ('Al Jahra SC', 'Kuwait'),
  ('Al Nasr Sporting Club', 'Kuwait'),
  ('Al Salibikhaet SC', 'Kuwait'),
  ('Al Yarmouk Kuwait', 'Kuwait'),
  ('Al-Arabi SC', 'Kuwait'),
  ('Al-Fahaheel FC', 'Kuwait'),
  ('Al-Qurain SC', 'Kuwait'),
  ('Al-Salmiya SC', 'Kuwait'),
  ('Al-Shabab SC', 'Kuwait'),
  ('Al-Tadamon SC', 'Kuwait'),
  ('Burgan SC', 'Kuwait'),
  ('Kazma Sporting Club', 'Kuwait'),
  ('Khaitan Sporting Club', 'Kuwait'),
  ('Kuwait SC', 'Kuwait'),
  ('Sahel SC', 'Kuwait'),
  ('Champasak United FC', 'Laos'),
  ('CSC Champa FC', 'Laos'),
  ('Eastern Star FC', 'Laos'),
  ('Electricite du Laos FC', 'Laos'),
  ('Ezra FC', 'Laos'),
  ('Hoang Anh Attapeu FC', 'Laos'),
  ('Lao Army FC', 'Laos'),
  ('Lao Lane Xang FC', 'Laos'),
  ('Lao Police Club', 'Laos'),
  ('Lao Toyota FC', 'Laos'),
  ('National University of Laos FC', 'Laos'),
  ('SHB Champasak FC', 'Laos'),
  ('Young Elephants FC', 'Laos'),
  ('Matlama FC', 'Lesoto'),
  ('BFC Daugavpils', 'Letónia'),
  ('FB Gulbene', 'Letónia'),
  ('FC Daugava', 'Letónia'),
  ('FC Jūrmala', 'Letónia'),
  ('FC RFS', 'Letónia'),
  ('FK Auda', 'Letónia'),
  ('FK Grobiņa', 'Letónia'),
  ('FK Jelgava', 'Letónia'),
  ('FK Liepāja', 'Letónia'),
  ('FK Metta', 'Letónia'),
  ('FK Spartaks Jūrmala', 'Letónia'),
  ('FS Jelgava', 'Letónia'),
  ('Ogre United', 'Letónia'),
  ('Riga FC', 'Letónia'),
  ('SK Blāzma', 'Letónia'),
  ('SK Super Nova', 'Letónia'),
  ('Tukums 2000', 'Letónia'),
  ('Valmiera FC', 'Letónia'),
  ('AC Tripoli', 'Líbano'),
  ('Akhaa Ahli Aley FC', 'Líbano'),
  ('Al Ahed FC', 'Líbano'),
  ('Al Ansar FC', 'Líbano'),
  ('Al Mabarra FC', 'Líbano'),
  ('Al Rayyan SC Sarafand', 'Líbano'),
  ('AS DPHB', 'Líbano'),
  ('AS Hilmi-Sport', 'Líbano'),
  ('Homenetmen Beirut', 'Líbano'),
  ('Jwaya SC', 'Líbano'),
  ('Nejmeh SC', 'Líbano'),
  ('Racing Club Beirut', 'Líbano'),
  ('Safa SC', 'Líbano'),
  ('Shabab Al Sahel FC', 'Líbano'),
  ('Shabab Baalbek Sport Club', 'Líbano'),
  ('Tadamon Sour SC', 'Líbano'),
  ('Invincible Eleven', 'Libéria'),
  ('Al AHLI TRIPOLI SC', 'Líbia'),
  ('Al Ahly SC (Benghazi)', 'Líbia'),
  ('Al-Hilal SC', 'Líbia'),
  ('Al-ittihad', 'Líbia'),
  ('Al-Madina SC', 'Líbia'),
  ('Al-Nasser SC', 'Líbia'),
  ('Attahaddy Benghazi SC', 'Líbia'),
  ('Olympic Azzaweya SC', 'Líbia'),
  ('the White SC', 'Líbia'),
  ('FC Balzers', 'Listenstaine'),
  ('FC Ruggell', 'Listenstaine'),
  ('FC Schaan', 'Listenstaine'),
  ('FC Triesen', 'Listenstaine'),
  ('FC Triesenberg', 'Listenstaine'),
  ('FC Vaduz', 'Listenstaine'),
  ('USV Eschen/Mauren', 'Listenstaine'),
  ('DFK Dainava', 'Lituânia'),
  ('FA Šiauliai', 'Lituânia'),
  ('FC Džiugas', 'Lituânia'),
  ('FC Hegelmann', 'Lituânia'),
  ('FC Neptūnas', 'Lituânia'),
  ('FC Pakruojis', 'Lituânia'),
  ('FC Vilniaus Vytis', 'Lituânia'),
  ('FK Atlantas', 'Lituânia'),
  ('FK Atmosfera', 'Lituânia'),
  ('FK Babrungas', 'Lituânia'),
  ('FK Banga Gargždai', 'Lituânia'),
  ('FK Dainava Alytus', 'Lituânia'),
  ('FK Garliava', 'Lituânia'),
  ('FK Jonava', 'Lituânia'),
  ('FK Kauno Žalgiris', 'Lituânia'),
  ('FK Koralas', 'Lituânia'),
  ('FK Kražantė', 'Lituânia'),
  ('FK Lokomotyvas Radviliškis', 'Lituânia'),
  ('FK Minija', 'Lituânia'),
  ('FK Minija (2017)', 'Lituânia'),
  ('FK Mykolo Riomerio universitetas', 'Lituânia'),
  ('FK Nacionalinė futbolo akademija', 'Lituânia'),
  ('FK Nevėžis', 'Lituânia'),
  ('FK Palanga', 'Lituânia'),
  ('FK Panevėžys', 'Lituânia'),
  ('FK Riteriai', 'Lituânia'),
  ('FK Šilas', 'Lituânia'),
  ('FK Šilutė', 'Lituânia'),
  ('FK Širvėna Biržai', 'Lituânia'),
  ('FK Sūduva', 'Lituânia'),
  ('FK Tauras Kaunas', 'Lituânia'),
  ('FK Tauras Tauragė', 'Lituânia'),
  ('FK Transinvest', 'Lituânia'),
  ('FK Utenis', 'Lituânia'),
  ('FK Vėtra', 'Lituânia'),
  ('FK Vilnius', 'Lituânia'),
  ('FK Žalgiris', 'Lituânia'),
  ('FK Žalgiris B', 'Lituânia'),
  ('ROMAR Mažeikiai', 'Lituânia'),
  ('CS Fola Esch', 'Luxemburgo'),
  ('CS Grevenmacher', 'Luxemburgo'),
  ('CS Muhlenbach Lusitanos', 'Luxemburgo'),
  ('F91 Dudelange', 'Luxemburgo'),
  ('FC Atert Bissen', 'Luxemburgo'),
  ('FC Avenir Beggen', 'Luxemburgo'),
  ('FC Differdange 03', 'Luxemburgo'),
  ('FC Etzella Ettelbruck', 'Luxemburgo'),
  ('FC Jeunesse Canach', 'Luxemburgo'),
  ('FC Luxembourg City', 'Luxemburgo'),
  ('FC Mamer 32', 'Luxemburgo'),
  ('FC Mondercange', 'Luxemburgo'),
  ('FC Progrès Niederkorn', 'Luxemburgo'),
  ('FC Rodange 91', 'Luxemburgo'),
  ('FC Swift Hesperange', 'Luxemburgo'),
  ('FC UNA Strassen', 'Luxemburgo'),
  ('FC Wiltz 71', 'Luxemburgo'),
  ('Football Club Victoria Rosport', 'Luxemburgo'),
  ('Jeunesse Esch', 'Luxemburgo'),
  ('Racing Club Luxembourg', 'Luxemburgo'),
  ('Racing FC Union Luxembourg', 'Luxemburgo'),
  ('Sporting Club Luxembourg', 'Luxemburgo'),
  ('UN Käerjeng ''97', 'Luxemburgo'),
  ('Union 05 Kayl-Tétange', 'Luxemburgo'),
  ('Union Titus Pétange', 'Luxemburgo'),
  ('US Hollerich Bonnevoie', 'Luxemburgo'),
  ('US Hostert', 'Luxemburgo'),
  ('US Mondorf-les-Bains', 'Luxemburgo'),
  ('US Rumelange', 'Luxemburgo'),
  ('SL Benfica de Macau', 'Macau'),
  ('Akademija Pandev', 'Macedónia do Norte'),
  ('FC Struga', 'Macedónia do Norte'),
  ('FK 11 Oktomvri', 'Macedónia do Norte'),
  ('FK Arsimi', 'Macedónia do Norte'),
  ('FK Bashkimi', 'Macedónia do Norte'),
  ('FK Belasica', 'Macedónia do Norte'),
  ('FK Borec', 'Macedónia do Norte'),
  ('FK Bregalnica 2008', 'Macedónia do Norte'),
  ('FK Cementarnica 55', 'Macedónia do Norte'),
  ('FK Drita', 'Macedónia do Norte'),
  ('FK Gostivar', 'Macedónia do Norte'),
  ('FK Karaorman', 'Macedónia do Norte'),
  ('FK Ljuboten', 'Macedónia do Norte'),
  ('FK Makedonija Gjorče Petrov', 'Macedónia do Norte'),
  ('FK Metalurg Skopje', 'Macedónia do Norte'),
  ('FK Milano Kumanovo', 'Macedónia do Norte'),
  ('FK Mladost Carev Dvor', 'Macedónia do Norte'),
  ('FK Napredok', 'Macedónia do Norte'),
  ('FK Ohrid', 'Macedónia do Norte'),
  ('FK Pelister', 'Macedónia do Norte'),
  ('FK Pobeda Junior', 'Macedónia do Norte'),
  ('FK Rabotnički', 'Macedónia do Norte'),
  ('FK Renova', 'Macedónia do Norte'),
  ('FK Shkëndija', 'Macedónia do Norte'),
  ('FK Shkupi', 'Macedónia do Norte'),
  ('FK Sileks', 'Macedónia do Norte'),
  ('FK Skopje', 'Macedónia do Norte'),
  ('FK Teteks', 'Macedónia do Norte'),
  ('FK Turnovo', 'Macedónia do Norte'),
  ('FK Vardar', 'Macedónia do Norte'),
  ('FK Voska Sport', 'Macedónia do Norte'),
  ('GFK Tikveš', 'Macedónia do Norte'),
  ('KF Besa Dobërdoll', 'Macedónia do Norte'),
  ('CNaPS Sport', 'Madagáscar'),
  ('SO l''Emyrne', 'Madagáscar'),
  ('Armed Forces FC', 'Malásia'),
  ('FELDA United FC', 'Malásia'),
  ('Johor Darul Ta''zim FC', 'Malásia'),
  ('Kedah Darul Aman FC', 'Malásia'),
  ('Kelantan FC', 'Malásia'),
  ('Kuala Lumpur City FC', 'Malásia'),
  ('Kuala Muda Naza FC', 'Malásia'),
  ('Kuching City FC', 'Malásia'),
  ('Melaka TMFC', 'Malásia'),
  ('Melaka United', 'Malásia'),
  ('Negeri Sembilan FA', 'Malásia'),
  ('Penang FC', 'Malásia'),
  ('Perak FC', 'Malásia'),
  ('Perlis FA', 'Malásia'),
  ('PLUS FC', 'Malásia'),
  ('Sabah FC', 'Malásia'),
  ('Sarawak Football Association', 'Malásia'),
  ('Selangor FC', 'Malásia'),
  ('Selangor FC U-23', 'Malásia'),
  ('Sri Pahang FC', 'Malásia'),
  ('Terengganu FC', 'Malásia'),
  ('Terengganu FC II', 'Malásia'),
  ('Big Bullets FC', 'Malawi'),
  ('Mighty Wanderers FC', 'Malawi'),
  ('Club Valencia', 'Maldivas'),
  ('Maziya S&RC', 'Maldivas'),
  ('New Radiant SC', 'Maldivas'),
  ('VB Addu FC', 'Maldivas'),
  ('Victory Sports Club', 'Maldivas'),
  ('AS Real Bamako', 'Mali'),
  ('Djoliba AC', 'Mali'),
  ('Stade Malien', 'Mali'),
  ('Balzan FC', 'Malta'),
  ('Birkirkara FC', 'Malta'),
  ('Floriana FC', 'Malta'),
  ('Gudja United FC', 'Malta'),
  ('Gżira United FC', 'Malta'),
  ('Ħamrun Spartans FC', 'Malta'),
  ('Hibernians FC', 'Malta'),
  ('Marsa FC', 'Malta'),
  ('Marsaxlokk FC', 'Malta'),
  ('Melita FC', 'Malta'),
  ('Mosta FC', 'Malta'),
  ('Msida Saint-Joseph FC', 'Malta'),
  ('Naxxar Lions FC', 'Malta'),
  ('Pembroke Athleta FC', 'Malta'),
  ('Pietà Hotspurs FC', 'Malta'),
  ('Qormi FC', 'Malta'),
  ('Rabat Ajax FC', 'Malta'),
  ('Senglea Athletic FC', 'Malta'),
  ('Sirens FC', 'Malta'),
  ('Sliema Wanderers FC', 'Malta'),
  ('St. Andrews FC', 'Malta'),
  ('St. George''s FC', 'Malta'),
  ('St. Lucia FC', 'Malta'),
  ('St. Patrick FC', 'Malta'),
  ('Tarxien Rainbows FC', 'Malta'),
  ('Valletta FC', 'Malta'),
  ('Vittoriosa Stars FC', 'Malta'),
  ('Żurrieq FC', 'Malta'),
  ('AS Salé', 'Marrocos'),
  ('Chabab Rif Al Hoceima', 'Marrocos'),
  ('COD Meknès', 'Marrocos'),
  ('Difaa Hassani El Jadidi', 'Marrocos'),
  ('FAR Rabat', 'Marrocos'),
  ('FUS de Rabat', 'Marrocos'),
  ('Hassania Agadir', 'Marrocos'),
  ('IR Tanger', 'Marrocos'),
  ('Ittihad Khemisset', 'Marrocos'),
  ('JS Massira', 'Marrocos'),
  ('KAC Kénitra', 'Marrocos'),
  ('KACM', 'Marrocos'),
  ('Maghreb of Fez', 'Marrocos'),
  ('MC Oujda', 'Marrocos'),
  ('Moghreb Atlético Tetuán', 'Marrocos'),
  ('Nahdat Zemamra', 'Marrocos'),
  ('OC Khouribga', 'Marrocos'),
  ('Olympique Club de Safi', 'Marrocos'),
  ('Racing de Casablanca', 'Marrocos'),
  ('Raja Beni Mellal', 'Marrocos'),
  ('Raja Club Athletic', 'Marrocos'),
  ('RS Berkane', 'Marrocos'),
  ('SCC Mohammédia', 'Marrocos'),
  ('Union de Touarga', 'Marrocos'),
  ('Wydad Athletic Club', 'Marrocos'),
  ('Youssoufia Berrechid', 'Marrocos'),
  ('Pamplemousses SC', 'Maurícia'),
  ('ASAC Concorde', 'Mauritânia'),
  ('FC Nouadhibou', 'Mauritânia'),
  ('FC Tevragh Zeïna', 'Mauritânia'),
  ('Atlante FC', 'México'),
  ('Atlas FC', 'México'),
  ('Atletico de San Luis', 'México'),
  ('CD Guadalajara', 'México'),
  ('CD Oro', 'México'),
  ('CF Pachuca', 'México'),
  ('Chiapas FC', 'México'),
  ('Club América', 'México'),
  ('Club América Reserves', 'México'),
  ('Club Atlético Morelia', 'México'),
  ('Club Celaya', 'México'),
  ('Club de Fútbol Laguna', 'México'),
  ('Club de Fútbol Monterrey', 'México'),
  ('Club León', 'México'),
  ('Club Necaxa', 'México'),
  ('Club Tijuana', 'México'),
  ('Cruz Azul', 'México'),
  ('Cruz Azul Reserves', 'México'),
  ('Dorados de Sinaloa', 'México'),
  ('FC Juárez', 'México'),
  ('Jaguares de Tapachula', 'México'),
  ('Jaiba Brava', 'México'),
  ('Leones Negros de la Universidad de Guadalajara', 'México'),
  ('Lobos de la BUAP', 'México'),
  ('Mazatlán Fútbol Club', 'México'),
  ('Puebla FC', 'México'),
  ('Puebla FC Reserves', 'México'),
  ('Pumas UNAM', 'México'),
  ('Querétaro FC', 'México'),
  ('Real Club España', 'México'),
  ('Santos Laguna', 'México'),
  ('Santos Laguna Reserves and Academy', 'México'),
  ('Tampico FC', 'México'),
  ('Tiburones Rojos de Veracruz', 'México'),
  ('Tigres UANL', 'México'),
  ('Toluca FC', 'México'),
  ('Toros Neza', 'México'),
  ('Ayeyawady United FC', 'Mianmar'),
  ('Best United FC', 'Mianmar'),
  ('Hanthawaddy United FC', 'Mianmar'),
  ('Kanbawza FC', 'Mianmar'),
  ('Magway FC', 'Mianmar'),
  ('Manawmye FC', 'Mianmar'),
  ('Nay Pyi Taw FC', 'Mianmar'),
  ('Rakhapura United FC', 'Mianmar'),
  ('Rakhine United FC', 'Mianmar'),
  ('Sagaing United FC', 'Mianmar'),
  ('Southern Myanmar United FC', 'Mianmar'),
  ('Yadanarbon FC', 'Mianmar'),
  ('Yangon United FC', 'Mianmar'),
  ('Zeyashwemye FC', 'Mianmar'),
  ('Zwegabin United FC', 'Mianmar'),
  ('CD Costa do Sol', 'Moçambique'),
  ('CD Maxaquene', 'Moçambique'),
  ('Clube Ferroviário da Beira', 'Moçambique'),
  ('Clube Ferroviário de Maputo', 'Moçambique'),
  ('GD HCB Songo', 'Moçambique'),
  ('Grupo Desportivo de Maputo', 'Moçambique'),
  ('Liga Muçulmana de Maputo', 'Moçambique'),
  ('CF Găgăuzia', 'Moldávia'),
  ('FC Bălți', 'Moldávia'),
  ('FC Codru Lozova', 'Moldávia'),
  ('FC Dacia Buiucani', 'Moldávia'),
  ('FC Dinamo-Auto Tiraspol', 'Moldávia'),
  ('FC Florești', 'Moldávia'),
  ('FC Iskra-Stal', 'Moldávia'),
  ('FC Milsami', 'Moldávia'),
  ('FC Petrocub Hîncești', 'Moldávia'),
  ('FC Politehnica Chișinău', 'Moldávia'),
  ('FC Saxan', 'Moldávia'),
  ('FC Sheriff Tiraspol', 'Moldávia'),
  ('FC Speranța Crihana Veche', 'Moldávia'),
  ('FC Tighina', 'Moldávia'),
  ('FC Ungheni', 'Moldávia'),
  ('FC Veris Chișinău', 'Moldávia'),
  ('FC Zimbru Chișinău', 'Moldávia'),
  ('Moldova Boroșeni', 'Moldávia'),
  ('Real Sireti', 'Moldávia'),
  ('Speranța Nisporeni', 'Moldávia'),
  ('AS Monaco FC', 'Mónaco'),
  ('Arvis FC', 'Mongólia'),
  ('Athletic 220 FC', 'Mongólia'),
  ('Bayangol FC', 'Mongólia'),
  ('Deren FC', 'Mongólia'),
  ('Erchim', 'Mongólia'),
  ('FC Ulaanbaatar', 'Mongólia'),
  ('Goyo FC', 'Mongólia'),
  ('Khangarid', 'Mongólia'),
  ('Khasiin Khulguud', 'Mongólia'),
  ('Khoromkhon', 'Mongólia'),
  ('Selenge Press', 'Mongólia'),
  ('Soyombiin Baarsuud', 'Mongólia'),
  ('Ulaanbaatar City FC', 'Mongólia'),
  ('Ulaanbaataryn Mazaalaynuud', 'Mongólia'),
  ('Ulaanbaataryn Unaganuud FC', 'Mongólia'),
  ('FK Arsenal Tivat', 'Montenegro'),
  ('FK Berane', 'Montenegro'),
  ('FK Bokelj', 'Montenegro'),
  ('FK Bratstvo Cijevna', 'Montenegro'),
  ('FK Budućnost Podgorica', 'Montenegro'),
  ('FK Cetinje', 'Montenegro'),
  ('FK Dečić', 'Montenegro'),
  ('FK Grafičar Podgorica', 'Montenegro'),
  ('FK Ibar', 'Montenegro'),
  ('FK Igalo 1929', 'Montenegro'),
  ('FK Iskra Danilovgrad', 'Montenegro'),
  ('FK Jedinstvo Bijelo Polje', 'Montenegro'),
  ('FK Jezero', 'Montenegro'),
  ('FK Kom', 'Montenegro'),
  ('FK Lovćen', 'Montenegro'),
  ('FK Mornar', 'Montenegro'),
  ('FK Otrant', 'Montenegro'),
  ('FK Podgorica', 'Montenegro'),
  ('FK Radnički Berane', 'Montenegro'),
  ('FK Rudar Pljevlja', 'Montenegro'),
  ('FK Sutjeska Nikšić', 'Montenegro'),
  ('FK Zeta', 'Montenegro'),
  ('OFK Grbalj', 'Montenegro'),
  ('OFK Mladost Donja Gorica', 'Montenegro'),
  ('OFK Petrovac', 'Montenegro'),
  ('OFK Titograd', 'Montenegro'),
  ('African Stars FC', 'Namíbia'),
  ('Black Africa FC', 'Namíbia'),
  ('FC Civics Windhoek', 'Namíbia'),
  ('Orlando Pirates FC Windhoek', 'Namíbia'),
  ('Manang Marshyangdi Club', 'Nepal'),
  ('Nepal Police Club', 'Nepal'),
  ('Three Star Club', 'Nepal'),
  ('Club Deportivo Walter Ferretti', 'Nicarágua'),
  ('Diriangén Fútbol Club', 'Nicarágua'),
  ('Real Estelí FC', 'Nicarágua'),
  ('AS Douanes Niamey', 'Níger'),
  ('AS GNN', 'Níger'),
  ('AS Police', 'Níger'),
  ('AS SONIDEP', 'Níger'),
  ('Olympic FC de Niamey', 'Níger'),
  ('Sahel Sporting Club', 'Níger'),
  ('Abia Warriors FC', 'Nigéria'),
  ('ABS FC', 'Nigéria'),
  ('Akwa United FC', 'Nigéria'),
  ('Bayelsa United FC', 'Nigéria'),
  ('Bendel Insurance FC', 'Nigéria'),
  ('Bridge FC', 'Nigéria'),
  ('El-Kanemi Warriors', 'Nigéria'),
  ('Enugu Rangers', 'Nigéria'),
  ('Enyimba International FC', 'Nigéria'),
  ('Giwa FC', 'Nigéria'),
  ('Gombe United FC', 'Nigéria'),
  ('Heartland FC', 'Nigéria'),
  ('Ikorodu City FC', 'Nigéria'),
  ('Ikorodu United FC', 'Nigéria'),
  ('Jasper United', 'Nigéria'),
  ('Kaduna United FC', 'Nigéria'),
  ('Kano Pillars FC', 'Nigéria'),
  ('Kwara United FC', 'Nigéria'),
  ('Leventis United', 'Nigéria'),
  ('Lobi Stars FC', 'Nigéria'),
  ('MFM FC', 'Nigéria'),
  ('Mighty Jets FC', 'Nigéria'),
  ('Nasarawa United FC', 'Nigéria'),
  ('Nembe City FC', 'Nigéria'),
  ('New Nigeria Bank FC', 'Nigéria'),
  ('Niger Tornadoes FC', 'Nigéria'),
  ('NITEL Vasco Da Gama FC', 'Nigéria'),
  ('Ocean Boys FC', 'Nigéria'),
  ('Plateau United FC', 'Nigéria'),
  ('Racca Rovers', 'Nigéria'),
  ('Ranchers Bees FC', 'Nigéria'),
  ('Remo Stars FC', 'Nigéria'),
  ('Rivers United FC', 'Nigéria'),
  ('Shooting Stars SC', 'Nigéria'),
  ('Sporting Lagos FC', 'Nigéria'),
  ('Sunshine Stars FC', 'Nigéria'),
  ('Udoji United FC', 'Nigéria'),
  ('Warri Wolves FC', 'Nigéria'),
  ('Wikki Tourists FC', 'Nigéria'),
  ('Aalesunds FK', 'Noruega'),
  ('Arna-Bjørnar', 'Noruega'),
  ('Åsane Fotball', 'Noruega'),
  ('Bærum SK', 'Noruega'),
  ('Bryne FK', 'Noruega'),
  ('FK Bodø/Glimt', 'Noruega'),
  ('FK Haugesund', 'Noruega'),
  ('FK Jerv', 'Noruega'),
  ('FK Ørn-Horten', 'Noruega'),
  ('Follo FK', 'Noruega'),
  ('Fredrikstad FK', 'Noruega'),
  ('Frigg Oslo FK', 'Noruega'),
  ('Hamarkameratene', 'Noruega'),
  ('Hønefoss BK', 'Noruega'),
  ('IK Start', 'Noruega'),
  ('Kattem IL FK', 'Noruega'),
  ('KFUM-Kameratene Oslo', 'Noruega'),
  ('Kongsvinger IL Toppfotball', 'Noruega'),
  ('Kristiansund BK', 'Noruega'),
  ('Lillestrøm SK', 'Noruega'),
  ('Lyn 1896 FK', 'Noruega'),
  ('Mjøndalen IF Fotball', 'Noruega'),
  ('Molde FK', 'Noruega'),
  ('Moss FK', 'Noruega'),
  ('Odds BK', 'Noruega'),
  ('Ranheim Fotball', 'Noruega'),
  ('Raufoss Fotball', 'Noruega'),
  ('Rosenborg BK', 'Noruega'),
  ('Sandefjord Fotball', 'Noruega'),
  ('Sandnes Ulf', 'Noruega'),
  ('Sarpsborg 08 FF', 'Noruega'),
  ('SK Brann', 'Noruega'),
  ('SK Gjøvik-Lyn', 'Noruega'),
  ('SK Vard Haugesund', 'Noruega'),
  ('Skeid Fotball', 'Noruega'),
  ('Sogndal Fotball', 'Noruega'),
  ('Stabæk Fotball', 'Noruega'),
  ('Strømmen IF', 'Noruega'),
  ('Strømsgodset TF', 'Noruega'),
  ('Tromsø IL', 'Noruega'),
  ('Ullensaker/Kisa IL', 'Noruega'),
  ('Vålerenga Fotball', 'Noruega'),
  ('Viking FK', 'Noruega'),
  ('Auckland City FC', 'Nova Zelândia'),
  ('Auckland FC', 'Nova Zelândia'),
  ('Canterbury United', 'Nova Zelândia'),
  ('Central United FC', 'Nova Zelândia'),
  ('Eastern Suburbs AFC', 'Nova Zelândia'),
  ('Hawke''s Bay United', 'Nova Zelândia'),
  ('Southern United FC', 'Nova Zelândia'),
  ('Tasman United', 'Nova Zelândia'),
  ('Team Wellington', 'Nova Zelândia'),
  ('Tupapa Maraerenga FC', 'Nova Zelândia'),
  ('University-Mount Wellington', 'Nova Zelândia'),
  ('Waitakere United', 'Nova Zelândia'),
  ('Wellington Phoenix FC', 'Nova Zelândia'),
  ('Wellington Phoenix FC Reserves', 'Nova Zelândia'),
  ('Al Nahda Club', 'Omã'),
  ('Al-Ahli', 'Omã'),
  ('Al-Ittihad Club', 'Omã'),
  ('Al-Khaburah', 'Omã'),
  ('Al-Musannah SC', 'Omã'),
  ('Al-Nasr SC', 'Omã'),
  ('Al-Orouba SC', 'Omã'),
  ('Al-Salam SC', 'Omã'),
  ('Al-Seeb Club', 'Omã'),
  ('Al-Shabab SC', 'Omã'),
  ('Al-Suwaiq Club', 'Omã'),
  ('Al-Wahda SC', 'Omã'),
  ('Bahla Club', 'Omã'),
  ('Bosher Club', 'Omã'),
  ('Dhofar Club', 'Omã'),
  ('Fanja SC', 'Omã'),
  ('Mirbat SC', 'Omã'),
  ('Mjees', 'Omã'),
  ('Muscat Club', 'Omã'),
  ('Nizwa Club', 'Omã'),
  ('Oman Club', 'Omã'),
  ('Saham Club', 'Omã'),
  ('Salalah SC', 'Omã'),
  ('Sur SC', 'Omã'),
  ('Talia Club', 'Omã'),
  ('Aberystwyth Town', 'País de Gales'),
  ('Afan Lido', 'País de Gales'),
  ('Airbus UK Broughton', 'País de Gales'),
  ('Bala Town', 'País de Gales'),
  ('Bangor City', 'País de Gales'),
  ('Barry Town', 'País de Gales'),
  ('Caernarfon Town', 'País de Gales'),
  ('Caersws', 'País de Gales'),
  ('Cardiff City', 'País de Gales'),
  ('Cardiff Metropolitan University', 'País de Gales'),
  ('Carmarthen Town', 'País de Gales'),
  ('Cefn Druids', 'País de Gales'),
  ('Cwmbrân Town', 'País de Gales'),
  ('Flint Town United', 'País de Gales'),
  ('Gap Connah''s Quay', 'País de Gales'),
  ('Haverfordwest County', 'País de Gales'),
  ('Llandudno', 'País de Gales'),
  ('Llanelli', 'País de Gales'),
  ('Llanfairpwll', 'País de Gales'),
  ('Merthyr Town', 'País de Gales'),
  ('Newport County', 'País de Gales'),
  ('Newtown', 'País de Gales')
) as v(name, country)
join countries c on c.name = v.country
on conflict (name, country_id) do nothing;
