-- Football clubs from Wikidata (CC0), part 4 of 4. Safe to re-run: existing name+country pairs are skipped.
-- Run 0023_uk_countries.sql first (it creates Inglaterra, Escocia, etc.).
insert into teams (name, country_id)
select v.name, c.id
from (values
  ('Pen-y-Bont', 'País de Gales'),
  ('Port Talbot Town', 'País de Gales'),
  ('Porthmadog', 'País de Gales'),
  ('Prestatyn Town', 'País de Gales'),
  ('Rhyl', 'País de Gales'),
  ('Swansea City', 'País de Gales'),
  ('The New Saints', 'País de Gales'),
  ('Ton Pentre', 'País de Gales'),
  ('Welshpool Town', 'País de Gales'),
  ('Wrexham', 'País de Gales'),
  ('Achilles''29', 'Países Baixos'),
  ('ADO ''20', 'Países Baixos'),
  ('ADO Den Haag', 'Países Baixos'),
  ('AFC Ajax', 'Países Baixos'),
  ('AFC DWS', 'Países Baixos'),
  ('Almere City FC', 'Países Baixos'),
  ('Amsterdamsche FC', 'Países Baixos'),
  ('Asser Christelijke Voetbalvereniging', 'Países Baixos'),
  ('AZ Alkmaar', 'Países Baixos'),
  ('Blauw-Wit Amsterdam', 'Países Baixos'),
  ('BVV Barendrecht', 'Países Baixos'),
  ('De Graafschap', 'Países Baixos'),
  ('De Treffers', 'Países Baixos'),
  ('Excelsior Maassluis', 'Países Baixos'),
  ('Excelsior Rotterdam', 'Países Baixos'),
  ('FC Den Bosch', 'Países Baixos'),
  ('FC Dordrecht', 'Países Baixos'),
  ('FC Eindhoven', 'Países Baixos'),
  ('FC Emmen', 'Países Baixos'),
  ('FC Groningen', 'Países Baixos'),
  ('FC Twente', 'Países Baixos'),
  ('FC Utrecht', 'Países Baixos'),
  ('FC Volendam', 'Países Baixos'),
  ('Feyenoord Rotterdam', 'Países Baixos'),
  ('Fortuna Sittard', 'Países Baixos'),
  ('Go Ahead Eagles', 'Países Baixos'),
  ('GVVV', 'Países Baixos'),
  ('Helmond Sport', 'Países Baixos'),
  ('Heracles Almelo', 'Países Baixos'),
  ('HHC Hardenberg', 'Países Baixos'),
  ('HVV Den Haag', 'Países Baixos'),
  ('Jong Ajax', 'Países Baixos'),
  ('Jong FC Twente', 'Países Baixos'),
  ('Jong FC Utrecht', 'Países Baixos'),
  ('Jong PSV', 'Países Baixos'),
  ('Koninklijke HFC', 'Países Baixos'),
  ('MVV Maastricht', 'Países Baixos'),
  ('NAC Breda', 'Países Baixos'),
  ('NEC', 'Países Baixos'),
  ('PEC Zwolle', 'Países Baixos'),
  ('PSV Eindhoven', 'Países Baixos'),
  ('Quick Boys', 'Países Baixos'),
  ('RCH', 'Países Baixos'),
  ('Rijnsburgse Boys', 'Países Baixos'),
  ('RKAV Volendam', 'Países Baixos'),
  ('RKC Waalwijk', 'Países Baixos'),
  ('Roda JC Kerkrade', 'Países Baixos'),
  ('SBV Vitesse', 'Países Baixos'),
  ('SC Cambuur', 'Países Baixos'),
  ('SC Heerenveen', 'Países Baixos'),
  ('SC Telstar', 'Países Baixos'),
  ('Schiedamse Voetbal Vereniging', 'Países Baixos'),
  ('Sparta Rotterdam', 'Países Baixos'),
  ('Sportclub Enschede', 'Países Baixos'),
  ('SV Spakenburg', 'Países Baixos'),
  ('SVV Scheveningen', 'Países Baixos'),
  ('TOP Oss', 'Países Baixos'),
  ('VV DOS', 'Países Baixos'),
  ('VV Katwijk', 'Países Baixos'),
  ('VV Noordwijk', 'Países Baixos'),
  ('VVK/Telstar', 'Países Baixos'),
  ('VVV-Venlo', 'Países Baixos'),
  ('Willem II', 'Países Baixos'),
  ('Hilal Al-Quds Club', 'Palestina'),
  ('Club Deportivo Árabe Unido', 'Panamá'),
  ('Club Deportivo Plaza Amador', 'Panamá'),
  ('Club Deportivo Universitario', 'Panamá'),
  ('San Francisco FC', 'Panamá'),
  ('Sporting San Miguelito', 'Panamá'),
  ('Tauro FC', 'Panamá'),
  ('Hekari United FC', 'Papua-Nova Guiné'),
  ('Afghan FC', 'Paquistão'),
  ('Baloch FC', 'Paquistão'),
  ('HBL FC', 'Paquistão'),
  ('KESC FC', 'Paquistão'),
  ('KPT FC', 'Paquistão'),
  ('KRL FC', 'Paquistão'),
  ('Lyallpur FC', 'Paquistão'),
  ('Muslim FC', 'Paquistão'),
  ('NBP FC', 'Paquistão'),
  ('PAF FC', 'Paquistão'),
  ('Pak Afghan Clearing FC', 'Paquistão'),
  ('Pakistan Army FC', 'Paquistão'),
  ('Pakistan International Airlines FC', 'Paquistão'),
  ('Pakistan Navy FC', 'Paquistão'),
  ('Pakistan Railways FC', 'Paquistão'),
  ('PEL FC', 'Paquistão'),
  ('PMC Club Athletico Faisalabad', 'Paquistão'),
  ('SSGC FC', 'Paquistão'),
  ('WAPDA FC', 'Paquistão'),
  ('ZTBL FC', 'Paquistão'),
  ('Cerro Porteño', 'Paraguai'),
  ('Club 12 de Octubre', 'Paraguai'),
  ('Club Atlético 3 de Febrero', 'Paraguai'),
  ('Club Cerro Porteño', 'Paraguai'),
  ('Club Deportivo Capiatá', 'Paraguai'),
  ('Club General Díaz', 'Paraguai'),
  ('Club Guaraní', 'Paraguai'),
  ('Club Libertad', 'Paraguai'),
  ('Club Nacional', 'Paraguai'),
  ('Club Olimpia', 'Paraguai'),
  ('Club Presidente Hayes', 'Paraguai'),
  ('Club River Plate Asunción', 'Paraguai'),
  ('Club Rubio Ñu', 'Paraguai'),
  ('Club Silvio Pettirossi', 'Paraguai'),
  ('Club Sol de América', 'Paraguai'),
  ('Club Sport Colombia', 'Paraguai'),
  ('Club Sportivo 2 de Mayo', 'Paraguai'),
  ('Club Sportivo San Lorenzo', 'Paraguai'),
  ('Deportivo Recoleta', 'Paraguai'),
  ('Independiente FBC', 'Paraguai'),
  ('Resistencia SC', 'Paraguai'),
  ('Sportivo Carapeguá', 'Paraguai'),
  ('Sportivo Luqueño', 'Paraguai'),
  ('Sportivo Trinidense', 'Paraguai'),
  ('Tacuary Football Club', 'Paraguai'),
  ('Atlético Grau', 'Peru'),
  ('Ayacucho FC', 'Peru'),
  ('CD Universidad César Vallejo', 'Peru'),
  ('Centro Iqueño', 'Peru'),
  ('Cienciano', 'Peru'),
  ('Club Alianza Lima', 'Peru'),
  ('Club Deportivo Municipal', 'Peru'),
  ('Club Deportivo Pacífico FC', 'Peru'),
  ('Club Juan Aurich', 'Peru'),
  ('Club Sporting Cristal', 'Peru'),
  ('Club Universitario de Deportes', 'Peru'),
  ('Cultural and Sports Club Technical University of Cajamarca', 'Peru'),
  ('Cusco FC', 'Peru'),
  ('FBC Melgar', 'Peru'),
  ('José Gálvez FBC', 'Peru'),
  ('León de Huánuco', 'Peru'),
  ('Merchants United Social, Sports and Cultural Association', 'Peru'),
  ('Pirata F.C', 'Peru'),
  ('San Simón de Moquegua', 'Peru'),
  ('Sport Áncash', 'Peru'),
  ('Sport Boys', 'Peru'),
  ('Sport Huancayo', 'Peru'),
  ('Sport Rosario', 'Peru'),
  ('Sporting Tabaco (1926–1955)', 'Peru'),
  ('Sports Association Club Alianza Atlético de Sullana', 'Peru'),
  ('Unión Comercio', 'Peru'),
  ('Unión Huaral', 'Peru'),
  ('Arka Gdynia', 'Polónia'),
  ('Chrobry Głogów', 'Polónia'),
  ('Cracovia', 'Polónia'),
  ('Dolcan Ząbki', 'Polónia'),
  ('Flota Świnoujście', 'Polónia'),
  ('Garbarnia Kraków', 'Polónia'),
  ('GKS Bełchatów', 'Polónia'),
  ('GKS Katowice', 'Polónia'),
  ('GKS Tychy', 'Polónia'),
  ('Górnik Łęczna', 'Polónia'),
  ('Górnik Zabrze', 'Polónia'),
  ('Gwardia Warsaw', 'Polónia'),
  ('Hutnik Nowa Huta', 'Polónia'),
  ('Jagiellonia Białystok', 'Polónia'),
  ('Korona Kielce', 'Polónia'),
  ('KS Lechia Gdańsk', 'Polónia'),
  ('KSZO Ostrowiec Świętokrzyski', 'Polónia'),
  ('Lech Poznań', 'Polónia'),
  ('ŁKS Łódź', 'Polónia'),
  ('LKS Nieciecza', 'Polónia'),
  ('Miedź Legnica', 'Polónia'),
  ('MKP Pogoń Siedlce', 'Polónia'),
  ('Motor Lublin', 'Polónia'),
  ('Odra Opole', 'Polónia'),
  ('Odra Wodzisław', 'Polónia'),
  ('Piast Gliwice', 'Polónia'),
  ('Podbeskidzie Bielsko-Biała', 'Polónia'),
  ('Pogoń Szczecin', 'Polónia'),
  ('Polonia Bytom', 'Polónia'),
  ('Polonia Warsaw', 'Polónia'),
  ('Puszcza Niepołomice', 'Polónia'),
  ('Radomiak Radom', 'Polónia'),
  ('Raków Częstochowa', 'Polónia'),
  ('ROW 1964 Rybnik', 'Polónia'),
  ('RTS Widzew Łódź', 'Polónia'),
  ('Ruch Chorzów', 'Polónia'),
  ('Sandecja Nowy Sącz', 'Polónia'),
  ('Śląsk Wrocław', 'Polónia'),
  ('Stal Mielec', 'Polónia'),
  ('Stal Rzeszów', 'Polónia'),
  ('Stal Stalowa Wola', 'Polónia'),
  ('Szombierki Bytom', 'Polónia'),
  ('Warta Poznań', 'Polónia'),
  ('Wieczysta Kraków', 'Polónia'),
  ('Wigry Suwałki', 'Polónia'),
  ('Wisła Kraków', 'Polónia'),
  ('Wisła Płock', 'Polónia'),
  ('Zagłębie Lubin', 'Polónia'),
  ('Zagłębie Sosnowiec', 'Polónia'),
  ('Zagłębie Wałbrzych', 'Polónia'),
  ('Zawisza Bydgoszcz', 'Polónia'),
  ('Znicz Pruszków', 'Polónia'),
  ('Académico de Viseu FC', 'Portugal'),
  ('AD Ovarense', 'Portugal'),
  ('AD Sanjoanense', 'Portugal'),
  ('Associação Académica de Coimbra – OAF', 'Portugal'),
  ('Associação Naval 1º de Maio', 'Portugal'),
  ('Atlético Clube de Portugal', 'Portugal'),
  ('AVS Futebol SAD', 'Portugal'),
  ('Boavista FC', 'Portugal'),
  ('B-SAD', 'Portugal'),
  ('Casa Pia AC', 'Portugal'),
  ('CD Cova da Piedade', 'Portugal'),
  ('CD Fátima', 'Portugal'),
  ('CD Feirense', 'Portugal'),
  ('CD Mafra', 'Portugal'),
  ('CD Nacional', 'Portugal'),
  ('CD Santa Clara', 'Portugal'),
  ('CD Tondela', 'Portugal'),
  ('CD Trofense', 'Portugal'),
  ('CF Andorinha', 'Portugal'),
  ('CF Estrela da Amadora', 'Portugal'),
  ('CF Os Belenenses', 'Portugal'),
  ('CF União', 'Portugal'),
  ('Clube Desportivo das Aves', 'Portugal'),
  ('Clube Oriental de Lisboa', 'Portugal'),
  ('CS Marítimo', 'Portugal'),
  ('CS Marítimo B', 'Portugal'),
  ('FC Alverca', 'Portugal'),
  ('FC Arouca', 'Portugal'),
  ('FC Barreirense', 'Portugal'),
  ('FC Famalicão', 'Portugal'),
  ('FC Felgueiras', 'Portugal'),
  ('FC Maia', 'Portugal'),
  ('FC Paços de Ferreira', 'Portugal'),
  ('FC Penafiel', 'Portugal'),
  ('FC Porto', 'Portugal'),
  ('FC Porto B', 'Portugal'),
  ('FC Tirsense', 'Portugal'),
  ('FC Vizela', 'Portugal'),
  ('GD Chaves', 'Portugal'),
  ('GD Estoril Praia', 'Portugal'),
  ('GD Fabril', 'Portugal'),
  ('GD Ribeirão', 'Portugal'),
  ('Gil Vicente FC', 'Portugal'),
  ('Gondomar SC', 'Portugal'),
  ('Leça FC', 'Portugal'),
  ('Leixões SC', 'Portugal'),
  ('Louletano DC', 'Portugal'),
  ('Moreirense FC', 'Portugal'),
  ('Portimonense SC', 'Portugal'),
  ('Real Sport Clube', 'Portugal'),
  ('Rio Ave FC', 'Portugal'),
  ('SC Beira-Mar', 'Portugal'),
  ('SC Braga', 'Portugal'),
  ('SC Braga B', 'Portugal'),
  ('SC Campomaiorense', 'Portugal'),
  ('SC Covilhã', 'Portugal'),
  ('SC Espinho', 'Portugal'),
  ('SC Farense', 'Portugal'),
  ('SC Freamunde', 'Portugal'),
  ('SC Olhanense', 'Portugal'),
  ('SC Salgueiros', 'Portugal'),
  ('SCU Torreense', 'Portugal'),
  ('SL Benfica', 'Portugal'),
  ('SL Benfica B', 'Portugal'),
  ('SL Benfica de Macau', 'Portugal'),
  ('Sporting CP', 'Portugal'),
  ('Sporting CP B', 'Portugal'),
  ('UD Leiria', 'Portugal'),
  ('UD Oliveirense', 'Portugal'),
  ('UD Vilafranquense', 'Portugal'),
  ('Varzim SC', 'Portugal'),
  ('Vitória FC', 'Portugal'),
  ('Vitória SC', 'Portugal'),
  ('Vitória SC B', 'Portugal'),
  ('AFC Leopards', 'Quénia'),
  ('Bandari FC', 'Quénia'),
  ('Chemelil Sugar FC', 'Quénia'),
  ('Gor Mahia FC', 'Quénia'),
  ('Kakamega Homeboyz FC', 'Quénia'),
  ('Kariobangi Sharks', 'Quénia'),
  ('Karuturi Sports', 'Quénia'),
  ('Kenya Commercial Bank', 'Quénia'),
  ('Kenya Pipeline FC', 'Quénia'),
  ('Kenya Revenue Authority FC', 'Quénia'),
  ('Kisumu Telkom', 'Quénia'),
  ('Mara Sugar', 'Quénia'),
  ('Mathare United FC', 'Quénia'),
  ('Muhoroni Youth FC', 'Quénia'),
  ('Nairobi City Stars', 'Quénia'),
  ('Nairobi United', 'Quénia'),
  ('Nakumatt FC', 'Quénia'),
  ('Nakuru AllStars', 'Quénia'),
  ('Nzoia United FC', 'Quénia'),
  ('Reunion FC', 'Quénia'),
  ('Sofapaka FC', 'Quénia'),
  ('Sony Sugar FC', 'Quénia'),
  ('Thika United FC', 'Quénia'),
  ('Tusker FC', 'Quénia'),
  ('Ulinzi Stars FC', 'Quénia'),
  ('Utalii FC', 'Quénia'),
  ('Vihiga Bullets', 'Quénia'),
  ('Wazito FC', 'Quénia'),
  ('Western Stima FC', 'Quénia'),
  ('Zoo Kericho FC', 'Quénia'),
  ('FC Abdish-Ata Kant', 'Quirguistão'),
  ('FC Abdish-Ata-91', 'Quirguistão'),
  ('FC Akademija Osh', 'Quirguistão'),
  ('FC Ak-Bura Osh', 'Quirguistão'),
  ('FC Ak-Maral Tokmok', 'Quirguistão'),
  ('FC Ak-Zhol', 'Quirguistão'),
  ('FC Alamudun', 'Quirguistão'),
  ('FC Ala-Too Naryn', 'Quirguistão'),
  ('FC Alay', 'Quirguistão'),
  ('FC Aldiyer Kurshab', 'Quirguistão'),
  ('FC Alga Bishkek', 'Quirguistão'),
  ('FC Alga-2 Bishkek', 'Quirguistão'),
  ('FC Asia Talas', 'Quirguistão'),
  ('FC Ata-Spor Bishkek', 'Quirguistão'),
  ('FC Bazar-Korgon-Babur', 'Quirguistão'),
  ('FC Dinamo Ala-Buka', 'Quirguistão'),
  ('FC Dinamo Kant', 'Quirguistão'),
  ('FC Dinamo-Manas-SKIF Bishkek', 'Quirguistão'),
  ('FC Dinamo-UVD Osh', 'Quirguistão'),
  ('FC Dordoi Bishkek', 'Quirguistão'),
  ('FC Dordoi-Plaza', 'Quirguistão'),
  ('FC Dostuk Uzgen', 'Quirguistão'),
  ('FC Dzhalal-Abad', 'Quirguistão'),
  ('FC Ekolog Bishkek', 'Quirguistão'),
  ('FC Energetik Karaköl', 'Quirguistão'),
  ('FC Issyk-Kol Karakol', 'Quirguistão'),
  ('FC Kambar-Ata', 'Quirguistão'),
  ('FC Kant', 'Quirguistão'),
  ('FC Kant-Oil', 'Quirguistão'),
  ('FC Kelechek Osh', 'Quirguistão'),
  ('FC Khimik Suzak', 'Quirguistão'),
  ('FC Kyrgyzaltyn', 'Quirguistão'),
  ('FC Lokomotiv Jalal-Abad', 'Quirguistão'),
  ('FC Manas Talas', 'Quirguistão'),
  ('FC Manas-Ordo Talas', 'Quirguistão'),
  ('FC Muras-Sport Bishkek', 'Quirguistão'),
  ('FC Neftchi Kochkor-Ata', 'Quirguistão'),
  ('FC Nookat', 'Quirguistão'),
  ('FC Olimpia-85 Bishkek', 'Quirguistão'),
  ('FC Orto-Nur Sokuluk', 'Quirguistão'),
  ('FC Pivo Belovodskoye', 'Quirguistão'),
  ('FC Polyot Bishkek', 'Quirguistão'),
  ('FC Rotor Bishkek', 'Quirguistão'),
  ('FC RUOR-Guardia Bishkek', 'Quirguistão'),
  ('FC Shakhtyor Kyzyl-Kiya', 'Quirguistão'),
  ('FC Shakhtyor Tashkömür', 'Quirguistão'),
  ('FC Sher-Ak-Dan Bishkek', 'Quirguistão'),
  ('FC Shoro Bishkek', 'Quirguistão'),
  ('FC SKA-Alay Osh', 'Quirguistão'),
  ('FC Svetotekhnika Mayli-Su', 'Quirguistão'),
  ('FC Uchkun Kara-Suu', 'Quirguistão'),
  ('FC Zhashtyk-Ak-Altyn Kara-Suu', 'Quirguistão'),
  ('FC-95 Bishkek', 'Quirguistão'),
  ('Muras United FC', 'Quirguistão'),
  ('OshMU Aldier FC', 'Quirguistão'),
  ('1. FC Slovácko', 'República Checa'),
  ('1. SC Znojmo', 'República Checa'),
  ('1. SK Prostějov', 'República Checa'),
  ('AC Sparta Prague', 'República Checa'),
  ('Bohemians 1905', 'República Checa'),
  ('FC Baník Ostrava', 'República Checa'),
  ('FC Hradec Králové', 'República Checa'),
  ('FC Silon Táborsko', 'República Checa'),
  ('FC Slovan Liberec', 'República Checa'),
  ('FC Viktoria Plzeň', 'República Checa'),
  ('FC Vysočina Jihlava', 'República Checa'),
  ('FC Zbrojovka Brno', 'República Checa'),
  ('FC Zlín', 'República Checa'),
  ('FK Baník Sokolov', 'República Checa'),
  ('FK Chmel Blšany', 'República Checa'),
  ('FK Dukla Prague', 'República Checa'),
  ('FK Hvězda Cheb', 'República Checa'),
  ('FK Jablonec', 'República Checa'),
  ('FK Mladá Boleslav', 'República Checa'),
  ('FK Pardubice', 'República Checa'),
  ('FK Příbram', 'República Checa'),
  ('FK Teplice', 'República Checa'),
  ('FK Ústí nad Labem', 'República Checa'),
  ('FK Varnsdorf', 'República Checa'),
  ('FK Viktoria Žižkov', 'República Checa'),
  ('MFK Karviná', 'República Checa'),
  ('MFK Vítkovice', 'República Checa'),
  ('SFC Opava', 'República Checa'),
  ('SK Dynamo České Budějovice', 'República Checa'),
  ('SK Kladno', 'República Checa'),
  ('SK Sigma Olomouc', 'República Checa'),
  ('SK Slavia Prague', 'República Checa'),
  ('AC Capaco', 'República Democrática do Congo'),
  ('AC Sodigraf', 'República Democrática do Congo'),
  ('AS Dauphins Noirs', 'República Democrática do Congo'),
  ('AS Dragons', 'República Democrática do Congo'),
  ('AS Makiso', 'República Democrática do Congo'),
  ('AS Maniema Union', 'República Democrática do Congo'),
  ('AS New Soger', 'República Democrática do Congo'),
  ('AS Nika', 'República Democrática do Congo'),
  ('AS Rojolu', 'República Democrática do Congo'),
  ('AS Saint-Luc', 'República Democrática do Congo'),
  ('AS Veti', 'República Democrática do Congo'),
  ('Association Sportive Vita Club', 'República Democrática do Congo'),
  ('CS Don Bosco', 'República Democrática do Congo'),
  ('Daring Club Motema Pembe', 'República Democrática do Congo'),
  ('DC Virunga', 'República Democrática do Congo'),
  ('FC MK Etanchéité', 'República Democrática do Congo'),
  ('FC Saint Eloi Lupopo', 'República Democrática do Congo'),
  ('JS Groupe Bazano', 'República Democrática do Congo'),
  ('Lubumbashi Sport', 'República Democrática do Congo'),
  ('OC Bukavu Dawa', 'República Democrática do Congo'),
  ('OC Muungano', 'República Democrática do Congo'),
  ('SC Cilu', 'República Democrática do Congo'),
  ('SCOM Mikishi', 'República Democrática do Congo'),
  ('Sharks XI FC', 'República Democrática do Congo'),
  ('SM Sanga Balende', 'República Democrática do Congo'),
  ('TC Elima', 'República Democrática do Congo'),
  ('TP Mazembe', 'República Democrática do Congo'),
  ('TP Molunge', 'República Democrática do Congo'),
  ('US Panda B52', 'República Democrática do Congo'),
  ('US Tshinkunku', 'República Democrática do Congo'),
  ('Club Deportivo Pantoja', 'República Dominicana'),
  ('AFC Chindia Târgoviște', 'Roménia'),
  ('AFC Dacia Unirea Brăila', 'Roménia'),
  ('ASA Târgu Mureș', 'Roménia'),
  ('CFR Cluj', 'Roménia'),
  ('Club Atletic Oradea', 'Roménia'),
  ('CS Concordia Chiajna', 'Roménia'),
  ('CS Gaz Metan Mediaș', 'Roménia'),
  ('CS Inter Ilfov', 'Roménia'),
  ('CS Pandurii Târgu Jiu', 'Roménia'),
  ('CS Universitatea Craiova', 'Roménia'),
  ('CSM Ceahlăul Piatra Neamț', 'Roménia'),
  ('CSM Politehnica Iași', 'Roménia'),
  ('CSM Reșița', 'Roménia'),
  ('CSM Unirea Alba Iulia', 'Roménia'),
  ('Daco-Getica', 'Roménia'),
  ('FC Argeș', 'Roménia'),
  ('FC Astra Giurgiu', 'Roménia'),
  ('FC Bihor Oradea', 'Roménia'),
  ('FC Botoșani', 'Roménia'),
  ('FC Corvinul Hunedoara', 'Roménia'),
  ('FC Dinamo Bucharest', 'Roménia'),
  ('FC Dunărea Călărași', 'Roménia'),
  ('FC Hermannstadt', 'Roménia'),
  ('FC Jiul Petroșani', 'Roménia'),
  ('FC Olt Scornicești', 'Roménia'),
  ('FC Petrolul Ploiești', 'Roménia'),
  ('FC Rapid București', 'Roménia'),
  ('FC Ripensia Timișoara', 'Roménia'),
  ('FC U Craiova 1948', 'Roménia'),
  ('FC Unirea Slobozia', 'Roménia'),
  ('FC Unirea Urziceni', 'Roménia'),
  ('FC Universitatea Cluj', 'Roménia'),
  ('FC UTA Arad', 'Roménia'),
  ('FC Voluntari', 'Roménia'),
  ('FCSB', 'Roménia'),
  ('FK Csíkszereda', 'Roménia'),
  ('SC Oțelul Galați', 'Roménia'),
  ('Sepsi OSK Sfântu Gheorghe', 'Roménia'),
  ('SSC Farul Constanța', 'Roménia'),
  ('Venus București', 'Roménia'),
  ('Amagaju', 'Ruanda'),
  ('Armée Patriotique Rwandaise FC', 'Ruanda'),
  ('AS Kigali', 'Ruanda'),
  ('Electrogaz FC', 'Ruanda'),
  ('Espoir FC', 'Ruanda'),
  ('Etincelles FC', 'Ruanda'),
  ('Gicumbi FC', 'Ruanda'),
  ('Gorilla FC', 'Ruanda'),
  ('Marines FC', 'Ruanda'),
  ('Mukungwa', 'Ruanda'),
  ('Mukura Victory Sports FC', 'Ruanda'),
  ('Musanze FC', 'Ruanda'),
  ('Panthères Noires', 'Ruanda'),
  ('Police FC', 'Ruanda'),
  ('Rayon Sports FC', 'Ruanda'),
  ('Rutsiro FC', 'Ruanda'),
  ('SC Kiyovu Sports', 'Ruanda'),
  ('Baltika-BFU', 'Rússia'),
  ('FC Akademiya Futbola Rostov-on-Don', 'Rússia'),
  ('FC Akhmat Grozny', 'Rússia'),
  ('FC Akron Tolyatti', 'Rússia'),
  ('FC Alania Vladikavkaz', 'Rússia'),
  ('FC Amkar Perm', 'Rússia'),
  ('FC Arsenal Tula', 'Rússia'),
  ('FC Arsenal-2 Tula', 'Rússia'),
  ('FC Astrakhan', 'Rússia'),
  ('FC Avangard Kursk', 'Rússia'),
  ('FC Avtodor Vladikavkaz', 'Rússia'),
  ('FC Baikal Irkutsk', 'Rússia'),
  ('FC Balashikha', 'Rússia'),
  ('FC Baltika Kaliningrad', 'Rússia'),
  ('FC Biolog-Novokubansk Progress', 'Rússia'),
  ('FC Chayka Peschanokopskoye', 'Rússia'),
  ('FC Chelyabinsk', 'Rússia'),
  ('FC Chernomorets Novorossiysk', 'Rússia'),
  ('FC Chertanovo Moscow', 'Rússia'),
  ('FC Chita', 'Rússia'),
  ('FC Dinamo Moscow', 'Rússia'),
  ('FC Dnepr Smolensk', 'Rússia'),
  ('FC Domodedovo Moscow', 'Rússia'),
  ('FC Druzhba Maykop', 'Rússia'),
  ('FC Dynamo Barnaul', 'Rússia'),
  ('FC Dynamo Bryansk', 'Rússia'),
  ('FC Dynamo Kirov', 'Rússia'),
  ('FC Dynamo Makhachkala', 'Rússia'),
  ('FC Dynamo Saint Petersburg', 'Rússia'),
  ('FC Dynamo Vladivostok', 'Rússia'),
  ('FC Dynamo-2 Moscow', 'Rússia'),
  ('FC Elista', 'Rússia'),
  ('FC Energiya Volzhsky', 'Rússia'),
  ('FC Fakel Voronezh', 'Rússia'),
  ('FC Forte Taganrog', 'Rússia'),
  ('FC Irtysh Omsk', 'Rússia'),
  ('FC Iskra Novoaleksandrovsk', 'Rússia'),
  ('FC Kaluga', 'Rússia'),
  ('FC KAMAZ Naberezhnye Chelny', 'Rússia'),
  ('FC Khimik Dzerzhinsk', 'Rússia'),
  ('FC Khimik-Arsenal', 'Rússia'),
  ('FC Khimik-Avgust', 'Rússia'),
  ('FC Khimki', 'Rússia'),
  ('FC Kolomna', 'Rússia'),
  ('FC Kolos Krasnodar', 'Rússia'),
  ('FC Krasnodar', 'Rússia'),
  ('FC Krasnodar-2', 'Rússia'),
  ('FC Krylia Sovetov Samara', 'Rússia'),
  ('FC Kuban Holding', 'Rússia'),
  ('FC Kuban-2 Krasnodar', 'Rússia'),
  ('FC Leningradets Leningrad Oblast', 'Rússia'),
  ('FC Leon Saturn', 'Rússia'),
  ('FC Lokomotiv Moscow', 'Rússia'),
  ('FC Lokomotiv Nizhny Novgorod', 'Rússia'),
  ('FC Luki-SKIF Velikiye Luki', 'Rússia'),
  ('FC Mashuk-KMV Pyatigorsk', 'Rússia'),
  ('FC Metallurg Lipetsk', 'Rússia'),
  ('FC Murom', 'Rússia'),
  ('FC MVO Moscow', 'Rússia'),
  ('FC Neftekhimik Nizhnekamsk', 'Rússia'),
  ('FC Neftyanik Uray', 'Rússia'),
  ('FC Nizhny Novgorod', 'Rússia'),
  ('FC Nosta Novotroitsk', 'Rússia'),
  ('FC Olimpia Volgograd', 'Rússia'),
  ('FC Orenburg', 'Rússia'),
  ('FC Peresvet Podolsk', 'Rússia'),
  ('FC Petrotrest Saint Petersburg', 'Rússia'),
  ('FC Rodina Moscow', 'Rússia'),
  ('FC Rostov', 'Rússia'),
  ('FC Rotor Volgograd', 'Rússia'),
  ('FC Rotor-2 Volgograd', 'Rússia'),
  ('FC Rubin Yalta', 'Rússia'),
  ('FC Ryazan', 'Rússia'),
  ('FC Sakhalinets', 'Rússia'),
  ('FC Salyut Belgorod', 'Rússia'),
  ('FC Saturn-2 Moscow Region', 'Rússia'),
  ('FC Shakhtyor Prokopyevsk', 'Rússia'),
  ('FC Shinnik Yaroslavl', 'Rússia'),
  ('FC Sibir', 'Rússia'),
  ('FC SKA Rostov-on-Don', 'Rússia'),
  ('FC SKA-Energiya Khabarovsk', 'Rússia'),
  ('FC SKChF Sevastopol', 'Rússia'),
  ('FC Smolensk', 'Rússia'),
  ('FC Sokol Saratov', 'Rússia'),
  ('FC Spartak Kostroma', 'Rússia'),
  ('FC Spartak Shchyolkovo', 'Rússia'),
  ('FC Spartak Tambov', 'Rússia'),
  ('FC Spartak Tuymazy', 'Rússia'),
  ('FC Spartak Yoshkar-Ola', 'Rússia'),
  ('FC Spartak-2 Moscow', 'Rússia'),
  ('FC Spartak-Peresvet Bryansk', 'Rússia'),
  ('FC Strogino Moscow', 'Rússia'),
  ('FC Syzran-2003', 'Rússia'),
  ('FC Tekstilshchik Ivanovo', 'Rússia'),
  ('FC Tekstilshchik Kamyshin', 'Rússia'),
  ('FC Tom Tomsk', 'Rússia'),
  ('FC Torpedo Armavir', 'Rússia'),
  ('FC Torpedo Moscow', 'Rússia'),
  ('FC Torpedo-2', 'Rússia'),
  ('FC Torpedo-ZIL Moscow', 'Rússia'),
  ('FC Tuapse', 'Rússia'),
  ('FC Tver', 'Rússia'),
  ('FC Ufa', 'Rússia'),
  ('FC Ural Yekaterinburg', 'Rússia'),
  ('FC Ural-2 Yekaterinburg', 'Rússia'),
  ('FC Veles Moscow', 'Rússia'),
  ('FC Vityaz Podolsk', 'Rússia'),
  ('FC Volga Ulyanovsk', 'Rússia'),
  ('FC Volgar Astrakhan', 'Rússia'),
  ('FC Volgograd', 'Rússia'),
  ('FC Volna Nizhny Novgorod Oblast', 'Rússia'),
  ('FC Volochanin-Ratmir Vyshny Volochyok', 'Rússia'),
  ('FC Yadro Saint-Petersburg', 'Rússia'),
  ('FC Yenisey Krasnoyarsk', 'Rússia'),
  ('FC Yenisey-2 Krasnoyarsk', 'Rússia'),
  ('FC Yessentuki', 'Rússia'),
  ('FC Zenit Penza', 'Rússia'),
  ('FC Zenit Saint Petersburg', 'Rússia'),
  ('FC Zenit-Izhevsk Izhevsk', 'Rússia'),
  ('FC Zhemchuzhina-Sochi', 'Rússia'),
  ('FC Znamya Truda', 'Rússia'),
  ('PFC CSKA Moscow', 'Rússia'),
  ('PFC Kuban Krasnodar', 'Rússia'),
  ('PFC Sochi', 'Rússia'),
  ('PFC Spartak Nalchik', 'Rússia'),
  ('Rubin Kazan', 'Rússia'),
  ('Spartak Moscow', 'Rússia'),
  ('Torpedo Olleart FC', 'Rússia'),
  ('ZFK Dynamo Moscow', 'Rússia'),
  ('Zvezda', 'Rússia'),
  ('Kiwi FC', 'Samoa'),
  ('Vaivase-tai', 'Samoa'),
  ('AC Juvenes/Dogana', 'San Marino'),
  ('AC Libertas', 'San Marino'),
  ('AC Virtus', 'San Marino'),
  ('FC Domagnano', 'San Marino'),
  ('FC Fiorentino', 'San Marino'),
  ('gil paja', 'San Marino'),
  ('San Marino Calcio', 'San Marino'),
  ('SC Faetano', 'San Marino'),
  ('SP Cailungo', 'San Marino'),
  ('SP La Fiorita', 'San Marino'),
  ('SS Cosmos', 'San Marino'),
  ('SS Folgore Falciano Calcio', 'San Marino'),
  ('SS Murata', 'San Marino'),
  ('SS Pennarossa', 'San Marino'),
  ('SS San Giovanni', 'San Marino'),
  ('Tre Fiori Football Club', 'San Marino'),
  ('La Passe FC', 'Seicheles'),
  ('Saint Louis Suns United', 'Seicheles'),
  ('St Michel United FC', 'Seicheles'),
  ('AS Douanes', 'Senegal'),
  ('AS Pikine', 'Senegal'),
  ('ASC HLM', 'Senegal'),
  ('ASC Jaraaf', 'Senegal'),
  ('ASC Jeanne d''Arc', 'Senegal'),
  ('ASC Port Autonome', 'Senegal'),
  ('ASC Yakaar', 'Senegal'),
  ('ASC Yeggo', 'Senegal'),
  ('ASCE La Linguère', 'Senegal'),
  ('ASFA Dakar', 'Senegal'),
  ('Association sportive Cambérène', 'Senegal'),
  ('Association sportive et culturelle SONACOS', 'Senegal'),
  ('Casa Sports', 'Senegal'),
  ('Compagnie Sucrière Sénégalaise', 'Senegal'),
  ('Dakar UC', 'Senegal'),
  ('Diambars FC', 'Senegal'),
  ('Génération Foot', 'Senegal'),
  ('Guédiawaye FC', 'Senegal'),
  ('Niary Tally', 'Senegal'),
  ('Olympique de Ngor', 'Senegal'),
  ('Stade Mbour', 'Senegal'),
  ('Teungueth FC', 'Senegal'),
  ('Touré Kunda Footpro', 'Senegal'),
  ('US Gorée', 'Senegal'),
  ('US Ouakam', 'Senegal'),
  ('Diamond Stars FC', 'Serra Leoa'),
  ('East End Lions FC', 'Serra Leoa'),
  ('FC Kallon', 'Serra Leoa'),
  ('FK BASK', 'Sérvia'),
  ('FK Bečej', 'Sérvia'),
  ('FK Bežanija', 'Sérvia'),
  ('FK Bor', 'Sérvia'),
  ('FK Borac Čačak', 'Sérvia'),
  ('FK BSK Borča', 'Sérvia'),
  ('FK Budućnost Banatski Dvor', 'Sérvia'),
  ('FK Crvena zvezda', 'Sérvia'),
  ('FK ČSK Čelarevo', 'Sérvia'),
  ('FK Čukarički', 'Sérvia'),
  ('FK Dinamo Vranje', 'Sérvia'),
  ('FK Donji Srem', 'Sérvia'),
  ('FK Inđija', 'Sérvia'),
  ('FK Jagodina', 'Sérvia'),
  ('FK Javor Ivanjica', 'Sérvia'),
  ('FK Jedinstvo Ub', 'Sérvia'),
  ('FK Kolubara', 'Sérvia'),
  ('FK Mačva Šabac', 'Sérvia'),
  ('FK Metalac Gornji Milanovac', 'Sérvia'),
  ('FK Mladost Apatin', 'Sérvia'),
  ('FK Mladost Lučani', 'Sérvia'),
  ('FK Napredak Kruševac', 'Sérvia'),
  ('FK Naša Krila Zemun', 'Sérvia'),
  ('FK Novi Pazar', 'Sérvia'),
  ('FK Obilić', 'Sérvia'),
  ('FK Partizan', 'Sérvia'),
  ('FK Proleter Novi Sad', 'Sérvia'),
  ('FK Proleter Zrenjanin', 'Sérvia'),
  ('FK Rad', 'Sérvia'),
  ('FK Radnički 1923', 'Sérvia'),
  ('FK Radnički Beograd', 'Sérvia'),
  ('FK Radnički Niš', 'Sérvia'),
  ('FK Radnički Obrenovac', 'Sérvia'),
  ('FK Radnik Surdulica', 'Sérvia'),
  ('FK Sloboda Užice', 'Sérvia'),
  ('FK Smederevo 1924', 'Sérvia'),
  ('FK Spartak Subotica', 'Sérvia'),
  ('FK Srem', 'Sérvia'),
  ('FK Teleoptik', 'Sérvia'),
  ('FK TSC', 'Sérvia'),
  ('FK Vojvodina', 'Sérvia'),
  ('FK Voždovac', 'Sérvia'),
  ('FK Železničar Pančevo', 'Sérvia'),
  ('FK Zemun', 'Sérvia'),
  ('FK Zlatibor Čajetina', 'Sérvia'),
  ('OFK Bačka', 'Sérvia'),
  ('OFK Beograd', 'Sérvia'),
  ('RFK Novi Sad 1921', 'Sérvia'),
  ('Albirex Niigata FC', 'Singapura'),
  ('Balestier Khalsa FC', 'Singapura'),
  ('Étoile FC', 'Singapura'),
  ('Geylang United FC', 'Singapura'),
  ('Hougang United FC', 'Singapura'),
  ('Lion City Sailors FC', 'Singapura'),
  ('Sinchi FC', 'Singapura'),
  ('Super Reds FC', 'Singapura'),
  ('Tampines Rovers FC', 'Singapura'),
  ('Tanjong Pagar United FC', 'Singapura'),
  ('Warriors FC', 'Singapura'),
  ('Young Lions', 'Singapura'),
  ('Afrin SC', 'Síria'),
  ('Ahli of Aleppo SC', 'Síria'),
  ('Al-Fotuwa SC', 'Síria'),
  ('Al-Herafyeen SC', 'Síria'),
  ('Al-Horgelah SC', 'Síria'),
  ('Al-Jazeera SC Hasakah', 'Síria'),
  ('Al-Karamah SC', 'Síria'),
  ('Al-Muhafaza', 'Síria'),
  ('Al-Sahel SC', 'Síria'),
  ('Al-Shorta SC', 'Síria'),
  ('Al-Wahda SC Damascus', 'Síria'),
  ('Al-Wathba SC', 'Síria'),
  ('Al-wathbaa', 'Síria'),
  ('Baniyas Refinery SC', 'Síria'),
  ('Damascus Al-Ahli Club', 'Síria'),
  ('Hurriya SC', 'Síria'),
  ('Hutteen SC', 'Síria'),
  ('Jableh SC', 'Síria'),
  ('Nawair SC', 'Síria'),
  ('Taliya SC', 'Síria'),
  ('Tishreen SC', 'Síria'),
  ('AC Mogadiscio', 'Somália'),
  ('Alba CF', 'Somália'),
  ('Badbaado', 'Somália'),
  ('Brothers Somali Fc', 'Somália'),
  ('Dekedaha FC', 'Somália'),
  ('Elman FC', 'Somália'),
  ('Feynuus FC', 'Somália'),
  ('Gaadiidka FC', 'Somália'),
  ('Jamhuuriya TB', 'Somália'),
  ('Jeenyo United FC', 'Somália'),
  ('Marine Club FC', 'Somália'),
  ('Mogadishu City Club', 'Somália'),
  ('Mogadishu Municipality', 'Somália'),
  ('Savana FC', 'Somália'),
  ('SITT Daallo', 'Somália'),
  ('Somali Police FC', 'Somália'),
  ('Super Shell', 'Somália'),
  ('Al Ahli Club (Merowe)', 'Sudão'),
  ('Al Ahli SC (Khartoum)', 'Sudão'),
  ('Al Mirghani ESC', 'Sudão'),
  ('Al Nile SC', 'Sudão'),
  ('Al Rabita Kosti', 'Sudão'),
  ('Al-Ahli Club (Atbara)', 'Sudão'),
  ('Al-Ahli SC', 'Sudão'),
  ('Al-Ahly Shendi', 'Sudão'),
  ('Alamal SC Atbara', 'Sudão'),
  ('Al-Hilal Club', 'Sudão'),
  ('Al-Hilal SC (Al-Ubayyid)', 'Sudão'),
  ('Al-Hilal SC Kadougli', 'Sudão'),
  ('Al-Ittihad SC', 'Sudão'),
  ('Al-Merreikh Al-Thagher', 'Sudão'),
  ('Al-Merreikh SC (Al-Fasher)', 'Sudão'),
  ('Al-Merrikh SC', 'Sudão'),
  ('Al-Mourada SC', 'Sudão'),
  ('Al-Nsoor', 'Sudão'),
  ('Al-Shamali AC', 'Sudão'),
  ('Hay el-Arab SC', 'Sudão'),
  ('Jazeerat Al-Feel SC', 'Sudão'),
  ('Khartoum NC', 'Sudão'),
  ('Wad Nobawi SC', 'Sudão'),
  ('AFC Eskilstuna', 'Suécia'),
  ('AIK Fotboll', 'Suécia'),
  ('Ängelholms FF', 'Suécia'),
  ('Assyriska FF', 'Suécia'),
  ('Assyriska IK', 'Suécia'),
  ('Åtvidabergs FF', 'Suécia'),
  ('BK Häcken', 'Suécia'),
  ('Brynäs IF', 'Suécia'),
  ('Carlstad United BK', 'Suécia'),
  ('Dalkurd FF', 'Suécia'),
  ('Degerfors IF', 'Suécia'),
  ('Djurgårdens IF Fotboll', 'Suécia'),
  ('Falkenbergs FF', 'Suécia'),
  ('FC Rosengård 1917', 'Suécia'),
  ('GAIS', 'Suécia'),
  ('Gefle IF', 'Suécia'),
  ('GIF Sundsvall', 'Suécia'),
  ('Halmstads BK', 'Suécia'),
  ('Hammarby Fotboll', 'Suécia'),
  ('Helsingborgs IF', 'Suécia'),
  ('Husqvarna FF', 'Suécia'),
  ('IF Brommapojkarna', 'Suécia'),
  ('IF Elfsborg', 'Suécia'),
  ('IF Väster', 'Suécia'),
  ('IFK Eskilstuna', 'Suécia'),
  ('IFK Göteborg', 'Suécia'),
  ('IFK Haninge/Brandbergen', 'Suécia'),
  ('IFK Luleå', 'Suécia'),
  ('IFK Malmö', 'Suécia'),
  ('IFK Norrköping', 'Suécia'),
  ('IFK Sundsvall', 'Suécia'),
  ('IFK Värnamo', 'Suécia'),
  ('IK Brage', 'Suécia'),
  ('IK Frej', 'Suécia'),
  ('IK Oddevold', 'Suécia'),
  ('IK Sirius FK', 'Suécia'),
  ('IK Sleipner', 'Suécia'),
  ('Jönköpings Södra IF', 'Suécia'),
  ('Kalmar FF', 'Suécia'),
  ('KSF Prespa Birlik', 'Suécia'),
  ('Landskrona BoIS', 'Suécia'),
  ('Ljungskile SK', 'Suécia'),
  ('Lunds BK', 'Suécia'),
  ('Malmö FF', 'Suécia'),
  ('Mjällby AIF', 'Suécia'),
  ('Norrby IF', 'Suécia'),
  ('Nyköpings BIS', 'Suécia'),
  ('Örebro SK', 'Suécia'),
  ('Örgryte IS', 'Suécia'),
  ('Östers IF', 'Suécia'),
  ('Östersunds FK', 'Suécia'),
  ('Qviding FIF', 'Suécia'),
  ('Råå IF', 'Suécia'),
  ('Sandvikens IF', 'Suécia'),
  ('Selånger FK', 'Suécia'),
  ('Skövde AIK', 'Suécia'),
  ('Sollentuna FK', 'Suécia'),
  ('Syrianska FC', 'Suécia'),
  ('Trelleborgs FF', 'Suécia'),
  ('Tvååkers IF', 'Suécia'),
  ('Umeå FC', 'Suécia'),
  ('Utsiktens BK', 'Suécia'),
  ('Vänersborgs IF', 'Suécia'),
  ('Varbergs BoIS FC', 'Suécia'),
  ('Vasalunds IF', 'Suécia'),
  ('Västerås SK Fotboll', 'Suécia'),
  ('AC Bellinzona', 'Suíça'),
  ('Anglo-American Club Zürich', 'Suíça'),
  ('BSC Old Boys', 'Suíça'),
  ('BSC Young Boys', 'Suíça'),
  ('CS Chênois', 'Suíça'),
  ('Étoile Carouge FC', 'Suíça'),
  ('FC Aarau', 'Suíça'),
  ('FC Baden', 'Suíça'),
  ('FC Balzers', 'Suíça'),
  ('FC Basel', 'Suíça'),
  ('FC Baulmes', 'Suíça'),
  ('FC Bern', 'Suíça'),
  ('FC Biel-Bienne', 'Suíça'),
  ('FC Bulle', 'Suíça'),
  ('FC Chiasso', 'Suíça'),
  ('FC Concordia Basel', 'Suíça'),
  ('FC Fribourg', 'Suíça'),
  ('FC Gossau', 'Suíça'),
  ('FC Grenchen', 'Suíça'),
  ('FC La Chaux-de-Fonds', 'Suíça'),
  ('FC Lausanne-Sport', 'Suíça'),
  ('FC Le Mont', 'Suíça'),
  ('FC Locarno', 'Suíça'),
  ('FC Lugano', 'Suíça'),
  ('FC Luzern', 'Suíça'),
  ('FC Nordstern Basel', 'Suíça'),
  ('FC Rapperswil-Jona', 'Suíça'),
  ('FC Schaffhausen', 'Suíça'),
  ('FC Sion', 'Suíça'),
  ('FC St. Gallen', 'Suíça'),
  ('FC Stade Lausanne-Ouchy', 'Suíça'),
  ('FC Stade Nyonnais', 'Suíça'),
  ('FC Thun', 'Suíça'),
  ('FC Wettingen', 'Suíça'),
  ('FC Wil 1900', 'Suíça'),
  ('FC Winterthur', 'Suíça'),
  ('FC Wohlen', 'Suíça'),
  ('FC Zürich', 'Suíça'),
  ('Grasshopper Club Zürich', 'Suíça'),
  ('Neuchâtel Xamax FCS', 'Suíça'),
  ('SC Brühl', 'Suíça'),
  ('SC Kriens', 'Suíça'),
  ('SC Veltheim', 'Suíça'),
  ('SC Young Fellows Juventus', 'Suíça'),
  ('Servette FC', 'Suíça'),
  ('Yverdon-Sport FC', 'Suíça'),
  ('Zug 94', 'Suíça'),
  ('Inter Moengotapoe', 'Suriname'),
  ('SV Robinhood', 'Suriname'),
  ('SV Transvaal', 'Suriname'),
  ('Bangkok United FC', 'Tailândia'),
  ('BBCU FC', 'Tailândia'),
  ('BG Pathum United FC', 'Tailândia'),
  ('Buriram United FC', 'Tailândia'),
  ('Chainat Hornbill FC', 'Tailândia'),
  ('Chiangmai United FC', 'Tailândia'),
  ('Chiangrai United FC', 'Tailândia'),
  ('Chonburi FC', 'Tailândia'),
  ('Jumpasri United FC', 'Tailândia'),
  ('Muangthong United FC', 'Tailândia'),
  ('Nakhon Ratchasima FC', 'Tailândia'),
  ('Pattaya United FC', 'Tailândia'),
  ('Police Tebrau FC', 'Tailândia'),
  ('Port FC', 'Tailândia'),
  ('Prachuap FC', 'Tailândia'),
  ('Rasisalai United FC', 'Tailândia'),
  ('Ratchaburi Mitr Phol FC', 'Tailândia'),
  ('Rayong FC', 'Tailândia'),
  ('Samut Prakan City FC', 'Tailândia'),
  ('Samut Songkhram FC', 'Tailândia'),
  ('Sisaket FC', 'Tailândia'),
  ('Sukhothai FC', 'Tailândia'),
  ('Suphanburi FC', 'Tailândia'),
  ('Trat FC', 'Tailândia'),
  ('Ubon UMT United FC', 'Tailândia'),
  ('Uthai Thani FC', 'Tailândia'),
  ('Wuachon United FC', 'Tailândia'),
  ('Taichung Futuro FC', 'Taiwan'),
  ('Tainan City FC', 'Taiwan'),
  ('Taiwan Power Company FC', 'Taiwan'),
  ('Tatung FC', 'Taiwan'),
  ('Dynamo Dushanbe', 'Tajiquistão'),
  ('Energetik Dushanbe', 'Tajiquistão'),
  ('FC Panjshir', 'Tajiquistão'),
  ('FK Daleron-Uroteppa', 'Tajiquistão'),
  ('FK Istaravshan', 'Tajiquistão'),
  ('FK Khujand', 'Tajiquistão'),
  ('FK Spitamen', 'Tajiquistão'),
  ('Guardia Dushanbe', 'Tajiquistão'),
  ('Hima Dushanbe', 'Tajiquistão'),
  ('Istiqlol Dushanbe', 'Tajiquistão'),
  ('Khatlon Qurghonteppa', 'Tajiquistão'),
  ('Khayr Vahdat FK', 'Tajiquistão'),
  ('Khosilot Farkhor', 'Tajiquistão'),
  ('Kuktosh Rudaki', 'Tajiquistão'),
  ('Olimi Karimzod Mastchoh', 'Tajiquistão'),
  ('Parvoz Bobojon Ghafurov', 'Tajiquistão'),
  ('Ravshan Kulob', 'Tajiquistão'),
  ('Saroykamar Panj', 'Tajiquistão'),
  ('Shodmon Ghissar', 'Tajiquistão'),
  ('Tajik Telecom Qurghonteppa', 'Tajiquistão'),
  ('Zarafshon Pendjikent', 'Tajiquistão'),
  ('African Lyon FC', 'Tanzânia'),
  ('African Sports', 'Tanzânia'),
  ('Alliance Schools FC', 'Tanzânia'),
  ('Azam FC', 'Tanzânia'),
  ('Bandari FC', 'Tanzânia'),
  ('Coastal Union', 'Tanzânia'),
  ('JKT Mgambo', 'Tanzânia'),
  ('JKT Oljoro FC', 'Tanzânia'),
  ('JKT Ruvu Stars', 'Tanzânia'),
  ('Kagera Sugar FC', 'Tanzânia'),
  ('KenGold FC', 'Tanzânia'),
  ('Kinondoni Municipal Council F. C.', 'Tanzânia'),
  ('Maji Maji FC', 'Tanzânia'),
  ('Mbao FC', 'Tanzânia'),
  ('Mbeya City FC', 'Tanzânia'),
  ('Moro United FC', 'Tanzânia'),
  ('Mtibwa Sugar FC', 'Tanzânia'),
  ('Ndanda FC', 'Tanzânia'),
  ('Pan African FC', 'Tanzânia'),
  ('Polisi Dodoma', 'Tanzânia'),
  ('Polisi Morogoro', 'Tanzânia'),
  ('Prisons FC (Tanzania)', 'Tanzânia'),
  ('Rhino Rangers FC', 'Tanzânia'),
  ('Ruvu Shooting', 'Tanzânia'),
  ('Simba Sports Club', 'Tanzânia'),
  ('Singida Fountain Gate FC', 'Tanzânia'),
  ('Stand United FC', 'Tanzânia'),
  ('Tabora United', 'Tanzânia'),
  ('Toto African', 'Tanzânia'),
  ('Villa Squad', 'Tanzânia'),
  ('Young Africans SC', 'Tanzânia'),
  ('Karketu Dili', 'Timor-Leste'),
  ('Dynamic Togolais', 'Togo'),
  ('Étoile Filante (Lomé)', 'Togo'),
  ('Kozah Football Club Sports Association', 'Togo'),
  ('Central FC', 'Trindade e Tobago'),
  ('Club Sando FC', 'Trindade e Tobago'),
  ('Defence Force FC', 'Trindade e Tobago'),
  ('Joe Public FC', 'Trindade e Tobago'),
  ('La Horquetta Rangers FC', 'Trindade e Tobago'),
  ('Ma Pau SC', 'Trindade e Tobago'),
  ('Morvant Caledonia United', 'Trindade e Tobago'),
  ('North East Stars', 'Trindade e Tobago'),
  ('Point Fortin Civic FC', 'Trindade e Tobago'),
  ('Police FC', 'Trindade e Tobago'),
  ('San Juan Jabloteh', 'Trindade e Tobago'),
  ('T&TEC SC', 'Trindade e Tobago'),
  ('W Connection FC', 'Trindade e Tobago'),
  ('AS Gabès', 'Tunísia'),
  ('AS Marsa', 'Tunísia'),
  ('AS Rejiche', 'Tunísia'),
  ('CA Bizertine', 'Tunísia'),
  ('Club Africain', 'Tunísia'),
  ('CS Hammam-Lif', 'Tunísia'),
  ('CS Sfaxien', 'Tunísia'),
  ('EGS Gafsa', 'Tunísia'),
  ('EO Sidi Bouzid', 'Tunísia'),
  ('ES Beni-Khalled', 'Tunísia'),
  ('ES Hammam-Sousse', 'Tunísia'),
  ('ES Zarzis', 'Tunísia'),
  ('Espérance Sportive de Tunis', 'Tunísia'),
  ('Etoile Sportive de Metlaoui', 'Tunísia'),
  ('Étoile Sportive du Sahel', 'Tunísia'),
  ('JS Kairouan', 'Tunísia'),
  ('Olympique Béja', 'Tunísia'),
  ('Sfax Railways Sports', 'Tunísia'),
  ('Stade Gabèsien', 'Tunísia'),
  ('Stade Tunisien', 'Tunísia'),
  ('US Ben Guerdane', 'Tunísia'),
  ('US Monastir', 'Tunísia'),
  ('US Tataouine', 'Tunísia'),
  ('FC Ahal', 'Turquemenistão'),
  ('FC Altyn Asyr', 'Turquemenistão'),
  ('FC Aşgabat', 'Turquemenistão'),
  ('FC Balkan', 'Turquemenistão'),
  ('FC Daşoguz', 'Turquemenistão'),
  ('FC Energetik Türkmebaşy', 'Turquemenistão'),
  ('FC Gara Altyn', 'Turquemenistão'),
  ('FC Lebap', 'Turquemenistão'),
  ('FC Merw', 'Turquemenistão'),
  ('FC Şagadam', 'Turquemenistão'),
  ('FC Talyp Sporty', 'Turquemenistão'),
  ('FK Arkadag', 'Turquemenistão'),
  ('HTTU Aşgabat', 'Turquemenistão'),
  ('Köpetdag Aşgabat', 'Turquemenistão'),
  ('Nisa Aşgabat', 'Turquemenistão'),
  ('1461 Trabzon', 'Turquia'),
  ('Adana Demirspor', 'Turquia'),
  ('Adanaspor', 'Turquia'),
  ('Akhisar Belediyespor', 'Turquia'),
  ('Alanyaspor', 'Turquia'),
  ('Altay SK', 'Turquia'),
  ('Altınordu FK', 'Turquia'),
  ('Amed SFK', 'Turquia'),
  ('Ankara Keçiörengücü SK', 'Turquia'),
  ('Ankaraspor', 'Turquia'),
  ('Antalyaspor', 'Turquia'),
  ('Bakırköyspor', 'Turquia'),
  ('Balıkesirspor', 'Turquia'),
  ('Bandırmaspor', 'Turquia'),
  ('Beşiktaş JK', 'Turquia'),
  ('Bodrum FK', 'Turquia'),
  ('Boluspor', 'Turquia'),
  ('Bucaspor', 'Turquia'),
  ('Bursaspor', 'Turquia'),
  ('Çaykur Rizespor', 'Turquia'),
  ('Çorum FK', 'Turquia'),
  ('Denizlispor', 'Turquia'),
  ('Elazığspor', 'Turquia'),
  ('Erzurumspor FK', 'Turquia'),
  ('Eskişehirspor', 'Turquia'),
  ('Eyüpspor', 'Turquia'),
  ('Fatih Karagümrük SK', 'Turquia'),
  ('Fenerbahçe Istanbul', 'Turquia'),
  ('Galatasaray SK', 'Turquia'),
  ('Gaziantep ALG SK', 'Turquia'),
  ('Gaziantep FK', 'Turquia'),
  ('Gençlerbirliği SK', 'Turquia'),
  ('Gençlerbirliği Sports Club', 'Turquia'),
  ('Giresunspor', 'Turquia'),
  ('Göztepe SK', 'Turquia'),
  ('Hacettepe SK', 'Turquia'),
  ('Hatayspor', 'Turquia'),
  ('İstanbul Başakşehir FK', 'Turquia'),
  ('İstanbulspor A.Ş.', 'Turquia'),
  ('Kahramanmaraşspor', 'Turquia'),
  ('Kardemir Karabükspor', 'Turquia'),
  ('Kartal SK', 'Turquia'),
  ('Kasımpaşa SK', 'Turquia'),
  ('Kayseri Erciyesspor', 'Turquia'),
  ('Kayserispor', 'Turquia'),
  ('Kocaelispor', 'Turquia'),
  ('Konyaspor', 'Turquia'),
  ('Malatyaspor', 'Turquia'),
  ('Manisa FK', 'Turquia'),
  ('Manisaspor', 'Turquia'),
  ('Mersin İdmanyurdu', 'Turquia'),
  ('MKE Ankaragücü', 'Turquia'),
  ('MKE Kırıkkalespor', 'Turquia'),
  ('Orduspor', 'Turquia'),
  ('Oyak Renault', 'Turquia'),
  ('Pendikspor', 'Turquia'),
  ('Sakaryaspor', 'Turquia'),
  ('Samsunspor FC', 'Turquia'),
  ('Şanlıurfaspor', 'Turquia'),
  ('Sarıyer GK', 'Turquia'),
  ('Sivasspor', 'Turquia'),
  ('TKİ Tavşanlı Linyitspor', 'Turquia'),
  ('Trabzonspor', 'Turquia'),
  ('Ümraniyespor', 'Turquia'),
  ('Vefa SC', 'Turquia'),
  ('Yeni Malatyaspor', 'Turquia'),
  ('Zeytinburnuspor', 'Turquia'),
  ('FC Ahrobiznes Volochysk', 'Ucrânia'),
  ('FC Alians Lypova Dolyna', 'Ucrânia'),
  ('FC Arsenal-Kyivshchyna Bila Tserkva', 'Ucrânia'),
  ('FC Avanhard Kramatorsk', 'Ucrânia'),
  ('FC Cherkashchyna', 'Ucrânia'),
  ('FC Chornomorets Odesa', 'Ucrânia'),
  ('FC Desna Chernihiv', 'Ucrânia'),
  ('FC Dynamo Kyiv', 'Ucrânia'),
  ('FC Enerhetyk Burshtyn', 'Ucrânia'),
  ('FC Epitsentr Kamianets-Podilskyi', 'Ucrânia'),
  ('FC Helios Kharkiv', 'Ucrânia'),
  ('FC Ihroservice Simferopol', 'Ucrânia'),
  ('FC Inhulets Petrove', 'Ucrânia'),
  ('FC Karpaty Lviv', 'Ucrânia'),
  ('FC Knyazha Shchaslyve', 'Ucrânia'),
  ('FC Kolos Kovalivka', 'Ucrânia'),
  ('FC Komunalnyk Luhansk', 'Ucrânia'),
  ('FC Krymteplytsia Molodizhne', 'Ucrânia'),
  ('FC Kryvbas Kryvyi Rih', 'Ucrânia'),
  ('FC Kudrivka', 'Ucrânia'),
  ('FC Livyi Bereh Kyiv', 'Ucrânia'),
  ('FC LNZ Cherkasy', 'Ucrânia'),
  ('FC Lviv', 'Ucrânia'),
  ('FC Metal Kharkiv', 'Ucrânia'),
  ('FC Metalist 1925 Kharkiv', 'Ucrânia'),
  ('FC Metalist Kharkiv', 'Ucrânia'),
  ('FC Minaj', 'Ucrânia'),
  ('FC Naftovyk-Ukrnafta Okhtyrka', 'Ucrânia'),
  ('FC Nyva Bershad', 'Ucrânia'),
  ('FC Nyva Ternopil', 'Ucrânia'),
  ('FC Obolon Kyiv', 'Ucrânia'),
  ('FC Oleksandriya', 'Ucrânia'),
  ('FC Olimpik Donetsk', 'Ucrânia'),
  ('FC Polissya Zhytomyr', 'Ucrânia'),
  ('FC Poltava', 'Ucrânia'),
  ('FC Rubin Yalta', 'Ucrânia'),
  ('FC Rukh Lviv', 'Ucrânia'),
  ('FC Shakhtar Donetsk', 'Ucrânia'),
  ('FC Sirius Zhovti Vody', 'Ucrânia'),
  ('FC Spartak Sumy', 'Ucrânia'),
  ('FC Temp Shepetivka', 'Ucrânia'),
  ('FC Uzhhorod', 'Ucrânia'),
  ('FC Volyn Lutsk', 'Ucrânia'),
  ('FC Vorskla Poltava', 'Ucrânia'),
  ('FC VPK-Ahro Shevchenkivka', 'Ucrânia'),
  ('FC Zirka Kropyvnytskyi', 'Ucrânia'),
  ('FC Zorya Luhansk', 'Ucrânia'),
  ('FSC Bukovyna Chernivtsi', 'Ucrânia'),
  ('MFC Mykolaiv', 'Ucrânia'),
  ('NK Veres Rivne', 'Ucrânia'),
  ('PFC Nyva Vinnytsia', 'Ucrânia'),
  ('SC Poltava', 'Ucrânia'),
  ('BUL FC', 'Uganda'),
  ('Busoga United Football Club', 'Uganda'),
  ('Coffee Kakira SC', 'Uganda'),
  ('CRO FC', 'Uganda'),
  ('Express FC', 'Uganda'),
  ('Gaddafi FC', 'Uganda'),
  ('Jinja Municipal Hippos FC', 'Uganda'),
  ('Kampala Queens Women Football Club', 'Uganda'),
  ('KCCA FC', 'Uganda'),
  ('Kiira Young FC', 'Uganda'),
  ('Kitara FC', 'Uganda'),
  ('Lugazi FC', 'Uganda'),
  ('Lweza FC', 'Uganda'),
  ('Makerere University WFC', 'Uganda'),
  ('Maroons FC', 'Uganda'),
  ('Masaka Local Council FC', 'Uganda'),
  ('Mbarara City FC', 'Uganda'),
  ('NEC FC', 'Uganda'),
  ('Nyamityobora FC', 'Uganda'),
  ('Onduparaka FC', 'Uganda'),
  ('Paidha Black Angels FC', 'Uganda'),
  ('Police FC', 'Uganda'),
  ('Proline FC', 'Uganda'),
  ('SC Villa', 'Uganda'),
  ('Simba FC (Uganda)', 'Uganda'),
  ('SOLTILO Bright Stars FC', 'Uganda'),
  ('Tooro United FC', 'Uganda'),
  ('Uganda Revenue Authority SC', 'Uganda'),
  ('Victoria University SC', 'Uganda'),
  ('Victors FC', 'Uganda'),
  ('Vipers SC', 'Uganda'),
  ('Albion FC', 'Uruguai'),
  ('Atenas de San Carlos', 'Uruguai'),
  ('Boston River', 'Uruguai'),
  ('CA Bella Vista', 'Uruguai'),
  ('CA Cerro', 'Uruguai'),
  ('CA Progreso', 'Uruguai'),
  ('CA Rentistas', 'Uruguai'),
  ('Central Español', 'Uruguai'),
  ('Centro Atlético Fénix', 'Uruguai'),
  ('Cerro Largo FC', 'Uruguai'),
  ('Club Atlético Peñarol', 'Uruguai'),
  ('Club Atlético River Plate', 'Uruguai'),
  ('Club Nacional de Football', 'Uruguai'),
  ('Club Sportivo Cerrito', 'Uruguai'),
  ('Colón FC', 'Uruguai'),
  ('CSD Villa Española', 'Uruguai'),
  ('Danubio FC', 'Uruguai'),
  ('Defensor Sporting Club', 'Uruguai'),
  ('Deportivo Colonia', 'Uruguai'),
  ('Deportivo Maldonado', 'Uruguai'),
  ('El Tanque Sisley', 'Uruguai'),
  ('Juventud de Las Piedras', 'Uruguai'),
  ('Liverpool FC (Montevideo)', 'Uruguai'),
  ('Miramar Misiones', 'Uruguai'),
  ('Montevideo City Torque', 'Uruguai'),
  ('Montevideo Wanderers Fútbol Club', 'Uruguai'),
  ('Plaza Colonia', 'Uruguai'),
  ('Racing Club de Montevideo', 'Uruguai'),
  ('Rampla Juniors Football Club', 'Uruguai'),
  ('Rocha FC', 'Uruguai'),
  ('Sud América', 'Uruguai'),
  ('Tacuarembó FC', 'Uruguai'),
  ('Universal Football Club', 'Uruguai'),
  ('Uruguay Athletic Club', 'Uruguai'),
  ('Uruguay Montevideo FC', 'Uruguai'),
  ('FC AGMK', 'Usbequistão'),
  ('FC Bunyodkor', 'Usbequistão'),
  ('FC Khorazm', 'Usbequistão'),
  ('FC Neftchi Fergana', 'Usbequistão'),
  ('FC Shurtan Guzar', 'Usbequistão'),
  ('FC Surkhon Termez', 'Usbequistão'),
  ('FK Andijan', 'Usbequistão'),
  ('FK Buxoro', 'Usbequistão'),
  ('FK Dinamo Samarqand', 'Usbequistão'),
  ('FK Mash''al Mubarek', 'Usbequistão'),
  ('Kokand 1912', 'Usbequistão'),
  ('Lokomotiv Tashkent', 'Usbequistão'),
  ('Metallurg Bekabad', 'Usbequistão'),
  ('MHSK Tashkent', 'Usbequistão'),
  ('Nasaf Qarshi', 'Usbequistão'),
  ('Navbahor Namangan', 'Usbequistão'),
  ('Pakhtakor Tashkent FK', 'Usbequistão'),
  ('PFK Qizilqum', 'Usbequistão'),
  ('Sogdiana Jizzakh', 'Usbequistão'),
  ('Topalang Sariosiyo', 'Usbequistão'),
  ('Vobkent FK', 'Usbequistão'),
  ('Amicale FC', 'Vanuatu'),
  ('Tafea FC', 'Vanuatu'),
  ('Academia Puerto Cabello', 'Venezuela'),
  ('América Fútbol Club', 'Venezuela'),
  ('Aragua Fútbol Club', 'Venezuela'),
  ('Asociación Civil Deportivo Lara', 'Venezuela'),
  ('Asociación Civil Mineros de Guayana', 'Venezuela'),
  ('Atlético El Vigía', 'Venezuela'),
  ('Atlético Venezuela', 'Venezuela'),
  ('Banco Obrero Fútbol Club', 'Venezuela'),
  ('Carabobo FC', 'Venezuela'),
  ('Caracas Fútbol Club', 'Venezuela'),
  ('Caroní Fútbol Club', 'Venezuela'),
  ('Centro Atlético Sport Club', 'Venezuela'),
  ('Deportivo Anzoátegui', 'Venezuela'),
  ('Deportivo JBL del Zulia', 'Venezuela'),
  ('Deportivo La Guaira FC', 'Venezuela'),
  ('Deportivo Lara Fútbol Club', 'Venezuela'),
  ('Deportivo Petare FC', 'Venezuela'),
  ('Deportivo Vasco', 'Venezuela'),
  ('Deportivo Venezuela', 'Venezuela'),
  ('Dos Caminos Sport Club', 'Venezuela'),
  ('Estrella Roja FC', 'Venezuela'),
  ('Estudiantes de Mérida', 'Venezuela'),
  ('Guaros Fútbol Club', 'Venezuela'),
  ('Internacional de Bogotá', 'Venezuela'),
  ('La Salle FC', 'Venezuela'),
  ('Lala Fútbol Club', 'Venezuela'),
  ('Litoral de Cochabamba', 'Venezuela'),
  ('Litoral Sport Club', 'Venezuela'),
  ('Loyola Sport Club', 'Venezuela'),
  ('Metropolitanos FC', 'Venezuela'),
  ('Monagas Sport Club', 'Venezuela'),
  ('Portuguesa FC', 'Venezuela'),
  ('Trujillanos FC', 'Venezuela'),
  ('Unión Lara', 'Venezuela'),
  ('Venzóleo', 'Venezuela'),
  ('Yaracuyanos FC', 'Venezuela'),
  ('Zamora FC', 'Venezuela'),
  ('Zulia FC', 'Venezuela'),
  ('Becamex Binh Duong FC', 'Vietname'),
  ('Cong An Ha Noi FC', 'Vietname'),
  ('Cong An Ho Chi Minh City FC', 'Vietname'),
  ('Đồng Tâm Long An FC', 'Vietname'),
  ('Haiphong Football Club', 'Vietname'),
  ('Hanoi FC', 'Vietname'),
  ('Hoang Anh Gia Lai FC', 'Vietname'),
  ('Hong Linh Ha Tinh FC', 'Vietname'),
  ('MerryLand Quy Nhon Binh Dinh FC', 'Vietname'),
  ('Nam Dinh FC', 'Vietname'),
  ('QNK Quang Nam FC', 'Vietname'),
  ('Quang Ninh Charcoal FC', 'Vietname'),
  ('Sài Gòn FC', 'Vietname'),
  ('Sanna Khanh Hoa FC', 'Vietname'),
  ('SHB Da Nang FC', 'Vietname'),
  ('Sông Lam Nghệ An FC', 'Vietname'),
  ('Thanh Hóa FC', 'Vietname'),
  ('Thể Công–Viettel FC', 'Vietname'),
  ('Buildcon FC', 'Zâmbia'),
  ('Forest Rangers FC', 'Zâmbia'),
  ('Green Buffaloes FC', 'Zâmbia'),
  ('Green Eagles', 'Zâmbia'),
  ('Kabwe Warriors FC', 'Zâmbia'),
  ('Kabwe Youth Soccer Academy FC', 'Zâmbia'),
  ('Konkola Blades FC', 'Zâmbia'),
  ('Konkola Mine Police FC', 'Zâmbia'),
  ('Lime Hotspurs Football Club', 'Zâmbia'),
  ('Lusaka Dynamos FC', 'Zâmbia'),
  ('Maestro United Zambia FC', 'Zâmbia'),
  ('Mines United FC', 'Zâmbia'),
  ('Mufulira Wanderers FC', 'Zâmbia'),
  ('Mutondo Stars Football Club', 'Zâmbia'),
  ('Nakambala Leopards FC', 'Zâmbia'),
  ('NAPSA Stars FC', 'Zâmbia'),
  ('National Assembly FC', 'Zâmbia'),
  ('Nchanga Rangers FC', 'Zâmbia'),
  ('Nkana FC', 'Zâmbia'),
  ('Nkwazi FC', 'Zâmbia'),
  ('Power Dynamos FC', 'Zâmbia'),
  ('Red Arrows FC', 'Zâmbia'),
  ('Roan United FC', 'Zâmbia'),
  ('Trident Football Club', 'Zâmbia'),
  ('Zanaco FC', 'Zâmbia'),
  ('ZESCO United FC', 'Zâmbia'),
  ('Amazulu FC Zimbabwe', 'Zimbabué'),
  ('Bantu Tshintsha Guluva Rovers FC', 'Zimbabué'),
  ('Black Mambas FC', 'Zimbabué'),
  ('Black Rhinos FC', 'Zimbabué'),
  ('Blackpool FC Harare', 'Zimbabué'),
  ('Buffaloes FC', 'Zimbabué'),
  ('Cachetitos fc', 'Zimbabué'),
  ('CAPS FC', 'Zimbabué'),
  ('CAPS United FC', 'Zimbabué'),
  ('Chapungu United FC', 'Zimbabué'),
  ('Chicken Inn FC', 'Zimbabué'),
  ('Chiredzi FC', 'Zimbabué'),
  ('Dynamos FC', 'Zimbabué'),
  ('FC Platinum', 'Zimbabué'),
  ('Gunners FC', 'Zimbabué'),
  ('Harare City FC', 'Zimbabué'),
  ('Highlanders FC', 'Zimbabué'),
  ('Highway FC', 'Zimbabué'),
  ('How Mine FC', 'Zimbabué'),
  ('Hwange Colliery FC', 'Zimbabué'),
  ('Kiglon FC', 'Zimbabué'),
  ('Lancashire Steel FC', 'Zimbabué'),
  ('Lengthens FC', 'Zimbabué'),
  ('Masvingo United FC', 'Zimbabué'),
  ('Monomotapa United FC', 'Zimbabué'),
  ('Ngezi Platinum FC', 'Zimbabué'),
  ('Njube Sundowns FC', 'Zimbabué'),
  ('Shabanie Mine FC', 'Zimbabué'),
  ('Triangle United', 'Zimbabué'),
  ('Triple B FC', 'Zimbabué'),
  ('Underhill FC', 'Zimbabué'),
  ('Zimbabwe Saints FC', 'Zimbabué'),
  ('ZPC Kariba', 'Zimbabué')
) as v(name, country)
join countries c on c.name = v.country
on conflict (name, country_id) do nothing;
